### PR TITLE
Security optimizations for the container base image

### LINKED ISSUE #10508: Base image fixes (sec + compat)
The preparation to run the containers on OpenShift introduced an error in the base image: the `USER payara` statement after fixing the domain dir permissions is missing, so keeps user `root`.

In addition, to prepare for Ubuntu 24.04 we need to change:

1. `netcat` -> `netcat-openbsd` (avail in 22.04 and 24.04)
2. `adduser` -> `useradd`
3. `addgroup` -> `groupadd`

- Also, we make `payara` a system user, but use UID 1000, which is beyond the system user range. Let's fix that.
- In addition, we should adapt good practices and have a script to change the user password by env var/secret file, warning users they are using a default password and which that is
- Same for the Payara admin user password

### LINKED ISSUE #10722: Upgrade from Ubuntu 22 to 24 breaks container images
As @poikilotherm mentioned in last week's container meeting ([recording](https://harvard.zoom.us/rec/share/6YV8RWVgXNtANjLIpnGnL9tKN4AeMWbBjy_A6zzJu0dUgM48pOtYN8WU_J0mRSIl.9-ja80A1IHfF8cUW)), the `eclipse-temurin:17-jre` image we build on has switched from Ubuntu 22 to 24. See https://github.com/adoptium/containers/commit/d762761bff59ad4ee3bacf89050e2081e5464c65 via https://github.com/adoptium/containers/issues/606#issuecomment-2244787657

Unfortunately, this broke a few things. For example, the `addgroup` command is missing. See https://github.com/IQSS/dataverse/actions/runs/10078623902/job/27869639991?pr=10721 and https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/.5BINFO.5D.20DOCKER.3E.20ERROR.3A.20failed.20to.20solve/near/453771298

For now, I think we should revert to Ubuntu 22. Then we can worry about upgrading the Ubuntu 24 and rewriting scripts that use `addgroup` etc. at our leisure.

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
This issue addressed some flaws I found that are security related as well as enabling better compatibility with OpenShift and Kubernetes.

**Which issue(s) this PR closes**:

Closes #10508 
Closes #10722 

**Special notes for your reviewer**:
None

**Suggestions on how to test this**:
Run them locally in Docker:
```shell
mvn -Pct -f modules/container-base clean package -Dbase.image.tag=10508
mvn -Pct clean package docker:run -Dbase.image.tag=10508
```
To test changing the passwords, you need to add the documented settings to the compose file as env vars.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope

**Is there a release notes update needed for this change?**:
Included.

**Additional documentation**:
:battery: included

### CODE REVIEW

**Comment by poikilotherm** [comment]
I think this is ready for review!

**Comment by pdurbin** [comment]
Unfortunately, I get the dreaded `[INFO] DOCKER> unknown flag: --driver` error when I try to run `mvn -Pct -f modules/container-base clean package -Dbase.image.tag=10508` on my Mac.

We saw this error before:

- #9771

To fix this, I bumped to this version: `<fabric8-dmp.version>0.44.0</fabric8-dmp.version>`. See 146c9273e2.

**Comment by poikilotherm** [comment]
We can bump the DMP version in this PR, too.

**Comment by pdurbin** [comment]
Hmm, when I run `mvn -Pct clean package docker:run -Dbase.image.tag=10508` I get an error:

```
[INFO] --- docker:0.44.0:build (default-build) @ dataverse ---
[INFO] Reading assembly descriptor: /Users/PDurbin/github/iqss/dataverse/src/main/docker/assembly.xml
[INFO] Copying files to /Users/PDurbin/github/iqss/dataverse/target/docker/gdcc/dataverse/unstable/build/maven
[INFO] Building tar: /Users/PDurbin/github/iqss/dataverse/target/docker/gdcc/dataverse/unstable/tmp/docker-build.tar
[INFO] DOCKER> [gdcc/dataverse:unstable] "dev_dataverse": Created docker-build.tar in 1 second 
[INFO] DOCKER> [gdcc/dataverse:unstable] "dev_dataverse": Built image sha256:45db6
[WARNING] DOCKER> gdcc/dataverse:unstable: Unable to remove image [sha256:56818] : {"message":"conflict: unable to delete 568185d0af61 (cannot be forced) - image is being used by running container e4fdb985b8bf"} (Conflict: 409) (dangling image) [{"message":"conflict: unable to delete 568185d0af61 (cannot be forced) - image is being used by running container e4fdb985b8bf"} (Conflict: 409)]
[INFO] Reading assembly descriptor: /Users/PDurbin/github/iqss/dataverse/modules/container-configbaker/assembly.xml
[INFO] Copying files to /Users/PDurbin/github/iqss/dataverse/target/docker/gdcc/configbaker/unstable/build/maven
[INFO] Building tar: /Users/PDurbin/github/iqss/dataverse/target/docker/gdcc/configbaker/unstable/tmp/docker-build.tar
[INFO] DOCKER> [gdcc/configbaker:unstable] "dev_bootstrap": Created docker-build.tar in 36 milliseconds
[ERROR] DOCKER> Unable to inspect image [solr:] : {"message":"invalid reference format"} (Bad Request: 400) [{"message":"invalid reference format"} (Bad Request: 400)]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.042 s
[INFO] Finished at: 2024-07-25T09:18:57-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.44.0:build (default-build) on project dataverse: Unable to inspect image [solr:] : {"message":"invalid reference format"} (Bad Request: 400) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Review by pdurbin — APPROVED** [review]
I tested this on Rocky 8 (my dev3 server) and it seems to work fine. Merging.

**Comment by poikilotherm** [comment]
Thanks for testing and merging! Much appreciated, as always! :heart:

**Comment by pdurbin** [comment]
Thanks for the PR! There's a lot in here! 😄

**Pull request merged**
