### PR TITLE
Rewrite DatasetVersionFilesServiceBean QueryDSL queries using JPA Criteria and remove the QueryDSL library from the application dependencies

### LINKED ISSUE #10028: Rewrite DatasetVersionFilesServiceBean QueryDSL queries using JPA Criteria and remove the QueryDSL library from the application dependencies
**Overview of the Feature Request**

As decided at the frontend weekly meeting on 19th October, DatasetVersionFilesServiceBean should be rewritten using JPA Criteria instead of QueryDSL. After all code is rewritten, the Dataverse library will be removed.

**What kind of user is the feature intended for?**
N/A

**What inspired the request?**

- Architecture decisions
- Frontend weekly meeting

**What existing behavior do you want changed?**

None

**Any brand new behavior do you want to add to Dataverse?**

None

**Any open or closed issues related to this feature request?**
 
PR where QueryDSL is introduced:

- https://github.com/IQSS/dataverse/pull/9783

### PR DESCRIPTION
**Pull request by GPortas**
**What this PR does / why we need it**:

As decided at the frontend weekly meeting on 19th October, DatasetVersionFilesServiceBean has been rewritten using JPA Criteria instead of QueryDSL. The QueryDSL library has been removed.

**Which issue(s) this PR closes**:

- Closes #10028
- Closes https://github.com/IQSS/dataverse/issues/9990

**Suggestions on how to test this**:

The following API endpoints use the rewritten queries:

- getVersionFiles _/datasets/{id}/versions/{versionId}/files_ (https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/api/native-api.rst#list-files-in-a-dataset)
 
- getVersionFileCounts _/datasets/{id}/versions/{versionId}/files/counts_ (https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/api/native-api.rst#get-file-counts-in-a-dataset)

- getDownloadSize _/datasets/{id}/versions/{versionId}/downloadsize_ (https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/api/native-api.rst#get-the-size-of-downloading-all-the-files-of-a-dataset-version)

Despite we can test manual curl calls to these endpoints by sending different combinations of parameters (Described in the Native API documentation) and verify that they work correctly, testing all cases is extensive. Integration tests mainly cover all possible scenarios, so to verify the new implementation we can check that all test cases still pass as they did with the previous QueryDSL implementation.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

No

### CODE REVIEW

**Comment by pdurbin** [comment]
@GPortas I think you can safely update the description to say this PR closes this issue as well:

- #9990

I say this because I checked https://coveralls.io/github/IQSS/dataverse and this branch sent the first Coveralls report we've received since branches that pull in the following PR was merged:

- #9783


Here's a screenshot:

Screenshot 2023-10-25 at 10 23 07 AM

**Comment by pdurbin** [comment]
As mentioned in standup and Slack, I kicked off API tests here: https://github.com/gdcc/api-test-runner/actions/runs/6642486541

Using https://github.com/gdcc/api-test-runner Click Actions, then manual then “Run workflow” and change the branch like this:

Screenshot 2023-10-25 at 11 14 13 AM


Here’s the issue to automate this (need prioritization): 

- #9790

**Comment by GPortas** [comment]
@pdurbin API tests are passing on: https://github.com/gdcc/api-test-runner/actions/runs/6642486541

**Review by rtreacy — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
