### PR TITLE
Add new unit tests for JsonParser; implement getContactEmails in Dataverse

### PR DESCRIPTION
**Pull request by bencomp**
Rebased on the 4.3 branch, thinking that you should enough time to review the PR :)

Although I promised to not spend more free time on coding for Dataverse, I couldn't
help myself after interacting with the "native API" and talking about code coverage
with @pdurbin some more.

The new tests parse JSON test files from the test resources - rather than test that
JsonPrinter output can be parsed. Only date and date-time tests test a round-trip.
I added comments to explain what the test tries to accomplish.

Although line coverage of JsonParser with these tests is > 56%, not all branches are
covered even though NetBeans may show green: inline if/else statements 'hide' some
branches in the green lines.

To make the tests pass, I added `dv.setAffiliation` in `JsonParser.parseDataverse`
with a default value of `null` if the JSON doesn't include affiliation and
implemented `Dataverse.getContactEmails` to produce a comma-separated string of
email addresses. I hope these have been good assumptions for how the API behaves.

Note that because the JsonParser works on a different level than the API, the default
values that the parser uses may be different than the business logic prescribes
(see `dv.setPermissionRoot` in `parseDataverse`). The tests expect the parser's
defaults.

### CODE REVIEW

**Comment by bencomp** [comment]
This is the renewed #2478.

**Comment by pdurbin** [comment]
@scolapasta a comment from @michbarsinai - "The whole getContactEmails() thing is, I think, on its way out, and was never really used (currently it's hard coded to "")."

**Comment by michbarsinai** [comment]
That is indeed my comment, except that I'm cooking for, like, 12 people and so @pdurbin beat me to commenting it.

**Comment by pdurbin** [comment]
"My name is @michbarsinai and I approve this message." #election2016 ;)

**Comment by pdurbin** [comment]
@bencomp please see my comments about closing pull requests made against the 4.3 branch at https://github.com/IQSS/dataverse/pull/2860#issuecomment-171331960 (Let's discuss in one place, there.)

**Pull request closed without merging**
