### PR TITLE
Fixed #5954 Uploading large files with S3 - Multipart Upload

### LINKED ISSUE #5954: Issue uploading large files with an S3 backend
Hi,

We have managed to successfully couple Dataverse with an Openstack SWIFT S3 backend. The problem that we run into now is that uploading small files works fine, but uploading a 6GB file fails. When you upload a big file to an S3 object store you have to do multipart uploading, where an object is uploaded in smaller pieces. 
We have had a quick look at the S3-related code in Dataverse but we did not find an implementation of multipart uploading. 

Is multipart uploading implemented? And if not, could this be implemented so that we can upload large objects?

Cheers,

Ron

### PR DESCRIPTION
**Pull request by mderuijter**
## Related Issues

- closes #5954 : Issue uploading large files with an S3 backend

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
@mderuijter thanks for this pull request!

The code looks fine but where you planning to add anything to the guides? Do you need any help with this?

Also, I noticed a failure at https://jenkins.dataverse.org//job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-6341/lastCompletedBuild//testReport/junit/edu.harvard.iq.dataverse.api/AccessIT/AccessIT/ but I'm pretty sure this is because your branch is a little behind the "develop" branch. If you merge the latest from "develop" into your branch, you'll pick up pull request #6334, which should fix that error.

**Comment by mderuijter** [comment]
> @mderuijter thanks for this pull request!
> 
> The code looks fine but where you planning to add anything to the guides? Do you need any help with this?
> 
> Also, I noticed a failure at https://jenkins.dataverse.org//job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-6341/lastCompletedBuild//testReport/junit/edu.harvard.iq.dataverse.api/AccessIT/AccessIT/ but I'm pretty sure this is because your branch is a little behind the "develop" branch. If you merge the latest from "develop" into your branch, you'll pick up pull request #6334, which should fix that error.

Thank you @pdurbin, I was wondering what documentation to add and where to put it. A little help would be nice indeed. 

I've followed your instructions regarding the jenkins failure and it seems to have passed all the checks.

**Comment by pdurbin** [comment]
@mderuijter I added a note in https://github.com/mderuijter/dataverse/pull/1 which you are welcome to merge (or not). 😄 

I'm moving this to QA. Thanks again!

**Comment by kcondon** [comment]
Hi @mderuijter @pdurbin, to activate this feature one would need s3 storage enabled and upload through either the browser or api or this intended for api use only?

**Comment by pdurbin** [comment]
@kcondon the code change is in the S3 driver itself which is used by both the UI and the API.

**Pull request merged**
