### PR TITLE
7000 mpconfig fqdn & siteUrl

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
This pull request is simply swapping the former retrieval of the setting for FQDN and/or Site URL to MPCONFIG.
The code has been de-duplicated in some places that had the fqdn/siteUrl logic repeated. Those dups have been replaced with SystemConfig calls.

This PR does not address the changes requested in #6636 by request of @pdurbin for a smaller scope and less brain overload.
As this PR reuses existing config settings and does no renaming, this is 100% backward compatible.
Nonetheless, I really tried to make the description of the two settings in the config guide more comprehensible.

Relates to #6636
Relates to #7000

**Which issue(s) this PR closes**:
None.

**Special notes for your reviewer**:
It is again a good and simple start to see how the pieces laid out in #8823 are coming together.

**Suggestions on how to test this**:
Play around with the settings described in the added docs and watch it work. You could try an env var for a change (although in a classic installation, these might be hard to change for the Payara appserver...)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Not really.

**Is there a release notes update needed for this change?**:
Maybe? Dunno. The actual behaviour did not change as requested, this is not a solution to #6636.

**Additional documentation**:
Included.

### CODE REVIEW

**Comment by mreekie** [comment]
added to sprint Dec 15, 2022

**Comment by pdurbin** [comment]
@poikilotherm can you please resolve the merge conflicts? Thanks!

**Comment by poikilotherm** [comment]
> @poikilotherm can you please resolve the merge conflicts? Thanks!

I did! :smile_cat:

**Comment by pdurbin** [comment]
I'm running "build now" in Jenkins, hoping that this error goes away:

java.lang.AssertionError: expected:<201> but was:<500>
	at edu.harvard.iq.dataverse.api.HarvestingClientsIT.testHarvestingClientRun(HarvestingClientsIT.java:184)

**Review by pdurbin — APPROVED** [review]
I didn't test this but the code changes make sense, the docs look good, and all API tests are passing (I did have to re-run them due to the new harvest client tests). Sending to QA. Thanks, @poikilotherm.

**Comment by poikilotherm** [comment]
Woo-hoo! Thanks y'all, as always!

**Pull request merged**
