### PR TITLE
6359 life sciences metadata

### LINKED ISSUE #6359: Life Sciences metadata
The Dataverse North Metadata group has suggestions to improve the Life Sciences metadata block.

1. Add "Other" to the drop-down menu for "Design Type". (Note: there is "Unspecified" which has a different meaning).
2. Add "Other Design Type" box.
3. Add "Other Factor Type" box.
4. Add "Other Technology Type" box.
5. Add "Other Technology Platform" box.
6. For consistency, list Other at the end of all drop-down menus (vs. alphabetical as in Factor Type).

Thank you,
Sally

### PR DESCRIPTION
**Pull request by lubitchv**
**What this PR does / why we need it**: Updates Life Science metadata block. It adds new boxes:  "Other Design Type", "Other Factor Type", "Other Technology Type" and  "Other Technology Platform". It also adds OTHER in controlled vocabulary for "Design Type".

**Which issue(s) this PR closes**:

Closes #6359 

**Is there a release notes update needed for this change?**: Yes, it is in PR

### CODE REVIEW

**Comment by jggautier** [comment]
I spun up the branch at http://ec2-54-84-26-114.compute-1.amazonaws.com. Everything seems to work the way described in #6359 (new fields and their tooltips, "Other" terms being re-ordered to the bottom of the dropdown list for each vocabulary).

**Comment by jggautier** [comment]
@djbrooke, should I terminate that AWS instance [I wrote about a few days ago](https://github.com/IQSS/dataverse/pull/7278#issuecomment-696800884)? I hear it's not free to keep running, but it's cheap...

**Comment by jggautier** [comment]
Instance shut down 👋

**Review by sekmiller — APPROVED** [review]
Looks good. A little weird that there are entries in the properties file for watermarks that are blank, but it looks like that has been done previously as well.

**Pull request merged**
