### PR TITLE
2957 Dataverse UI updates for BARI tabular mapping and TwoRavens on/off

### PR DESCRIPTION
**Pull request by raprasad**
Related Issues:
#2961 (includes test instructions)
#2957
#2997
#2135

RFI Checklist

- [x]  Functionality completed as described in FRD.
  - not applicable, pre-FRD
- [x]  Dependencies, risks, assumptions in FRD addressed
  - not applicable, pre-FRD
- [x]  Unit tests completed
  - none, requires db and need integration testing
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing)
  - Yes
- [x]  Documentation completed
- [x]  All code checkins completed

---

- [x]  Code review completed or waived
- [x]  Testing requirements completed
  - Test settings included so that mock data may be added
- [x]  Usability testing completed or waived
- [x]  Support testing completed or waived -waived
- [x]  Merged with develop branch and resolved conflicts
    - merged with develop before making request

### CODE REVIEW

**Comment by kcondon** [comment]
Passing to EQ for UX review.

**Comment by eaquigley** [comment]
@kcondon is this on beta for me to see?

**Comment by eaquigley** [comment]
Forgot to check off for this one. @scolapasta and @kcondon who do i send this one too now?

**Comment by kcondon** [comment]
It needs to be rebuit and verified, right? Send it back to me. Once I verify it works still, if you want to check that message or change you wanted then great. Otherwise we'll merge. Is the required change recorded anywhere?



________________________________

**Comment by eaquigley** [comment]
Unassigning myself. Question for @raprasad, should I update the WorldMap user guide section at all for this release?

**Comment by raprasad** [comment]
@eaquigley  Yes, I can update it if needed (separate from this merge pull request)

**Pull request merged**
