### PR TITLE
update link in harvestserver.rst

### LINKED ISSUE #9168: Spreadsheet of DV Installations referred to in OAI doc is deprecated
**What steps does it take to reproduce the issue?**
Click on "This shared list" link in [the documentation of OAI Server](https://guides.dataverse.org/en/latest/admin/harvestserver.html) and it brings up [a deprecated spreadsheet](https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8) which in turn has a link to [the current spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo)

* When does this issue occur?
see above

* Which page(s) does it occurs on?
[OAI Server documentation](https://guides.dataverse.org/en/latest/admin/harvestserver.html) 

* What happens?
Goes to [a deprecated spreadsheet](https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8)

* To whom does it occur (all users, curators, superusers)?
all

* What did you expect to happen?
link should open [the current version](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo)

**Which version of Dataverse are you using?**
5.12.1

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

### PR DESCRIPTION
**Pull request by Rehan-stack**
- closes #9168

### CODE REVIEW

**Comment by pdurbin** [comment]
I checked the link at https://dataverse-guide--9436.org.readthedocs.build/en/9436/admin/harvestserver.html and it looks perfect! Thanks, @Rehan-stack!

I'm going to add the magic "closes" syntax to the description above so that it closes the issue in question.

**Review by pdurbin — APPROVED** [review]
@Rehan-stack perfect! Thank you! Sending to QA to merge.

**Comment by pdurbin** [comment]
@Rehan-stack out of curiosity, did you use the "quick fix" workflow at https://guides.dataverse.org/en/latest/developers/documentation.html#quick-fix ?

I'm asking because when I follow that workflow, the branch in my fork is called "patch-1" (or patch-2, etc.). But in your fork the branch is called "develop". This is not a problem for this tiny fix. Just curious! 😄

**Comment by Rehan-stack** [comment]
> @Rehan-stack out of curiosity, did you use the "quick fix" workflow at https://guides.dataverse.org/en/latest/developers/documentation.html#quick-fix ?
> 
> I'm asking because when I follow that workflow, the branch in my fork is called "patch-1" (or patch-2, etc.). But in your fork the branch is called "develop". This is not a problem for this tiny fix (but it sometimes [can be a problem](https://github.com/IQSS/dataverse/pull/8970#issuecomment-1430241288) for us). Just curious! 😄

No i do not follow that.

**Comment by pdurbin** [comment]
> No i do not follow that.

@Rehan-stack ok, no problem. Are you interested in making future contributions? (You seem to like Python and I can point you at some projects!) If so, please create a branch other than "develop" when making your pull request next time. For example, something like `9168-fix-link` would be a nice name. We explain this here: https://guides.dataverse.org/en/5.13/developers/version-control.html#create-a-new-branch-off-the-develop-branch

**Comment by Rehan-stack** [comment]
> 

ok that will be great to work in python. I will make another PR with new branch on this issue.

**Comment by pdurbin** [comment]
Great! Please jump in https://chat.dataverse.org to talk about Python sometime. Maybe you can help with https://github.com/gdcc/pyDataverse

Thanks for the new PR. I'm closing this one in favor of that one:

- #9437

**Pull request closed without merging**
