### PR TITLE
issue #5277: first implementation step for exporting related publicat…

### PR DESCRIPTION
**Pull request by pkiraly**
…ion to DataCite

**What this PR does / why we need it**:

It was a feature request from our users, and as I found in the issue queue others also missed that related publications and also other "Related ..." metadata fields are not exported into DataCite metadata. 

**Which issue(s) this PR closes**:

It is a "baby step" towards a better solution. Its intention is to move forward the discussion and to highlight theoretical and practical topics.

**Special notes for your reviewer**:

**Suggestions on how to test this**:

1. modify an existing dataset or create a new one
2. add some values into Related Publications's ID Type and ID number field.
3. save it
4. publish it
5. click on Metadata > Export metadata > Datacite
6. check if there is a line similare to
```xml
<relatedIdentifier relatedIdentifierType="ARK" relationType="Cites">ark:222</relatedIdentifier>
```
in the `<relatedIdentifiers>` section.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

It changes the XML output of the DataCite export - see previous point.

**Is there a release notes update needed for this change?**:
If community accepts this approach, it would worth to mention in the release not since I believe it increases the number of connections between papers and dataset in the PID network, thus somehow it might increase the discoverability.

**Additional documentation**:

---

Related to #5277

### CODE REVIEW

**Comment by djbrooke** [comment]
Hi @pkiraly - thanks! I know that this is a long-standing issue, and I appreciate the PR to start conversations around a potential solution. I think any solution would need to require user selection of the relationship, and that would require some UI changes. I don't think we'll review and merge this in it's current form, and this is one of my last few days with the project, but:

- @jggautier I know you've thought about this more than I have, so if I'm wrong about anything above let me know :)
- @TaniaSchlatter @scolapasta I think this focus on relationships and interoperability would fit in well with the NIH work (https://datascience.nih.gov/news/nih-office-of-data-science-strategy-announces-new-initiative-to-improve-data-access) and potentially the DASH work of Harvard Data Commons. There may be an opportunity to generate some use cases around this and better inform/prioritize a solution but I'm not sure.

**Comment by jggautier** [comment]
I think we'd want to move forward with this PR because it's a small step toward functionality that's been on our radar since at least 2015, but it would also be best to agree on some details about the next steps. I've always thought that QDR's and Madrono's repositories took this PR's approach because they figured that doing something to reap the benefits of sending this metadata to DataCite (such as contributing to the Make Data Count effort, whose metrics they were also early to implement in their repositories) was better than potentially waiting years for a longer lasting solution, which is what wound up happening. If this work was done as part of the NIH work or the Harvard Data Commons work, would it be another year or longer before Dataverse repositories would be able to start sending related publication metadata to DataCite?

The Make Data Count database considers several relationTypes when tracking and reporting relationships between resources, so in practice when Make Data Count says that a dataset has 3 "citation counts," that might not mean that three other resources formally cited that dataset. When looking at Make Data Count's data, I think we can reliably say only that the dataset has some sort of relationship with three other resources (and we know that we can't rely on the formal citation of datasets for measuring the influence of data). I heard in some DataCite webinar last year that researchers have been analyzing Make Data Count data collected so far, and maybe they're seeing patterns in publishers' uses of relationship types that can help DataCite and Crossref better define and maybe somehow enforce relationship type definitions.

But right now I don't think that the benefits of specifying relationship types have been realized, while I think there are already some benefits to reporting to DataCite that a dataset is somehow related to another resource. And Dataverse repositories have been collecting this information for years. Many Dataverse repositories don't know and I think would be hard pressed to figure out the types of relationships to apply to the Related Publication metadata they already have. To me that means that repositories will need to apply some type of general relationship type by default. And I think that's what this PR does.

Maybe the term IsCitedBy is too specific and shouldn't be used as a general, "somehow related to" term. When we were talking about relationTypes in https://github.com/IQSS/dataverse/issues/2778, in [a Google Doc](https://docs.google.com/document/d/1hc3Pa9fNJdEecKzxi1QkwCZLdciQjxv45eYZCvBKmeE) I proposed using IsReferencedBy, which DataCite defines as "indicates A is used as a source of information by B". But if we do use IsCitedBy to say that a dataset is somehow related, we should make sure that we all know this so that it's easier later to update the metadata with another term for "somehow related" if we want to reserve IsCitedBy for "this dataset appears in a citation in this publication". The more consistently the Dataverse community can use these terms, even if other publishing communities (like Zenodo) aren't using them the same way, the easier it'll be to apply changes if, for example, DataCite and/or CrossRef settle on fewer relationship types or revise their definitions based on how they're actually being used.

**Comment by pkiraly** [comment]
@TaniaSchlatter @scolapasta Did you have a chance to take a look on this issue? For us it would be quite urgent, and seems nothing happened in the last  2 months. Do you think it is this out of scope/interest for the majority of the Dataverse community?

**Comment by qqmyers** [comment]
My sense is that one reason this is stuck is the choice of isCitedBy. From the discussion in [#2778](https://github.com/IQSS/dataverse/issues/2778#issuecomment-446999587). isCitedBy is usually reserved for cases when a dataset is in the reference section of a paper. QDR decided on 'IsSupplementTo' in it's fork as an incremental step while waiting for support for a broader range of relationships to be supported (e.g. by adding a relationship type field to the related publications entry). (That said, it sounds like there is another site using isCitedBy).

While recognizing that support for multiple types is of interest, perhaps a way forward would be to select one of the more vague relationship types (IsSupplementTo, IsReferencedBy) as a default and poll the community (e.g. via email) on a few questions:

- Is adding related publications to the DataCite xml (sent to DataCite and in the DataCite export) with relationship X something we should do now?
- If no, would making the relationship type reported configurable at your site make this something we should do now? And, if yes, what relationship would you use?
- If neither of these is acceptable, it would also be possible to add an option to not report related publications (as is currently the case), but please tell us why you would not want to turn this feature on.

Hopefully that would provide enough feedback to quickly tweak this PR (e.g. by adding a setting(s) to select the type and/or turn off relationship reporting) as needed.

**Comment by pdurbin** [comment]
I'm just noting that we're still discussing what to send to DataCite and how: https://groups.google.com/g/dataverse-community/c/vxAw8vs7_K8/m/DRppjQjnEAAJ

Also, @jggautier made a nice list of related issues with regard to sending more and better data to DataCite: https://docs.google.com/document/d/1z6pPVT4_fc833thD9MyhoAMy2lwKDmCFX5QtKq8I04Y

Finally, some related discussion here:

- On 2022-10-06 there was a meeting about sending more metadata to DataCite: https://docs.google.com/document/d/1tNnvVh8jYY1g53BEwpJmMmm9w6Vgy_Q7RrmFjGnYOyA/edit?usp=sharing
- On 2022-10-20 there was another meeting about sending more metadata to DataCite: https://docs.google.com/document/d/1XMDGBNofnZbYp1vkP-qp497hxUr3GXvq2XDBjZMPK14/edit?usp=sharing

**Comment by scolapasta** [comment]
If you are still interested in this PR, can you please merge and resolve any merge conflicts with the latest from develop? If so, we can prioritize reviewing and QAing the changes. If we don’t hear from you by May 22, 2024, we’ll go ahead and close this PR (it can always be reopened after that date, if there is still interest).

**Comment by jggautier** [comment]
[I wrote that my proposal for merging the DataCite and OpenAIRE exports](https://github.com/IQSS/dataverse/issues/5889#issuecomment-2025510299) proposal will do what @pkiraly proposed in this PR, and I wrote that I thought this PR could be closed (or I guess deleted?) after the DataCite and OpenAIRE exports are merged.

@pkiraly if you're available, I'm hoping you can check out that proposal if you haven't already. @qqmyers said he'd work on it.

The proposal also references work that we're planning, outside of that proposal, about defining how datasets are related to other research objects.

**Comment by pkiraly** [comment]
@jggautier Is it OK for you if I do it early next week?

**Comment by jggautier** [comment]
Definitely, that's OK with me. Thanks!

**Comment by pkiraly** [comment]
@jggautier I read your plan, and it is absolutely fine for me.

**Comment by pdurbin** [comment]
It sounds like there's agreement to close this PR in favor of the proposal above. Great. Closing.

**Pull request closed without merging**
