### PR TITLE
ScholarsPortal Internationlization_4.5

### PR DESCRIPTION
**Pull request by JayanthyChengan**
# RFI Checklist

_**Before** submitting the pull request, fill out sections (1.) Related Issues and (2.) Pull Request Checklist._
### 1. Related Issues

_List and [link](https://guides.github.com/features/issues/#notifications) to the issues in this Pull Request._
- [#### + Title HERE]

---
### 2. Pull Request Checklist
- [ ]  Functionality completed as described in FRD
- [ ]  Dependencies, risks, assumptions in FRD addressed
- [ ]  Unit tests completed
- [ ]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [ ]  Documentation completed
- [ ]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._
- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

Connects to #209.

### CODE REVIEW

**Comment by mheppler** [comment]
@JayanthyChengan when trying to build your branch, I received some error msg regarding a missing column.

Please provide the necessary SQL update script in the "dataverse/scripts/database/upgrades/" directory. (See an example of such an update script in commit b703e27ec2d785adff459d3ff806e10344a2ef06.)

```Info:   Loading application [dataverse] at [/]
Warning:   Context path from ServletContext:  differs from path from bundle: /
Warning:   Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: column "frenchdescription" does not exist
  Position: 161
Error Code: 0
Call: SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, frenchdescription, frenchtitle, name, REQUIRED, title, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE ORDER BY ID
Query: ReadAllQuery(referenceClass=DatasetFieldType sql="SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, frenchdescription, frenchtitle, name, REQUIRED, title, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE ORDER BY ID")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:682)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2002)```

**Comment by JayanthyChengan** [comment]
Step 1:

Run the database update script. 
psql -U -d -f upgrade_v4.5_to_SPInternationlization.sql


Step 2: 

- place the tsv file on the web server.
- run these api commands to update the metadata block: 

curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @citation.tsv -H "Content-type: text/tab-separated-values"
curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @geospatial.tsv -H "Content-type: text/tab-separated-values"
curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @social_science.tsv -H "Content-type: text/tab-separated-values"
curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @astrophysics.tsv -H "Content-type: text/tab-separated-values"
curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @biomedical.tsv -H "Content-type: text/tab-separated-values"
curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @journals.tsv -H "Content-type: text/tab-separated-values"

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for participating in the community call yesterday: https://groups.google.com/d/msg/dataverse-community/d7BnFiRA3_I/O6cYqSBfCAAJ

**Comment by pdurbin** [comment]
This pull request is so old and is so far behind the "develop" branch that there are many merge conflicts. I'm closing it. As we indicated in the 2017-11-07 Dataverse Community Call notes at https://groups.google.com/d/msg/dataverse-community/d7BnFiRA3_I/O6cYqSBfCAAJ IQSS doesn't have the capacity to lead on internationalization so we are looking to the community to help. The "Dev Efforts by the Dataverse Community" spreadsheet at https://docs.google.com/spreadsheets/d/1pl9U0_CtWQ3oz6ZllvSHeyB0EG1M_vZEC_aZ7hREnhE/edit?usp=sharing is a good place to see what the community is up to. As of this writing you can entries for "internationalization" and "multilingual" and note that some of the cells have comments. For more context on that spreadsheet, see the " Which GitHub issues are being worked on by the Dataverse community?" at https://groups.google.com/d/msg/dataverse-community/X2diSWYll0w/ikp1TGcfBgAJ

**Pull request closed without merging**
