### PR TITLE
class field can be replaced by local variable

### LINKED ISSUE #8771: Feature Request/Idea:Code optimization suggestions
**Overview of the Feature Request**

Some fields can be replaced by local variables
**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

**What inspired the request?**

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**

**Any related open or closed issues to this feature request?**

<!DOCTYPE html><p cid="n2" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Hi,</span></p><p cid="n3" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">I find that the private field cm at Line 20 in the file 'dataverse/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SWORDv2ContainerServlet.java' on the master branch is only assigned and used in the method init. Therefore, this field can be removed from the class, and become a local variable in the method init. This transformation will normally reduce memory usage and improve readability of your code.</span></p><pre class="md-fences md-end-block md-fences-with-lineno ty-contain-cm modeLoaded" spellcheck="false" lang="java" cid="n10" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: var(--monospace); font-size: 0.9em; display: block; break-inside: avoid; text-align: left; white-space: normal; background-image: inherit; background-size: inherit; background-attachment: inherit; background-origin: inherit; background-clip: inherit; background-color: rgb(248, 248, 248); position: relative !important; border: 1px solid rgb(231, 234, 237); border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; padding: 8px 4px 6px 0px; margin-bottom: 15px; margin-top: 15px; width: inherit; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; background-position: inherit inherit; background-repeat: inherit inherit;">&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">private</span> <span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">ContainerManager</span> <span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">cm</span>; <span class="cm-comment" style="box-sizing: border-box; color: rgb(170, 85, 0);">// line 20 this field can be replaced by local variable</span></span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">public</span> <span class="cm-variable-3" style="box-sizing: border-box; color: rgb(0, 136, 85);">void</span> <span class="cm-def" style="box-sizing: border-box; color: rgb(0, 0, 255);">init</span>() <span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">throws</span> <span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">ServletException</span> {</span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp;<span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">super</span>.<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">init</span>();</span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp;<span class="cm-comment" style="box-sizing: border-box; color: rgb(170, 85, 0);">// ContainerManager cm = containerManagerImpl;</span></span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp;<span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">this</span>.<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">cm</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> <span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">containerManagerImpl</span>;</span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" cm-zwsp="" style="box-sizing: border-box;">​</span></span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp;<span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">this</span>.<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">sm</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> <span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">statementManagerImpl</span>;</span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp;</span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp; &nbsp; &nbsp; &nbsp;<span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">this</span>.<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">api</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> <span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">new</span> <span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">ContainerAPI</span>(<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">cm</span>, <span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">this</span>.<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">sm</span>, <span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">this</span>.<span class="cm-variable" style="box-sizing: border-box; color: rgb(0, 0, 0);">config</span>);</span><br>&nbsp;<span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;  }</span></pre><p cid="n11" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">Besides, there are other fields like this.I sorted them out and put them in the table below.I will be happy if this transformation is helpful.</span></p><figure class="md-table-fig" cid="n15" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">

Location | Field
-- | --
edu.harvard.iq.dataverse.api.datadeposit.SWORDv2ContainerServlet | sm
edu.harvard.iq.dataverse.api.datadeposit.SWORDv2StatementServlet | sm
edu.harvard.iq.dataverse.Shib | emailAddress
edu.harvard.iq.dataverse.DataCiteMetadataTemplate | xmlMetadata
edu.harvard.iq.dataverse.search.IndexServiceBean | rootDataverseName
edu.harvard.iq.dataverse.DatasetPage | protocol
edu.harvard.iq.dataverse.DatasetPage | customFields
edu.harvard.iq.dataverse.DatasetPage | authority
edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.csv.CSVFileReader | doubleMathContext
edu.harvard.iq.dataverse.DatasetServiceBean | xmlOutputFactory
edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet | repositoryConfiguration
edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet | setRepository
edu.harvard.iq.dataverse.harvest.server.web.servlet.OAIServlet | itemRepository
edu.harvard.iq.dataverse.dashboard.DashboardUsersPage | authUser
edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.dta.NewDTAFileReader | constantTable
edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.dta.NewDTAFileReader | dataLabelLength
edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.dta.NewDTAFileReader | headerLength
edu.harvard.iq.dataverse.harvest.client.FastGetRecord | xmlInputFactory
edu.harvard.iq.dataverse.rserve.VariableNameCheckerForR | safeVarNames
edu.harvard.iq.dataverse.mydata.DataRetrieverAPI | rolePermissionHelper
edu.harvard.iq.dataverse.mydata.DataRetrieverAPI | roleList
edu.harvard.iq.dataverse.mydata.DataRetrieverAPI | myDataFinder
edu.harvard.iq.dataverse.search.SearchIncludeFragment | solrQueryResponseAllTypes
edu.harvard.iq.dataverse.ManagePermissionsPage | roleList
edu.harvard.iq.dataverse.mydata.MyDataFinder | userIdentifier
edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.por.PORFileReader | caseQnty
edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.sav.SAVFileReader | spssVersionNumber
edu.harvard.iq.dataverse.ingest.IngestableDataChecker | regex
edu.harvard.iq.dataverse.ingest.IngestableDataChecker | rdargx

</figure>

### PR DESCRIPTION
**Pull request by noobyu6**
**What this PR does / why we need it**:
class fields can be replaced by local variables which can save memory
**Which issue(s) this PR closes**:

- Closes #8771

**Special notes for your reviewer**:
no
**Suggestions on how to test this**:
code review
**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
no
**Is there a release notes update needed for this change?**:
reduce memory usage
**Additional documentation**:

### CODE REVIEW

**Comment by scolapasta** [comment]
Hi @noobyu6 , for this next sprint we are catching up on Community PRs. Would you mind updating/ refreshing thiis PR from develop? Thanks!

**Comment by pdurbin** [comment]
As discussed at standup, we're comfortable with the same person doing review and QA. I'm merging this. Again, it's a trivial change and the SWORD API tests pass.

**Comment by pdurbin** [comment]
@noobyu6 I'm very sorry but I merged this pull request without noticing that it was targeting the "master" branch rather than the "develop" branch. Can you please create a new pull request that targets the "develop" branch? Thanks.

**Comment by noobyu6** [comment]
I see the same situation exists in the master branch, so merging into the master branch is also ok

**Comment by pdurbin** [comment]
@noobyu6 no. I reverted the master branch (see #8967). It comes down to our process. All PRs are merged into develop. Then at release time we merge develop into master. So please make a new PR against develop if you want this change. Sorry for the inconvenience.

**Comment by noobyu6** [comment]
@pdurbin I have made a new PR (see #8970).

**Pull request merged**
