### PR TITLE
Upgrade to Java 17

### LINKED ISSUE #8094: Migrate codebase to Java 17 LTS
Today, Java 17 has been released. This is the next LTS version of Java following 11, which will still be around for some time and then EOL.

Dataverse should run on the next generation Java, too! 🎊🥳

Things that pop up:
- Payara has had a roadmap item for JDK 17 support for Q3/2021. Let's see how fast this will become a reality.
- We might already add support for compiling and unit testing etc with Java 17 on CI to watch out for any trouble.
- Maybe it's a good idea so rewrite some DTOs to records...?

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

Upgrade from Java 11 to 17

**Which issue(s) this PR closes**:

- Closes #8094

**Special notes for your reviewer**:

The biggest change (in terms of number of files) has to do with REST Assured. I had to upgrade it to get it working on Java 17. The upgrade required a namespace change so I had to fix all the classes that import REST Assured.

The following tests were failing...

```
Error:  Errors: 
Error:    DataAccessTest.testCreateNewStorageIO_createsFileAccessIObyDefault:59 » NullPointer
Error:    DatasetUtilTest.testGetThumbnailCandidates:33 » NullPointer
Error:    DatasetUtilTest.testGetThumbnailNullDataset:51 » NullPointer
```

... and I fixed the DatasetUtilTest failures by cherry picking 23cc3b5 and DataAccessTest by my setting the dataset authority in a mock (c1b57a168c).

I've set up an API test running on the side at https://github.com/pdurbin/dataverse-api-test-runner/actions/workflows/java17.yml but I'd be happy to put this into the main code base.

Jenkins tests are failing until we switch Jenkins to Payara 6.

**Suggestions on how to test this**:

Test with Java 17

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

Included.

**Additional documentation**:

Included.

### CODE REVIEW

**Review by sekmiller — APPROVED** [review]
Discussed with Phil the reason for the necessary change in fileAccessIO

**Comment by pdurbin** [comment]
Just a note that [Jenkins is failing](https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9764/13/console) with "Fatal error compiling: error: release version 17 not supported". We should probably make changes to Jenkins/Ansible to upgrade to Java 17 to get the API tests to run.

**Comment by pdurbin** [comment]
I ran the tests at https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5871829299/job/15922098349#step:17:34910 and I'm seeing these failures:

```
Error:  Failures: 
Error:    DatasetsIT.testExcludeEmail:763 expected:<[]> but was:<null>
Error:    DatasetsIT.testExport:617 1 expectation failed.
JSON path data.latestVersion.metadataBlocks.citation.fields[2].value[0].datasetContactEmail.value doesn't match.
Expected: sammi@sample.com
  Actual: null

Error:    DatasetsIT.testReCreateDataset:2600 1 expectation failed.
Expected status code <201> but was <403>.

Error:    DatasetsIT.testSemanticMetadataAPIs:2498 https://dataverse.org/schema/citation/datasetContact
Expected: https://dataverse.org/schema/citation/datasetContactEmail
     but none found
```

If memory serves, I wasn't able to reproduce these locally. 🤔

**Comment by pdurbin** [comment]
Whoops! We just talked about this during sprint planning and I gave it a 33 because of 4-5 tests failing but after a single tiny fix at 8de674b having to do with syntax for the upgraded REST Assured library that's part of this PR (by necessity to get it to run on Java 17), the API test suite is passing in multiple places now:

- https://jenkins.dataverse.org/job/IQSS-dataverse-java17/3/testReport/
- https://github.com/pdurbin/dataverse-api-test-runner/actions/runs/5883385616/job/15955939871

(I also just ran the full test suite in Docker on my laptop and it passed there too.)

I'm putting this back into ready for QA.

**Comment by pdurbin** [comment]
@kcondon if it's of interest, thanks to @poikilotherm in #9789 (merged into this PR), we are now uploading a war file built from PRs to GitHub Actions.

To find the war file (`dataverse-java17.war`), under the list of checks, you can click the "Details" link under "Maven Unit Tests / (Stable / JDK 17) Unit Tests" and then "Summary".

I find it easier to go directly to https://github.com/IQSS/dataverse/actions/workflows/maven_unit_test.yml and then pick the right branch for the PR. Either way will get you there.

Note the file will be downloaded as `dataverse-java17.war.zip` and you'll need to unzip it. (This is a GitHub Actions thing: https://github.com/actions/upload-artifact#zipped-artifact-downloads .)

**Comment by kcondon** [comment]
Issues found:
1. Log entries related to flash and cookies. Not sure yet when they happen, happens sporadically. No apparent user impact: [2023-08-18T14:18:31.624+0000] [Payara 6.2023.8] [SEVERE] [faces.externalcontext.flash.bad.cookie] [jakarta.enterprise.resource.webcontainer.faces.flash] [tid: _ThreadID=99 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1692368311624] [levelValue: 1000] [[
  JSF1094: Could not decode flash data from incoming cookie value Invalid characters in decrypted value.  Processing will continue, but the flash is unavailable for this request.]]

2. Basic search seems not to differentiate/work, adv, navbar search do. "Check limited perms" returns all. Seems to refresh the page only, since terms are cleared from search box. They work and remain on demo with correct results shown.

3. Download file doesn't work with private url, throws 403.

**Comment by kcondon** [comment]
Given that none of the above issues are showstoppers specifically related to j17, we've decided to merge and look at the issues separately. See above for issue.

**Pull request merged**
