### PR TITLE
Cleaned up preview tab on file pg [ref #6437]

### LINKED ISSUE #6437: File Preview - UI clean up
There was some UI clean up that was missing in #3758. After reviewing with @TaniaSchlatter the to-do list is as follows:

- "Previews" btn text label should be "Preview Tools"
- White btn background for "access" is not appropriate on the Preview btn, it should be default gray
- Dropdown menu is aligned right, when it should be aligned left
- "Open {Preview Tool Name}" btn is small, not styled with Bootstrap, and breaks to a second line
- "Open {Preview Tool Name}" btn text label should be "Explore on {Preview Tool Name}", and needs an explore icon
- Preview tool iframe border needs styling, [responsive Bootstrap classes](https://getbootstrap.com/docs/3.4/components/#responsive-embed)

Screen Shot 2019-11-18 at 11 29 54 AM

### PR DESCRIPTION
**Pull request by mheppler**
**What this PR does / why we need it**:

The new preview tab on the file pg needed some UI clean up.

**Which issue(s) this PR closes**:

Closes #6437 _File Preview - UI clean up_

**Special notes for your reviewer**:

Thank you for reviewing.

**Suggestions on how to test this**:

Single tool, multiple tools, with and without guestbook/terms of access

**Does this PR introduce a user interface change?**:

Sure does.

**Is there a release notes update needed for this change?**:

No.

**Additional documentation**:

N/A

### CODE REVIEW

**Comment by mheppler** [comment]
@qqmyers I was hoping you can help clarify a problem with the Preview tab render logic on the file pg in this branch, as well as develop. @kcondon was testing this PR and found that your changes to the render logic were not behaving as expected in my branch.

In your PR #6420 which was merged into develop on 12/2, you changed the render logic of the tab on file.xhtml to:

```
... and FilePage.fileMetadata.datasetVersion == FilePage.fileMetadata.datasetVersion.dataset.getLatestVersionForCopy()
```

But, in another commit on 12/2 37906d3800d6876ebd5fea6911c80d1a87bffac1, directly to the develop branch (I'd scold you but I did the same thing last week), you changed it again to:

```
... and FilePage.fileMetadata.datasetVersion.isPublished()
```

That latest commit seems to have revert the bug fix of your PR. Can you provide some guidance here on what that latest commit does? Was it an unintended commit? Thanks.

**Comment by qqmyers** [comment]
@mheppler - I don't think I have privs to commit to dev - these should have been from 2 PRs. I did try to fix a merge issue and ended up making a null PR, but I then added a corecting commit.

FOr the two PRs: The first one corrected an issue where the previewers would not show if there was a draft version since the current version (i.e. a published v 2.0) would not equal the latest version, but would equal the latestversionforcopy (basically the latest published/public one). 
The second issue/PR was that, even with this fix, one could not preview files in earlier versions (e.g. a file only in the published v1 version). The second commit is to replace the comparison between the current version and the latest/latestforcopy with a simple test to see if the current version is public. Since this PR changes the same line as the other one, it led to a merge conflict (which I then bungled before correcting).

After both are in, I think the FilePage.fileMetadata.datasetVersion.isPublished() should fix both issues.

**Comment by mheppler** [comment]
Ahh, my apologies. I didn't notice there were two PRs (#6420, #6422) to the same line of code, on the same day, from the same developer.

I'll tell you what I am seeing in develop/my branch, and you can tell me if it's behaving as expected.

- preview tab displays on file pg for file in V1 of a dataset with no other versions, or drafts
- preview tab displays for file in V1 of a dataset with no other versions, BUT has a draft (fixed in #6419)
- preview tab does NOT display for file in DRAFT of a dataset
- preview tab does NOT display for file in V1 or V2 of a dataset with no draft (still a bug from #6421?)

**Comment by kcondon** [comment]
@qqmyers Jim, have seen a couple issues that were not addressed by your fixes. Not sure whether you would have included them if known: 1. If file is restricted or request for access is specified. 2. if tou specified, 3. if gb specified. In any of these cases, preview tab will not appear.

**Comment by qqmyers** [comment]
@mheppler  - I'm surprised if you don't get a preview for v1 or v2 when there's no draft, unless it is due to one of the issues @kcondon brings up. For those issues, my understanding is that those limitations were 'by design' at this point - awaiting thinking about how to display the terms/ask for gb info, etc. when the file isn't public. (These should still be viewable through the external preview button which has a way to popup terms, etc. - it's just the in page display). So I took them as out of scope at present and just tried to fix issues where I saw valid public datasets not getting preview displays.

**Comment by mheppler** [comment]
@qqmyers my apoloogies, @kcondon helped me diagnose what I was seeing, which was the expected behavior because those files were in datasets that had terms or guestbooks.

Someday this we will build out _File Page needs a Term Tab to define terms at the file level #4391_ and all this preview tab render logic will be a lot easier to determine per file.

**Pull request merged**
