### PR TITLE
Fixes license service NPE in the json parser (8634)

### LINKED ISSUE #8634: Harvesting: Harvest client runs but fails to harvest due to null ptr, at edu.harvard.iq.dataverse.util.json.JsonParser.parseLicense
Running the identical harvest client set on two different boxes but having different license sets configured locally, one client succeeds, the other fails all records with Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseLicense(JsonParser.java:402)

This is likely related to #8512 

Working license set:
select * from license;
 id | active |                     iconurl                     | isdefault |  name   |                       shortdescription   
                    |                       uri                        
----+--------+-------------------------------------------------+-----------+---------+------------------------------------------
--------------------+--------------------------------------------------
  1 | t      | https://licensebuttons.net/p/zero/1.0/88x31.png | t         | CC0 1.0 | Creative Commons CC0 1.0 Universal Public
 Domain Dedication. | http://creativecommons.org/publicdomain/zero/1.0
(1 row)

Failing set:
select * from license;
 id | active |                       iconurl                       | isdefault |      name       |                              
    shortdescription                                   |                       uri                        
----+--------+-----------------------------------------------------+-----------+-----------------+------------------------------
-------------------------------------------------------+--------------------------------------------------
  1 | t      | https://licensebuttons.net/p/zero/1.0/88x31.png     | t         | CC0 1.0         | Creative Commons CC0 1.0 Univ
ersal Public Domain Dedication.                        | http://creativecommons.org/publicdomain/zero/1.0
 14 | t      | https://licensebuttons.net/l/by-nd/4.0/88x31.png    | f         | CC BY-ND 4.0    | Creative Commons Attribution-
NoDerivatives 4.0 International License.               | http://creativecommons.org/licenses/by-nd/4.0
 16 | t      | https://licensebuttons.net/l/by-nc-nd/4.0/88x31.png | f         | CC BY-NC-ND 4.0 | Creative Commons Attribution-
NonCommercial-NoDerivatives 4.0 International License. | http://creativecommons.org/licenses/by-nc-nd/4.0
 19 | t      | https://licensebuttons.net/l/by-nc/4.0/88x31.png    | f         | CC BY-NC 4.0    | Creative Commons Attribution-
NonCommercial 4.0 International License.               | http://creativecommons.org/licenses/by-nc/4.0
  2 | t      | https://licensebuttons.net/l/by/4.0/88x31.png       | f         | CC BY 4.0       | Creative Commons Attribution 
4.0 International License.                             | http://creativecommons.org/licenses/by/4.0
 13 | t      |                                                     | f         | CC BY-NC-SA 4.0 | Creative Commons Attribution-
NonCommercial-ShareAlike 4.0 International License.    | http://creativecommons.org/licenses/by-nc-sa/4.0
  8 | t      | https://i.creativecommons.org/l/by-sa/4.0/88x31.png | f         | CC-BY-SA-4.0    | Creative Commons Attribution-
ShareAlike 4.0 International License.                  | http://creativecommons.org/licenses/by-sa/4.0
(7 rows)

Server log error:
[harvestclienterr.log](https://github.com/IQSS/dataverse/files/8532905/harvestclienterr.log)

### PR DESCRIPTION
**Pull request by landreev**
**What this PR does / why we need it**:

quick/trivial fix for an NPE in json import, when license lookup is needed. 

**Which issue(s) this PR closes**:

Closes #8634

**Special notes for your reviewer**:

**Suggestions on how to test this**:

As described in the issue. 

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by qqmyers — COMMENTED** [review]
Looks good to me. FWIW: I noticed 3 more instances of this in the ImportGenericServiceBean - would it make sense to fix those now as well? (I see other calls to create a JsonParser in the code but the Import* beans seem to be the only ones that use it to parse a DatasetVersion which is where the licenseSeerviceBean is called (that didn't already include it in the constructor).)

**Comment by landreev** [comment]
(@qqmyers Didn't mean to make it your problem, deciding what to do with some weird legacy code; I'm inclined to get rid of it, was just curious about another developer's opinion)

**Comment by qqmyers** [comment]
Yeah - FWIW: I also see that the second importXML that takes a File as a first param also doesn't appear to be used. I didn't mean to make this PR more work so definitely your call since these aren't one-liners. My guess is deleting the importDCTerms makes sense (it's still in git) and mayne the importXML(File ...) one as well if you want to take it on here.

**Comment by landreev** [comment]
I'm assuming this last commit also Closes #8580.

**Pull request merged**
