### PR TITLE
fix backwards newest oldest sort order

### LINKED ISSUE #10742: Dataset File Listing: Sort Order for Newest/Oldest is backwards
**What steps does it take to reproduce the issue?**
On a dataset file listing, click "Sort -> Newest"
The resulting order is oldest first.

On a dataset file listing, click "Sort -> Oldest"
the resulting order is newest first.

* When does this issue occur?
On the Dataset file listing section

* To whom does it occur (all users, curators, superusers)?
All Users

* What did you expect to happen?
Newest should be sorted "descending" (desc), but Oldest is sorted that way

**Which version of Dataverse are you using?**
V6.2

Happens on my local V6.2 dataverse instance as well as on Harvard's (V6.2):
Example, This dataset: https://doi.org/10.7910/DVN/KFVIIH

This is the URL that is displayed when "Oldest" sort is selected - notice "fileSortOrder=desc"

`https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/KFVIIH&version=&q=&fileTypeGroupFacet=&fileAccess=&fileSortField=date&fileSortOrder=desc&tagPresort=false`

### PR DESCRIPTION
**Pull request by stevenwinship**
**What this PR does / why we need it**: Sort order in UI on dataset file listing is backwards for Newest and Oldest

**Which issue(s) this PR closes**:https://github.com/IQSS/dataverse/issues/10742

- Closes #10742

**Special notes for your reviewer**: fully tested the comparator and determined it was just a UI issue

**Suggestions on how to test this**: Test using UI
On a dataset file listing, click "Sort -> Newest"
The resulting order should be newest first.

On a dataset file listing, click "Sort -> Oldest"
The resulting order should be oldest first.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**: Included

**Additional documentation**:

### CODE REVIEW

**Comment by qqmyers** [comment]
@stevenwinship  - I see the JsonParserTest.parseDataverseDTO test failure - can you update from develop to get the fix for it (I assume that's the problem).

**Review by qqmyers — APPROVED** [review]
Looks good - a simple swap of the two cases to get the order right. There is a test failing, presumably unrelated, but we should verify in QA.

**Comment by ofahimIQSS** [comment]
@stevenwinship I'm trying to push the PR to Internal and received a failure in jenkins: [ERROR] Failures: 
[ERROR]   JsonParserTest.parseDataverseDTO:286 expected: <pi@example.edu,student@example.edu> but was: <pi@example.edu>

Could you please update your PR with the latest from Dev. Thanks!

**Comment by ofahimIQSS** [comment]
Thanks @qqmyers that did the trick. Merging PR


https://github.com/user-attachments/assets/6fc180cc-42f8-42c4-be04-77ea1fdfc3b0

**Pull request merged**
