### PR TITLE
8531 refactor validators

### LINKED ISSUE #8531: Tech debt: refactor URL + Email validation
While hacking on Jakarta + Payara 6 compatibility #8305 , I came across these errors (see screenshot).

grafik

Let's fix this:

- Move [email](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/EMailValidator.java) + [url](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/URLValidator.java) validation classes and annotations to sub packages (where they belong...), refactor using code to reflect the relocation (7 classes)
- Make the Validator classes less complicated (some strange constructions in URLValidator with NPE etc????)
- Make the messages come from ValidationMessages.properties via standard mechanisms instead of Bundle.properties
- Fix the tests to not use internal classes but use the standard ways of testing ConstraintValidations

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
This pull request pays back some technical debt around validators.
- Cleanup some strange code constructs that slipped in over time
- Add way more tests for bean validation and programmatic usage
- Make the programmatic API more comprehensible, adding API docs etc

**Which issue(s) this PR closes**:

Closes #8531

**Special notes for your reviewer**:
None. I really put effort into keeping things working. I did draw a line: I did not refactor the JSF validation parts. They are as messy as before (it would make things cleaner by reusing bean validation :shrug: - less duplicated code, less different error messages.). And I did not cleanup all the code in `DatasetFieldValueValidator`, which could use some love...

**Suggestions on how to test this**:
There is a large amount of unit tests added with this PR. I tried very hard not to introduce unexpected behavior changes, but better watch out for those.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope.

**Is there a release notes update needed for this change?**:
Nope.

**Additional documentation**:
None so far.

### CODE REVIEW

**Comment by poikilotherm** [comment]
@donsizemore what does "Ansible run terminated abnormally, failing build." on Jenkins mean?

**Comment by donsizemore** [comment]
it means Ansible exited 1 - EC2 instance fell over, something timed out or generally went splat.

**Comment by poikilotherm** [comment]
Thx @qqmyers - fixed with 43126e1

**Comment by poikilotherm** [comment]
@qqmyers I see a [failing test](https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-8534/4/tests)

```
java.lang.AssertionError: 
Expected: https://dataverse.org/schema/citation/Contact
     but none found
	at edu.harvard.iq.dataverse.api.DatasetsIT.testSemanticMetadataAPIs(DatasetsIT.java:2333)
```

I'm puzzled if this is related to my changes or sth else...

**Review by sekmiller — APPROVED** [review]
Looks good. 
(is there any thought to allowing the min and max username size to be configurable?)

**Comment by poikilotherm** [comment]
> Looks good. 
> (is there any thought to allowing the min and max username size to be configurable?)

Well it hasn't been configurable for a looooong time, so maybe this is not necessary?

Btw this would be hard to do with annotations, as these require constants at compile time.

And IIRC the schema is generating limitations for SQL fields from this, so it might be necessary to create a schema migration.

**Comment by sekmiller** [comment]
I wasn't saying that this was desirable or necessary - just wondering if the change here was for something beyond readability and maintainability at some point in the future.

**Comment by poikilotherm** [comment]
Nope, it maintains status quo.

Guess if you'd want to do this at a later point in time, you'd remove the `@Size` and create a custom annotation that supports retrieving the configured maximum form a setting and skips any database length restrictions.

**Review by scolapasta — APPROVED** [review]

**Comment by kcondon** [comment]
@poikilotherm would you mind refreshing from develop branch? thanks

**Comment by poikilotherm** [comment]
> @poikilotherm would you mind refreshing from develop branch? thanks

:heavy_check_mark:

**Comment by poikilotherm** [comment]
As always thx for merging @kcondon 🤩

**Pull request merged**
