### PR TITLE
Return valid JSON from API blocking filters

### PR DESCRIPTION
**Pull request by bencomp**
**What this PR does / why we need it**:
Add `"` around the keys in the JSON responses from `ApiBlockingFilter`, so that Firefox accepts them as JSON.

```json
{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}
```
should be
```json
{ "status":"error", "message":"Endpoint available from localhost only. Please contact the dataverse administrator"}
```
URL that produces invalid JSON: <https://dataverse.harvard.edu/api/admin/datasetfield>

**Which issue(s) this PR closes**:
None; I did not create an issue for this and could not find related issues.

**Special notes for your reviewer**: thank you for reviewing :)

**Suggestions on how to test this**: check that the JSON is valid after applying this PR.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No

**Is there a release notes update needed for this change?**:
No

**Additional documentation**:
No

### CODE REVIEW

**Comment by pdurbin** [comment]
Well, the tests are passing. That's good. And this is a nice cleanup. ❤️ I hate broken JSON!

However, it's a minor backward incompatible change. @bencomp I'd love to hear your thought on this issue I opened recently:

- #10060

How do you feel about adding a release note snippet? This issue is related:

- #9264

And how do you feel like stubbing out the API changelog (or whatever we call it) from #10060?

**Comment by bencomp** [comment]
> Well, the tests are passing. That's good. And this is a nice cleanup. ❤️ I hate broken JSON!

Thanks!

> However, it's a minor backward incompatible change.

I guess it is. Since I could not find any issue that relates to this, I do think very few people have run into this. It was easier to fix the error than to imagine making or setting up workarounds to fix the JSON at the client's end. :)

> How do you feel about adding a release note snippet?

I can add something.

> And how do you feel like stubbing out the API changelog (or whatever we call it) from #10060?

No thanks. I do agree that versioning the API and providing a changelog is a useful activity if changes are not backwards compatible.

**Comment by pdurbin** [comment]
@bencomp your release note snippet is great. 😄 Thanks!

**Comment by bencomp** [comment]
@stevenwinship was there something I needed to do for this PR? (Other than merge the develop branch into this branch?)

**Review by stevenwinship — APPROVED** [review]

**Pull request merged**
