### PR TITLE
4856 french property files

### PR DESCRIPTION
**Pull request by JayanthyChengan**
Updated French files, ready to merge to develop branch

connects to #4856

### CODE REVIEW

**Comment by kcondon** [comment]
@JayanthyChengan Please update this from /develop since version number has changed. Will test right away, thanks.

**Comment by JayanthyChengan** [comment]
@kcondon: merged to latest from develop branch

**Comment by kcondon** [comment]
@JayanthyChengan  Thanks!

**Comment by kcondon** [comment]
@JayanthyChengan This branch has merge conflicts. Can you resolve them? Might be due to the mimetypes branch I just merged. Thanks!

**Comment by kcondon** [comment]
@JayanthyChengan  Thanks! Merged.

**Pull request merged**
