### PR TITLE
add Private URL feature

### PR DESCRIPTION
**Pull request by pdurbin**
First, please read the Business Requirements Document (BRD): https://docs.google.com/document/d/1FT47QkZKcmjSgRnePaJO2g1nzcotLyN3Yb2ORvBr6cs/edit?usp=sharing

Then, please read the Private URL design document, which explains edge cases and expected behavior: https://github.com/IQSS/dataverse/blob/b62959884ad8deb06a7135e485517672eb3c6fdf/doc/Architecture/privateurl.md

Four API endpoints have been added and documented at https://github.com/IQSS/dataverse/blob/b62959884ad8deb06a7135e485517672eb3c6fdf/doc/sphinx-guides/source/api/native-api.rst and they should be tested along with the more GUI-oriented descriptions above:

- List all the role assignments at the given dataset
- Create a Private URL (must be able to manage dataset permissions)
- Get a Private URL from a dataset (if available)
- Delete a Private URL from a dataset (if it exists)

In order to deploy this code you must run the sql script provided: https://github.com/IQSS/dataverse/blob/b62959884ad8deb06a7135e485517672eb3c6fdf/scripts/database/upgrades/privateurl.sql

@posixeleni has been waiting for me to create a branch in the main repo before documenting the Private URL feature in the User Guide so please pass the pull request to her after testing is complete. Update: this was done in #3138.

@scolapasta @michbarsinai I'm still wondering if we should use a ":" or not in the RoleAssignee identifier. Please see my comments and javadoc at https://github.com/IQSS/dataverse/blob/9480a63ec41e117c7868786ed44fb2276f62469a/src/main/java/edu/harvard/iq/dataverse/privateurl/PrivateUrlUtil.java#L27

@scolapasta once you have decided which version this feature will land in, we need to add the content of `privateurl.sql` to the official database migration script for that release. It's my understanding that the Private URL feature is slated for 4.5. Thanks, @kcondon for reminding me of this task. Update: this was done in 95570c7

# RFI Checklist

### 1. Related Issues

- #1012 Private URL To Unpublished Dataset  
- #3138 User Guide: Add section about Private URL
- #3174 Private URL -- UI Improvements
- #3200 Delete Dataset: Contributor deleting a draft of a published version is not indexed
- #3201 Private URL: When a contributor deletes a draft of a published dataset with privateURL defined, role is not cleared

---
### 2. Pull Request Checklist

- [x]  Functionality completed as described in BRD: https://docs.google.com/document/d/1FT47QkZKcmjSgRnePaJO2g1nzcotLyN3Yb2ORvBr6cs/edit?usp=sharing
- [x]  Dependencies, risks, assumptions in BRD addressed
- [x]  Unit tests completed
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [x]  Documentation completed (see #3138 and #3174)
- [x]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

Requires scripts/database/upgrades/privateurl.sql

Design doc at doc/Architecture/privateurl.md

New API endpoints: doc/sphinx-guides/source/api/native-api.rst

### CODE REVIEW

**Comment by pdurbin** [comment]
The merging of several pull requests yesterday has resulted in the message, "This branch has conflicts that must be resolved." I'm stealing this pull request back to resolve merge conflicts.

**Comment by pdurbin** [comment]
I just merged "develop" into the branch this pull request is based on and resolved merge conflicts in dd6ceb1 which has details (nothing big). Passing to QA.

**Comment by kcondon** [comment]
passing to  Gustavo for code review

**Comment by pdurbin** [comment]
@scolapasta here's a comment from @michbarsinai 'Little nitpicking regarding the comment at line 37 - ":" means "built-in" rather than "user". E.g. :authenticated-users. I'm also leaning towards using some other character, maybe "#"? In fact, even "P" will do.'

**Comment by pdurbin** [comment]
The status of this pull request is that I'm asking @mheppler to review UI changes I made yesterday and today in #3174 and I'm asking @eaquigley to use #3138 for any last changes to the User Guide.

Once they're done we'll check the boxes for "Documentation completed" and "All code checkins completed" and move this pull request to QA.

@scolapasta I went ahead and made the change of namespace that @michbarsinai suggested in e9bab79 (`#42` instead of `:privateUrl42`) so that's the commit to revert if you have any objections. RoleAssigneeServiceBean.getRoleAssignee is much cleaner, I think.

**Comment by pdurbin** [comment]
@eaquigley @mheppler and I (with help from @scolapasta ) put the finishing touches on this pull request today. Passing to QA.

**Comment by pdurbin** [comment]
@kcondon found bugs #3200 and #3201 (thanks!) which I consider show stoppers so I'm pulling this out of QA.

**Comment by pdurbin** [comment]
@scolapasta I need a ruling on the two proposed fixes described at https://github.com/IQSS/dataverse/issues/3200#issuecomment-232458080 so I'm assigning this pull request to you for code review.

**Comment by pdurbin** [comment]
@scolapasta and @michbarsinai blessed the fix at 24df280 so I merged it into this pull request. Passing to QA.

**Pull request merged**
