### PR TITLE
update Vagrantfile to use CentOS-8.2 and Payara5

### LINKED ISSUE #6849: Get Vagrant working on Payara and with updated installer
Vagrant appears in our docs in a number of places (screenshot below) and has a prominent place in the "Choose Your Own Installation Adventure" section of the Installation Guide:

Screen Shot 2020-04-22 at 10 38 24 AM

I took a swing at getting our Vagrant code working with Payara and the changes to the installer scripts but it turns out to be enough effort that a dedicated issue is warranted.

Here's what I learned or was reminded of:

- The Vagrant code uses the old Perl installer.
- The default.config file format has changed.

My plan is to commit what I have which at least gets rid of references to Glassfish 4.1. Moving forward, I would suggest the following:

- Switching to the Python installer.
- Using the default.config file provided rather than creating it on the fly.

Here are the many mentions of Vagrant:

Search_—_Dataverse org_-_2020-04-22_10 36 38

### PR DESCRIPTION
**Pull request by donsizemore**
**What this PR does / why we need it**: updates Vagrantfile to use CentOS-8.2 and Payara5

**Which issue(s) this PR closes**:

Closes #6849 

**Special notes for your reviewer**: none

**Suggestions on how to test this**: `vagrant up`

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: no

**Is there a release notes update needed for this change?**: no

**Additional documentation**: plenty of code comments for the curious

### CODE REVIEW

**Comment by pdurbin** [comment]
I'm giving this a try. Assuming is works we'll probably want to back out of some of my doc changes at a7c986d (screenshot below) when I de-emphasized the use of (broken at the time) Vagrant.

Screen Shot 2020-07-31 at 3 32 11 PM

**Comment by pdurbin** [comment]
I tried this on Friday but hit a snag (below). I'm on Vagrant 2.2.3.

```
murphy:guides.dataverse.org pdurbin$ vagrant up
==> vagrant: A new version of Vagrant is available: 2.2.9 (installed version: 2.2.3)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-8.2' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/centos-8.2'
    default: URL: https://vagrantcloud.com/bento/centos-8.2
==> default: Adding box 'bento/centos-8.2' (v202007.17.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/centos-8.2/versions/202007.17.0/providers/virtualbox.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'bento/centos-8.2' (v202007.17.0) for 'virtualbox'!
==> default: Importing base box 'bento/centos-8.2'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-8.2' version '202007.17.0' is up to date...
==> default: Setting the name of the VM: guidesdataverseorg_default_1596223937486_65660
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8888 (host) (adapter 1)
    default: 443 (guest) => 9999 (host) (adapter 1)
    default: 8983 (guest) => 8993 (host) (adapter 1)
    default: 8080 (guest) => 8088 (host) (adapter 1)
    default: 8181 (guest) => 8188 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
[default] GuestAdditions versions on your host (5.2.22) and guest (6.1.12) do not match.
Last metadata expiration check: 0:00:02 ago on Fri 31 Jul 2020 07:32:58 PM UTC.
Package centos-release-8.2-2.2004.0.1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Error: Unknown repo: 'C8.2.2004-base'
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 6.1.12
    default: VirtualBox Version: 5.2
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C8.2.2004-base --enablerepo=C8.2.2004-updates

Stdout from the command:



Stderr from the command:

Error: Unknown repo: 'C8.2.2004-base'

murphy:guides.dataverse.org pdurbin$ vagrant version
Installed Version: 2.2.3
Latest Version: 2.2.9
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/hashicorp/vagrant/blob/v2.2.9/CHANGELOG.md
murphy:guides.dataverse.org pdurbin$ 
```

**Comment by donsizemore** [comment]
@pdurbin did you try Vagrant 2.2.9?

**Comment by pdurbin** [comment]
No.

**Comment by pdurbin** [comment]
Ok, I upgraded and it works great. Thanks, @donsizemore !

```
curl -i http://localhost:8088/api/info/version
HTTP/1.1 200 OK
Server: Payara Server  5.2020.2 #badassfish
X-Powered-By: Servlet/4.0 JSP/2.3 (Payara Server  5.2020.2 #badassfish Java/Oracle Corporation/1.8)
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Dataverse-Key
Content-Type: application/json;charset=UTF-8
Content-Length: 54
X-Frame-Options: SAMEORIGIN

{"status":"OK","data":{"version":"4.20","build":null}}
```

**Comment by pdurbin** [comment]
This is almost ready for QA but we should remove the line in the docs about Vagrant being broken. I made this pull request for that: https://github.com/OdumInstitute/dataverse/pull/54

I looked thought the other docs changes above: https://github.com/IQSS/dataverse/pull/7153#issuecomment-667315353

Now that we have nice for-production solutions like dataverse-ansible, I don't feel the need to promote Vagrant as much in the Installation Guide. The Vagrant enthusiasts will find the Vagrantfile and I think that's enough.

@donsizemore heads up about the pull request above. Thanks.

**Pull request merged**
