### PR TITLE
6052 pageload slow

### PR DESCRIPTION
**Pull request by JayanthyChengan**
Related to #6052

### CODE REVIEW

**Comment by JayanthyChengan** [comment]
@pdurbin  - please refer to this comment
https://github.com/IQSS/dataverse/issues/6052#issuecomment-548509761

**Comment by JayanthyChengan** [comment]
@pdurbin - Yes, I tested the code and also released latest version at dataverse.scholarsportal.info today.  Please verify the performance .

**Comment by djbrooke** [comment]
@JayanthyChengan @poikilotherm @pdurbin It's great to see the performance boost here but it looks like there may be an unresolved question so I'll move this back to Community Dev for now.

**Comment by pdurbin** [comment]
@JayanthyChengan heads up the it's a holiday for @poikilotherm today so I wouldn't expect a reply right away. Thanks again for this pull request! If there's anything I can do to help move it forward, please let me know! A couple times at standup in recent memory @landreev has mentioned how much of a problem #6052 is so he might want to take a look when he has a few minutes.

**Comment by poikilotherm** [comment]
I just made a start with profiling to get to the root cause of this issue, as I don't think we should *break* the feature, but instead fix the implementation.

Please see my comments on #6052 and the [chatter on IRC today](http://irclog.iq.harvard.edu/dataverse/2019-11-05#i_111818).

@djbrooke I will unassign me, as IMHO I created a base from where to continue. I need to get going with #5974... Happy to answer questions. Find me on IRC from 9-17 CET, happy to videochat.

**Comment by djbrooke** [comment]
Thanks @poikilotherm for your efforts here, we appreciate it!!

@JayanthyChengan, let us know if you want to discuss anything about @poikilotherm's feedback. I'll keep this in community dev for now.

**Comment by pdurbin** [comment]
This morning I pinged @JayanthyChengan and she mentioned at https://github.com/IQSS/dataverse/issues/6052#issuecomment-561677893 that in production they use the workaround that this pull request represents.

She is busy with large file upload (Canarie Project) so I'll unassign her.

It probably doesn't make sense to have this in "community dev" right now. @djbrooke should we move it to another column?

**Comment by pdurbin** [comment]
@JayanthyChengan now that pull request #6428 has been merged, is it ok to close this pull request?

**Comment by pdurbin** [comment]
@JayanthyChengan Happy New Year! I'm just checking in.

Above I asked if this PR can be closed. Please advise!

Also, you may be aware of that we're hoping to restructure Dataverse ( https://groups.google.com/g/dataverse-community/c/uDeNUfqe3RE/m/dph8fZUaEAAJ ) and I'm wondering if this PR will still apply if we move from JSF to React. I'm not sure, to be honest! 😄

**Comment by JayanthyChengan** [comment]
@pdurbin - I am closing this now as we are not seeing any issues with page load at ScholarsPortal.  Thanks

**Pull request closed without merging**
