### PR TITLE
4684 metadatablock localedisplayname

### PR DESCRIPTION
**Pull request by JayanthyChengan**
## Related Issues

- connects to #4684 : Internationalization : redesign the architecture to handle metadatablocks

## Pull Request Checklist

- Merged latest from "develop"

### CODE REVIEW

**Comment by JayanthyChengan** [comment]
@matthew-a-dunlap - checked-in all the changes related to this comment https://github.com/IQSS/dataverse/pull/5111#issuecomment-437091863 . Please review

**Comment by JayanthyChengan** [comment]
@matthew-a-dunlap - yes, it's replacement for #5111

**Comment by matthew-a-dunlap** [comment]
@JayanthyChengan Ah great. Was the change to `LocalBundle.java` no longer needed?

**Comment by JayanthyChengan** [comment]
I would like to do the changes to LocalBundle.java similar to BundleUtil.java .
Please refer: https://github.com/IQSS/dataverse/commit/8d4b2db66d66617bcf187a4063852a77d36f7d6a

Can I do the changes to LocalBundle and submit in this PR , or do i need to open separate issue?

**Comment by scolapasta** [comment]
it's ok to do it as part of this one, assuming that's what you prefer.

**Comment by JayanthyChengan** [comment]
@scolapasta  committed LocalBundle.java

**Comment by JayanthyChengan** [comment]
@scolapasta let me know for any other corrections after codereview.

**Pull request merged**
