### PR TITLE
build(ci): atempt to fix coveralls report. #7977

### LINKED ISSUE #7977: Maven Unit Tests failing (new Coveralls check in GitHub Actions)
Ever since merging pull request #7944 commits are showing a failure of the "Maven Unit Tests" check like this:

Screen Shot 2021-06-29 at 10 06 49 AM

If you did into the error, it says:

> Error:  Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project dataverse: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]

Here's a screenshot from https://github.com/IQSS/dataverse/runs/2941612189 for more context:

@poikilotherm has his eye on these potential fixes:

- https://github.com/trautonen/coveralls-maven-plugin/issues/136#issuecomment-797322126
- https://github.com/common-workflow-language/cwlviewer/blob/main/.github/workflows/ci-build.yml

As fate should have it, old friend @michbarsinai ran into similar trouble a while back! 😄 https://stackoverflow.com/questions/41433800/travis-ci-org-project-cannot-submit-code-coverage-report-to-coveralls-io

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
This PR should finally resolve the coveralls report problem.

**Which issue(s) this PR closes**:

Closes #7977

**Special notes for your reviewer**:
None

**Suggestions on how to test this**:
None

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope

**Is there a release notes update needed for this change?**:
Nope

**Additional documentation**:
None

### CODE REVIEW

**Comment by poikilotherm** [comment]
This PR fixes the problem for pull requests. See https://coveralls.io/builds/40999007

It might be still broken for pushes. No way to test that but merge this and see what happens.

**Review by pdurbin — COMMENTED** [review]
@poikilotherm thank you for this pull request! 🎉 

It's along the lines I expected, based on posts I've seen.

I'm a little confused about one thing though...

In the pull request we see this:

    -DrepoToken=${COVERALLS_SECRET}

Instead, should this be...

    -DrepoToken=${COVERALLS_TOKEN}

... to match the secret we set up in pull request #7944? Here's a screenshot I just took:

Screen Shot 2021-06-30 at 10 47 42 AM

I'm confused about this because I can see that https://coveralls.io/github/IQSS/dataverse was updated this morning (the first time in a couple weeks) so whatever you're doing seems to be working:

Screen Shot 2021-06-30 at 10 51 27 AM

**Review by pdurbin — APPROVED** [review]
In Matrix @poikilotherm explained that we don't need COVERALLS_TOKEN in https://github.com/IQSS/dataverse/settings/secrets so I deleted it.

What's used instead is the GitHub token (`COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}`).

Thanks again for the pull request, @poikilotherm 

@kcondon like pull request #7944 this one should be safe to merge without any real testing. We just want to see if https://coveralls.io/github/IQSS/dataverse starts updating automatically again or not afterwards.

**Comment by poikilotherm** [comment]
Thanks for merging @kcondon ! :smile:

**Pull request merged**
