### PR TITLE
9933 configbaker expose bootstrap

### LINKED ISSUE #9933: Enable transfering information as environment variables from a configbaker bootstrap job to the host
This is related to gdcc/dataverse-action#1

For now, we need to enable transfer information like the `dataverseAdmin` API token extracted by the bootstrap job to some other place, e.g. the host. To enable further interaction *after* the bootstrap is done, it is crucial to enable exposition of this API token.

The idea is to mount a directory into the container (from wherever that might come) and write a `.env` file containing the sensitive information.

The bootstrap command script will provide a temp file to write this to, so we don't need to catch errors in the lower levels. If the target directory given as an argument exists (and has been mounted), the file will be copied once bootstrap is done.

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
Add capability to expose data from within the bootstrap process

**Which issue(s) this PR closes**:

- Closes #9933

**Special notes for your reviewer**:
None

**Suggestions on how to test this**:
Modify compose file to mount an existing *file* into the bootstrap container, add `-e <file>` (note the array notation!!!) and see it populated when bootstrap is running

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope

**Is there a release notes update needed for this change?**:
Nope

**Additional documentation**:
None

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
Works great. Low risk. This is how I tested it:

```
$ touch envfile.txt
$ vim docker-compose-dev.yml
$ git diff docker-compose-dev.yml
diff --git a/docker-compose-dev.yml b/docker-compose-dev.yml
index ab44dbc180..4a0d40917e 100644
--- a/docker-compose-dev.yml
+++ b/docker-compose-dev.yml
@@ -40,7 +40,11 @@ services:
     restart: "no"
     command:
       - bootstrap.sh
+      - -e
+      - envfile.txt
       - dev
+    volumes:
+      - ./envfile.txt:/envfile.txt
     networks:
       - dataverse
 
$ cat envfile.txt 
API_TOKEN=97cad752-983a-446f-866e-b032998ee33d
```

Approved. Just a container thing.

**Comment by kcondon** [comment]
@poikilotherm There is a branch conflict, can you resolve?

**Comment by poikilotherm** [comment]
> @poikilotherm There is a branch conflict, can you resolve?

Done

**Comment by JR-1991** [comment]
Can confirm!

```yaml
  dev_bootstrap:
    container_name: "dev_bootstrap"
    image: gdcc/configbaker:unstable
    restart: "no"
    command:
      - bootstrap.sh
      - -e
      - env_file.txt
      - dev
    networks:
      - dataverse
    volumes:
      - ./env_file.txt:/env_file.txt
```

```bash
# env_file.txt
API_TOKEN=435c7b36-6c88-4747-9ae5-27d0bb06562d
```

**Comment by pdurbin** [comment]
@JR-1991 with his next-level YAML colorization! So fancy!  🪄 🦄 🌷

**Pull request merged**
