### PR TITLE
7081 kebab file options icon btn

### LINKED ISSUE #7081: Dataset Page - File Options Kebab Btn 🍡
Change the file table button style and appearance in the UI to maximum 3 icon buttons (3rd being "kabob" to display additional actions in a dropdown) to add scalability for future file-level actions.

Pulling this out as an individual issue from #6605. Link to mockup: https://www.sketch.com/s/c6f49cf6-795a-4138-931c-fd962ae2542a/a/Emwabv

### PR DESCRIPTION
**Pull request by scolapasta**
**What this PR does / why we need it**:
This PR adds a new fragment for edit buttons (and one for related popups) so that the UI code can be reused in multiple locations - currently, as of this PR used on: FilePage and DatasetPage, both for the kebabs and the selected files edit button. 

**Which issue(s) this PR closes**:

Closes #7081 

**Special notes for your reviewer**:
This is the infrastructure for this - some of the options are still specific and have logic, for example, to only render on the file page (e.g. replace and provenance). There are open issues to add those to DatasetPage (and one for file tags to be added to both kebabs and file page). Eventually, we will likely want to use this as well for the edit files page / fragment.

One thing I did for the new fragments is add a section at the top (with a ui:remove) that lists the different parameters that can be passed and/or are needed for usage of the fragment. 

**Suggestions on how to test this**:
Make sure the correct edit functions appear and work in the 3 locations: File Page, Dataset Page kebab, and Dataset Page edit button for selected files.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Yes. Any needed mockups should be in the issue.

**Is there a release notes update needed for this change?**:
no

**Additional documentation**:

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
From a quick look, I think this would be ok to move to QA but there are conflicts in src/main/webapp/filesFragment.xhtml (and two pages in the guides) between this branch and the preview tools branch. So, I think we should let preview tools get merged before this gets to QA.

**Review by sekmiller — APPROVED** [review]

**Comment by kcondon** [comment]
Tested, this appears consistent across elements and works.
Did notice one UI issue where kebab menu appears behind footer text at bottom, like it is on the wrong layer. @djbrooke @TaniaSchlatter @mheppler what do you think? Merge, then fix or wait, fix, then merge?

**Comment by djbrooke** [comment]
Thanks @kcondon - let's wait on merging until we can investigate. @scolapasta can you take a quick look and see if there's anything obvious here?

**Comment by kcondon** [comment]
@djbrooke @scolapasta It was a shift+reload issue. Can merge at any time but maybe tomorrow.

**Pull request merged**
