### PR TITLE
5850 bagit export2 local fs

### LINKED ISSUE #5850: allow BagIT API to export to a local filesystem
pull request forthcoming.

### PR DESCRIPTION
**Pull request by donsizemore**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- closes #5850 

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
Overall, this seems like a very cool feature and nothing jumped out at me as wrong from a quick look at the code.

I have a little feedback on the docs.

Can "BagIt Export" have some sub-items in the table of contents? Here's how it looks right now:

Screen Shot 2019-07-01 at 10 44 06 AM

This looks strange:

Screen Shot 2019-07-01 at 10 44 23 AM

Finally, I think it might be worth clarifying early in the doc that you have to pick between one of two archivers. You can't run both at the same time. That's my understanding anyway. 😄

**Comment by pdurbin** [comment]
@donsizemore once I got in there it made more sense to add additional headings, I think:

Screen Shot 2019-07-01 at 1 05 07 PM

That was in f7fe5e4 . Please feel free to hack on it a little more if I made things worse. 😄 As long as you're done before QA returns next week. 😄 I'll go ahead and move it over.

**Comment by donsizemore** [comment]
if phil's happy, i'm happy!

**Comment by kcondon** [comment]
@donsizemore Would you update from develop? This is still using the 4.14 version. Thanks!

**Comment by donsizemore** [comment]
@kcondon done. thank you!

**Comment by kcondon** [comment]
@donsizemore I'm still seeing v4.14. Is that what you're seeing?

**Comment by donsizemore** [comment]
@kcondon sorry, i need more coffee. how about now?

**Comment by kcondon** [comment]
@donsizemore Just had some coffee myself. That did it, thanks!

**Comment by kcondon** [comment]
Tested, works. Ready for merge.

**Pull request merged**
