### PR TITLE
only call retrieveFileAccessRequesters for restricted files #7841

### LINKED ISSUE #7841: Many unnecessary SQL queries for public files (retrieveFileAccessRequesters)
While investigating performance problems I noticed that my dataset with 200 versions and 15 public files was generating many SQL queries when visiting the dataset landing page as a guest.

Specifically, 3000 of the 5206 queries were for the `fileaccessrequests` table.

Below are the query counts as of 0bd0691d4 on the develop branch.

For the code I used to create the dataset, see https://github.com/IQSS/dataverse/issues/7812#issuecomment-828680172

```
Parsed and counted the queries. Total number:
5206

Queries, counted and sorted: 

3000 select authenticated_user_id from fileaccessrequests
 201 SELECT ID, UNF, ARCHIVALCOPYLOCATION, ARCHIVENOTE, ARCHIVETIME, CREATETIME, DEACCESSIONLINK, LASTUPDATETIME, MINORVERSIONNUMBER, RELEASETIME, VERSION, VERSIONNOTE, VERSIONNUMBER, VERSIONSTATE, DATASET_ID, termsOfUseAndAccess_id FROM DATASETVERSION
 200 select t0.filecategories_id, t0.filemetadatas_id from filemetadata_datafilecategory t0, filemetadata t1
 200 select id, datafile_id, DESCRIPTION, LABEL, RESTRICTED, DIRECTORYLABEL, prov_freeform from FileMetadata
 200 SELECT ID, CREATETIME, NAME, USAGECOUNT, DATAVERSE_ID, termsOfUseAndAccess_id FROM TEMPLATE
 200 SELECT ID, AVAILABILITYSTATUS, CITATIONREQUIREMENTS, CONDITIONS, CONFIDENTIALITYDECLARATION, CONTACTFORACCESS, DATAACCESSPLACE, DEPOSITORREQUIREMENTS, DISCLAIMER, FILEACCESSREQUEST, LICENSE, ORIGINALARCHIVE, RESTRICTIONS, SIZEOFCOLLECTION, SPECIALPERMISSIONS, STUDYCOMPLETION, TERMSOFACCESS, TERMSOFUSE FROM TERMSOFUSEANDACCESS
 178 SELECT ID, AUTHENTICATIONPROVIDERID, PERSISTENTUSERID, AUTHENTICATEDUSER_ID FROM AUTHENTICATEDUSERLOOKUP
 178 SELECT ID, AFFILIATION, CREATEDTIME, DEACTIVATED, DEACTIVATEDTIME, EMAIL, EMAILCONFIRMED, FIRSTNAME, LASTAPIUSETIME, LASTLOGINTIME, LASTNAME, POSITION, SUPERUSER, USERIDENTIFIER FROM AUTHENTICATEDUSER
 131 SELECT ID, ALIAS, DESCRIPTION, NAME, PERMISSIONBITS, OWNER_ID FROM DATAVERSEROLE
 122 SELECT t0.ID, t0.DTYPE, t0.AUTHORITY, t0.CREATEDATE, t0.GLOBALIDCREATETIME, t0.IDENTIFIER, t0.IDENTIFIERREGISTERED, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PREVIEWIMAGEAVAILABLE, t0.PROTOCOL, t0.PUBLICATIONDATE, t0.STORAGEIDENTIFIER, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.AFFILIATION, t1.ALIAS, t1.DATAVERSETYPE, t1.description, t1.FACETROOT, t1.GUESTBOOKROOT, t1.METADATABLOCKROOT, t1.NAME, t1.PERMISSIONROOT, t1.STORAGEDRIVER, t1.TEMPLATEROOT, t1.THEMEROOT, t1.DEFAULTCONTRIBUTORROLE_ID, t1.DEFAULTTEMPLATE_ID FROM DVOBJECT t0, DATAVERSE t1
 122 SELECT ID, BACKGROUNDCOLOR, LINKCOLOR, LINKURL, LOGO, LOGOALIGNMENT, LOGOBACKGROUNDCOLOR, LOGOFOOTER, LOGOFOOTERALIGNMENT, LOGOFOOTERBACKGROUNDCOLOR, LOGOFORMAT, TAGLINE, TEXTCOLOR, dataverse_id FROM DATAVERSETHEME
 109 SELECT ID, CONTENT, LANG, NAME FROM SETTING
 100 SELECT DISTINCT DTYPE FROM DVOBJECT
  42 SELECT t0.ID, t0.DTYPE, t0.AUTHORITY, t0.CREATEDATE, t0.GLOBALIDCREATETIME, t0.IDENTIFIER, t0.IDENTIFIERREGISTERED, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PREVIEWIMAGEAVAILABLE, t0.PROTOCOL, t0.PUBLICATIONDATE, t0.STORAGEIDENTIFIER, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.FILEACCESSREQUEST, t1.HARVESTIDENTIFIER, t1.LASTEXPORTTIME, t1.STORAGEDRIVER, t1.USEGENERICTHUMBNAIL, t1.citationDateDatasetFieldType_id, t1.harvestingClient_id, t1.guestbook_id, t1.thumbnailfile_id FROM DVOBJECT t0, DATASET t1
  35 SELECT t0.ID, t0.DESCRIPTION, t0.DISPLAYNAME, t0.GROUPALIAS, t0.GROUPALIASINOWNER, t0.OWNER_ID FROM EXPLICITGROUP t0, ExplicitGroup_CONTAINEDROLEASSIGNEES t1
  35 SELECT ID, ASSIGNEEIDENTIFIER, PRIVATEURLTOKEN, DEFINITIONPOINT_ID, ROLE_ID FROM ROLEASSIGNMENT
  20 SELECT t0.ID, t0.DTYPE, t0.AUTHORITY, t0.CREATEDATE, t0.GLOBALIDCREATETIME, t0.IDENTIFIER, t0.IDENTIFIERREGISTERED, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PREVIEWIMAGEAVAILABLE, t0.PROTOCOL, t0.PUBLICATIONDATE, t0.STORAGEIDENTIFIER, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.CHECKSUMTYPE, t1.CHECKSUMVALUE, t1.CONTENTTYPE, t1.FILESIZE, t1.INGESTSTATUS, t1.PREVIOUSDATAFILEID, t1.prov_entityname, t1.RESTRICTED, t1.ROOTDATAFILEID FROM DVOBJECT t0, DATAFILE t1
  20 SELECT ID, CONTROLCARD, FORCETYPECHECK, LABELSFILE, TEXTENCODING, datafile_id FROM INGESTREQUEST
  20 SELECT ID, CASEQUANTITY, ORIGINALFILEFORMAT, ORIGINALFILENAME, ORIGINALFILESIZE, ORIGINALFORMATVERSION, RECORDSPERCASE, UNF, VARQUANTITY, DATAFILE_ID FROM DATATABLE
  19 SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, name, REQUIRED, title, uri, VALIDATIONFORMAT, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE
  11 select count(o.id) from GuestbookResponse  o 
  10 SELECT ID, CITEDBYURL, DATASET_ID FROM DATASETEXTERNALCITATIONS
  10 SELECT ID, CHECKSUM, CONTENTTYPE, FILESIZE, FORMATTAG, FORMATVERSION, ISPUBLIC, ORIGIN, TYPE, DATAFILE_ID FROM AUXILIARYFILE
   7 SELECT ID, DISPLAYORDER, value, DATASETFIELD_ID FROM DATASETFIELDVALUE
   4 SELECT t1.ID, t1.CONTENTTYPE, t1.DESCRIPTION, t1.DISPLAYNAME, t1.SCOPE, t1.TOOLNAME, t1.TOOLPARAMETERS, t1.TOOLURL FROM EXTERNALTOOLTYPE t0, EXTERNALTOOL t1
   4 SELECT ID, DATASETFIELDTYPE_ID, DATASETVERSION_ID, PARENTDATASETFIELDCOMPOUNDVALUE_ID, TEMPLATE_ID FROM DATASETFIELD
   3 SELECT df.id FROM datafile df, filemetadata fm, datasetversion dv, dvobject o
   3 SELECT ID, DISPLAYORDER, PARENTDATASETFIELD_ID FROM DATASETFIELDCOMPOUNDVALUE
   2 SELECT ID, INFO, REASON, STARTTIME, DATASET_ID, USER_ID FROM DATASETLOCK
   2 SELECT ID, INCLUDE, REQUIRED, datasetfieldtype_id, dataverse_id FROM DataverseFieldTypeInputLevel
   2 SELECT DISTINCT t0.ID, t0.DTYPE, t0.DESCRIPTION, t0.DISPLAYNAME, t0.PERSISTEDGROUPALIAS FROM IPV4RANGE t1 LEFT OUTER JOIN PERSISTEDGLOBALGROUP t0 ON (t0.ID = t1.OWNER_ID)
   1 SELECT t1.ID, t1.DISPLAYORDER, t1.IDENTIFIER, t1.STRVALUE, t1.DATASETFIELDTYPE_ID FROM DATASETFIELD_CONTROLLEDVOCABULARYVALUE t0, CONTROLLEDVOCABULARYVALUE t1
   1 SELECT t1.ID, t1.DISPLAYNAME, t1.NAME, t1.namespaceuri, t1.owner_id FROM DATAVERSE_METADATABLOCK t0, METADATABLOCK t1
   1 SELECT t1.ID, t1.ADVANCEDSEARCHFIELDTYPE, t1.ALLOWCONTROLLEDVOCABULARY, t1.ALLOWMULTIPLES, t1.description, t1.DISPLAYFORMAT, t1.DISPLAYONCREATE, t1.DISPLAYORDER, t1.FACETABLE, t1.FIELDTYPE, t1.name, t1.REQUIRED, t1.title, t1.uri, t1.VALIDATIONFORMAT, t1.WATERMARK, t1.METADATABLOCK_ID, t1.PARENTDATASETFIELDTYPE_ID FROM dataverse_citationDatasetFieldTypes t0, DATASETFIELDTYPE t1
   1 SELECT t0.ID, t0.DATAFILE_ID, t0.UNF, t0.CASEQUANTITY, t0.VARQUANTITY, t0.ORIGINALFILEFORMAT, t0.ORIGINALFILESIZE, t0.ORIGINALFILENAME FROM dataTable t0, dataFile t1, dvObject t2
   1 SELECT t0.ID, t0.CREATEDATE, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PUBLICATIONDATE, t0.CREATOR_ID, t0.RELEASEUSER_ID, t1.CONTENTTYPE, t0.STORAGEIDENTIFIER, t1.FILESIZE, t1.INGESTSTATUS, t1.CHECKSUMVALUE, t1.RESTRICTED, t1.CHECKSUMTYPE, t1.PREVIOUSDATAFILEID, t1.ROOTDATAFILEID, t0.PROTOCOL, t0.AUTHORITY, t0.IDENTIFIER FROM DVOBJECT t0, DATAFILE t1
   1 SELECT t0.DATAFILE_ID, t0.TYPE FROM DataFileTag t0, dvObject t1
   1 SELECT t.typlen FROM pg_catalog.pg_type t, pg_catalog.pg_namespace n
   1 SELECT id FROM fileMetadata
   1 SELECT ID, NAME, DATASET_ID FROM DATAFILECATEGORY
   1 SELECT ID, DISPLAYNAME, NAME, namespaceuri, owner_id FROM METADATABLOCK
   1 SELECT ID, CREATETIME, EMAILREQUIRED, ENABLED, INSTITUTIONREQUIRED, NAME, NAMEREQUIRED, POSITIONREQUIRED, DATAVERSE_ID FROM GUESTBOOK
   1 SELECT ID, CREATED, MESSAGE, TOBESHOWN, TYPE, AUTHENTICATEDUSER_ID, DATASETVERSION_ID FROM WORKFLOWCOMMENT
   1 SELECT ID, AUTHORITY, GLOBALIDCREATETIME, IDENTIFIER, IDENTIFIERREGISTERED, PROTOCOL, STORAGELOCATIONDESIGNATOR, DVOBJECT_ID FROM ALTERNATIVEPERSISTENTIDENTIFIER
   1 SELECT ID, ACTIVE, DISMISSIBLEBYUSER FROM BANNERMESSAGE
   1 INSERT INTO ACTIONLOGRECORD (ID, ACTIONRESULT, ACTIONSUBTYPE, ACTIONTYPE, ENDTIME, INFO, STARTTIME, USERIDENTIFIER) VALUES ('e6499205-3402-4f26-be21-5d560c60d6ab', 'OK', 'edu.harvard.iq.dataverse.engine.command.impl.GetLatestPublishedDatasetVersionCommand', 'Command', '2021-05-03 15:08:05.922', ':[211 Darwin''s Finches] ', '2021-05-03 15:08:05.893', ':guest')
   1 INSERT INTO ACTIONLOGRECORD (ID, ACTIONRESULT, ACTIONSUBTYPE, ACTIONTYPE, ENDTIME, INFO, STARTTIME, USERIDENTIFIER) VALUES ('62d7aa4b-b5de-4d78-a84e-4ee1dc5c6104', 'PermissionError', 'edu.harvard.iq.dataverse.engine.command.impl.GetPrivateUrlCommand', 'Command', '2021-05-03 15:08:06.547', ':[211 Darwin''s Finches]  Can''t execute command edu.harvard.iq.dataverse.engine.command.impl.GetPrivateUrlCommand@3e287646, because request [DataverseRequest user:[GuestUser :guest]@127.0.0.1] is missing permissions [ManageDatasetPermissions] on Object Darwin''s Finches', '2021-05-03 15:08:06.541', ':guest')
```

Here's how the profiler showed `retrieveFileAccessRequesters` taking up the most time:

Screen Shot 2021-04-28 at 3 51 55 PM (1)

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

Reduces the number of queries for a dataset with 200 versions and 15 public files for each version from 5206 to 2204. (The reduction of 3000 is 200 x 15.)

**Which issue(s) this PR closes**:

Closes #7841

**Special notes for your reviewer**:

None.

**Suggestions on how to test this**:

Compare query counts (the pull request vs develop) for datasets with many versions.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

No. I assume there will be a mention of performance in general.

**Additional documentation**:

Here's the "after" report of query counts. The "before" can be found in #7841.

```
Parsed and counted the queries. Total number:
2204

Queries, counted and sorted: 

 201 SELECT ID, UNF, ARCHIVALCOPYLOCATION, ARCHIVENOTE, ARCHIVETIME, CREATETIME, DEACCESSIONLINK, LASTUPDATETIME, MINORVERSIONNUMBER, RELEASETIME, VERSION, VERSIONNOTE, VERSIONNUMBER, VERSIONSTATE, DATASET_ID, termsOfUseAndAccess_id FROM DATASETVERSION
 200 select t0.filecategories_id, t0.filemetadatas_id from filemetadata_datafilecategory t0, filemetadata t1
 200 select id, datafile_id, DESCRIPTION, LABEL, RESTRICTED, DIRECTORYLABEL, prov_freeform from FileMetadata
 200 SELECT ID, CREATETIME, NAME, USAGECOUNT, DATAVERSE_ID, termsOfUseAndAccess_id FROM TEMPLATE
 200 SELECT ID, AVAILABILITYSTATUS, CITATIONREQUIREMENTS, CONDITIONS, CONFIDENTIALITYDECLARATION, CONTACTFORACCESS, DATAACCESSPLACE, DEPOSITORREQUIREMENTS, DISCLAIMER, FILEACCESSREQUEST, LICENSE, ORIGINALARCHIVE, RESTRICTIONS, SIZEOFCOLLECTION, SPECIALPERMISSIONS, STUDYCOMPLETION, TERMSOFACCESS, TERMSOFUSE FROM TERMSOFUSEANDACCESS
 178 SELECT ID, AUTHENTICATIONPROVIDERID, PERSISTENTUSERID, AUTHENTICATEDUSER_ID FROM AUTHENTICATEDUSERLOOKUP
 178 SELECT ID, AFFILIATION, CREATEDTIME, DEACTIVATED, DEACTIVATEDTIME, EMAIL, EMAILCONFIRMED, FIRSTNAME, LASTAPIUSETIME, LASTLOGINTIME, LASTNAME, POSITION, SUPERUSER, USERIDENTIFIER FROM AUTHENTICATEDUSER
 131 SELECT ID, ALIAS, DESCRIPTION, NAME, PERMISSIONBITS, OWNER_ID FROM DATAVERSEROLE
 122 SELECT t0.ID, t0.DTYPE, t0.AUTHORITY, t0.CREATEDATE, t0.GLOBALIDCREATETIME, t0.IDENTIFIER, t0.IDENTIFIERREGISTERED, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PREVIEWIMAGEAVAILABLE, t0.PROTOCOL, t0.PUBLICATIONDATE, t0.STORAGEIDENTIFIER, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.AFFILIATION, t1.ALIAS, t1.DATAVERSETYPE, t1.description, t1.FACETROOT, t1.GUESTBOOKROOT, t1.METADATABLOCKROOT, t1.NAME, t1.PERMISSIONROOT, t1.STORAGEDRIVER, t1.TEMPLATEROOT, t1.THEMEROOT, t1.DEFAULTCONTRIBUTORROLE_ID, t1.DEFAULTTEMPLATE_ID FROM DVOBJECT t0, DATAVERSE t1
 122 SELECT ID, BACKGROUNDCOLOR, LINKCOLOR, LINKURL, LOGO, LOGOALIGNMENT, LOGOBACKGROUNDCOLOR, LOGOFOOTER, LOGOFOOTERALIGNMENT, LOGOFOOTERBACKGROUNDCOLOR, LOGOFORMAT, TAGLINE, TEXTCOLOR, dataverse_id FROM DATAVERSETHEME
 108 SELECT ID, CONTENT, LANG, NAME FROM SETTING
 100 SELECT DISTINCT DTYPE FROM DVOBJECT
  42 SELECT t0.ID, t0.DTYPE, t0.AUTHORITY, t0.CREATEDATE, t0.GLOBALIDCREATETIME, t0.IDENTIFIER, t0.IDENTIFIERREGISTERED, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PREVIEWIMAGEAVAILABLE, t0.PROTOCOL, t0.PUBLICATIONDATE, t0.STORAGEIDENTIFIER, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.FILEACCESSREQUEST, t1.HARVESTIDENTIFIER, t1.LASTEXPORTTIME, t1.STORAGEDRIVER, t1.USEGENERICTHUMBNAIL, t1.citationDateDatasetFieldType_id, t1.harvestingClient_id, t1.guestbook_id, t1.thumbnailfile_id FROM DVOBJECT t0, DATASET t1
  35 SELECT t0.ID, t0.DESCRIPTION, t0.DISPLAYNAME, t0.GROUPALIAS, t0.GROUPALIASINOWNER, t0.OWNER_ID FROM EXPLICITGROUP t0, ExplicitGroup_CONTAINEDROLEASSIGNEES t1
  35 SELECT ID, ASSIGNEEIDENTIFIER, PRIVATEURLTOKEN, DEFINITIONPOINT_ID, ROLE_ID FROM ROLEASSIGNMENT
  20 SELECT t0.ID, t0.DTYPE, t0.AUTHORITY, t0.CREATEDATE, t0.GLOBALIDCREATETIME, t0.IDENTIFIER, t0.IDENTIFIERREGISTERED, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PREVIEWIMAGEAVAILABLE, t0.PROTOCOL, t0.PUBLICATIONDATE, t0.STORAGEIDENTIFIER, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.CHECKSUMTYPE, t1.CHECKSUMVALUE, t1.CONTENTTYPE, t1.FILESIZE, t1.INGESTSTATUS, t1.PREVIOUSDATAFILEID, t1.prov_entityname, t1.RESTRICTED, t1.ROOTDATAFILEID FROM DVOBJECT t0, DATAFILE t1
  20 SELECT ID, CONTROLCARD, FORCETYPECHECK, LABELSFILE, TEXTENCODING, datafile_id FROM INGESTREQUEST
  20 SELECT ID, CASEQUANTITY, ORIGINALFILEFORMAT, ORIGINALFILENAME, ORIGINALFILESIZE, ORIGINALFORMATVERSION, RECORDSPERCASE, UNF, VARQUANTITY, DATAFILE_ID FROM DATATABLE
  19 SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, name, REQUIRED, title, uri, VALIDATIONFORMAT, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE
  11 select count(o.id) from GuestbookResponse  o 
  10 SELECT ID, CITEDBYURL, DATASET_ID FROM DATASETEXTERNALCITATIONS
  10 SELECT ID, CHECKSUM, CONTENTTYPE, FILESIZE, FORMATTAG, FORMATVERSION, ISPUBLIC, ORIGIN, TYPE, DATAFILE_ID FROM AUXILIARYFILE
   7 SELECT ID, DISPLAYORDER, value, DATASETFIELD_ID FROM DATASETFIELDVALUE
   4 SELECT t1.ID, t1.CONTENTTYPE, t1.DESCRIPTION, t1.DISPLAYNAME, t1.SCOPE, t1.TOOLNAME, t1.TOOLPARAMETERS, t1.TOOLURL FROM EXTERNALTOOLTYPE t0, EXTERNALTOOL t1
   4 SELECT ID, DATASETFIELDTYPE_ID, DATASETVERSION_ID, PARENTDATASETFIELDCOMPOUNDVALUE_ID, TEMPLATE_ID FROM DATASETFIELD
   3 SELECT df.id FROM datafile df, filemetadata fm, datasetversion dv, dvobject o
   3 SELECT ID, DISPLAYORDER, PARENTDATASETFIELD_ID FROM DATASETFIELDCOMPOUNDVALUE
   2 SELECT ID, INFO, REASON, STARTTIME, DATASET_ID, USER_ID FROM DATASETLOCK
   2 SELECT ID, INCLUDE, REQUIRED, datasetfieldtype_id, dataverse_id FROM DataverseFieldTypeInputLevel
   2 SELECT DISTINCT t0.ID, t0.DTYPE, t0.DESCRIPTION, t0.DISPLAYNAME, t0.PERSISTEDGROUPALIAS FROM IPV4RANGE t1 LEFT OUTER JOIN PERSISTEDGLOBALGROUP t0 ON (t0.ID = t1.OWNER_ID)
   1 SELECT t1.ID, t1.DISPLAYORDER, t1.IDENTIFIER, t1.STRVALUE, t1.DATASETFIELDTYPE_ID FROM DATASETFIELD_CONTROLLEDVOCABULARYVALUE t0, CONTROLLEDVOCABULARYVALUE t1
   1 SELECT t1.ID, t1.DISPLAYNAME, t1.NAME, t1.namespaceuri, t1.owner_id FROM DATAVERSE_METADATABLOCK t0, METADATABLOCK t1
   1 SELECT t1.ID, t1.ADVANCEDSEARCHFIELDTYPE, t1.ALLOWCONTROLLEDVOCABULARY, t1.ALLOWMULTIPLES, t1.description, t1.DISPLAYFORMAT, t1.DISPLAYONCREATE, t1.DISPLAYORDER, t1.FACETABLE, t1.FIELDTYPE, t1.name, t1.REQUIRED, t1.title, t1.uri, t1.VALIDATIONFORMAT, t1.WATERMARK, t1.METADATABLOCK_ID, t1.PARENTDATASETFIELDTYPE_ID FROM dataverse_citationDatasetFieldTypes t0, DATASETFIELDTYPE t1
   1 SELECT t0.ID, t0.DATAFILE_ID, t0.UNF, t0.CASEQUANTITY, t0.VARQUANTITY, t0.ORIGINALFILEFORMAT, t0.ORIGINALFILESIZE, t0.ORIGINALFILENAME FROM dataTable t0, dataFile t1, dvObject t2
   1 SELECT t0.ID, t0.CREATEDATE, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PUBLICATIONDATE, t0.CREATOR_ID, t0.RELEASEUSER_ID, t1.CONTENTTYPE, t0.STORAGEIDENTIFIER, t1.FILESIZE, t1.INGESTSTATUS, t1.CHECKSUMVALUE, t1.RESTRICTED, t1.CHECKSUMTYPE, t1.PREVIOUSDATAFILEID, t1.ROOTDATAFILEID, t0.PROTOCOL, t0.AUTHORITY, t0.IDENTIFIER FROM DVOBJECT t0, DATAFILE t1
   1 SELECT t0.DATAFILE_ID, t0.TYPE FROM DataFileTag t0, dvObject t1
   1 SELECT id FROM fileMetadata
   1 SELECT ID, NAME, DATASET_ID FROM DATAFILECATEGORY
   1 SELECT ID, DISPLAYNAME, NAME, namespaceuri, owner_id FROM METADATABLOCK
   1 SELECT ID, CREATETIME, EMAILREQUIRED, ENABLED, INSTITUTIONREQUIRED, NAME, NAMEREQUIRED, POSITIONREQUIRED, DATAVERSE_ID FROM GUESTBOOK
   1 SELECT ID, CREATED, MESSAGE, TOBESHOWN, TYPE, AUTHENTICATEDUSER_ID, DATASETVERSION_ID FROM WORKFLOWCOMMENT
   1 SELECT ID, AUTHORITY, GLOBALIDCREATETIME, IDENTIFIER, IDENTIFIERREGISTERED, PROTOCOL, STORAGELOCATIONDESIGNATOR, DVOBJECT_ID FROM ALTERNATIVEPERSISTENTIDENTIFIER
   1 SELECT ID, ACTIVE, DISMISSIBLEBYUSER FROM BANNERMESSAGE
   1 INSERT INTO ACTIONLOGRECORD (ID, ACTIONRESULT, ACTIONSUBTYPE, ACTIONTYPE, ENDTIME, INFO, STARTTIME, USERIDENTIFIER) VALUES ('2145672a-ae75-4743-a11c-e7d992102932', 'OK', 'edu.harvard.iq.dataverse.engine.command.impl.GetLatestPublishedDatasetVersionCommand', 'Command', '2021-05-03 14:57:06.808', ':[211 Darwin''s Finches] ', '2021-05-03 14:57:06.807', ':guest')
   1 INSERT INTO ACTIONLOGRECORD (ID, ACTIONRESULT, ACTIONSUBTYPE, ACTIONTYPE, ENDTIME, INFO, STARTTIME, USERIDENTIFIER) VALUES ('03b01b7f-3d6a-446e-9e23-062772370d78', 'PermissionError', 'edu.harvard.iq.dataverse.engine.command.impl.GetPrivateUrlCommand', 'Command', '2021-05-03 14:57:06.837', ':[211 Darwin''s Finches]  Can''t execute command edu.harvard.iq.dataverse.engine.command.impl.GetPrivateUrlCommand@461c505d, because request [DataverseRequest user:[GuestUser :guest]@127.0.0.1] is missing permissions [ManageDatasetPermissions] on Object Darwin''s Finches', '2021-05-03 14:57:06.835', ':guest')
```

### CODE REVIEW

**Review by scolapasta — COMMENTED** [review]
This still goes to the db for each restricted file, no? It is definitely an improvement, but should we go further with this and call one query to get them all and then assign them appropriately?

**Comment by pdurbin** [comment]
@scolapasta right. This optimization is only for unrestricted files.

Should we go further? I don't know. I guess it depends on how much time and effort it takes. Please take a look at 6ac1946e1 which I pushed to a new branch. I haven't tested it but I believe it's the direction you have in mind.

Please advise on where we should go from here.

**Comment by landreev** [comment]
The net reduction in queries is great. But I am super curious to see how much *time* it saves, with that BZ7FPH dataset (for example), in a large (prod. copy) db. 
As we saw with the download-all issue, the numbers of queries do not directly translate into time (definitely not linearly). The queries saved in this PR are definitely a waste; but they weren't finding or instantiating any results... So I am just really curious to actually measure it.

**Comment by pdurbin** [comment]
Closing in favor of pull request #7853.

**Pull request closed without merging**
