### PR TITLE
Issue 2826

### PR DESCRIPTION
**Pull request by lwo**
This fix strips the first left side IP address from a a comma separated list of IP addresses in the  X-Forwarded-For header.

### CODE REVIEW

**Comment by pdurbin** [comment]
This is a proposed fix for the "IPv4Address exception using API via proxy" at #2826 (as @lwo noted in the subject of this pull request) so I believe the first step is to confirm that bug. Does the sound right @michbarsinai @scolapasta @landreev ?

**Comment by lwo** [comment]
To reproduce the error on the demo site, use this with your key:

curl -X GET --insecure --header "X-FORWARDED-FOR: 1.2.3.4, 5.6.7.8" "https://dataverse-demo.iq.harvard.edu/api/dataverses/harrisonlab?key=a_key"

**Comment by michbarsinai** [comment]
Looks like a great fix (and extra points for the unit test!).
Thanks, @Iwo!

**Comment by pdurbin** [comment]
Actually, now that I've merged the fix the latest from 4.2.3 into develop this pull request has merge conflicts. @lwo what's your take on all this? I'm trying to keep up on the conversation at #2826 and maybe the conversation is better continued there? I'm not sure.

**Comment by lwo** [comment]
Yes, I think @landreev commit at df200fcc3f122fea36745570cef89a8aa84b2a2c has precedence, until there is a proper advice on how to treat this XFF header. I will close this PR so that discussion can continue in 2826.

**Pull request closed without merging**
