### PR TITLE
make the application build w/ PrimeFaces 7

### LINKED ISSUE #5975: Upgrade to PrimeFaces 7
Saw this warning in my server log today while on the create dataset form, and it reminded me to create this placeholder issue for the eventual move to [PrimeFaces 7](https://www.primefaces.org/primefaces-7-0-final-released/) (released Mar '19).

```
Info:   autoUpdate attribute is deprecated and will be removed in a future version, use p:autoUpdate component instead.
```

For a background on this component, see my [comment on the _PrimeFaces 6.2 Upgrade_ issue](https://github.com/IQSS/dataverse/issues/4220#issuecomment-401107637)

Accessibility improvements are also a big selling point for the upgrade.

>Various components have been enhanced for accessibility related to keyboard support and screen readers.

From the PrimeFaces upgrade guide:

https://github.com/primefaces/primefaces/wiki/Migration-Guide

**6.2 to 7.0**

**Breaking Changes**

- Push has been removed. Please use the JSF2.3 socket or OmniFaces now.
- Mobile has been removed in favor of responsive features.
- RequestContext has been replaced by PrimeFaces.current(). RequestContext is still available as PrimeRequestContext but it's internal PrimeFaces API and should therefore be avoided to use.
- autoUpdate attribute of outputPanel, fragment, messages and growl has been removed. Use p:autoUpdate instead.
- OverlayPanel: appendToBody has been removed. Use appendTo="@(body)" instead.
- Button/Link/MenuItem: The url/href attribute isn't automatically prepended by contextPath anymore. Use the outcome attribute for referencing JSF views in the same application or manually prepend url/href with #{request.contextPath}. See https://github.com/primefaces/primefaces/issues/3506.

**Others**

- Schedule: Schedule was updated to the newest FullCalender version and therefore some attributes are deprecated.
    - Instead of slotMinutes, use slotDuration now (format: 12:30:00).
    - Instead of firstHour, use scrollTime now (format 12:30:00).
    - Instead of ignoreTimezone, use clientTimezone='local'
    - Instead of axisFormat, use slotLabelFormat

### PR DESCRIPTION
**Pull request by landreev**
## Related Issues

- closes #5975
## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by djbrooke** [comment]
@pdurbin OK, I'm happy to discuss but is that a reason to hold up this PR? I assume there were many security fixes (and other good stuff) included in 7, so while I'm happy to discuss longer term plans I don't see any reason not to upgrade now.

**Comment by pdurbin** [comment]
@djbrooke no, there is no need to hold up this PR. We're in an unfortunate situation when it comes to security but what I'd like is a strategy for how to not having cross-site scripting vulnerabilities such as https://github.com/primefaces/primefaces/issues/4913 in Dataverse. Should I create an issue for that specific security vulnerability as an example and we'll talk as a team about how to address it?

**Comment by djbrooke** [comment]
Thanks for letting me know it won't hold up this PR. I'll move it to QA. I think creating an issue for the Primefaces issue is fine, about whether to address it as a one off or to get consensus around a longer term strategy. Sounds like a good tech hours (or other venue) discussion with @scolapasta and other devs.

**Comment by pdurbin** [comment]
@djbrooke ok, I created https://github.com/IQSS/dataverse-security/issues/9

**Comment by djbrooke** [comment]
Helping @kcondon with testing for this and I got the message below under "Verbose" in Chrome Dev Tools once on dataverse-internal when loading the dataverse search page. I haven't been able to reproduce it on either dataverse-internal, production, or demo since. Not sure if it's related to this change, I'll let others decide. :)

`[Violation] Added non-passive event listener to a scroll-blocking ‘touchstart’ event. Consider marking event handler as ‘passive’ to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

Otherwise everything looks good! Nice work!

**Comment by kcondon** [comment]
Found this when editing file metadata from file page. Everything worked fine though:
```
file.xhtml?persistentId=doi:10.70122/FK2/RTP87H/891HZC&version=DRAFT:1 Uncaught TypeError: Cannot read property 'hide' of undefined
   at HTMLButtonElement.onclick (file.xhtml?persistentId=doi:10.70122/FK2/RTP87H/891HZC&version=DRAFT:1)
onclick @ file.xhtml?persistentId=doi:10.70122/FK2/RTP87H/891HZC&version=DRAFT:1
```

**Comment by mheppler** [comment]
After looking over the `5975-primefaces-7.0` locally in Chrome, I was finally able to replicate the warnings and errors reported by @djbrooke and @kcondon. I was also able to replicate them on demo.

- `[Violation] Added non-passive event listener...` can be seen on https://demo.dataverse.org/dataverse/demo (on page load)
- `Uncaught TypeError: Cannot read property 'hide'...` can be seen on https://demo.dataverse.org/file.xhtml?fileId=25&version=2.0 (click Explore btn, then click Cancel btn on Dataset Terms popup)
- `[Deprecation] Synchronous XMLHttpRequest...` can be seen on https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/VRNWIF (click Metadata tab)

None of these seem to cause any functionality to break. I was able to find a smoking gun related to the Uncaught TypeError on the file pg (`PF('blockDatasetForm').hide();`) but that is merely trying to hide an element that isn't on the file pg (it's only on the dataset pg). We can address this console error during dataset/file pg redesign efforts.

**Pull request merged**
