### PR TITLE
Adds new update dataverse general endpoint

### LINKED ISSUE #10904: Edit Dataverse Collection Native API endpoint
**Overview of the Feature Request**

We need an **_Edit Dataverse Collection_** Native API endpoint.
For the Edit Collection page in the SPA, we need to create first a  use case in js-dataverse for editing a collection and for that we need an API endpoint for editing a collection.
We have already implement a use case in js-dataverse for creating a collection which uses this [Create Dataverse Collection Native API endpoint](https://guides.dataverse.org/en/latest/api/native-api.html#create-a-dataverse-collection)

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
Q4 Roadmap

**What existing behavior do you want changed?**
None

**Any brand new behavior do you want to add to Dataverse?**
None

**Any open or closed issues related to this feature request?**
https://github.com/IQSS/dataverse-client-javascript/issues/200

### PR DESCRIPTION
**Pull request by GPortas**
**What this PR does / why we need it**:

Adds a new endpoint (`PUT /api/dataverses/<identifier>`) for updating an existing Dataverse collection using a JSON file following the same structure as the one used in the API for the creation.

**Which issue(s) this PR closes**:

- Closes #10904 

**Special notes for your reviewer**:

I have refactored commands `CreateDataverseCommand` and `UpdateDataverseCommand`, so that they now inherit from a common parent class called `AbstractWriteDataverseCommand`, where the shared logic of these commands is centralized.

**Suggestions on how to test this**:

- Create a Dataverse using JSF, or the UI
- Create a json file using https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/_static/api/dataverse-complete-optional-params.json as example. Include in the JSON file only the properties you want to update.

Call the new API endpoint using curl:

`curl -H "X-Dataverse-key:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -X PUT "http://localhost:8080/api/dataverses/<ALIAS_OF_CREATED_DV>" --upload-file <YOUR_JSON_FILE>
`

Verify that the new properties specified in the JSON are correctly reflected in the dataverse collection.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

Yes. Attached.

### CODE REVIEW

**Comment by DS-INRAE** [comment]
Hi @GPortas Sorry I didn't take a look at the code if it would have answered my question.
Does this new endpoint also addresses some of the editable elements of the collections that are hard-coded ?
- Related issue #9420

**Comment by GPortas** [comment]
> Hi @GPortas Sorry I didn't take a look at the code if it would have answered my question. Does this new endpoint also addresses some of the editable elements of the collections that are hard-coded ?
> 
> * Related issue [Feature Request/Idea: Make dataverses metadata configurable #9420](https://github.com/IQSS/dataverse/issues/9420)

Hi @DS-INRAE,

If I understood it correctly, your issue is related to creating custom metadata structures for collections, while this PR focuses on creating a new endpoint for updating existing collections based on the only structure currently supported.

So I think your requested changes are not related, sorry!

**Comment by sekmiller** [comment]
Not sure if it's 100% related to the issue at hand here, but I think it would be helpful in general and possibly to make this endpoint more useful for the non-SPA user if we updated the getDataverse endpoint/ jsonPrinter for Dataverses to include/return the metadata blocks for the Dataverse

**Comment by GPortas** [comment]
> Not sure if it's 100% related to the issue at hand here, but I think it would be helpful in general and possibly to make this endpoint more useful for the non-SPA user if we updated the getDataverse endpoint/ jsonPrinter for Dataverses to include/return the metadata blocks for the Dataverse

Yes, it is not entirely related to this issue, as we are only focusing on the creation of the dataverse through the API, not on reading it.

Currently, if you want to obtain the metadata blocks of the dataverse, you would have to call the listMetadata blocks endpoint separately from the getDataverse endpoint. It could be interesting, as you say, to offer the option in the future to get everything together in the getDataverse endpoint. We can create an issue to prioritize it according to the importance and user demand for this functionality.

**Review by sekmiller — APPROVED** [review]

**Comment by sekmiller** [comment]
@GPortas you should probably update this from DEV. A branch that I have a PR was failing until I got the reverted artifact branch that was just merged

**Comment by ofahimIQSS** [comment]
Testing Complete - No issues found. Merging PR. 
[Testing of 10925.docx](https://github.com/user-attachments/files/17619534/Testing.of.10925.docx)

**Comment by pdurbin** [comment]
I made a followup pull request here about docs:

- #11002

**Pull request merged**
