### PR TITLE
4448 api edit var meta

### LINKED ISSUE #4174: DDI Metadata Enrichment (Adding weights to variables) aka The Data Curation Tool
Having the ability to modify the DDI Metadata would be hugely beneficial for our community. 
Primarily, being able to assign which variable is the weight and what variables use this weight, noting that there may be multiple weights within a dataset. 

Here's how the DDI expresses weights:

**Weight assignment**
`<var ID="V22" name="WeightForAllQs" wgt="wgt" files="F1" dcml="12" intrvl="contin">`

**Weight assignment to variable**
`<var ID="V7" name="Q7" wgt-var="V22" files="F1" dcml="2" intrvl="discrete">`

**Calculate weighted frequency (done automatically upon assignment**
```
_<catStat type="freq">
500
</catStat>
<catStat wgtd="wgtd" type="freq">
479.707_
```

### LINKED ISSUE #4448: Provide API and internal framework for modifying variable-level (tabular) metadata.
This is the first concrete dev. issue being opened as part of work on #4174; based on the discussion with the Scholars Portal team (see the notes in that issue). 
The plan is to create an (external) tool that will allow the data owner to modify data variable metadata (for example: add weights to variables; change variable type; add categorical labels... etc. in order to make the metadata more descriptive and/or accurate). 

On the Dataverse end, we need to provide an API to accept the updated version of the metadata (in DDI/xml format) and save it in the database permanently. 

Creating this API endpoint would be trivial; so is parsing variable-level DDI (we already have legacy code for this, that we inherited from the DVN project). The main technical challenge is that, as of now, our tabular (data variable) metadata are *immutable*. The DataVariable objects are created during tabular ingest; they are linked directly to DataFile objects (bypassing versionable FileMetadata hierarchy). With no mechanism provided for modifying the information in this objects. 

So the first task is  to make the DataVariable metadata versionable. We may need to invest some thought into how we want to achieve this. A trivial solution would be to simply replicate what we are doing with all the other metadata. By simply linking the DataTable->DataVariable hierarchy to FileMetadata (instead of DataFile); thus allowing multiple versions of DataVariables associated with the same DataFile; the same way the same DataFile can have different file names in different versions. 
HOWEVER, this system is fairly wasteful by design. If you have a dataset and you modify a single metadata field - fix a typo in the title, for example - we always create a new DatasetVersion, that duplicates ALL THE METADATA fields that existed in the previous version (not just the changed title!), including all the FileMetadata information associated with every file in the dataset. Making all the variable-level metadata subject to this automatic duplication will increase the size of the database by on order of magnitude or worse, I believe. We probably want to avoid this, by designing some mechanism for creating new versions of these variable-level metadata only when there is an actual change. We should be able to reuse the same DataVariable objects between different versions, until an actual change is made - and then we create a new one. This would warrant a dedicated architecture discussion. 

Aside for that, all very doable.

### PR DESCRIPTION
**Pull request by lubitchv**
New API endpoint in  EditDDI.java  for updating variable level metadata. 
It is used in Data Curation Tool and also can be called using curl command with corresponding xml file.

## Related Issues 

Closes #4448 
Closes #4174

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ X] Integration [tests][]: EditDDIIT.java
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ x] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

### CODE REVIEW

**Comment by djbrooke** [comment]
Hey @lubitchv, nice to meet you last week! Thanks for all of your work on this so far! We'll review this ASAP. Do you feel that this issue should close out both of the issues linked above (#4448 and #4174) or do you think there's additional work to be done? Let us know if we can help with any documentation or other guidance. 

Thanks again!

**Comment by lubitchv** [comment]
Hi @djbrooke, I was also glad to meet all of you last week. Yes, I think this pull request will close both issues. #4174 for sure, since weights were added in this pull request. The only think that left is a codebook (pdf and html). But this can be done in separate issue and it is not directly related to the external tool. Further enhancements also can be done such as making categories editable, they are not editable in external tool at the moment. But this is for future work maybe.

**Comment by djbrooke** [comment]
@dlmurphy and I added some docs to the dataset management page and moved the API documentation under the "files" header in the API docs.

**Comment by pdurbin** [comment]
@lubitchv I just made this pull request against your pull request: https://github.com/lubitchv/dataverse/pull/23

Please take a look and merge it if you're happy with it. Then I'll move this pull request to QA.

If you don't like anything in my pull request, please let me know!

I'm excited about the Data Curation Tool! After talking to @djbrooke we decided to go ahead and add it to the list of external tools. This means someone will need to add some installation instructions to the README at https://github.com/scholarsportal/Dataverse-Data-Curation-Tool just like https://github.com/scholarsportal/Dataverse-Data-Explorer#installation

**Comment by pdurbin** [comment]
> This means someone will need to add some installation instructions to the README at https://github.com/scholarsportal/Dataverse-Data-Curation-Tool just like https://github.com/scholarsportal/Dataverse-Data-Explorer#installation

I just created an issue for this: https://github.com/scholarsportal/Dataverse-Data-Curation-Tool/issues/4

**Comment by lubitchv** [comment]
@pdubrin I merged your pull request into mine.

**Comment by pdurbin** [comment]
@lubitchv thanks! I moved your pull request to QA. Please don't forget to work on https://github.com/scholarsportal/Dataverse-Data-Curation-Tool/issues/4 so the Dataverse community can start installing and using this great new tool!

**Comment by kcondon** [comment]
@lubitchv FYI, curation tool persists weighted var on selected var even if cancel, eg. make var 1 wgt, make var2 have var1 as wgt but then cancel. If view, var2 still has var1 as wgt unless choose unweighted.

**Comment by lubitchv** [comment]
Thank you, @kcondon 
1) Persistence of weighted var on selected var even if cancel is indeed a bug in UI Data Curation Tool. I started  working on fixing it. But it does not have a direct connection to this pull request (API), it is an UI issue. Thank you for noticing it.

2) Save edits does not work in DCT if one integrates external tool with siteUrl (for example github). Then it runs into issue of CORS. We should discuss it. How should we allow PUT from external site.  But if one integrates external tool putting it in webapps and compiling it with dataverse, getting it in war file then save edits works.
This issue can be treated as separate issue and I was planning to open an issue for that.

3) Version tab indeed shows difference type but no details. It was done on purpose. The reason for it: there can be hundreads of variables that may be updated. It was not clear how to present it in dataverse UI. And we probably should think how it can be done and we left it for later work.

**Comment by kcondon** [comment]
@lubitchv OK, makes sense. Thanks. What does the 1 represent in: "Variable Metadata (Changed Variable Metadata: 1); View Details"

**Comment by lubitchv** [comment]
@kcondon  1 represents number of files changed, not a number of variables, since in in one dataset can be several files that maybe updated.

**Comment by kcondon** [comment]
@lubitchv OK, thanks. Will move it back to qa. Ready to merge, pending point release planning. It may need refresh from develop if it is not included in point release.

**Comment by ingridpacheco** [comment]
Hey guys, I hope you can help me out with this problem. I tried using this endpoint to update my variable level metadata, but it turns out that it didn't really update it and nothing happened.

I followed exactly the steps in the documentation and performed a curl updating my file with an XML file: 

`curl -H "X-Dataverse-key:xxxxxx" -X PUT https://gofairbr.rnp.br/api/edit/118 --upload-file dct.xml`

As a response, I received an empty object on my terminal screen and when I went to check my file on Dataverse, its variable metadata was exactly the same, as if I have never updated it.

Captura de Tela 2021-11-09 às 23 22 39

Do you have any idea what could have happened? Do I need special permission to do this or only being the owner of my dataset is enough? Does this endpoint need any special input that I am not aware of?

Thanks in advance,
Ingrid

**Comment by lubitchv** [comment]
Hello @ingridpacheco,

How do you get the dct.xml file? 

The best way to get it is to get first variable metadata for specific file:
`curl -H "X-Dataverse-key:XXXX" -X GET https://$SERVER/api/access/datafile/8484/metadata?fileMetadataId=$ID` where $ID is file metadata id for that specific file. You also can get it from UI from Download->Variable Metadata. Then update the needed fields, for example label,  or add additional fields. It maybe that XML is wrongly formatted or fields that are not allowed were added or edited. 

Do you update publish version or Draft version? If it is published version, the new Draft version should be created.
How do you check that variable metadata remaines the same? 

Another way to update variable level metadata is to use "Data Curation Tool". If your installation has it, you should see "Configure" drop-down  on the right side of files listing. You can update variable metadata using that tool.
Also with "Data Curation Tool" you can see the variable level metadata.

It would be useful if you could attach original xml and updated xml (dct.xml in your example).

**Comment by pdurbin** [comment]
@ingridpacheco thanks for opening this new issue about this:

- API endpoint to update variable level metadata not working #8231

**Pull request merged**
