### PR TITLE
6053 - Add custom configuration for wei/pull to enable auto-sync forks

### PR DESCRIPTION
**Pull request by poikilotherm**
## Related Issues

- #6053

## Pull Request Checklist

- [x] Documentation completed
- [x] Merged latest from "develop" and resolved conflicts

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @poikilotherm for the PR. I assigned this to myself at standup with the intention of getting some feedback from some of the more regular community contributors to Dataverse. So, two quick questions for @qqmyers @lubitchv @JayanthyChengan @donsizemore @carlosmcgregor @mdmADA @PaulBoon and others:

- Is the issue that @poikilotherm describes a common issue for the community developers? 
- Is what @poikilotherm suggested here a good solution? Are there other projects that do this in a better way, with or without tools like this?

Thanks in advance for any feedback!

**Comment by carlosmcgregor** [comment]
Hello @djbrooke ~!

- It feels that this is a convenient tool to have in order to keep you on your toes re: the state of the upstream. However, if you religiously `pull` from `upstream` as part of your workflow, then this will have less of an impact. Probably people who have worked on larger features like @JayanthyChengan and @lubitchv can provide more valuable feedback.
- I have never thought of this as an issue per se, so I do not know of any other solutions to this.

Hope that helps!

**Comment by JayanthyChengan** [comment]
@djbrooke - Yes, as @carlosmcgregor mentioned I do perform 'git pull' more frequently,  and never tried any tools for this purpose.  This might be a useful one.

**Comment by qqmyers** [comment]
@djbrooke - I primarily work through Eclipse and sync when needed. I don't think I'll set it up, but I don't see a problem in having a pointer in the dev docs either.

**Comment by djbrooke** [comment]
Thanks @carlosmcgregor @JayanthyChengan and @qqmyers for the feedback!

**Pull request closed without merging**
