### PR TITLE
5886 link harvested datasets via api

### LINKED ISSUE #5586: JSF errors when adding a dataset: duplicated component IDs
Steps to reproduce:
1. Use Firefox 60+
2. Start a fresh installation, preferrably using Minikube and IQSS/dataverse-kubernetes
3. Create a dataset and watch the errors in the logs ([exception-log.txt](https://github.com/IQSS/dataverse/files/2914803/exception-log.txt)).

I am not sure if this is something related to my setup and could not yet investigate further. Maybe others have seen those, too?

### LINKED ISSUE #5886: Dataset linking API doesn't work for harvested datasets
When trying to create a link of a dataset that has been harvested, using the API (http://guides.dataverse.org/en/latest/api/native-api.html#link-a-dataset) I get the error that I "can't link a dataset that has not been published." I am able to create links of some harvested datasets (e.g. the datasets in https://dataverse.harvard.edu/dataverse/nara), but not others (e.g. the datasets in https://dataverse.harvard.edu/dataverse/qdr).

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**:
Allows a user to link a harvested dataset via the api. Previously there was a test that required that the dataset be published before it could be linked. This expands the test to allow datasets that haven't been published but are harvested to be linked

**Which issue(s) this PR closes**:

Closes #5886 

**Special notes for your reviewer**:
I wasn't able to come up with a way to test this in the integration test. Any suggestions here would be welcome. (I tested by manually giving an unpublished dataset a dummy harvesting client id)

**Suggestions on how to test this**:

**Does this PR introduce a user interface change?**:
no

**Is there a release notes update needed for this change?**:
no

**Additional documentation**:
None

### CODE REVIEW

**Comment by kcondon** [comment]
@sekmiller I have some questions when you have a minute:
1. how does it fix the issue it closes since it appears to be ui related and create dataset related.
2. how can you harvest unpublished datasets for them to be linked in the first place?

**Comment by scolapasta** [comment]
Right, the issue wasn't unpublished, harvested (which can't exist), but (some) harvested datasets being identified as unpublished, possibly because they were missing a publication date in the db.

**Comment by kcondon** [comment]
@scolapasta Do you have a known test case? Also, what about the issue it purports to close with the JSF errors?

**Comment by scolapasta** [comment]
JSF issue was just a type - 5586 instead of 5886. (I just fixed it for @sekmiller in the description)

**Comment by scolapasta** [comment]
as for test cases, here is a search results of four harvested datasets in production that could not be linked:

https://dataverse.harvard.edu/dataverse/harvard?q=covid+coronavirus&fq1=metadataSource%3A%22Harvested%22&fq0=dvObjectType%3A%28dataverses+OR+datasets+OR+files%29&types=dataverses%3Adatasets%3Afiles&sort=score&order=

(can't link to dataset pages of course, because they don't have any. - here are there dbids for the API: 3822842, 3724321, 3767398, 3767393 )

**Comment by kcondon** [comment]
@scolapasta Thanks, just found that out from Julian as well.

**Pull request merged**
