### PR TITLE
5822 export var meta

### PR DESCRIPTION
**Pull request by lubitchv**
fileMetadataId optional parameter was added to export variable metadata API. fileMetadataId parameter was also added to ExternalTool. PostQuestion column was added to VariableMetadata. Also treatment of  VarGroup and other var metadata for variables was included in export xml.

- connects to #5822 

## Pull Request Checklist

- [x ] Unit [tests][]  updated
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
> could you please document the extra API parameters in the API guide

@lubitchv if you need any advice on this please feel free to ask her in the pull request or in http://chat.dataverse.org and I'll be happy to help. Thanks!

**Comment by lubitchv** [comment]
@landreev I updated spinx guide doc for dataaccess api

**Comment by pdurbin** [comment]
@lubitchv thanks! @landreev is out today but he asked us to move this to QA once the docs are in, which I just did. I built the docs locally and they look good! (I haven't tested the code.) Thanks!

**Comment by kcondon** [comment]
@lubitchv Please refresh your branch from /develop since our version number has changed. Thanks!

**Comment by lubitchv** [comment]
@kcondon I updated the branch from develop.

**Comment by lubitchv** [comment]
@kondon Should I also rename V4.13.0.1__5822-export-var-meta.sql into V4.14.0.1__5822-export-var-meta.sql ?

**Comment by pdurbin** [comment]
@lubitchv good catch. I renamed it for you in 49f74df03 just as you suggested.

**Comment by pdurbin** [comment]
We need to adjust the flyway script because new installations cannot deploy the war file. For details, please see #5862.

**Pull request merged**
