### PR TITLE
Update the description for the Data Explorer

### PR DESCRIPTION
**Pull request by kevinworthington**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #ISSUE_NUMBER: ISSUE_TITLE

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/4.6.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
@kevinworthington thanks! Merged! You're welcome to add a pull request that fixes the tests, if you like. 😄

**Comment by pdurbin** [comment]
`Failed tests:   testGetToolUrlWithOptionalQueryParameters(edu.harvard.iq.dataverse.externaltools.ExternalToolHandlerTest)` at https://travis-ci.org/IQSS/dataverse/builds/324749098 I mean. I was in a rush on get some code pushed before getting my daughter to basketball practice yesterday.

**Comment by kevinworthington** [comment]
Ok, I'll have a look first thing tomorrow.

**Comment by pdurbin** [comment]
@kevinworthington that's ok. I was off today (snow day) but I'm pretty sure I'm working from home tomorrow and will take care of it. I do want to check in with you about the Explore button but I'll leave a comment, probably with screenshots, in #3657.

**Comment by kevinworthington** [comment]
Alright @pdurbin, Will look for your comment.

**Comment by pdurbin** [comment]
@kevinworthington ok, I just left a comment in #3657 that's even longer than I expected. I hope it makes sense. Let's move the conversation there. Thanks.

**Pull request merged**
