### PR TITLE
Update DublinCoreExportUtil.java

### PR DESCRIPTION
**Pull request by rmo-cdsp**
# RFI Checklist
### 1. Related Issues

_List and [link](https://guides.github.com/features/issues/#notifications) to the issues in this Pull Request._
- #3368 Possible error in oai-pmh xml output file (dc elements namespace and uses)
- #3307 Harvest: Investigate OAI-PMH protocol test for registration as a data provider.
---
### 2. Pull Request Checklist
- [ ]  Functionality completed as described in FRD
- [ ]  Dependencies, risks, assumptions in FRD addressed
- [ ]  Unit tests completed
- [ ]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [ ]  Documentation completed
- [ ]  All code checkins completed
---
### 3. Review Checklist
- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

Connects to #3368.

### CODE REVIEW

**Comment by pdurbin** [comment]
@landreev I just moved this pull request to Code Review in https://waffle.io/IQSS/dataverse and am assigning it to you based on your comment to @rmo-cdsp at https://github.com/IQSS/dataverse/issues/3307#issuecomment-253254031 that the fix has been incorporated into your pull request at #3409. Can we update pull request #3409 to say it fixes #3368 (assuming it does!) and connect it that issue in Waffle with the magic "connects to" syntax? Assuming the fix is elsewhere, this should allow us to close this pull request.

**Comment by kcondon** [comment]
Hi @rmo-cdsp,
I'm testing your code just prior to merging but am running into a problem publishing datasets. Can you update your branch from /develop? It's failing to publish datasets due to a column change.

Regards,
Kevin

**Comment by rmo-cdsp** [comment]
Hey,

What about now ?

**Comment by kcondon** [comment]
Still not working. The patch-1 branch in your pull request is still behind though it looks like you updated your own develop branch. @pdurbin any suggestions?

**Comment by rmo-cdsp** [comment]
I'll make a clean branch tonight if needed, can't do this right now, got
stuff to do.

2016-11-03 15:30 GMT+01:00 kcondon <notifications@github.com>:

**Comment by kcondon** [comment]
OK, thanks! Sorry for the delay.

**Comment by pdurbin** [comment]
@rmo-cdsp I just created a new pull request at #3458 based on your fix at 4d783b3.

**Comment by kcondon** [comment]
This was merged through pull request 3368-dc-elements-only. Closing.

**Pull request closed without merging**
