### PR TITLE
#5245 - fix global id url parsing when parsing OAI

### PR DESCRIPTION
**Pull request by tcoupin**
## Related Issues

- connects to #5245 Harvesting OAI with URL identifier fail

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pameyer** [comment]
on 756fa24a10ec145c0a443ffada7b53c704549599:
```
[ERROR] Failures: 
[ERROR]   FileMetadataIT.testJsonParserWithDirectoryLabels Multiple Failures (2 failures)
        Expected status code <201> doesn't match actual status code <500>.

        Expected status code <200> doesn't match actual status code <404>.

[INFO] 
[ERROR] Tests run: 79, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by tcoupin** [comment]
@pameyer I can not reproduce the test fail:

```
$ mvn test -P all-unit-tests
...
[WARNING] Tests run: 564, Failures: 0, Errors: 0, Skipped: 6
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.443 s
[INFO] Finished at: 2018-10-31T06:26:13Z
[INFO] ------------------------------------------------------------------------
```

It's the same on Travis Build https://travis-ci.org/IQSS/dataverse/builds/448350282#L6777

**Comment by pdurbin** [comment]
@tcoupin hi! Travis is only executing unit tests. We also have integration tests but we have not automated this very well. Running them requires effort on the part of each developer.

@pameyer is using Docker to run the integration tests. Please see http://guides.dataverse.org/en/4.9.4/developers/testing.html#running-the-full-api-test-suite-using-docker

**Comment by tcoupin** [comment]
on https://github.com/IQSS/dataverse/commit/756fa24a10ec145c0a443ffada7b53c704549599 using docker-aio

```
[WARNING] Tests run: 79, Failures: 0, Errors: 0, Skipped: 1
```

**Comment by pdurbin** [comment]
@tcoupin well, the failure we're seeing on phoenix has to do with account conversion: #5260

**Comment by tcoupin** [comment]
Merge done, comment removed

**Pull request merged**
