### PR TITLE
Bundle trouble #5078

### PR DESCRIPTION
**Pull request by pdurbin**
connect to #5078

### CODE REVIEW

**Comment by JayanthyChengan** [comment]
@pdurbin : when we deploy the app from develop branch ( if the JVM option is not set for 
-Ddataverse.lang.directory and if the /tmp/lang directory doesn't exists ) ,  then the app should not look for files in file system and it should not throw exception while deploying.

**Comment by pdurbin** [comment]
@JayanthyChengan ok, thanks. I'm not sure why it's throwing an exception then. Very strange.

**Comment by JayanthyChengan** [comment]
@pdurbin : 
The changes in BundleUtil.java is fine.
Do we still need the quick fix comments in doc/sphinx-guides/source/developers/dev-environment.rst ?

**Comment by pdurbin** [comment]
@JayanthyChengan I hope not. I just reverted it in 9ce1b3a

**Comment by JayanthyChengan** [comment]
The logic in src/main/java/edu/harvard/iq/dataverse/util/BundleUtil.java looks good.

We have to follow the same logic in src/main/java/edu/harvard/iq/dataverse/util/LocalBundle.java ( which is used in faces-config.xml) for resourcebundle.

**Comment by JayanthyChengan** [comment]
@sekmiller:
After reading the comment at https://github.com/IQSS/dataverse/issues/5078#issuecomment-424365753
    
Noticed that the if-condition at https://github.com/IQSS/dataverse/blob/26bb4280f0cb8e4d97e26dc769c120ff901c31a1/src/main/java/edu/harvard/iq/dataverse/util/BundleUtil.java#L31 , checks only if the **length of string** is 0 ,

Not checking whether the directory set from JVM **exists** and whether the directory contains files.

I feel, it's better to check that the directory mentioned in the JVM option exists and is not empty.

**Comment by sekmiller** [comment]
Hi  @JayanthyChengan, we did make a change to the logic so that if the jvm option is present we want to throw a missing resource error if the directory isn't present - just in case there's a typo in the jvm option, say and the installation would silently go about its business using the default bundles. 

If you disagree with this approach, please let us know why.

Thanks!

**Comment by JayanthyChengan** [comment]
@sekmiller:  It's clear now, and I accept your suggestion.  Thanks for the explanation

**Pull request merged**
