### PR TITLE
4874 openshift pull policy

### PR DESCRIPTION
**Pull request by pdurbin**
connects to #4874

### CODE REVIEW

**Comment by danmcp** [comment]
@pdurbin This PR shouldn't have the first commit in it right?  That was submitted in a different PR already.

**Comment by pdurbin** [comment]
@danmcp yeah, I'm not so good with git, I guess. 😄 

I'm planning on piling another commit on this pull request to git ignore `conf/docker/dataverse-glassfish/init-container/postgres-setup`

**Comment by pdurbin** [comment]
The commit to focus on is 8587646 where I put this message:

 internal minishift registry works with "IfNotPresent" #4874

In ec5e821 I finally got the internal minishift registry working which
saves me a ton of time and bandwidth pushing and pulling large images to
and from Docker Hub. So far, the "IfNotPresent" pull policy works for me
but the "Always" pull policy does not. Under "Always", the images
continue to be pulled down from Docker Hub rather than the internal
minishift registry.

Any objections?

**Comment by pdurbin** [comment]
@danmcp I got rid of the other commit (the one for pull request #4885) by merging the latest from develop in 58791f6

**Pull request merged**
