### PR TITLE
add S3 tests, LocalStack, MinIO

### LINKED ISSUE #6783: Add S3 tests to the regular integration test suite
We rely heavily on S3 storage, including in our production use, but there are no regularly-run integration tests for the functionality.
We do already have a RestAssured test class (test/java/edu/harvard/iq/dataverse/api/S3AccessIT.java) with one test, written by @bsilverstein (hi!). We are not regularly running it on jenkins.dataverse.org. 
S3 needs to be configured on the test bed installation for the test to work. But since our new jenkins infrastructure already depends on utilizing AWS, this is not an issue. We would just need to modify our scripts to copy the AWS credentials to the target EC2 instance and configure an S3 file store there. 

So I propose we do that; plus extend the S3 test class above, for some more extensive testing and to test the functionality that's been added since it was written. (for example, as it is now, the test relies on having S3  configured as the default storage driver. We can instead make it create a new dataverse, set S3 as the storage for that specific dataverse, using the new multistore functionality, and proceed testing it)

S3 testing was specifically requested in #5068. But I'm opening a dedicated issue for it since there were other things being discussed there.

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

Developers can now test S3 locally by using the Dockerized development environment, which now includes both LocalStack and MinIO. See S3AccessIT which executes API (end to end) tests.

In addition, a new integration test test class
(not an API test, the new kind launched with `mvn verify`) has been added at S3AccessIOLocalstackIT. It uses Testcontainers to spin up Localstack for S3 testing and does not require Dataverse to be running.

~~TODO: Exercise direct upload, possibly borrowing [code from DVUploader](https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/blob/b5d85a7ea1e4f3790f32a150e98de07adc265396/src/main/java/org/sead/uploader/dataverse/DVUploader.java#L966).~~

**Which issue(s) this PR closes**:

- Closes #6783

**Special notes for your reviewer**:

Note that the format of docker-compose-dev.yml had to change to allow for JVM options to be added.

**Suggestions on how to test this**:

mvn -Pct clean package docker:run

mvn test -Dtest=S3AccessIT

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

Yes, included.

**Additional documentation**:

Tweaked various docs:

- Listing and setting stores via API.
- Using the direct upload API.

### CODE REVIEW

**Comment by jp-tosca** [comment]
I am testing this right now on a Windows/Containers environment and when I run the tests the first time after the containers start they run successfully, after this if I run the same tests again the "testNonDirectUpload" will fail. If I restart the containers it will work again. 

`edu.harvard.iq.dataverse.datasetutility.NoFilesException: newlyAddedFiles is empty!`

**Comment by jp-tosca** [comment]
I ran this test on my Mac environment. The first time I tried to run the tests they failed with the following stack trace:

`com.amazonaws.SdkClientException: Unable to execute HTTP request: s3.localhost.localstack.cloud
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)`

After connecting to the VPN the tests run fine.

**Comment by pdurbin** [comment]
@jp-tosca @poikilotherm and I just discussed three old issues and I am in the process of reaching out to the people who opened them to ask if they can be closed as no longer relevant since we've significantly refactored the code since they were opened:

- #5062
- #5065
- #5068

**Comment by jp-tosca** [comment]
I wanted to post an update since I was doing some more testing tonight, this test is failing when you try to list the buckets from s3localstack:

`for (Bucket bucket : s3localstack.listBuckets()) {
            System.out.println("bucket: " + bucket);
}`

The issue may be on the container; if I try to access s3.localhost.localstack.cloud:4566
without a VPN this is the output:
image

While on VPN:
image

Another thing that I noticed while testing was, if for any reason the test pauses for 45 seconds before listing the buckets a timeout will happen and when the buckets are printed they will be null, the test ends successfully so it seems this code is not used for the test, should we remove it from it?

**Comment by donsizemore** [comment]
@jp-tosca I got things (mostly) working this morning; discovered what we believe is a bug in Dataverse in the process. Just wanted to document here that, while MinIO doesn't like repeated attempts to create a bucket via AWS CLI, re-running S3AccessIt tests manually doesn't return an error. Rocky Linux 8, LocalStack and MinIO are Dockerized.

**Comment by donsizemore** [comment]
Screenshot 2023-12-06 at 10 22 25

**Comment by pdurbin** [comment]
I approved the PR on the Ansible side:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/pull/337

Thank you, @donsizemore for all the hard work! 🚀 ❤️ 🎉 

Once it's merged, we'll kick off another build to see if Jenkins starts passing.

**Review by jp-tosca — APPROVED** [review]

**Pull request merged**
