### PR TITLE
Issue #6514: Implement affiliation reading from Shibboleth attribute.

### LINKED ISSUE #6514: Optionally read affiliation from a Shibbolet attribution instead of DiscoFeed
In our Shibboleth implementation the DiscoFeed contains only one service name, and the user's affiliation is stored in an attribution of the XML file sent by Shibboleth service. This makes several problems:

1) the service name is not an organisation name
2) the user can not change the bad affiliation string
3) the bad affiliation string occurs in every dataverse and dataset creation form as a default value

This situation is frustrating for bot our users and us.

Here is a suggestion for a Dataverse code change to solve this issue. It would have multiple components (all of these are pseudo code):

1) adding an optional configuration setting: `affiliationSource` for the source of affiliation with two options:

* DiscoFeed (default value, and runs the current code without any modification)
* a Shibboleth attribute name

2) configure Shibbolet to send the attribute we set in step 1

3) within `ShibServiceBean.getAffiliation()` method add a switch like this:

```
AffiliationSource affiliationSource = ... // read configuration
switch (affiliationSource.getType()) {
  case AffiliationSource.Shibbolet:
    String shibbolethAttribute = affiliationSource.getShibbolethAttribute();
    String affiliation = readAffiliationFromAttribute(shibbolethAttribute);
    break;
  case AffiliationSource.DiscoFeed:
  default:
    String affiliation = ... // run current code
    break;
}
```

`AffiliationSource` has a type, which is an enum of `ShibbolethAttribute` and `DiscoFeed`, and a `shibboletAttribute` (String) field, which contains which attribute should be used.

note: this comment is summary of a thread at the dataverse-community mailing list: https://groups.google.com/forum/#!topic/dataverse-community/7FwrzfIQZfY.

### PR DESCRIPTION
**Pull request by pkiraly**
**What this PR does / why we need it**: It adds a new setting :ShibAffiliationAttribute, which contains the name of a Shibboleth attribute (as a string), which attribute holds the affiliation of the user. If it is set, Dataverse reads the content of the attribute from the Shibboleth response, otherwise it reads from the DiscoFeed (which is currently the one and only source of affiliation). DiscoFeed is a wrong source in our use case. A closely related problem is that Dataverse overwrites the affiliation from Shibboleth for every login, so as a site admin it is not an option to fix the wrong data comes from the DiscoFeed by changing the database, because the next login eliminate my changes.

**Which issue(s) this PR closes**: #6514 

Closes #6514

**Special notes for your reviewer**: The configuration this PR implements adds a new database setting. I am aware that @poikilotherm is working on a related issue #6694 which will provide a common configuration for all authentication related settings. Once that ticket will be ready, we can modify this mechanism to use the JSON configuration. On the meantime I also provided documentation for the database setting.

**Suggestions on how to test this**: 
1. First the site admin should contact the Shibboleth administration to ask how to modify attribute-mapping.xml in order to retrieve the affiliation value. 
2. Then it should be tested and check the transaction log if the attribute is arrived. Let's suppose the Shibboleth response contain "ou" attribute as the affiliation.
3. Set the database setting:
```
curl -X PUT -d "ou" http://localhost:8080/api/admin/settings/:ShibAffiliationAttribute
```
4. log in, and check on the account data if the affiliation string has been changed (the value should come now from the Shibboleth attribute).
5. Log out, and delete the database setting:
```
curl -X DELETE http://localhost:8080/api/admin/settings/:ShibAffiliationAttribute
```
6. log in, and check on the account data if the affiliation string has been changed again back to the previous value (comes from DiscoFeed).

**Does this PR introduce a user interface change?**: no

**Is there a release notes update needed for this change?**: Yes, refer to the documentation this PR provides

**Additional documentation**: Yes, in the commit.

### CODE REVIEW

**Comment by djbrooke** [comment]
Hi @pkiraly - thanks for the PR. Can you give me write access to this branch? I'll work with a developer to review this and also make some doc changes. Thanks!

**Comment by pkiraly** [comment]
@djbrooke I made you a collaborator. Ping me if it is not working.

**Comment by djbrooke** [comment]
@pkiraly Yes, you're exactly right. I've updated with https://github.com/IQSS/dataverse/pull/6729/commits/5a27cdf4d599fb1ad08b5ed1ab537dc54d430df1. Thank you!

**Comment by pkiraly** [comment]
This PR was developed by Göttingen eResearch Alliance, Germany, and funded by SSHOC, "Social Sciences and Humanities Open Cloud". SSHOC has received funding from the European Union’s Horizon 2020 project call H2020-INFRAEOSC-04-2018, grant agreement #823782.

**Pull request merged**
