### PR TITLE
4260 jakarta

### LINKED ISSUE #4260: Java EE 8 Upgrade
At some point we should upgrade to Java EE 8 to gain the power of new java technology and remain secure.

Outcome of the #4217 spike.

### LINKED ISSUE #6230: Upgrade from Glassfish 4.1
Dataverse is currently running on a (modified) Glassfish 4.1. This has served us well, but is old and no longer actively supported. Especially in light of the upcoming DataTags integration, we want to upgrade to a new app server for security uogrades, as well as being able to leverage newer features (e.g. Config API) and enable upgrades of other core technology (e.g. Java EE 7 -> Jakarta EE 8).

There are a few options to explore. Some work has already been done for Payara 5, and this tickets will serve for both  for the evaluation of that and some other candidates (TomEE, Glassfish 5, Wildfly), and the actual upgrade.

Note that I'm closing this old issue #2628 with a very similar title, as that is several years old now and was originally about upgrading to 4.1.1. 

Let's use this issue going forward for comments related to upgrading from glassfish 4.1.

(per request, also adding a link to the GH project that references subtasks related to this upgrade: https://github.com/orgs/IQSS/projects/16)

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
When moving to Payara 5, we should move to Jakarta EE 8 (which is technically identical to Java EE 8). This is also unlocking new features like JSON-B, needed for #6694.

**Which issue(s) this PR closes**:

Closes #4260
Relates to #6230

**Special notes for your reviewer**:
I moved some dependencies around, too. Will further cleanup messy deps list when working on #6698. (Please note that I didn't move the GF JSON lib, this will change when with #6694.)

**Suggestions on how to test this**:
Compile and both unit and API tests should not fail.
We should test the usual happy pathes.

[added by @scolapasta: let's ket this be the issue that closes #6230, when ready to do final Payara testing, let's make sure this is merged with dev and then test this branch on Payara (other branches related to this work have been made so they also work on gf4; this one may not work*)]

(*) it might be interesting to try it on gf4, but that is not necessary

**Does this PR introduce a user interface change?**:
Nope.

**Is there a release notes update needed for this change?**:
Jakarta is wht cool kids use these days for EE development. We should add sth. to spread the word we are part of the cool gang and that devs should now start to use new standardized APIs.

**Additional documentation**:
Nothing so far.

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @poikilotherm for the PR.

@scolapasta going to assign to you for thoughts. With Draft PRs I don't know if there's something special we should handle process-wise, as they are specifically designed not to move forward to QA. Maybe in the template we should include a different field for what the person is expecting to get out of the review of a Draft PR... are there specific questions that need answering? I guess this would go back to Community Dev once CR feedback is added? Happy to talk if it's easier...

**Comment by poikilotherm** [comment]
I made this a draft to create a base for discussion. There might be things missing, like the release note. And maybe some proposed changes are not what you folks want...

**Comment by poikilotherm** [comment]
Should I refactor the three occurences of deprecated Beans, too?

With JSF 2.3, a few beans from Faces have been deprecated, see https://javaserverfaces.github.io/docs/2.3/managed-bean-javadocs/deprecated-list.html

image

**Comment by scolapasta** [comment]
@poikilotherm I approved before I saw the above comment; yes go ahead and let's refactor those now.

**Comment by poikilotherm** [comment]
Here we go, c0d24b0 was an easy one. Replaced the deprecated `@SessionScoped` and removed the other deprecated annotations. They already where annotated with `@Named`, so no real changes. I don't expect anything to break from this, as it's simply about easy cases of CDI.

**Comment by scolapasta** [comment]
@poikilotherm so no more expected changes on your end? I'm ready to move to QA if true.

**Comment by poikilotherm** [comment]
There is more, but beyond scope for this issue. :wink: Go @scolapasta go :smile:

**Comment by kcondon** [comment]
@poikilotherm Issues found so far:
1. When select file(s) from dataset and choose edit metadata, no files appear in view, only save/cancel buttons. No log error. Using Chrome unless otherwise noted.

**Comment by scolapasta** [comment]
@poikilotherm This was fixed in a PR I added, so a refresh should solve this.

**Pull request merged**
