### PR TITLE
Resolve conflicting version of MIME4J

### LINKED ISSUE #9077: sword2-server library overrides tika's apache-mime4j-core dependency with older version
**What steps does it take to reproduce the issue?**

1. Turn full text indexing on:  `curl -X PUT -d true http://localhost:8080/api/admin/settings/:SolrFullTextIndexing`
2. Create a dataset
3. Upload an e-mail file, for example 
    
        From: A
        To: B
        Subject: C

        An infrequent word: peripatetic

    Attached here: [email.txt](https://github.com/IQSS/dataverse/files/9812541/email.txt)

An error is displayed, even though the file is added. This is because full text indexing fails. The following error is found in the logs:

```
[2022-10-18T13:36:42.882+0200] [Payara 5.2022.3] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler] [tid: _ThreadID=108 _ThreadName=http-thread-poo
l::http-listener-1(16)] [timeMillis: 1666093002882] [levelValue: 1000] [[                                                                                                   javax.ejb.EJBException: org/apache/james/mime4j/stream/MimeConfig$Builder
        at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:723)
        at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:652)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:482)                                                            at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4601)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2134)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)                                                                at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
        at com.sun.proxy.$Proxy325.indexDataset(Unknown Source)
        at edu.harvard.iq.dataverse.search.__EJB31_Generated__IndexServiceBean__Intf____Bean__.indexDataset(Unknown Source)
        at edu.harvard.iq.dataverse.api.Index.indexDatasetByPersistentId(Index.java:319)                                                                                          at jdk.internal.reflect.GeneratedMethodAccessor1916.invoke(Unknown Source)
....        
Caused by: java.lang.NoClassDefFoundError: org/apache/james/mime4j/stream/MimeConfig$Builder
        at org.apache.tika.parser.mail.RFC822Parser.parse(RFC822Parser.java:74)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:289)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:289)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:185)                                                                                               at edu.harvard.iq.dataverse.search.IndexServiceBean.toSolrDocs(IndexServiceBean.java:1054)
        at edu.harvard.iq.dataverse.search.IndexServiceBean.addOrUpdateDataset(IndexServiceBean.java:1307)
        at edu.harvard.iq.dataverse.search.IndexServiceBean.addOrUpdateDataset(IndexServiceBean.java:731)
        at edu.harvard.iq.dataverse.search.IndexServiceBean.indexDataset(IndexServiceBean.java:599)
        at jdk.internal.reflect.GeneratedMethodAccessor1747.invoke(Unknown Source)                                                                                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)                                                                          at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)                                                                                                              at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)                                                                                                              at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
        at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                               at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)                                                                     at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)                                                                                              at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        ... 78 more

```

* When does this issue occur?
When a e-mail file is to be indexed.

* Which page(s) does it occurs on?
Not really a user interface issue, but an error is displayed when you upload the file.

* What happens?
See above

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
The file should be indexed correctly

**Which version of Dataverse are you using?**
* v5.11.1
* develop

**Any related open or closed issues to this bug report?**
The problem is a recurring one: dependencies needed by Tika are overriden by older ones, so that the required classes or methods are not found at runtime. In this case `sword2-server` is the culprit. The quick fix is to exclude apache-mime4j-core from the `sword2-server` dependency (thanks to @qqmyers for the suggestion). A more solid fix would possibly be introducing Java modules into Dataverse, so that the transitive dependencies of primary dependencies don't interfere with one another.

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:

- Apache Abdera Parser, Apache Tika and RESTeasy (Testing) use MIME4J
- Tika and RESTeasy use newer APIs only present since v0.8+
- Abdera is an abandoned project, uses v0.7.2 and is hopefully compatible with newer releases
- v0.8.4 given by Apache Tika relies on vulnerable Apache Commons IO 2.6, we want 2.11 per dependency management. Upgrading to v0.8.7 as earliest version with 2.11 dependency

**Which issue(s) this PR closes**:

Closes #9077

**Special notes for your reviewer**:
None

**Suggestions on how to test this**:
Let Jenkins run the SWORD2 tests. Maybe @qqmyers can tell us how to run tests for full text indexing?

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope

**Is there a release notes update needed for this change?**:
Nope

**Additional documentation**:
None

### CODE REVIEW

**Comment by qqmyers** [comment]
@poikilotherm tika has a v2.9.1 (we're at 2.4.1) which I think includes the  v0.8.7 version you want. Should we upgrade tika in addition/instead? 2.9.1 looks like it works as well or better than the earlier version at QDR. 

Re: testing - we don't have a suite of files to test all of full-text indexing so the basic test would be to configure full-text indexing (":SolrFullTextIndexing":"true"), reindex a  dataset with test file(s) of various types, and see if they appear in search results for a term in the text (and don't appear in search when full-text is off).

**Comment by poikilotherm** [comment]
I agree - we should upgrade Tika. Let me check if I can provide a Testcontainers based integration test, would be interesting to have this use case properly covered by a nice integration test.

**Comment by pdurbin** [comment]
@poikilotherm can you please resolve merge conflicts? ❤️

**Review by pdurbin — APPROVED** [review]
@poikilotherm nevermind. I resolved them. I didn't run the code myself but I'm approving this.

**Comment by ofahimIQSS** [comment]
Spoke to Jim about testing this. Essentially, I performed a smoke test with SolrFullTextIndexing set to true. No issues found during testing. Merging PR. 
[Testing of 10301.docx](https://github.com/user-attachments/files/17512047/Testing.of.10301.docx)

**Pull request merged**
