### PR TITLE
set build number on beta war file

### LINKED ISSUE #9814: beta server doesn't show commit in /api/info/version
https://beta.dataverse.org/api/info/version shows "null" for the build:

```
{
  "status": "OK",
  "data": {
    "version": "5.14",
    "build": null
  }
}
```

We have a nice script that will populate "build" with the branch and commit:

```
$ scripts/installer/custom-build-number
No custom build number specified. Using "develop-45a3936190".
```

We should use it on the beta server so we know what code is running there.

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

It's nice to know what code is running on https://beta.dataverse.org

**Which issue(s) this PR closes**:

- Closes #9814

**Special notes for your reviewer**:

None.

**Suggestions on how to test this**:

Merge it and see it if works?

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

No.

**Additional documentation**:

None.

### CODE REVIEW

**Comment by GPortas** [comment]
@pdurbin I have tested it by adding the step to the GitHub action in my fork repository.

The new step is executed without errors:

buildnumber

But when deploying the built artifact to Payara we encounter the following error:

action_deploy_err

Job execution: https://github.com/GPortas/dataverse/actions/runs/5948494798/job/16132384602

On a second test, I deleted the step you added and executed the action again, obtaining the same error: https://github.com/GPortas/dataverse/actions/runs/5948579005

I'm going to approve the PR, since the error is not related to the action step you added, although we need to fix the error, since right now beta testing Dataverse service is not working: https://beta.dataverse .org

**Review by GPortas — APPROVED** [review]

**Comment by GPortas** [comment]
So, after switching [beta.dataverse.org](http://beta.dataverse.org/) to Java 17, deployment works and build info is displayed on the JSF UI:

buildnumberui

Job execution: https://github.com/GPortas/dataverse/actions/runs/5950689683/job/16139114289

Thanks for the help @donsizemore

**Comment by pdurbin** [comment]
@GPortas perfect! Thanks for testing! (And @donsizemore thanks for upgrading to Java 17 on beta.)

@scolapasta @kcondon this is very low risk if we'd like to merge it before 6.0 but it can also wait until after.

**Comment by pdurbin** [comment]
Huh, merged but https://beta.dataverse.org/api/info/version still shows null for the build:

```
{"status":"OK","data":{"version":"6.0","build":null}}
```

🤔

**Comment by pdurbin** [comment]
Oh, I guess it's because "deploy to payara" failed: https://github.com/IQSS/dataverse/actions/runs/6151994911/job/16693360612

**Pull request merged**
