### PR TITLE
Equals method fix

### LINKED ISSUE #9951: equals() methods check for wrong class in several classes
**What steps does it take to reproduce the issue?**

* When does this issue occur?
It *should* cause failures in unit tests, but the `equals(Object)` methods are rarely covered by unit tests.

* Which page(s) does it occurs on?
Not on pages, but in several classes.

* What happens?
The `.equals(Object)` method checks if the `other` object is of a different class than itself. This happens in

    - DataverseFacet (checks for DatasetFieldType)
    - DatasetFieldDefaultValue (checks for DatasetField)
    - DataverseContact (checks for DatasetFieldType)
    - DataverseFeaturedDataverse (checks for DatasetFieldType)
    - DataverseTheme (checks for DatasetFieldType)

* To whom does it occur (all users, curators, superusers)?
Failing tests should "occur" for developers.

* What did you expect to happen?
Unit tests should fail on equality tests.

**Which version of Dataverse are you using?**
Current development branch.

**Any related open or closed issues to this bug report?**
No.

**Screenshots:**

https://github.com/IQSS/dataverse/blob/5fc7b30d02e684f76bb985faeaef9e0becd69107/src/main/java/edu/harvard/iq/dataverse/DataverseFacet.java#L94-L101

### PR DESCRIPTION
**Pull request by Sakshi-75**
**What this PR does / why we need it**:
This PR fixes the equals method in the following classes:
1. DataverseFacet.java
2. DatasetFieldDefaultValue.java
3. DataverseContact.java
4. DataverseFeaturedDataverse.java
5. DataverseTheme.java
This PR also includes unit tests for these fixed equals methods.

**Which issue(s) this PR closes**: 

Closes #9951 

**Special notes for your reviewer**:
NA

**Suggestions on how to test this**:
NA

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
NA

**Is there a release notes update needed for this change?**:
NA

**Additional documentation**:
NA

### CODE REVIEW

**Comment by pdurbin** [comment]
@Sakshi-75 thanks for the pull request! I just kicked of some extra testing here: https://github.com/gdcc/api-test-runner/actions/runs/6420322844

**Review by bencomp — APPROVED** [review]

**Comment by bencomp** [comment]
@pdurbin I think you should use the *hacktoberfest-accepted* label (or approve it in a review) to make it count 🤓

**Comment by pdurbin** [comment]
I checked with @scolapasta about adding this to the sprint/board and he said let's go for it.

**Review by pdurbin — APPROVED** [review]
All API tests are passing (in both Jenkins and GitHub Actions). The fix looks good. Coverage increased (+0.04%) to 20.081% according to Coveralls. Approved! Thanks, @Sakshi-75!

**Comment by pdurbin** [comment]
@Sakshi-75 are there other issues you're thinking about working on? I'm happy to direct you to some. 😄

**Comment by Sakshi-75** [comment]
@pdurbin I can take a look at the other available issues and decide 🙂

**Comment by pdurbin** [comment]
@Sakshi-75 it's tricky finding issues that are small enough. I'm curious to hear what you think about this one:

- #8926

I could also point you at a long list of documentation issues, if you're interested! 😅 

Oh, and if you want to talk outside of this PR, https://chat.dataverse.org is a good place. 😄 Probably #dev.

**Comment by Sakshi-75** [comment]
Hi @pdurbin ,
I checked the issue you mentioned, and I'm a little confused. Is the issue asking to simply update the error message and remove the period `.` from the mentioned list of invalid characters?

**Comment by pdurbin** [comment]
@Sakshi-75 hmm, not sure but let's discuss in that issue or https://chat.dataverse.org (you could start a new topic under #dev).

**Pull request merged**
