### PR TITLE
Set up Sonar

### LINKED ISSUE #9846: Set up Sonar

### PR DESCRIPTION
**Pull request by pdurbin**
DRAFT UNTIL WE ADD GITHUB ACTIONS

**What this PR does / why we need it**:

We'd like to set up Sonar to check pull requests.

**Which issue(s) this PR closes**:

- Closes #9846

**Special notes for your reviewer**:

We'll be adding GitHub Actions to do the equivalent of what I ran at tech hours:

```
export SONAR_TOKEN=xxxx
mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=IQSS_dataverse
```

@poikilotherm already set this up for us for the xoai library, for example: https://github.com/gdcc/xoai/blob/xoai-5.0.0/.github/workflows/build_test_analyze.yml#L38

**Suggestions on how to test this**:

Check if Sonar reports are updated.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

Not sure a release note is necessary.

**Additional documentation**:

No, but we should add some.

### CODE REVIEW

**Comment by bencomp** [comment]
https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/github-actions-for-sonarcloud/

**Comment by bencomp** [comment]
@pdurbin no (specific) promises, but do you need help with this?

**Comment by pdurbin** [comment]
Yes! Well, to be more specific, this issue has not been prioritized so no one on the core team is actively working on it. If you'd like to help, that would be great! Perhaps we could start a topic about Sonar in #dev at https://chat.dataverse.org (Zulip).

**Comment by scolapasta** [comment]
If you are still interested in this PR, can you please merge and resolve any merge conflicts with the latest from develop? If so, we can prioritize reviewing and QAing the changes. If we don’t hear from you by May 22, 2024, we’ll go ahead and close this PR (it can always be reopened after that date, if there is still interest).

**Comment by pdurbin** [comment]
@scolapasta I just resolved the merge conflicts. Please prioritize! 😄

**Comment by pdurbin** [comment]
I still want Sonar to be set up but I'm closing this and will let someone else be the champion.

**Pull request closed without merging**
