### PR TITLE
Support SHA1 rather than MD5 as a checksum on a per file basis #3354

### PR DESCRIPTION
**Pull request by pdurbin**
# RFI Checklist

### 1. Related Issues

- #3354 Support SHA1 rather than MD5 as a checksum on a per file basis

---
### 2. Pull Request Checklist

- [x]  Functionality completed as described in FRD (no FRD)
- [x]  Dependencies, risks, assumptions in FRD addressed  (no FRD)
- [x]  Unit tests completed (REST Assured tests added)
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing) (scripts/database/upgrades/3354-alt-checksum.sql, new Solr schema, reindexing required)
- [x]  Documentation completed (Installation Guide updated)
- [x]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [x]  Code review completed or waived ( @bmckinney at https://github.com/IQSS/dataverse/pull/3367#issuecomment-248382961, @sekmiller @raprasad @landreev at https://github.com/IQSS/dataverse/pull/3367#issuecomment-249292061 )
- [x]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

A dependency for rsync support (#3145) is the ability to persist SHA-1
checksums for files rather than MD5 checksums.

A new installation-wide configuration setting called
":FileFixityChecksumAlgorithm" has been added which can be set to
"SHA-1" to have Dataverse calculate and show SHA-1 checksums rather than
MD5 checksums.

In order to run this branch you must run the provided SQL upgrade
script: scripts/database/upgrades/3354-alt-checksum.sql

In addition, the Solr schema should be updated to the version in this
branch.

This work connects to #3354.

### CODE REVIEW

**Comment by pdurbin** [comment]
@bmckinney this is a pretty big change and I don't expect you to grok all of it but can you please give me a thumbs up or thumbs down on the SQL update at https://github.com/IQSS/dataverse/blob/b703e27ec2d785adff459d3ff806e10344a2ef06/scripts/database/upgrades/3354-alt-checksum.sql ? I want to make sure it's what you, @scolapasta and I agreed to last Thursday. If you leave a positive comment here I'll move this issue to QA. Thanks!

**Comment by bmckinney** [comment]
SQL looks like what we discussed last week - thumbs up!

**Comment by pdurbin** [comment]
@bmckinney fantastic. @pameyer and I discussed it as well and he said it'll work for him. I'll leave this pull request in Code Review at https://waffle.io/IQSS/dataverse (feedback is welcome from @sekmiller and @raprasad because I touched MyData and from @landreev because I refactored how checksums are calculated) but the corresponding issue (#3354) I put in QA.

**Comment by pdurbin** [comment]
@djbrooke set #3354 in the 4.6 milestone so I'll do the same for this pull request.

**Comment by djbrooke** [comment]
@pdurbin you mentioned you were going to review this code with a few folks - moving back to code review

**Comment by pdurbin** [comment]
I did some code review of this pull request with @sekmiller @raprasad and @landreev 

@raprasad agreed that src/main/webapp/mydata_templates/cards.html is unused so I removed it in 2b2a3c7

@sekmiller and I talked about how I think it's unlikely that the code path at https://github.com/IQSS/dataverse/blob/b703e27ec2d785adff459d3ff806e10344a2ef06/src/main/java/edu/harvard/iq/dataverse/DatasetVersionDifference.java#L766 will be entered. We also observed what turns out to be a known file indexing issue at #3243.

@landreev and I talked about how I'm trying to maintain backwards compatibility in JsonParser.java by maintaining the existing behavior when "md5" is sent but also allowing a new "checksum" field to be sent which can contain a SHA-1 value.

Passing to QA in https://waffle.io/IQSS/dataverse

**Pull request merged**
