### PR TITLE
Added whitespace trimming to uploaded custom metadata TSV files

### PR DESCRIPTION
**Pull request by erodde**
**What this PR does / why we need it**:
when loading custom metadata blocks using the `api/admin/datasetfield/load` API, whitespace can be introduced into field names. The change trims whitespace at the beginning and end of all values read into the API before persisting them. I also added a null check for a potential NPE I found during testing.

**Which issue(s) this PR closes**:

Closes  https://github.com/IQSS/dataverse/issues/10688 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Load metadata file with whitespace into DV using the API mentioned above.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
no

**Is there a release notes update needed for this change?**:
I believe not

**Additional documentation**:

### CODE REVIEW

**Comment by pdurbin** [comment]
@erodde thanks for the pull request! Can you please add a release note snippet? Just a single line is fine. Please see https://guides.dataverse.org/en/6.3/developers/version-control.html#writing-release-note-snippets

**Comment by erodde** [comment]
> @erodde thanks for the pull request! Can you please add a release note snippet? Just a single line is fine. Please see https://guides.dataverse.org/en/6.3/developers/version-control.html#writing-release-note-snippets

Done!

**Comment by pdurbin** [comment]
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-10696/2/display/redirect said "not found" so I just merged the latest from develop into this PR to kick off a Jenkins run.

**Review by stevenwinship — APPROVED** [review]

**Comment by ofahimIQSS** [comment]
Merging PR - Testing Passed
[Testing of 10696.docx](https://github.com/user-attachments/files/17996661/Testing.of.10696.docx)

**Pull request merged**
