### PR TITLE
Facets filter labels not translated in result block

### LINKED ISSUE #9408: Facets filter labels not translated in result block
Hello Dataverse team,

We wanted to report that facet filters are not translated in the top block result after selection.
Here is a screenshot :
facets_fr

Current language is **French**, on the left panel, values are translated in **French** but in top block result fragment value are in **English** (default language for Payara in our case).

Same screnshot with **English** as language :
facets_en

**Which version of Dataverse are you using?**

5.12.1

**Any related open or closed issues to this bug report?**

Issue could be related to #8287 and #8286 but not sure. 

Can you do something about it ?
PR is not planned on our side for now. 

Regards.

### PR DESCRIPTION
**Pull request by jeromeroucou**
**What this PR does / why we need it**:

With this PR we have a translated facets filters on search block result, same as facets labels (on the left panel)

**Which issue(s) this PR closes**:

- Closes #9408 

**Special notes for your reviewer**:

I do 3 commits :
- the first to indent the code
- the second to had some comments and remove old "dead" code : `staticSolrFieldFriendlyNamesBySolrField` is now get resource bundle. So we doesn't have to keep the quick fix for #618 
- the third to get filter label from resource bundle, like for facets

**Suggestions on how to test this**:

To test this PR, I would recommend activating internationalization

### CODE REVIEW

**Comment by jeromeroucou** [comment]
Good news if it's help ! I can close my PR if it's include into yours

**Comment by pdurbin** [comment]
Sorry, I wasn't clear. Please don't close this PR as we plan to test it separately (but I'm not sure when). Thanks.

**Review by pdurbin — APPROVED** [review]
The code looks reasonable and Iike I said at https://github.com/IQSS/dataverse/pull/10158#issuecomment-2329233500 I did some light testing of this PR in a different context (while looking at https://github.com/IQSS/dataverse/pull/10694#issuecomment-2329229859 ). Approved.

@jeromeroucou we released 6.4 today so please merge the latest from "develop" into this PR when you get a chance. Thanks.

**Comment by stevenwinship** [comment]
QA: Tested with Spanish and saw the translated value

**Pull request merged**
