### PR TITLE
Update pyDataverse section

### PR DESCRIPTION
**Pull request by skasberger**
**What this PR does / why we need it**:

Update pyDataverse section in client libraries documentation.

### CODE REVIEW

**Comment by djbrooke** [comment]
Hey @skasberger - I have some suggested changes. Would you like me to put up a PR or update the branch directly? If the latter, I may need access to make the changes.

Also, note that you have this pointed to the Master branch instead of Develop.

**Comment by pdurbin** [comment]
@djbrooke while you're thinking about this, please check out https://github.com/gdcc/pyDataverse/issues/69#issuecomment-774359678

**Comment by skasberger** [comment]
> Would you like me to put up a PR or update the branch directly? If the latter, I may need access to make the changes.

@djbrooke Honestly, I don't really know, and I am not sure what you mean exactly. PR from where to where? Or update which branch? I have not a lot of experience in PR review procedures, so am happy if you can help me out.

**Comment by djbrooke** [comment]
Hey @skasberger, happy to try and help, and maybe we can appeal to @pdurbin for some help if I get something wrong... :) I don't have a lot of experience in this area!

- at the top of this pull request, it shows the target as IQSS:Master instead of IQSS:Develop 
Screen Shot 2021-02-12 at 2 59 01 PM Compare this with another PR like https://github.com/IQSS/dataverse/pull/7603 that targets develop. We merge things into our develop branch instead of master, and only merge into master as part of a the release process. You should be able to adjust this.

- regarding my change, I'm happy to either make changes to the branch at https://github.com/skasberger/dataverse/tree/patch-3 or I can create a pull request against that branch so that you can review my changes and decide whether or not you'd like to accept them. For text changes like this, I prefer to make changes directly, but it's not a strong preference.

**Comment by pdurbin** [comment]
Hey all. Yes, we should absolutely retarget this pull request to "develop" instead of master. Here's how (I'll let one of you do it):

Screen Shot 2021-02-12 at 3 52 23 PM

We only update "master" at release time. More on this at https://guides.dataverse.org/en/5.3/developers/version-control.html#branching-strategy

@djbrooke regarding updating forks I wrote up some docs here: https://guides.dataverse.org/en/5.3/developers/version-control.html#adding-commits-to-a-pull-request-from-a-fork

But looking at them again, they're pretty technical. It's good to get comfortable with making pull requests against pull requests (it's often nicer to make suggestions rather than bashing away) and I'd be happy to help people get up to speed with this.

There's also the newish "suggestion" feature of GitHub that I use a lot. You basically do something like this.

    This is a tpyo.
    ```suggestion
    This is a typo.
    ```

**Comment by skasberger** [comment]
@djbrooke Regarding committing direct: Wouldn't you need write permissions on my feature branch for this?

@pdurbin I can not change the branch, as shown in your screenshot. I guess only repo maintaners can.

**Comment by djbrooke** [comment]
Hey @skasberger, I updated the PR to point against develop, so we should be all set there. 

@skasberger, yes, I'd need permissions on the branch to do commit directly. I'll go ahead and make the PR against your branch as @pdurbin outlined above.

**Comment by djbrooke** [comment]
@skasberger I suggested some changes in https://github.com/IQSS/dataverse/pull/7587/commits/2fe2a57fd26194c94a7b029f6533a9ba054e827c 

Github did not let me create a PR (it gave a 404 :/) but the suggested changes are there if you'd like to take a look.

**Comment by skasberger** [comment]
Thanks @djbrooke, fine for me. PR can be done.

**Review by djbrooke — APPROVED** [review]
Thanks @skasberger !

**Pull request merged**
