### PR TITLE
4896 junit tests

### PR DESCRIPTION
**Pull request by benjamin-martinez**
connects to #4896

### CODE REVIEW

**Comment by matthew-a-dunlap** [comment]
@benjamin-martinez Did you look into using exclude groups for maven? Probably is better than having a category for Essential Tests that folks need to remember to add or the test won't be run: https://github.com/junit-team/junit4/wiki/categories#using-categories-with-maven

**Comment by pameyer** [comment]
@benjamin-martinez with 75ab1fe, using `./conf/docker-aio/run-test-suite.sh` fails with:
``
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ dataverse ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.816 s
[INFO] Finished at: 2018-08-20T10:45:52-04:00
[INFO] Final Memory: 60M/805M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project dataverse: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
``

**Comment by djbrooke** [comment]
@benjamin-martinez do the most recent commits cover @pameyer's feedback?

**Comment by pameyer** [comment]
@djbrooke Looks good as of  79c54a7359a7d0d5220de1631801c8fee9801d8b.

**Comment by pdurbin** [comment]
We merged pull request #4989 instead. Closing.

**Pull request closed without merging**
