### PR TITLE
New API endpoints for TRSA (Trusted Remote Storage Agent) of ImPACT project: stage 1

### PR DESCRIPTION
**Pull request by akio-sone**
This pull request is the first stage of adding new Dataverse Native API endpoints for the TRSA (Trusted Remote Storage Agent) of ImPACT  (Infrastructure for Privacy-Assured CompuTations: http://cyberimpact.us/).  
More specifically, These new API endpoints are expected to handle the submission of (1) a locally ingested new dataset or  (2) a locally ingest ingest new data file (s) as a JSON file without invoking the host Dataverse's ingest process. By design, this submission request from a TRSA does not or cannot upload locally ingested data files to the host Dataverse due to security restrictions on them. Also, these new API endpoints deal with up to Datavariable-level metadata in JSON format whose functionality is missing from the current set of Native API endpoints.

This pull requests implements the former API endpoint (1: adding a new dataset) and the latter one (2: adding new data files) is currently a stub.  The former (BatchImport#postImportWoI method) is a variant of BatchImport#postImport method and the latter (Datasets#addFileMetadataToDataset method) is based on Datasets#addFileToDataset method.  These two API endpoints are backed by newly added methods to JsonParser/JsonPrinter classes for Datavariable-level metadata. The implementation of the latter API endpoint would be covered by the next pull request.

## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #5213

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
@akio-sone I see @scolapasta assigned this to you. Any news?

**Comment by pdurbin** [comment]
@akio-sone head ups that there are merge conflicts in pom.xml

**Comment by djbrooke** [comment]
Closing this PR, updated PR incoming. Will link here when available.

**Comment by cmbz** [comment]
@scolapasta Do you know if there was ever an updated PR for this issue? https://github.com/IQSS/dataverse/issues/5213
See comment from 2018: https://github.com/IQSS/dataverse/pull/4750#issuecomment-517400234

**Comment by scolapasta** [comment]
I am not immediately aware - maybe @asone can recall?

**Comment by nherbin-ma** [comment]
You made a mistake, you probably meant @akio-sone ;)

**Comment by Asone** [comment]
I guess you made a mistake, you probably meant @akio-sone ;-)

**Pull request closed without merging**
