### PR TITLE
8778 harvester ddi exporter

### LINKED ISSUE #8778: Harvester exporter uses short version of XML
**What steps does it take to reproduce the issue?**

* When does this issue occur?

It occurs during harvesting dataverse via oai, for example:
``curl https:/localhost:8080/oai?metadataPrefix=oai_ddi&verb=GetRecord&identifier=$PERSISTENT_ID``

* What happens?

Harvesting through OAI_DDIExporter only harvests short version of DDI without fileDscr  and dataDscr sections.
It uses datasetJson2ddi(JsonObject datasetDtoAsJson, OutputStream outputStream) with dtoddi(DatasetDTO datasetDto, OutputStream outputStream) instead of datasetJson2ddi(JsonObject datasetDtoAsJson, DatasetVersion version, OutputStream outputStream)
The solution maybe to replace datasetJson2ddi with 2 parameters to datasetJson2ddi with 3 parameters.

* What did you expect to happen?

To get full xml with  fileDscr  and dataDscr sections. The same xml, one will get through api dataverse export metadata.

### PR DESCRIPTION
**Pull request by lubitchv**
**What this PR does / why we need it**:
It replaces short version of harvester exporter  XML with a full version, i.e it adds dataDscr and fileDscr sections.

**Which issue(s) this PR closes**:

- Closes #8778 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Use dataset with tab files. Run: 
``curl http:/localhost:8080/oai?metadataPrefix=ddi&verb=GetRecord&identifier=$PERSISTENT_ID`` 
The resulting xml should have dataDscr and fileDscr sections.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No

### CODE REVIEW

**Review by sekmiller — APPROVED** [review]

**Comment by landreev** [comment]
Hmmm. This is a pretty big deal of a change. I feel like this should've been discussed some more. 
There was some serious rationale behind making this harvestable version of the DDI "light"  and not include the data description sections. (If nothing else, if we were to make this "OAI_DDI" format *exactly the same* as "DDI" - there would be no reason to keep maintaining both!).

**Comment by lubitchv** [comment]
As for discussion in the ticket, oai_ddi format remains with short version. DDI format is made harvastable. The label for DDI format was replaced with DDI_full.

**Comment by pdurbin** [comment]
@lubitchv hi! Yesterday I merged the latest from develop into this PR (I hope you don't mind!) and now this test is failing:

java.lang.AssertionError: expected:<5> but was:<6>
	at edu.harvard.iq.dataverse.api.HarvestingServerIT.testOaiListMetadataFormats(HarvestingServerIT.java:188)

Can you please take a look? Also, @landreev recently added a bunch of tests in the following PR and you're welcome to add additional tests if you like!

- #9227

**Comment by pdurbin** [comment]
From looking at the code I'm still confused. It sure seems like the existing short format would disappear and replaced by the long format. 🤔 

Needs discussion or at least some testing.

**Comment by scolapasta** [comment]
If you are still interested in this PR, can you please merge and resolve any merge conflicts with the latest from develop? If so, we can prioritize reviewing and QAing the changes. If we don’t hear from you by May 22, 2024, we’ll go ahead and close this PR (it can always be reopened after that date, if there is still interest).

**Comment by scolapasta** [comment]
If you are still interested in this PR, can you please merge and resolve any merge conflicts with the latest from develop? If so, we can prioritize reviewing and QAing the changes. If we don’t hear from you by May 22, 2024, we’ll go ahead and close this PR (it can always be reopened after that date, if there is still interest).

**Comment by pdurbin** [comment]
> If we don’t hear from you by May 22, 2024, we’ll go ahead and close this PR (it can always be reopened after that date, if there is still interest).

Closing.

**Pull request closed without merging**
