### PR TITLE
adding proposed PR template

### LINKED ISSUE #6226: Revise PR Template
In https://github.com/IQSS/dataverse/pull/6223#discussion_r329180952 @pdurbin mentioned that he just deletes most of the PR template (https://github.com/IQSS/dataverse/blob/develop/PULL_REQUEST_TEMPLATE.md). I do the same. 

Let's think about this, get some opinions (from other people or other projects) and change what's in the template.

### PR DESCRIPTION
**Pull request by djbrooke**
To be discussed in tech hours.

## Related Issues

- closes #6226

### CODE REVIEW

**Comment by pdurbin** [comment]
@djbrooke before we discuss this at tech hours, you might want to remove the existing pull request template as part of this pull request. It looks like this:

Screen Shot 2019-11-22 at 2 33 24 PM

Or you could move `.github/PULL_REQUEST_TEMPLATE.md` to `PULL_REQUEST_TEMPLATE.md`, effectively overwriting the old one. I don't *think* it matters if it's in that `.github` folder you created. By this I mean that I don't think any links will break because I don't think we link to it.

**Comment by djbrooke** [comment]
Thanks @pdurbin. I don't see why this would have any impact on a discussion about the content of the new template but I'm happy to remove it at this point in time.

**Comment by djbrooke** [comment]
Removed in https://github.com/IQSS/dataverse/pull/6398/commits/728106c53909f3b813476e257624786487c380e0

**Comment by pdurbin** [comment]
@djbrooke thanks. This way we can discuss if anyone cares or minds that we are introducing a `.github` directory.

**Pull request merged**
