### PR TITLE
Use better typing, mostly relating to DatasetVersionDifference (#775 again)

### PR DESCRIPTION
**Pull request by bencomp**
In addition to defining and instantiating variables as typed lists and command, and using typed queries, I refactored some `Object[]`s to `SummaryData` and `BlockData` types and updated the references in the JSF. See the commit messages.

### CODE REVIEW

**Comment by pdurbin** [comment]
@bencomp and I mentioned at https://github.com/IQSS/dataverse/pull/2478#issuecomment-144416070 this pull request is against the 4.2 branch, which has already been tagged. It should be made against 4.3 instead.

Also, from chatting with @sekmiller it seems like this pull request is too long to easily reason about. I also wonder if you've tested these changes. :)

Please keep the pull requests coming! It's great stuff!

**Comment by bencomp** [comment]
When I made the pull request, 4.2 was the active branch. It's too bad I have to wait about two months to hear ["it's risky"](http://irclog.iq.harvard.edu/dataverse/2015-09-30#i_25027).

These changes mostly add static typing (because `Object` arrays have been replaced by proper and meaningful classes and raw `List`s etc. were analysed for their usage and made typed) and have been tested through ongoing static analysis in NetBeans and successful compilation by `javac`. I did not test the refactored JSF, but I felt confident about these changes because of @scolapasta's training.

Please note that in many places in the code methods are too long and documentation is too poor to reason about what things actually do, really. Unfortunately it has the effect that refactoring creates big changes. If you like, I can try to explain a few things via Skype or chat.

**Comment by scolapasta** [comment]
Hi Ben @bencomp ,

I'll send you an e-mail shortly, and coordinate with you our plan to review this and get the changes in.

**Comment by pdurbin** [comment]
@bencomp speaking of active branches, we now have two active branches:

- 4.2.1
- 4.3

This is because in 583ace0 I created the 4.2.1 branch based on work done in 4.3.

https://github.com/IQSS/dataverse/pull/2589 is against 4.3 which is perfect. We want to release 4.2.1 with as few changes as possible. I wouldn't want to put the changes in that pull request through QA for 4.2.1.

Even though we have two active branches, as of this writing the "default" branch is still 4.3. Why? My preference is that the "default" branch should be the branch where we want pull requests. That's why I haven't changed the "default" branch to 4.2.1.

@bencomp I'm curious what you think about all this. I'm thinking about writing a section about the "default" branch at http://guides.dataverse.org/en/latest/developers/branching-strategy.html to clarify why we make the default branch what it is.

(Another option is to create a "develop" branch that's always the "default" branch but I have been reluctant to create a "develop" branch because of the tendency for developers to never want to get off it as I explained in detail at https://github.com/IQSS/dataverse/pull/2478#issuecomment-144436722 .)

**Comment by bencomp** [comment]
@pdurbin I agree with you on keeping 4.3 the default branch.

I'll close this PR and open a new one but not right away. My time is limited ;)

**Comment by pdurbin** [comment]
@bencomp as discussed at #2478 this pull request has been made against an old branch (4.2) that should not receive any more commits. There's no way to switch the branch so I have to close the pull request. Sorry.

**Pull request closed without merging**
