### PR TITLE
6214 user notification following ingest

### LINKED ISSUE #6214: User Notification Following Ingest
Users need to wait for files to ingest before publishing. To let them know when the ingests are complete (successfully or not) and that they can now publish, we could provide a notification (to exist in Dataverse and email).

Created as a new issue from #6157.

### PR DESCRIPTION
**Pull request by alejandratenorio**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Note that we use the "closes" syntax below to trigger Github's automation to close the corresponding issue once the pull request is merged.

Thanks for your contribution to Dataverse!

## Related Issues

- closes #6214

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @alejandratenorio @ricvazo!

Moving my question here from #6214... does this provide messaging for ingest failures or only successes?

**Comment by alejandratenorio** [comment]
@djbrooke,

An email is always sent, if the ingest fails a message is sent: (Error) with datafileName (src/main/java/edu/harvard/iq/dataverse/ingest/IngestMessageBean.java  line 109 ).
Maybe we should add the message to Bundle.properties, what do you think?

**Comment by djbrooke** [comment]
Hi @alejandratenorio thanks for the quick response. If you can add that to bundle.properties it would be great, since that will allow others to translate the message. I'll be able to edit the text there, so just add any text that you feel makes sense. 

I'll also assign @landreev to this issue so that we can discuss next week. We have a long weekend but we'll back in the office on Tuesday.

**Comment by alejandratenorio** [comment]
@djbrooke, yeah, we'll add it. Thank you and regards.

**Comment by alejandratenorio** [comment]
Hi @djbrooke, @ricvazo changed messages when an ingest fails.

**Comment by djbrooke** [comment]
Thanks @ricvazo @alejandratenorio 

@landreev - all yours. Let me know when you've completed code review and I'll update the bundle text.

**Pull request merged**
