### PR TITLE
Added request access popup to file pg [ref #4897]

### PR DESCRIPTION
**Pull request by mheppler**
## Related Issues

- #4897 Request Access: button does not launch popup if logged in and request from file landing page.

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [x] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by kcondon** [comment]
@mheppler Request Access popup no longer sends request to admin from either dataset or file landing page. Works in develop. See dvn-build for develop, internal for your branch

**Comment by mheppler** [comment]
Removed a snippet of code from the file pg that seemed to have been an unintentional rogue pasting of `ui:param` components outside of the dialogs they were intended to be included in.

Unfortunately, these rogue lines of code did not change the behavior of the Request Access btns for me in my localhost. The buttons on the file pg and dataset pg all worked as expected, sending notifications to the dataverse admin through the system (no email server is setup for my localhost, so the server log complains about that).

Taking a look at the behavior of this branch on dataverse-internal, I noticed the Request Access btn works as expected on the file pg, and intermittently on the dataset pg.

Screen Shot 2019-06-25 at 1 48 26 PM

Screen Shot 2019-06-25 at 1 48 37 PM

While I am not sure if cleaning up the rogue code snippet changes anything, maybe the rogue popup btns on the dataset pg, reported in #5958 have something to do with the intermittent behavior of the Request Access btn.

@kcondon -- happy to update this branch with develop once that gets merge, if you want to put off testing this again.

**Comment by kcondon** [comment]
@mheppler does request access button change state to access requested and the actual username appear as a request under the files permissions?

**Comment by mheppler** [comment]
@kcondon Yes. See attached screenshots showing both.

**Comment by kcondon** [comment]
@mheppler was able to reproduce it: it happens when extra accept/cancel buttons appear at bottom of dataset due to this bug: #5958 So, let's fix/merge that one before retesting and merging this one.

**Comment by mheppler** [comment]
Merged the latest and greatest from develop (including #5958 dataset pg btn bug fixes), and pushed those changes to this branch. Confirmed the Request Access btn function on datasets that previously had the rogue Accept and Cancel btns at the bottom of the pg.

**Pull request merged**
