### PR TITLE
Make geospatial coverage "Other" field facetable

### LINKED ISSUE #7399: "other" as facet in the geospatial metadata
Would it be possible to make the "other" field in the geospatial metadata (under geographic coverage) into a facet like the countries are?

Thanks!
Michelle

### PR DESCRIPTION
**Pull request by jggautier**
**What this PR does / why we need it**:
This PR lets Dataverse admins add a search facet on their collection pages for the Geospatial metadatablock's "Other" field, so that others can narrow searches in their collections using the values entered in that "Other" field.

**Which issue(s) this PR closes**:

Closes #7399

**Special notes for your reviewer**:

**Suggestions on how to test this**:

- Edit a Dataverse collection (Edit > General Information) to enable the Geospatial metadatablock (in the Metadata Fields section) and in the in the Browse/Search Facets section, add the Geospatial metadatablock's "Other" field as a facet.
- Create a dataset with a value entered in the Geospatial metadatablock's "Other" field, save the dataset, and check if the Dataverse collection's page has an "Other" facet with a link for the value you entered in the Other field.
- Click on that facet link and the page should show the dataset you created.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

Yes, this PR introduces a UI change. Mockups not available.

**Is there a release notes update needed for this change?**:

Yes.

**Additional documentation**:

### CODE REVIEW

**Comment by djbrooke** [comment]
Go @jggautier !! 

For a release note, do you want to base the content like we did for the Biomedical block update in 5.1? https://github.com/IQSS/dataverse/releases/tag/v5.1

(I'm happy to do this step as well if you'd like)

Also, there's a test failing, but I'm not sure if it's related.

**Comment by jggautier** [comment]
Thanks, yeah, that makes sense to me. Something like this?:

> **Geospatial Metadata Block Updated**
> The Geospatial metadata block (geospatial.tsv) was updated. Dataverse collection administrators can now add a search facet on their collection pages for the metadata block's "Other" field, so that people searching in their collections can narrow searches using the values entered in that field.

Do installation admins need to follow the same steps in 5.1's "Additional Upgrade Steps" section?

**Comment by djbrooke** [comment]
@jggautier - yeah, I think you've got it. Once you make that change the tests should run again, and we'll see if they pass (which I hope they should!)

**Review by djbrooke — APPROVED** [review]

**Comment by kcondon** [comment]
@jggautier This did not work for me. I reloaded the tsv file and then followed your steps but no facet appeared.

**Comment by jggautier** [comment]
Thanks. Hmmm, did you or is it necessary to also do the steps described in the "Additional Upgrade Steps" section at the bottom of [5.1's release notes](https://github.com/IQSS/dataverse/releases/tag/v5.1)?:

I didn't include those steps in the release notes I draft for this PR because I wasn't sure if those steps needed to be followed for this change.

**Comment by kcondon** [comment]
I did both, checking for facet between times.

**Comment by jggautier** [comment]
Yikes, okay thanks. Should I open an issue about investigating why it doesn't seem possible to make this field facetable?

**Comment by kcondon** [comment]
Or we could just put this pr back into dev, saying it is not working and put it up for investigation

**Comment by kcondon** [comment]
@jggautier OK, was user error -I followed the first part of the bulletpoint, adding geospatial block but not the second part, adding the newly appearing facet option: Edit a Dataverse collection (Edit > General Information) to enable the Geospatial metadatablock (in the Metadata Fields section) and in the in the Browse/Search Facets section, add the Geospatial metadatablock's "Other" field as a facet.

**Comment by jggautier** [comment]
Ah okay. Probably less user error and more my poorly designed list of steps. :)

**Comment by kcondon** [comment]
Well, I often read things quickly so mea culpa

**Pull request merged**
