### PR TITLE
Add puppet agent settings for provisioning with vagrant.

### PR DESCRIPTION
**Pull request by lwo**
This is an addition to the Vagrantfile to install dataverse and its dependencies on Centos 6, Ubuntu 12 and 14 operating systems. It will use Vagrants provisioning ability with a puppet agent, hence the additional /scripts/puppet and optional /conf/puppet/hieradata. See the documentation in the Vagrantfile on how to start it up.

The actual Dataverse puppet module is pulled in from:
https://github.com/iish/iish-iqss
It does not live at Puppet Force.... not yet anyway.

The puppet module is intended for IT administrators who just want to use puppet to enroll a Dataverse infrastructure. The Vagrantfile addition is to help developers setup their box in a familiar environment.

### CODE REVIEW

**Comment by pdurbin** [comment]
Wow! Or should I say Wouw! You really did it @lwo ! We talked about you creating a puppet module over at https://github.com/IQSS/dataverse/issues/1059#issuecomment-111847394 and you delivered!

I just posted [a message on the Google Group](https://groups.google.com/forum/#!topic/dataverse-community/C-ym7r2AI5Y) about this to see if we can drum up some interest.

I haven't tried it myself but two quick thoughts:

- the pull request is against the 4.0.1 branch but I'm planning on deleting that branch since 4.0.1 has already been tagged. We're close to releasing 4.1 (I think) so lets try to get this merged into the 4.0.2 branch (which is actually 4.1 per #2348) or a future branch
- it would be **awesome** if we could somehow teach Travis to execute the puppet module: https://travis-ci.org/IQSS/dataverse

**Comment by pdurbin** [comment]
We might want to change this:

```
-    config.vm.network "forwarded_port", guest: 8983, host: 8983
+    config.vm.network "forwarded_port", guest: 8983, host: 8993
```

@akio-sone worked on this in #1613 . Otherwise I get a conflict when I run `vagrant up` because I'm already running Solr on my Mac on port 8983 (the default).

**Comment by pdurbin** [comment]
I'm sort of blocked because I tried to merge this pull request (locally) into the 4.0.2 branch which is really 4.1 but the app wasn't deployed...

```
-bash-4.1$ ~/glassfish-4.1/glassfish/bin/asadmin list-applications
Nothing to list.
No applications are deployed to this target server.
Command list-applications executed successfully.
```

... so the database tables haven't been created so I can't run the reference_data.sql script.

Also, in the existing incarnation of `vagrant up` there's no need to read and perform steps in a "Post installation setup" section of the Vagrantfile. It's fully automated and you get a working installation on port 8888 per http://guides.dataverse.org/en/latest/developers/tools.html#vagrant . I think I'd like to keep in that way.

Anyway, I'd also like to ping @doprdele about all this puppet stuff. :)

**Comment by pdurbin** [comment]
Oh, and I forgot to mention that I really like how https://github.com/IISH/iish-iqss/tree/v0.1.0/manifests includes configs for Rserve and TwoRavens! /cc @landreev @tercer @vjdorazio

**Comment by pdurbin** [comment]
@lwo it was very nice chatting you at http://irclog.iq.harvard.edu/dataverse/2015-07-24 ! To summarize, if you could make my older shell scripts the default (for now) and merge against an active branch (you may want to wait for us to create a 4.2 branch) we'll get this merged in right away.

**Comment by lwo** [comment]
@pdurbin: Likewise ! So Okiedokie: I'll  ensure the defaults and watch 4.2 branch like a hawk.

**Comment by pdurbin** [comment]
@lwo I just created a branch for 4.2: https://github.com/IQSS/dataverse/tree/4.2

**Comment by pdurbin** [comment]
@lwo I had another thought about this pull request that I wanted to run by you. Since I'm sort of insisting that you leave my (cough) lovely shell scripts as the default I'm wondering where the place would be where the Puppet version **is** the default.

Back in the DVN 3.x days I created a dedicated git repo outside of the DVN 3.x repo where Puppet was the default provisioner in a Vagrant environment. The Puppet code may not be pretty, but it works (last time I checked): https://github.com/dvn/dvn-install-demo . It pulls down a DVN war file from an official release (hosted by SourceForge in those days).

So... I'm wondering if you'd be interested in doing the same. I could even create a repo under the @IQSS organization and give you and others push access if you'd like. Maybe it could even (someday) be the code base from which a module is uploaded to https://forge.puppetlabs.com . It could contain a Vagrantfile and be kept up to date with the latest Dataverse release. It could be sort of a proving ground managing Dataverse with Puppet. People seem excited about your efforts which was added to [a proposal for reorganizing the Installation Guide](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing).

Hmm, actually, I just noticed that a Vagrantfile already exists at https://github.com/iish/iish-iqss . That's basically what I'm talking about... having separate repo dedicated to the Puppet module.

On a related note, @bencomp created a repo for Docker: https://github.com/bencomp/dataverse-docker

I hope this makes sense. Please let me know what you think!

**Comment by lwo** [comment]
Hello @pdurbin: Did I hear you cough... ? Having a cold are we ?

Yes, that is its purpose: a clean separation of code and packages on one place; an unknown environment on another ; and a stand alone provisioner that does all the hard work while you can drink a cup of tea.

I also think that this module will become dated and isolated in any private organisation's repo - even one so versatile as the IISH (modest cough) as developing it further - as opposed to contributing - may be beyond it's scope.

I think the IQSS repo is where its origin belongs anyway like dogfooding and it is in every bodies interest to be able to just plug and play. It is easier to evolve further in a community driven environment and at the same time close to the core. An IQSS repo could facilitate this... and discipline it with unit tests; a branching strategy; a CI build....

I would be all for it.

**Comment by pdurbin** [comment]
@lwo ok, just to confirm we are on the same page...

- I'll create https://github.com/IQSS/dataverse-puppet and give you push access to it
- You'll push code to that new dataverse-puppet repo that right now lives at https://github.com/iish/iish-iqss
- @IQSS will promote the new repo as a community-driven effort in the [Installation Guide](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing)
- We'll close this pull request (we won't change how the Vagrantfile works, at least not yet... maybe we'll love Puppet once we try it!)

Does that make sense? Please feel free to jump in http://chat.dataverse.org if that's easier!

We have a similar arrangement for https://github.com/IQSS/dataverse-client-python where the code was written by @rliebz from the @CenterForOpenScience . We give him a shout out at http://guides.dataverse.org/en/latest/api/client-libraries.html

Likewise, depending on how @leeper feels, I'm more than happy to create a repo under @IQSS for him to push a Dataverse 4-compatible R client to per https://github.com/ropensci/dvn/issues/23#issuecomment-106402748

**Comment by pdurbin** [comment]
@lwo as we [discussed](http://irclog.iq.harvard.edu/dataverse/2015-07-31#i_22395) I created the https://github.com/IQSS/dataverse-puppet for you and gave you and @gordan-cupac push access. Enjoy your holiday and please let us know if there's anything you need from us!

**Comment by scolapasta** [comment]
Discussed with @pdurbin; since separate repo was opened to handle the puppet implementation, we're closing this pull request (without merging it).

**Pull request closed without merging**
