### PR TITLE
9488 internationalization issues

### LINKED ISSUE #9488: Internationalization issues where English text is appearing in UI and system-generated emails
**What steps does it take to reproduce the issue?**

English text appears in messages and system-generated emails when the platform UI is set to another language.

* When does this issue occur?

When the UI is set to a non-English language (e.g., French), some text is appearing in English.

* Which page(s) does it occurs on?

- Tool tip as part of tabular ingest failed message on dataset page includes English text - "Ingest failed. No further information is available"
- File access menu on dataset page includes English text - "File access" and "Download metadata" strings
- Notifications (both in UI and in emails) show curation label status in English

* What happens?

Text strings are not completely showing in the appropriate non-English language.

* To whom does it occur (all users, curators, superusers)?

All users.

* What did you expect to happen?

We expect the strings to be completely in the selected non-English language.

**Which version of Dataverse are you using?**

Version 5.12.1

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

Note: Jayanthy (Borealis/Scholars Portal) will provide pull request to address these issues.

notificationpage
Screen Shot 2023-02-22 at 11 58 23 AM
borealis-i18n-ca-fr-1

### PR DESCRIPTION
**Pull request by JayanthyChengan**
**Which issue(s) this PR closes**:

- Closes #9488

### CODE REVIEW

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for the pull request!

These seem like straightforward changes. Standard "move English into properties files" stuff.

I gave this PR a 3 in term of effort to review (which I've basically done) and QA.

**Review by qqmyers — APPROVED** [review]
Looks good. I see in the notes @pdurbin has reviewed as well. FOr @kcondon - the issue has details about where the fixes should be visible.

**Review by qqmyers — COMMENTED** [review]
FWIW: #9451 has a couple of the same fixes.

**Comment by pdurbin** [comment]
@JayanthyChengan hi! Can you please resolve the merge conflicts in this pull request? They're in this file:

```
diff --cc src/main/webapp/file-download-button-fragment.xhtml
index 322bd58906,cecc7ef8d0..0000000000
--- a/src/main/webapp/file-download-button-fragment.xhtml
+++ b/src/main/webapp/file-download-button-fragment.xhtml
@@@ -12,7 -12,7 +12,11 @@@
      xmlns:iqbs="http://xmlns.jcp.org/jsf/composite/iqbs">
      
      <!-- Access Status -->
++<<<<<<< HEAD
 +    <li class="dropdown-header">#{bundle['dataset.accessBtn.header.fileaccess']} <span class="glyphicon glyphicon-file"/></li>
++=======
+     <li class="dropdown-header">#{bundle['file.accessBtn.header.access']} <span class="glyphicon glyphicon-file"/></li>
++>>>>>>> develop
      <li><span class="dropdown-item-text">
              <span class="#{!fileMetadata.restricted ?
                             'glyphicon glyphicon-globe text-success' : (!fileDownloadHelper.canDownloadFile(fileMetadata) ? 'glyphicon glyphicon-lock text-danger' : 'icon-unlock text-success')}"/>
@@@ -211,7 -211,7 +215,11 @@@
      <!-- END: CAN DOWNLOAD ACCESS Options -->
      
      <!-- Download Metadata -->
++<<<<<<< HEAD
 +    <li class="dropdown-header">#{bundle['dataset.accessBtn.header.downloadmetadata']} <span class="glyphicon glyphicon-download-alt"/></li>
++=======
+     <li class="dropdown-header">#{bundle['file.accessBtn.header.metadata']} <span class="glyphicon glyphicon-download-alt"/></li>
++>>>>>>> develop
      
      <ui:fragment rendered="#{fileMetadata.dataFile.tabularData and fileDownloadHelper.canDownloadFile(fileMetadata)}">
          <li>
```

**Comment by pdurbin** [comment]
Like @qqmyers said this PR is probably the cause:

- #9451

We merged it a couple hours ago.

**Comment by kcondon** [comment]
@JayanthyChengan When I clicked signup, I got a 500 error in the ui and this server.log error:
[signup_svr_log_err.txt](https://github.com/IQSS/dataverse/files/11629545/signup_svr_log_err.txt)

**Comment by JayanthyChengan** [comment]
@kcondon - Committed the correction

**Comment by kcondon** [comment]
@JayanthyChengan Thanks! I'm ready to merge it.

**Pull request merged**
