### PR TITLE
#8944 - Extend 'metadatablocks/{block_id}' endpoint JSON output

### LINKED ISSUE #1510: Expose Controlled Vocabulary Terms in the API
With the Native API we should be able to expose controlled vocabulary terms.

For example: this would be helpful if someone wants to use our required Subject controlled vocabulary without having to manually add and update the terms.

See this IRC chat for more information on user needs: http://irclog.greptilian.com/rest/2015-02-07#i_95635

@pdurbin is also stubbing this out here: https://github.com/IQSS/dataverse/commit/9e6c218821ec5f465c4b97224c734f4cb4f64ffd

### LINKED ISSUE #8944: Extend 'metadatablocks' endpoint to include the 'multiple' field
**Overview of the Feature Request**

Extend the ```/metadatablocks/{identifier}``` endpoint to include the ```multiple``` field such that the schema can be used to programmatically upload data.

**What kind of user is the feature intended for?**

API Users

**What inspired the request?**

While presenting the [EasyDataverse](https://github.com/gdcc/easyDataverse) library at the Dataverse Community Meeting 2022 it was brought up in the discussion that the missing field could allow more users to upload datasets programmatically.

**What existing behavior do you want changed?**

The current REST-API implementation offers the possibility to fetch all metadatablock configurations by using the ```/metadatablocks/{identifier}``` endpoint. It provides relevant information of a metadatablock but lacks the ```multiple``` statement in a field, which on the flip is necessary to upload data via [PyDataverse](https://github.com/gdcc/pyDataverse)/HTTP. At the moment, the TSV file has to be inspected to find the corresponding values, but since metadatablock TSVs usually aren't hosted publicly this is only possible for those with access (except for the default TSVs)

An extension of the endpoint would allow users to infer the correct schema to upload datasets programmatically. Furthermore, this would allow [EasyDataverse](https://github.com/gdcc/easyDataverse) to generate Python interfaces at runtime without the need of hosting a generated API such as the one [we are hosting](https://github.com/JR-1991/pyDaRUS) at our university. This would allow the following functionality as an example:

```python
from easyDataverse import Dataset

# Adds metadata configs as objects to which data can be added
dataset = Dataset.from_installation("https://www.mydataverse.com")
dataset.citation.add_author(...)
```

### PR DESCRIPTION
**Pull request by JR-1991**
_This is a continuation of PR #9091 due to a change of the branch name._

**What this PR does / why we need it**:

This PR extends the API endpoint ```/api/metadatablocks/{block_id}``` to include the following fields:

- ```multiple```: Whether or not multiple instances of this field can exist
- ```isControlledVocabulary```:  Whether or not this field has a controlled vocabulary. Important to derive the ```typeClass``` later on
- ```controlledVocabularyValues ``` - If a vocabulary is given, includes all possible values.

With this extension it is possible to build compatible Dataverse JSON files for upload and download from any installation without having access to the TSV files. EasyDataverse would greatly benefit from this and allow users to "connect" to a Dataverse installation without the need of generating specific code.

**Which issue(s) this PR closes**:

- Closes #8944
- Closes #1510

**Special notes for your reviewer**:

None

**Suggestions on how to test this**:

Add or extend a fixture to test if the new fields are given upon execution.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

The API endpoint ```/api/metadatablocks/{block_id}``` has been extended to include the following fields:

- ```multiple```: Whether or not multiple instances of this field can exist
- ```isControlledVocabulary```:  Whether or not this field has a controlled vocabulary.
- ```controlledVocabularyValues ``` - If a vocabulary is given, includes all possible values.

**Additional documentation**:

 None

### CODE REVIEW

**Comment by mreekie** [comment]
@pdurbin  I removed the sizing for this. Let's talk during the standup.

**Comment by pdurbin** [comment]
@mreekie this is a one to one replacement. I carefully copied everything over. Yes, let's discuss!

**Comment by pdurbin** [comment]
@JR-1991 I went ahead and added some docs and a release note. Please take a look:

ae83c2790f add docs #8944
2a87ae54ad add release note #8944

You can preview the doc changes here:

- https://dataverse-guide--9213.org.readthedocs.build/en/9213/api/native-api.html#metadata-blocks-api
- https://dataverse-guide--9213.org.readthedocs.build/en/9213/admin/metadatacustomization.html#exploring-metadata-blocks

I think this is ready for QA but at standup I plan on explaining that we could do a bit more work:

- add tests for the `isControlledVocabulary` and `multiple`
- get controlledVocabularyValues with non-English values

We could also defer this work, of course.

**Comment by JR-1991** [comment]
@pdurbin thanks for adding the docs and release notes! From my side everything looks fine :-)

**Pull request merged**
