### PR TITLE
API for creating OAI-PMH sets

### PR DESCRIPTION
**Pull request by pameyer**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #4095 : API for creating OAI-PMH sets

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/4.6.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
@pameyer any thoughts on this pull request? It has merge conflicts now. I agree with what you said at #4095 that "if it works from the UI, it should work from the API". That's what #3440 is all about.

**Comment by pameyer** [comment]
@pdurbin my thinking on this one hasn't changed; but it's not at the top of the priority list at the moment.

**Comment by pdurbin** [comment]
@pameyer ok. Thanks. I just hate it when pull requests are lying around open with no communication on them. I did update #3440 to say that creating OAI sets is a GUI-only feature. Bummer. 😞

**Comment by pameyer** [comment]
I think this one may be ready for another look.  @sekmiller addressed what looks to me like all of @landreev's requests; and I added a few tests.

**Pull request merged**
