### PR TITLE
Use production date in citation for harvested dataset

### LINKED ISSUE #8103: Year in citations of harvested datasets is always current year
I try to setup a harvest client for a generic oai-pmh server, using oai_dc metadata format.
For datasets before 2021, year in the citation text is always 2021:

image

I found that for a harvested dataset, the date used is the distribution date or harvesting date if undefined:

https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L714

But this date is not set for an harvested dataset, only the publication date is set

https://github.com/IQSS/dataverse/blob/develop/src/main/resources/db/migration/afterMigrate__1-7256-upsert-referenceData.sql

Ex:

https://dataverse.harvard.edu/dataverse/harvard?q=&fq2=publicationDate%3A%222012%22&fq0=dvObjectType%3A%28datasets%29&fq1=metadataSource%3A%22Harvested%22&types=datasets&sort=dateSort&order=

### PR DESCRIPTION
**Pull request by tcoupin**
**What this PR does / why we need it**:

Date in citation div is the "citation date" which is most of th time the publication date (the first release date) (https://guides.dataverse.org/en/latest/api/native-api.html?highlight=citationdate#set-citation-date-field-type-for-a-dataset).

But for a harvested dataset, the distribution date is used instead and this date is not always present. With oai_dc format the date tag if used as production date (when harvesting ([see code](https://github.com/IQSS/dataverse/blob/develop/src/main/resources/db/migration/afterMigrate__1-7256-upsert-referenceData.sql#L20)) AND serving ([see code](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/export/dublincore/DublinCoreExportUtil.java#L125))).

This PR try to use production date for harvested dataset in addition to distribution date

**Which issue(s) this PR closes**:

- Closes #8103 

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by pdurbin** [comment]
@tcoupin from a very quick look I think we'll need some documentation. A small change to the guides would be great and lasting (more lasting than a release note). In addition, a release note fragment would be nice so we can highlight the change. Please see https://guides.dataverse.org/en/5.10.1/developers/making-releases.html#write-release-notes

**Comment by tcoupin** [comment]
Hi @pdurbin 
Release note added.
But I don't found any section in the guide about citation building to update. The PR affects only the citation generation.

**Comment by scolapasta** [comment]
Hi @tcoupin, for this next sprint we are catching up on Community PRs. Would you mind updating/ refreshing thiis PR from develop? Thanks!

**Comment by tcoupin** [comment]
I rebase on develop branch

**Review by sekmiller — APPROVED** [review]
Looks good. Thank you for the contribution. And @tcoupin, please once again update this branch with the latest from develop. Thanks!

**Pull request merged**
