### PR TITLE
Fixed guides scrolling horizontal layout bug

### PR DESCRIPTION
**Pull request by mheppler**
**What this PR does / why we need it**:

Removes ``:caption::`` option from code-block in two pages to fix a horizontal scrolling over sidenav layout bug. Moved caption to context text so users can still reference it.

**Which issue(s) this PR closes**:

Closes *#3577 Documentation: When content is wide enough to require horizontal scroll, content scrolls but left nav outline does not.*

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by mheppler** [comment]
Removed ref to removed caption. Didn't notice that warning when building locally for whatever reason.

**Review by pdurbin — APPROVED** [review]
Looking good as of e26d4ea

@poikilotherm I guess we shouldn't use captions.

**Comment by mheppler** [comment]
@pdurbin @poikilotherm, didn't dig into how we can fix the use of captions. Just saw that captions caused bad horizontal scrolling issues, so I moved that context into the main content text.

There is another issue related the Sphinx version update #7233 that might magically resolve this simply by using the latest and greatest version of Sphinx... OR... it might require us to use not only the latest version of Sphinx to build the guides BUT also an updated version of the [theme template files](https://github.com/ryan-roemer/sphinx-bootstrap-theme) to resolve this layout issue.

**Comment by pdurbin** [comment]
@mheppler sure. Seems like a good fix. At first I was skeptical about it closing #3577 since pages are mentioned in there (Shib, Two Ravens) that you didn't touch. I have no idea why those pages are ok now. I guess we just need to keep avoiding horizontal scroll for now. And yeah, like you said, we're way behind on Sphinx so maybe an upgrade will help.

**Pull request merged**
