### PR TITLE
bump google.library.version to 26.30.0

### PR DESCRIPTION
**Pull request by donsizemore**
**What this PR does / why we need it**:

Switches to the latest version of a more focused bom as a way to address the issue. See the changed file.

**Which issue(s) this PR closes**:

dataverse-security #75

**Special notes for your reviewer**:

None

**Suggestions on how to test this**:

test Google Cloud preservation workflow. Unless IQSS wants to set up for this, @qqmyers can tested it at QDR (where v26.28 of the library has already been tested. Beyond that, general regression testing is needed.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

No

**Additional documentation**:

None

### CODE REVIEW

**Comment by qqmyers** [comment]
@donsizemore - QDR switched to using the libraries-bom, which I think is smaller. See https://github.com/QualitativeDataRepository/dataverse/blob/888503e5c248930fe9770073376cd75edfeee822/modules/dataverse-parent/pom.xml#L42-L48 and https://github.com/QualitativeDataRepository/dataverse/blob/888503e5c248930fe9770073376cd75edfeee822/modules/dataverse-parent/pom.xml#L156. Would that make sense here w.r.t. security? (I think we only use this in the Google Archiver and that works with the latest libraries-bom version (26.28.0)).

**Comment by donsizemore** [comment]
> @donsizemore - QDR switched to using the libraries-bom, which I think is smaller. See https://github.com/QualitativeDataRepository/dataverse/blob/888503e5c248930fe9770073376cd75edfeee822/modules/dataverse-parent/pom.xml#L42-L48 and https://github.com/QualitativeDataRepository/dataverse/blob/888503e5c248930fe9770073376cd75edfeee822/modules/dataverse-parent/pom.xml#L156. Would that make sense here w.r.t. security? (I think we only use this in the Google Archiver and that works with the latest libraries-bom version (26.28.0)).

I think this makes perfect sense. I'll update my branch - thank you.

**Review by qqmyers — APPROVED** [review]
Looks good. Note I've only tested up to v 26.28.0 so far (29 came out yesterday!). Before this is merged I can test 29 @ QDR (unless someone wants to setup a Google Archiver).

**Comment by qqmyers** [comment]
@donsizemore - care to bump this to 26.30.0 before QA? It came out the 17th.

**Comment by donsizemore** [comment]
> @donsizemore - care to bump this to 26.30.0 before QA? It came out the 17th.

@qqmyers done!

**Comment by qqmyers** [comment]
QDR is running this in production.

**Comment by landreev** [comment]
This test failed in the last Jenkins run on this PR: `edu.harvard.iq.dataverse.api.SwordIT.testDeleteFiles` - was it a random fluke? 
... let me run it again, just for s-n-g.

**Comment by landreev** [comment]
It did just bomb with the same test failure. Could still be something not specific to this pr - but it appears to be passing in develop branch as of this morning: https://jenkins.dataverse.org/job/IQSS-dataverse-develop/
?

**Comment by landreev** [comment]
Thank you @donsizemore and @qqmyers. 
Merging.

**Pull request merged**
