### PR TITLE
add experimental rApache RPM for CentOS 7

### PR DESCRIPTION
**Pull request by pdurbin**
# RFI Checklist

### 1. Related Issues

- #3208 rApache RPM for RHEL/CentOS 7

---
### 2. Pull Request Checklist

- [x]  Functionality completed as described in FRD
- [x]  Dependencies, risks, assumptions in FRD addressed
- [x]  Unit tests completed
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [x]  Documentation completed
- [x]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [x]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

### CODE REVIEW

**Comment by pdurbin** [comment]
I just wanted to mention that at https://github.com/jeffreyhorner/rapache/issues/42 @jeffreyhorner seems interested in me updating his (the) RPM spec file to 1.2.8 so perhaps we should do that instead of including 1.2.7, which is what's in this pull request. A reminder than in production we use 1.2.6 as documented at http://guides.dataverse.org/en/4.4/installation/r-rapache-tworavens.html#c-rapache

**Comment by pdurbin** [comment]
I just moved this issue to "Code Review" in Waffle. Ideally @landreev would do the review to see if he likes the change. Please note that we **could** update to 1.2.8 per my comment above first.

**Comment by pdurbin** [comment]
@landreev and I discussed this pull request yesterday and he approves of me moving it to the QA column at https://waffle.io/IQSS/dataverse which I just did.

The main thing we discussed was the various version of rApache. If you go to https://github.com/jeffreyhorner/rapache/releases you'll see newer versions that what we run in production, which is 1.2.6. 1.2.7 and 1.2.8 are available as well though there is no indication at https://github.com/jeffreyhorner/rapache/blob/v1.2.8/ChangeLog about what the differences are (or even 1.2.6) for that matter.

It turns out that the rApache code itself hasn't changed since 2013 (1.2.5) and that versions beyond that have to do with installation and packaging files, according to @jeffreyhorner at https://github.com/jeffreyhorner/rapache/issues/42#issuecomment-237294986

When I made this pull request I used the latest available RPM spec file which was for rApache 1.2.7. In short, @landreev and I think this version should be just fine for Dataverse users running CentOS 7 since it's equivalent to the 1.2.6 version we use in production. In #3208 I mention how @donsizemore has said the RPM works well.

**Comment by kcondon** [comment]
OK, checked with Phil and seems ok to merge.

**Pull request merged**
