### PR TITLE
2670 guestbook response display download

### PR DESCRIPTION
**Pull request by sekmiller**
# RFI Checklist

_**Before** submitting the pull request, fill out sections (1.) Related Issues and (2.) Pull Request Checklist._

### 1. Related Issues

_List and [link](https://guides.github.com/features/issues/#notifications) to the issues in this Pull Request._

- #2670 Guestbooks: View collected data for large dv, ds, downloads takes a really long time
- #1418 Download Data: Add place in UI to view no guestbook downloads and all downloads
- #1350 Guestbook: Logging information is recorded to db but most is not displayed in GUI
- #3064 Guestbook: Downloaded guestbook data has commas at end of each line, should not be.

---
### 2. Pull Request Checklist

- [X]  Functionality completed as described in Tickets
- [ ]  Dependencies, risks, assumptions in FRD addressed NA
- [X]  Unit tests completed
- [ ]  Deployment requirements identified (e.g., SQL scripts, indexing) NA
- [X]  Documentation completed
- [X]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [ ]  Code review completed or waived
- [x]  Testing requirements completed
- [x]  Usability testing completed or waived
- [x]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

### CODE REVIEW

**Comment by kcondon** [comment]
Passing to UX for review.

**Comment by sekmiller** [comment]
@eaquigley, @kcondon - I have addressed the UI issues brought up in the recent email - Breadcrumbs, button alignment and download of no responses (download button suppressed until responses exist.)

**Comment by eaquigley** [comment]
@kcondon @scolapasta @sekmiller I took a look at this and noticed two things:

1) on the dataset page, for some reason i am seeing an extra > in the breadcrumbs: 
screen shot 2016-04-15 at 3 57 04 pm

2) Guestbook Name: Test Dataset Guestbook and Download Responses button should be in line. Additionally, the Download Responses button shouldn't be hanging over the edge of the data table.
Current look: 
screen shot 2016-04-15 at 3 58 15 pm

What it should look like:
screen shot 2016-04-15 at 4 06 24 pm

**Comment by sekmiller** [comment]
Fixed button alignment and breadcrumb setup.

**Comment by kcondon** [comment]
OK, confirmed last two issues are fixed. Spoke with Liz, ready to merge.

**Pull request merged**
