### PR TITLE
Fixes an issue with search cards for harvested records

### LINKED ISSUE #10611: Harvested dataset display is broken on develop branch
**What steps does it take to reproduce the issue?**

With a Dataverse compiled with the latest version of the current development source code : 
* login as a super-user
* on dashboard page, add a new Harvesting Clients
* run the client
* after the client has finished, check that datasets have been harvested
* go to the dataverse page containing the harvested datasets
* the display of harvested datasets is like non-harvested (created on the repository)

**Which version of Dataverse are you using?**

I reproduce this bug after compiling the latest version of the code on `develop` branch.

**Any related open or closed issues to this bug report?**

I think this bug is related to the new feature #10298 : on [search-include-fragment.xhtml](https://github.com/IQSS/dataverse/blob/develop/src/main/webapp/search-include-fragment.xhtml#L506) at line 506, the display is conditioned by the [SolrSearchResult.isHarvested()](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java#L140) method. The `harvested` attribute is set by [SearchServiceBean](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L582) class at line 582.

With the new feature, `metadataSource` can now contain the repository source, [not only](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L581) `Harvested` value.

**Screenshots:**

Actual
harvested_datasets

Expected
expected_harvested_datasets

### PR DESCRIPTION
**Pull request by landreev**
**What this PR does / why we need it**:

See the issue, fairly straightforward

This implements indexing of the actual origin of harvested records as the "metadata source" as an optional feature - i.e., one needs to opt in to have it indexed; otherwise the old-style "Harvested" will be indexed for all harvested objects. 

**Which issue(s) this PR closes**:

Closes #10611

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by landreev** [comment]
I think it's ready, just needs an updated release note reflecting the new setting for the feature. 
The Jenkins run yesterday appears to have died because of an aws fluke/timeout. My commit has just started another run, we'll see how it goes.

**Comment by landreev** [comment]
(the 2 harvesting clients Jenkins tests are failing now, since they are relying on the "metadata source" feature - we'll add the flag to the harvesting config in jenkins.yml once the PR is merged)

**Review by qqmyers — APPROVED** [review]
Looks good.

**Comment by landreev** [comment]
@donsizemore has merged /gdcc/dataverse-ansible/pull/363 (thank you!), so I'm re-running the tests.

**Comment by landreev** [comment]
There were a couple of simple merge conflicts with #10579 (that's why the last Jenkins test refused to run); resolved.

**Comment by landreev** [comment]
Tests are passing now.

**Pull request merged**
