### PR TITLE
rename role.editor to role.contributor

### PR DESCRIPTION
**Pull request by tcoupin**
**Which issue(s) this PR closes**:

Closes https://github.com/IQSS/dataverse/issues/7129

### CODE REVIEW

**Comment by pdurbin** [comment]
@tcoupin hi! Sorry for the delay in looking at this. Two things: I noticed the Jenkins job failed. Also, your branch is called "develop", which makes it tricky for us to work on it locally.

Assuming you're still interested in this, could you please close this PR and make a fresh one with a branch called something like "7129-editor"? (Or you could create a fresh issue since that one is closed.)

**Comment by mreekie** [comment]
Sizing:
- rationale for changing editor to contributor?
- Change was made a long time ago, and this is a leftover that causes confusion in translating.
- The level of permissions is different for editor and contributor. However, we have eliminated editor in favor of contributor.
 - 2 lines in a property file

**Comment by scolapasta** [comment]
Hi @tcoupin  did you see the feedback @pdurbin provided back in January? Would you mind reviewing - thanks!

**Review by sekmiller — APPROVED** [review]
Looks good. @tcoupin can you just make sure the branch is up to date with dev?  thanks!

**Comment by kcondon** [comment]
Hi @tcoupin Would you refresh from develop since the version number has changed and so I cannot build in my test environment. Thanks!

**Pull request merged**
