### PR TITLE
consistent format for dataverseContacts JSON #5724

### PR DESCRIPTION
**Pull request by pdurbin**
Connects to #5724.

### CODE REVIEW

**Comment by djbrooke** [comment]
Closing this test-only PR as the tests are included in #5739.

**Comment by pdurbin** [comment]
Reopening as this is the "as usual" one we want (not a weird hotfix to master etc.)

**Comment by pdurbin** [comment]
Maybe @michbarsinai knows how to make it work but it was way easier to just take it out.

**Comment by michbarsinai** [comment]
@matthew-a-dunlap what lambda bug?

**Comment by pdurbin** [comment]
@michbarsinai please see https://github.com/IQSS/dataverse/issues/5724#issuecomment-481729978 for my take. In 50c5c2d I modified the `public static JsonArrayBuilder json(List<DataverseContact> dataverseContacts)` method, taking out

        return dataverseContacts.stream()
                .map(dc -> jsonObjectBuilder()
                .add("displayOrder", dc.getDisplayOrder())
                .add("contactEmail", dc.getContactEmail())
                ).collect(toJsonArray());

... and replacing it with this non-lamda function:

        JsonArrayBuilder jsonArrayOfContacts = Json.createArrayBuilder();
        for (DataverseContact dataverseContact : dataverseContacts) {
            NullSafeJsonBuilder contactJsonObject = NullSafeJsonBuilder.jsonObjectBuilder();
            contactJsonObject.add("displayOrder", dataverseContact.getDisplayOrder());
            contactJsonObject.add("contactEmail", dataverseContact.getContactEmail());
            jsonArrayOfContacts.add(contactJsonObject);
        }
        return jsonArrayOfContacts;

It's the weirdest thing. If you look at 50c0de8 (and earlier commit) you can see that the lambda version is emitting JSON for dataverse contacts from a unit test. But the later commit to remove the lambda was the quickest way to get the deployed app to emit JSON for dataverse contacts. I hope this makes sense. Again, in production the lambda would only ever emit an empty JSON array for dataset contacts. Weird.

**Comment by michbarsinai** [comment]
Weird indeed. We had issues with lambdas on classes weaved by our JPA implementation. These were fixed in later versions of EclipseLink, but I'm not sure whether we upgraded or not. This is probably not directly related, since JsonPrinter is  not an entity class. But maybe some other byte code level mechanism is involved (e.g. dependency injection)?

**Comment by pdurbin** [comment]
I have no idea but if we figure it out let's put it in a JavaOne^h^h^h CodeOne talk next year. 😄

**Pull request merged**
