### PR TITLE
Restore handle registration support (Based on DANS-KNAW's fork)

### PR DESCRIPTION
**Pull request by solhm**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #2437: Restore handle registration functionality in 4.x

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/4.6.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
@solhm @sekmiller @scolapasta has this pull request been replaced with pull request #3826? Is it safe to close?

**Comment by solhm** [comment]
@pdurbin yes, its replaced with #3826. And it's safe to close.

**Comment by pdurbin** [comment]
I just checked with @sekmiller and he said it's safe to close this. Indeed, it has been replaced by pull request #3826.

**Comment by pdurbin** [comment]
Oh! And @solhm left a comment as well. Thanks!

**Pull request closed without merging**
