### PR TITLE
sec35 duracloud update

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
Duracloud used a vulnerable XStream version. Since v7.1.0 this has been updated to XStream 1.4.18. This PR applies this version.

**Which issue(s) this PR closes**:

Closes IQSS/dataverse-security#35

**Special notes for your reviewer**:
None.

**Suggestions on how to test this**:
Guess @qqmyers knows this best, as it would require setting up the Duracloud archiving option. I cannot test this as I have no access to Duracloud.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope.

**Is there a release notes update needed for this change?**:
Nope. (Dunno if you folks wanna state fixed sec issues somewhere)

**Additional documentation**:
None.

### CODE REVIEW

**Comment by qqmyers** [comment]
I'd suggest just testing to assure nothing breaks with the main app (it shouldn't). The one place I know that is using it is TDL and we have some work coming up to add features there, so we can address any issues that arise with the new library there rather than as part of the PR.

**Review by pdurbin — APPROVED** [review]
I don't have the ability to test Duracloud ( https://guides.dataverse.org/en/5.9/installation/config.html#duracloud-configuration ) but @qqmyers indicated that he can test it in the future (see his comment). That's good enough for me. I don't think it's a widely used feature. Approved.

**Comment by donsizemore** [comment]
@pdurbin don't look now but https://github.com/IQSS/dataverse-security/issues/35#issuecomment-1027193725

**Comment by pdurbin** [comment]
@donsizemore thanks. I guess I'm in favor of putting this PR through QA because it does fix some stuff. And then another PR when new version of Duracloud is out, I suppose.

**Comment by kcondon** [comment]
@poikilotherm Please refresh from develop as a db column has been dropped and I can't deploy this as is. Thanks!

**Comment by poikilotherm** [comment]
@kcondon done! :smile:

**Pull request merged**
