### PR TITLE
Fixing Solr Init Script Instructions

### PR DESCRIPTION
**Pull request by dyaw-Drexel**
https://github.com/IQSS/dataverse/issues/5905

## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- #ISSUE_NUMBER: ISSUE_TITLE

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by dyaw-Drexel** [comment]
> 
> 
> Thank you for your first PR to Dataverse @dyaw-Drexel!
> 
> I fear the changes you request would not solve your problem we solved together at [the IRC logs](http://irclog.iq.harvard.edu/dataverse/2019-06-03#i_95878).
> 
> Would you like some guidance with this?

@poikilotherm Sure, did I leave something out?

**Comment by pdurbin** [comment]
@poikilotherm @donsizemore it looks like @dyaw-Drexel just pushed 1e022ab if you'd like like to take a look. Thanks, all!

**Comment by poikilotherm** [comment]
I just created https://github.com/dyaw-Drexel/dataverse/pull/1 with what I think shoud be done.
Maybe @pdurbin and @donsizemore can give it a look and even test it :-)
(The core.properties creation is exactly what I am doing in solr-k8s...)

**Comment by pdurbin** [comment]
@poikilotherm thanks. With all the whitespace changes it's a little tough to understand what you're suggesting. Here's a link that eliminates the whitespaces changes and (I hope) explains the core of the changes you're proposing: https://github.com/dyaw-Drexel/dataverse/pull/1/commits/5175a72bc2732067824ac0ad9111cd0937583877

**Comment by poikilotherm** [comment]
Meh. Editors sometimes really are annoying. Will change the commits to exclude indentation mangling in the doc.

**Comment by dyaw-Drexel** [comment]
Thanks! Sorry about that I am new to posting on Github.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by donsizemore** [comment]
@landreev I thought the issue was that with solr started manually by

`bin/solr start`

systemd didn't know what to do with the resulting process. My suggestion above was to change this line to a service or systemctl call so the installing person wouldn't need to manually kill solr.

**Pull request merged**
