### PR TITLE
#5937 docker-cp server.log into conf/docker-aio/ for debugging conven…

### PR DESCRIPTION
**Pull request by donsizemore**
…ience

## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- #5937 

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pameyer** [comment]
Changing `conf/docker-aio/run-test-suite.sh` to include docker commands locks that script into a stand-alone docker environment (which may not be an issue, if that's the only place/way it's used).  An alternative approach would be to map the host `conf/docker-aio` directory to `/usr/local/glassfish4/glassfish/domains/domain1/logs` by changing the `docker run -d -p 8084:80 -p 8083:8080 -p 9010:9009 --name dv dv0` line in `conf/docker-aio/prep_it.bash` (or it's equivalent) to `docker run -d -p 8084:80 -p 8083:8080 -p 9010:9009 -v `pwd`:/usr/local/glassfish4/glassfish/domains/domain1/logs --name dv dv0`.

**Comment by pdurbin** [comment]
> locks that script into a stand-alone docker environment

@pameyer hmm, good point about `run-test-suite.sh` but maybe we could factor out the list of tests or something. I forget if I told you but @donsizemore and I are working on step 1 ("Get https://jenkins.dataverse.org to do the same job that the older Jenkins server and phoenix do which is to catch regressions before a release) from this "thoughts on automated testing" post of mine: https://groups.google.com/d/msg/dataverse-dev/ISot5k4VjZQ/t-hzPk8tAwAJ

To be honest, I was thinking that maybe we'd add the `docker cp` to a future version of https://github.com/IQSS/dataverse-jenkins/blob/ad6a20e64eb7bcabf1e9593d6a0566a973667373/IQSS-dataverse-api-test-suite-docker-aio-develop.xml but I'm fine with whatever. 😄 The idea is to be able to see from a browser why a test failed.

**Comment by donsizemore** [comment]
@pameyer I thought about that, but the script was in docker-aio/ so I went with it.

I can add the command to whatever Jenkins job we wind up using; I just wanted to be sure to catch the logfile before anything happened to the container (or the service).

**Comment by pdurbin** [comment]
@donsizemore I'm still fine with whatever but thanks for explaining a bit more your thought process. Makes sense. I think the Docker image keeps running indefinitely. There's a `docker rm` or whatever early on in the "prep" script that deletes the old image before trying to spin up a fresh one.

**Comment by donsizemore** [comment]
will keep this in jenkins instead.

**Pull request closed without merging**
