### PR TITLE
update shellspec for Debian 12, Rocky 9

### LINKED ISSUE #10681: Shellspec jobs fail for CentOS 7
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When recent commits are built, that trigger the Shellspec workflow, the CentOS 7 job fails.

* Which page(s) does it occurs on?
n/a

* What happens?
E.g., in <https://github.com/IQSS/dataverse/actions/runs/9864329507/job/27239023962>, the job fails because some dependencies are missing for the build system.

* To whom does it occur (all users, curators, superusers)?
Developers

* What did you expect to happen?
The job should pass.

**Which version of Dataverse are you using?**
These are recent builds. >= 6.3

**Any related open or closed issues to this bug report?**
In #9829 I found a different problem with the build system, but this is unrelated – except in the way that I feel CentOS 7 may have become unsupported.

**Screenshots:**
n/a, see the linked action run.

### PR DESCRIPTION
**Pull request by donsizemore**
**What this PR does / why we need it**:

updates shellspec for Debian 12, Rocky 9

**Which issue(s) this PR closes**:

Closes #10681

**Special notes for your reviewer**:

none

**Suggestions on how to test this**:

none

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

no

**Is there a release notes update needed for this change?**:

no

**Additional documentation**:

none

### CODE REVIEW

**Comment by donsizemore** [comment]
@pdurbin @bencomp @poikilotherm how much do we care about shellspec on Deb12? see https://github.com/uncch-rdmc/dataverse/actions/runs/9941676940

**Comment by pdurbin** [comment]
Meh, I'm ok with dropping it. We still have Ubuntu.

**Comment by bencomp** [comment]
I do not care per se if Debian 12 is supported, unless it is supported for the rest of Dataverse. If the issue is that curl is not installed by default, that may be fixable.

I don't know if removing CentOS 7 from this workflow also means the official end of support for that platform? Then a release note would be useful.

**Comment by donsizemore** [comment]
@bencomp Debian 12 is as supported as any other Linux distribution. It is well known that CentOS 7 reached EOL on June 30 2024. I submitted this PR to update that documentation: https://github.com/IQSS/dataverse/pull/10624

**Review by bencomp — APPROVED** [review]

**Review by pdurbin — APPROVED** [review]
Looks good. Thanks, @donsizemore!

**Pull request merged**
