### PR TITLE
#8975 Fix tag display when they run off the page

### LINKED ISSUE #8975: File level metadata: File level metadata tags should wrap and not run off the page
Please fill out as much of the template as you can.
Start below this comment section.
-->
Follow the link to this draft dataset in production, which has a long list of file-level tags and long description:
https://dataverse.harvard.edu/file.xhtml?fileId=6489063&version=DRAFT
The tags run off the page, see screen capture

* When does this issue occur?
Whenever file level tags or description exceed a certain # of characters, not sure how many characters are supported

* Which page(s) does it occurs on?
FILE LANDING PAGE

* What happens?
FILE-LEVEL METADATA TAGS/description RUN OFF THE PAGE WHEN EXCEED CERTAIN #CHARACTERS

* To whom does it occur (all users, curators, superusers)?
SUPER USERS, ADMINS (ALL USERS)

* What did you expect to happen?
* TAGS/TEXT SHOULD WRAP

@scolapasta this is for a paid curation project we plan to release soon. Please add to sprint.

**Which version of Dataverse are you using?**

MOST RECENT

**Any related open or closed issues to this bug report?**

**Screenshots:**

Screen Shot 2022-09-13 at 4 18 29 PM

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**: The display of file tags (actually categories) runs off the side of the page on the file page when there are numerous long categories associated with a file. This PR updates the css to fix the word break. For reasons that are not entirely clear this also fixes the wrapping of the file description wrapping issue 9325

**Which issue(s) this PR closes**:

Closes #8975 File level metadata: File level metadata tags should wrap and not run off the page.
#9325 Description metadata field: description field text should wrap and not run off the page 

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No
**Is there a release notes update needed for this change?**:
no
**Additional documentation**:

### CODE REVIEW

**Comment by qqmyers** [comment]
On demo, if I add `word-break: break-word` to the `file-tags` div, these wrap:
from 
image
to
image
 Does just 
```
#file-tags {
word-break:break-word;
}
``` in the structure.css file work?

**Comment by sekmiller** [comment]
I wasn't able to get the css to recognize the style (is there a particular place I have to put it?)  but even when I did this:

                                                            <div id="file-tags" style="word-break:break-word; background-color: yellowgreen;"> 

directly in file.xhtml I got this:
Screen Shot 2023-01-27 at 3 43 44 PM

**Review by landreev — APPROVED** [review]
> For reasons that are not entirely clear this also fixes the wrapping of the file description wrapping issue 9325

I'm assuming the reason is that the page renders these separate divs based on the maximum character width, i.e. the longest one; which must have been these tags display - and now that it's solved, all the other ones are rendered normally? - just a guess.

**Comment by sekmiller** [comment]
the fix suggested by Jim works in Safari and Firefox. I did notice that the tags run off the page in Safari if you make the page too narrow, but we've seen that in other places on Safari and we may have to just live with it.

**Pull request merged**
