### PR TITLE
Sonarcube Fixes

### LINKED ISSUE #9280: In Files.java usr try-with-resources to for  JsonReader
In Files.java usr try-with-resources to for  JsonReader jsonReader = Json.createReader(new StringReader(jsonData)); in method updateFileMetadata

### LINKED ISSUE #9282: In TabularSubsetGenerator.java use try-with-resources for BufferedWriter
- [x] In TabularSubsetGenerator.java use try-with-resources for BufferedWriter out = new BufferedWriter(new FileWriter(outfile)); in method subsetFile(...) 
- [ ] 
- [x] -- FileChannel fc = (FileChannel.open(Paths.get(rotatedImageFile.getAbsolutePath()), StandardOpenOption.READ)); in method subsetObjectVector(...) 
- [ ] 
- [x] --  BufferedInputStream rotfileStream = new BufferedInputStream(new FileInputStream(rotatedImageFile)); in method extract(...)  
- [ ] 
- [x] --- Scanner scanner = new Scanner(tabfileStream); in generateRotatedImage(...) 
- [ ] 
- [x] ---    BufferedOutputStream finalOut = new BufferedOutputStream(new FileOutputStream (new File(rotatedImageFileName))); in generateRotatedImage(...) 
- [ ] 
- [x] --- BufferedInputStream cachedIn = new BufferedInputStream(new FileInputStream(cachedTempFile)); in method generateRotatedImage(...) 
- [ ] 
- [x] ---BufferedInputStream rotfileStream = new BufferedInputStream(new FileInputStream(rotfile)); in reverseRotatedImage(...)

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: This is a branch/draft PR to collect tech-debt fixes for sonarcube.

**Which issue(s) this PR closes**:

Closes #9280
Closes #9282

**Special notes for your reviewer**:

**Suggestions on how to test this**: Regression testing plus running through Sonarcube to assure the matching issues are gone.
#9280 is in the Files API {id}/metadata call (trivial fix replacing code with the same code in the JsonUtil class).
#9282 is a change in the tabular download subset functionality - not sure if there's already a test or guides example for that call. 

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by qqmyers** [comment]
FWIW - issues had combined size of 6.

**Review by rtreacy — APPROVED** [review]
Both clear SonarQube

**Comment by mreekie** [comment]
Sprint review:
- Not sure where this came from?
- Looks like it's going to go through QA so it needs sizing.
- Is this related to the re-arch? No labels.

**Comment by mreekie** [comment]
sprint kickoff
- include in QATail for Jan 11, 2023

**Pull request merged**
