### PR TITLE
7128 Change the source value from DVN to archive.

### LINKED ISSUE #7128: The source attribute in the DDI XML response has the incorrect value "DVN"
When the issue occurs: When harvesting a dataset with Geospatial Metadata
Which page it occurs on: It occurs when harvesting, so the Dashboard
To whom it occurs: People who harvest Geospatial Metadata
Version: 4.20

**Context**
The DDI XML response from Dataverse has multiple XSD validation errors which are being addressed one by one. This one deals with the source attribute.

Main issue: https://github.com/IQSS/dataverse/issues/3648
Geographic Bounding Box: https://github.com/IQSS/dataverse/issues/7108
Sequence: https://github.com/IQSS/dataverse/issues/7127

### PR DESCRIPTION
**Pull request by JingMa87**
**What this PR does / why we need it**: Improves the DDI XML according to the XSD

**Which issue(s) this PR closes**: 7128

Closes #7128 

**Special notes for your reviewer**: The fix we've all been waiting for.

**Suggestions on how to test this**: You can validate here https://www.freeformatter.com/xml-validator-xsd.html with this XSD https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd. You do need to fix the import elements first. These are the correct ones:
```
   <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/xml.xsd"/>
   <xs:import namespace="http://www.w3.org/1999/xhtml" schemaLocation="https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/ddi-xhtml11.xsd"/>
   <xs:import namespace="http://purl.org/dc/terms/" schemaLocation="https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/dcterms.xsd"/>
```

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: No

**Is there a release notes update needed for this change?**: No

**Additional documentation**:

### CODE REVIEW

**Comment by kcondon** [comment]
@JingMa87 Would you show my how to adjust this xml to use the correct import elements?

<?xml version='1.0' encoding='UTF-8'?><codeBook xmlns="ddi:codebook:2_5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ddi:codebook:2_5 https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd" version="2.5"><docDscr><citation><titlStmt><titl>Test Again</titl><IDNo agency="DOI">doi:10.70122/FK2/1DAG4Z</IDNo></titlStmt><distStmt><distrbtr source="archive">Root</distrbtr><distDate>2020-07-29</distDate></distStmt><verStmt source="archive"><version date="2020-07-29" type="RELEASED">1</version></verStmt><biblCit>Admin, Dataverse, 2020, "Test Again", https://doi.org/10.70122/FK2/1DAG4Z, Root, V1</biblCit></citation></docDscr><stdyDscr><citation><titlStmt><titl>Test Again</titl><IDNo agency="DOI">doi:10.70122/FK2/1DAG4Z</IDNo></titlStmt><rspStmt><AuthEnty affiliation="Dataverse.org">Admin, Dataverse</AuthEnty></rspStmt><prodStmt/><distStmt><distrbtr source="archive">Root</distrbtr><contact affiliation="Dataverse.org" email="dataverse@mailinator.com">Admin, Dataverse</contact><depositr>Admin, Dataverse</depositr><depDate>2020-07-29</depDate></distStmt></citation><stdyInfo><subject><keyword>Arts and Humanities</keyword></subject><abstract>1</abstract><sumDscr/></stdyInfo><method><dataColl><sources/></dataColl><anlyInfo/></method><dataAccs><notes type="DVN:TOU" level="dv">CC0 Waiver</notes><setAvail/><useStmt/></dataAccs><othrStdyMat/></stdyDscr></codeBook>

**Comment by jggautier** [comment]
Hey @JingMa87. I use https://www.freeformatter.com/xml-validator-xsd.html to check for XML validation and it gets the schemalocation info from the top `<codeBook>` element in the XML document itself. The "import elements" you mentioned looks like similar information, so you're saying they need to be used instead or in addition? I'd be curious to know why and how, too. I've been under the assumption that the info needed to valid these DDI XML docs against the DDI Codebook schema is also in the DDI XML doc.

**Comment by JingMa87** [comment]
@kcondon You only have to fix the import statements of the XSD schema. The DDI export you posted looks ok.

**Comment by JingMa87** [comment]
@kcondon I addressed that problem in this issue and accompanying PR: https://github.com/IQSS/dataverse/issues/7127.

**Comment by kcondon** [comment]
@JingMa87 Yes, I see that you addressed the dvn issue. What I am saying is there is another issue and I do not know whether it is a result of this being incorrect in some way or just another issue that should/will be addressed later.

**Comment by JingMa87** [comment]
@kcondon It's another problem and in my last comment I added the GitHub issue which addresses that. ;)

**Comment by kcondon** [comment]
@JingMa87 OK thanks for the clarification. I see so many prs it is not always so easy to interpret them.

**Pull request merged**
