### PR TITLE
Add Shib attribute characterset conversion to getValueFromAssertion

### LINKED ISSUE #8573: ShibAttributeCharacterSetConversionEnabled has no influence on affiliation
**What steps does it take to reproduce the issue?**

* When does this issue occur?
If you get the affiliation via shibboleth and use ShibAttributeCharacterSetConversionEnabled set to true

* Which page(s) does it occurs on?

* What happens?
affiliation has garbled chars from bad utf-8 conversation

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
the following code has to be enabled for affiliation too
Shib.java:
if(systemConfig.isShibAttributeCharacterSetConversionEnabled()) {
                        attributeValue= new String( attributeValue.getBytes("ISO-8859-1"), "UTF-8");
                }

**Which version of Dataverse are you using?**
5.9 

**Any related open or closed issues to this bug report?**
no

### PR DESCRIPTION
**Pull request by PaulBoon**
**What this PR does / why we need it**:
Adds optional Shib attribute characterset conversion to getValueFromAssertion

**Which issue(s) this PR closes**:

- Closes #8573

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by PaulBoon** [comment]
@pdurbin We are running this in production for some time now, whithout any problems. Could this small change be merged in the next version please?

**Comment by cmbz** [comment]
@pdurbin I have no objection. @scolapasta?

**Comment by pdurbin** [comment]
@PaulBoon I'm afraid there are merge conflicts. Do you mind resolving them?

**Comment by PaulBoon** [comment]
@pdurbin Should be OK now

**Review by pdurbin — APPROVED** [review]
Thanks. I didn't test this but the change makes sense. Approved.

**Comment by ofahimIQSS** [comment]
@PaulBoon Can you please add testing steps for this ticket. Thank you!

**Comment by PaulBoon** [comment]
Testing is difficult because we don't have a testIdp where we can fake an affiliation. 
But now that I had a peek at the code change, I do see it is wrong; it is now not mapping to StandardCharsets.UTF_8

**Comment by PaulBoon** [comment]
@ofahimIQSS I was hoping someone involved with the original issue or code for the `getRequiredValueFromAssertion` could test it.

**Comment by ofahimIQSS** [comment]
@PaulBoon Hey Paul - does your institution show up on the list of Institutions and when you login, is your information garbled or can you make it garbled? This is on https://demo.dataverse.org/  -  Can you reproduce the bug there and paste a screenshot?

**Comment by pdurbin** [comment]
I'm having trouble reproducing the bug. In the issue (#8573) the suggestion was to use "Universität", but it seems to work fine, at least when I use :DebugShibAccountType as described at https://guides.dataverse.org/en/6.4/developers/remote-users.html#shibboleth-and-oauth

Maybe we need a real Shibboleth setup to test with? And access to an account that has "Universität" or similar to test with?

Anyway, here are screenshots from my test:

Screenshot 2024-11-01 at 4 17 17 PM

Screenshot 2024-11-01 at 4 17 24 PM

Here's a commit I pushed for the above to a test branch: 28b6779489

Again, I'm not sure how to reproduce the bug. 🤷

**Comment by PaulBoon** [comment]
@ofahimIQSS Sorry for my late reply, I tend to ignore my mailbox regulary. About the login, the dropdown with institutes looks fine, but I can not find my institute (DANS), also not KNAW.

**Comment by PaulBoon** [comment]
@pdurbin That you could not reproduce the problem might have to do with the input, I mean that string was probably all ready in UTF-8 when you entered it in a form?

**Comment by pdurbin** [comment]
@PaulBoon probably. The [whole file](https://github.com/IQSS/dataverse/commit/28b6779489848e31885a36a4124e005a2af5194e) is UTF-8:

```
% file ~/Downloads/ShibUtil.java 
/Users/PDurbin/Downloads/ShibUtil.java: Java source, Unicode text, UTF-8 text
```

**Comment by PaulBoon** [comment]
Unless I made a copy error, it should work because I assume the existing code in getRequiredValueFromAssertion is correct, which I copied into getValueFromAssertion. 
So, testing is gold, but we could go for code inspection (silver or bronze?) instead.

**Comment by pdurbin** [comment]
@PaulBoon good idea. I tried this in https://github.com/PaulBoon/dataverse/pull/9/commits/368bcc9ddced52d0b6b07f2a571fbd10ca1177ec but "Universität" still looks fine.

Screenshot 2024-11-06 at 10 47 59 AM

Screenshot 2024-11-06 at 10 52 45 AM

I can't push to your branch, by the way. That's why I created https://github.com/PaulBoon/dataverse/pull/9

**Comment by ofahimIQSS** [comment]
No issues found during Regression. Merging PR. 

https://github.com/user-attachments/assets/4c12b148-a584-4383-bea1-9023fc467c84

**Pull request merged**
