### PR TITLE
Temp file cleanup for PrimeFaces uploads 10667

### LINKED ISSUE #10667: Temporary files in uploads directory not deleting automatically
**What steps does it take to reproduce the issue?**

* When does this issue occur?
After upgrading to 6.2 version

* Which page(s) does it occurs on?
File uploads

* What happens?
Files in `uploads` directory are not getting cleared after successful uploads. We are using Openstack Swift S3. As workaround I  had to setup a cronjob to manually files from uploads directory

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
After a successful upload, the temporary files from `uploads` should clear automatically 

**Which version of Dataverse are you using?**
6.2

**Any related open or closed issues to this bug report?**

**Screenshots:**
image

As you can see on our demo server, there are 69777 files after we upgraded to 6.2 on May 9

Related discussion: https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/Uploads.20directory.20content.20not.20clearing.20after.206.2E2.20upgrade/near/441953212

### PR DESCRIPTION
**Pull request by landreev**
**What this PR does / why we need it**:

A one-line fix for #10667 - apparently PrimeFaces UI file upload leaves every uploaded file in the temp directory .../domain1/uploads. 
With this line, the uploaded file is properly cleaned up after it's copied to the Dataverse holding location. There are still *multiple* tiny (5-50 bytes) files left with debugging/logging messages (?) - but at least that should not be a practically important issue. 

**Which issue(s) this PR closes**:

- Closes #10667

**Special notes for your reviewer**:

**Suggestions on how to test this**:

Upload some files through the UI, check what's left in .../domain1/uploads before and after. 

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Looks reasonable - probably needs a one line release note.

**Comment by pdurbin** [comment]
I'm confused. It seems about the same. 7 files instead of 8?

## Before

```
root@dataverse:/opt/payara# ls -1 /dv/uploads
upload__74533f62_1920f9f4c16__7ff8_00000000.tmp
upload__74533f62_1920f9f4c16__7ff8_00000003.tmp
upload__74533f62_1920f9f4c16__7ff8_00000005.tmp
upload__74533f62_1920f9f4c16__7ff8_00000006.tmp
upload__74533f62_1920f9f4c16__7ff8_00000007.tmp
upload__74533f62_1920f9f4c16__7ff8_00000008.tmp
upload__74533f62_1920f9f4c16__7ff8_00000009.tmp
upload__74533f62_1920f9f4c16__7ff8_00000010.tmp
root@dataverse:/opt/payara#
```

## After

```
root@dataverse:/opt/payara# ls -1 /dv/uploads
upload_7f69f7f1_1920fa5df62__7ff8_00000000.tmp
upload_7f69f7f1_1920fa5df62__7ff8_00000003.tmp
upload_7f69f7f1_1920fa5df62__7ff8_00000005.tmp
upload_7f69f7f1_1920fa5df62__7ff8_00000006.tmp
upload_7f69f7f1_1920fa5df62__7ff8_00000007.tmp
upload_7f69f7f1_1920fa5df62__7ff8_00000008.tmp
upload_7f69f7f1_1920fa5df62__7ff8_00000009.tmp
root@dataverse:/opt/payara# 
```

**Comment by donsizemore** [comment]
> I'm confused. It seems about the same. 7 files instead of 8?

this sounds right: `the uploaded file is properly cleaned up after it's copied to the Dataverse holding location. There are still multiple tiny (5-50 bytes) files left`

**Comment by pdurbin** [comment]
Yes, my bad. I wasn't looking at file sizes. I uploaded a 45 KB file and as of this pull request it doesn't stick around. Will merge.

## Before

```
root@dataverse:/opt/payara# ls -l /dv/uploads
total 72
-rw-r--r-- 1 payara payara    11 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000000.tmp
-rw-r--r-- 1 payara payara     5 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000003.tmp
-rw-r--r-- 1 payara payara    40 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000005.tmp
-rw-r--r-- 1 payara payara     4 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000006.tmp
-rw-r--r-- 1 payara payara    45 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000007.tmp
-rw-r--r-- 1 payara payara    22 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000008.tmp
-rw-r--r-- 1 payara payara    47 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000009.tmp
-rw-r--r-- 1 payara payara 45055 Sep 20 13:52 upload__69f114f2_1920fb298ce__7ff8_00000010.tmp
root@dataverse:/opt/payara# 
```

## After

```
root@dataverse:/opt/payara# ls -l /dv/uploads
total 28
-rw-r--r-- 1 payara payara 11 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000000.tmp
-rw-r--r-- 1 payara payara  5 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000003.tmp
-rw-r--r-- 1 payara payara 39 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000005.tmp
-rw-r--r-- 1 payara payara  4 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000006.tmp
-rw-r--r-- 1 payara payara 45 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000007.tmp
-rw-r--r-- 1 payara payara 22 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000008.tmp
-rw-r--r-- 1 payara payara 47 Sep 20 13:39 upload_7f69f7f1_1920fa5df62__7ff8_00000009.tmp
root@dataverse:/opt/payara#
```

**Comment by landreev** [comment]
Yeah. The tiny files are mildly annoying - I kinda wish I knew where they were coming from (not from any of our own javascript, as far as I could tell). But we honestly can't afford to invest any serious effort into this old UI. And for the reporting user the practical issue was that 
> ... So far cleanup every hour is working well but it still gets issues sometimes when there is 250GB of data uploaded in an hour.

so, with the bulk/payload data files cleaned up that should no longer be an issue.

**Comment by landreev** [comment]
Thank you everybody for moving this along quickly.
Jim did ask for a release note in the approving comment. But, did we really need one?

**Comment by donsizemore** [comment]
> Thank you everybody for moving this along quickly. Jim did ask for a release note in the approving comment. But, did we really need one?

I think it's worth mentioning the need to clean up that directory with a cronjob or some other mechanism.

**Comment by landreev** [comment]
(if you all think it's worth mentioning, I'll just add a line about it to the main extended notes directly)

**Comment by landreev** [comment]
@donsizemore @qqmyers 

> > Thank you everybody for moving this along quickly. Jim did ask for a release note in the approving comment. But, did we really need one?
> 
> I think it's worth mentioning the need to clean up that directory with a cronjob or some other mechanism.

Added directly to the main release note: https://github.com/IQSS/dataverse/pull/10866/commits/0b48c048967fcd41d114936d9533906b7231f83a

**Pull request merged**
