### PR TITLE
Adding a mechanism for disabling new remote auth signups. 

### LINKED ISSUE #9111: Add a mechanism for turning off OAuth account signups without disabling existing OAuth accounts
Should be a very straightforward fix.

### PR DESCRIPTION
**Pull request by landreev**
**What this PR does / why we need it**:

We all know why we need it. 
This implementation allows to disable new signups from specific remote/oauth type, without blocking all the existing accounts authenticated by this method. 
This is controlled by a new *compound* setting `:AllowRemoteAuthSignUp`. By default, if the setting is not present, all remote signups are open. If the setting is present, but the value for this specific method is not specified, it is assumed that the signups are allowed. 
Examples: 
```
curl -X PUT -d '{"default":"false"}' http://localhost:8080/api/admin/settings/:AllowRemoteAuthSignUp
```
disables all remote signups. 
```
curl -X PUT -d '{"default":"true","google":"false"}' http://localhost:8080/api/admin/settings/:AllowRemoteAuthSignUp
```
keeps signups open for all the methods except google. (but note that the `"default":"true"` part in this example is redundant, since it would default to true anyway for all the methods other than google). 

I am sure there are prettier ways to implement this. But, seeing how this is a bit of an emergency, I'm not super concerned about prettiness at this point. (I will move the error messages into the bundle though). 

I am concerned about whether there are still ways to go around this somehow. So it would definitely help to know how those users were able to create their google accounts after I had quote-unquote "disabled" it. 

**Which issue(s) this PR closes**:

Closes #9111

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by scolapasta — COMMENTED** [review]
Overall looks good. A few comments:
• I think you noted that you would move the texts into bundles. 
• This setting should be added to the docs
• Are there any tests we can add? There really isn't a concept of logging in through the API, so not sure what exactly we could add.

**Comment by landreev** [comment]
Did the cleanup/added the doc. section. 
I couldn't think of how to add tests for this. It may be possible; just like I think it should be possible to implement this in some more elegant way. But I would handle any such improvements as a separate issue in a normal release cycle. This patch I'm just itching to throw in prod. asap.

**Review by scolapasta — APPROVED** [review]

**Comment by qqmyers** [comment]
I think this one has been seen before and may be timing related - another case where a sleepForLocks/sleepForReindex might help?

**Comment by pdurbin** [comment]
I tested this on dataverse-internal and I'm satisfied that it's working properly. Will merge shortly.

I tweaked the docs in cf00e61 to emphasize that even though "remote" is in the name of the new database setting, for now this only affects OAuth accounts. I also did a little reorg, cross-linking, clean up, etc.

Here's how I tested.

## Regression test

I checked that I could still create a fresh Google account with nothing configured.

Then I deleted it.

## Am I prevented from creating a Google account?

Yes, by following the example in the guides, I get this error when I try:

Screen Shot 2022-11-03 at 2 29 48 PM

Screen Shot 2022-11-03 at 2 30 00 PM

Screen Shot 2022-11-03 at 2 30 21 PM

## With signup disabled, can I still log in with Google?

Yes, works fine.

Nice feature!

**Comment by pdurbin** [comment]
> may be timing related

I just checked the tests on develop after I merged this pull request and they all passed: https://jenkins.dataverse.org/job/IQSS-dataverse-develop/1192/testReport/

So, yes, probably timing related. It looks like we fixed DownloadFilesIT.downloadAllFilesRestricted here but it wasn't timing related then:

- #7195

Anyway, we can create a new issue if it comes up again.

**Pull request merged**
