### PR TITLE
1393 minimal machine-readable information in dataset landing pages

### PR DESCRIPTION
**Pull request by pameyer**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

Minimal Dublin-core metadata in dataset landing page in html meta elements (aka - machine-readable metadata).

- connects to #1393 Add Support for Meta-tags in HTML of Dataset for Reference Managers (Citation Metadata) 
- connects to #2899 Investigate possibility of using Altmetrics for reporting and sharing dataset metrics

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [x] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [x] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/4.6.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by oscardssmith** [comment]
@jggautier, can you look at this? I believe I have all the features done. I still need to add some tests, and any advice there would be great

**Comment by adam3smith** [comment]
I've now tested and refined this in Zotero and it works perfectly:
image
Zotero doesn't currently have a built-in dataset item type (that's on the roadmap) but the bit circled in red transforms the item type into a dataset for citation purposes. In APA style, e.g., the output is
Spruce, S. (2017). Spruce Goose [Data set]. https://doi.org/10.5072/FK2/RJI87V

We don't currently capture the publisher in there ("Root" in the example here) which is an issue on the Zotero side of things.

**Comment by pdurbin** [comment]
@adam3smith thanks! Is there an issue we can track on the Zotero side for the built-in dataset item type?

It's interesting to me that `type: dataset` gets turned into `Data set`. This was an early debate when we rewrote DVN 3 to Dataverse 4 and changed from "studies" to "datasets". I think we felt like "dataset" is more modern that "data set". It's like how "data base" eventually became "database".

**Comment by adam3smith** [comment]
It's "dataset" because that's the name of the Citation Style Language type and "Data set" because that's what APA wants (it could be different things in different citation styles and will eventually also be localizable).

The best issue to track is https://github.com/citation-style-language/zotero-bits/issues/22 -- it's semi-official, but Zotero devs have basically told us they'll do what we tell them. There's significant tech debt because they're syncing databases across machines with different versions, making DB schema upgrades hard so this will still take a bit. Target version is Zotero 5.1, we're currently in the beta for 5.0

**Comment by pdurbin** [comment]
@adam3smith I imagine this will look a little different (and better!) in Zotero as of https://github.com/zotero/zotero/commit/42a46494200d980437214e9535a1db53ce234446

That commit closed this issue:

- https://github.com/zotero/zotero-bits/issues/22

Instead of "Extra" I suppose "type: dataset" goes under some other field. Not sure.

In other news, there's a whole "Discoverability" page coming to the Admin Guide in this PR and it definitely covers machine readability:

- https://github.com/IQSS/dataverse/pull/8981

**Comment by adam3smith** [comment]
yes, indeed, though currently those changes aren't even available in the beta build yet. For anyone interested, I'll lead a Force11 workshop on April 19th on adding support for specific data repositories to Zotero (Dataverse repositories are well supported already, though). I'll post on the community group once I have more

**Comment by pdurbin** [comment]
@adam3smith sure, maybe you can post to the mailing list a little closer to the date to remind us. 😄

**Pull request merged**
