### PR TITLE
Feat existing doi on creation

### PR DESCRIPTION
**Pull request by tcoupin**
Allow to provide existing DOI on dataset creation using UI.
Fix also #5104

## Related Issues

- connects to #5104 Cant publish imported dataset with existing DOI 

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by pdurbin** [comment]
@tcoupin this is now our oldest pull request and I've forgotten where we are with it. Are you still wanting to get it merged?

**Comment by pdurbin** [comment]
@tcoupin I just noticed that this pull request has merge conflicts. 😢 

Any thoughts on it?

**Comment by tcoupin** [comment]
See https://github.com/IQSS/dataverse/issues/5104#issuecomment-430173132 : This PR was split in 2: a PR without ui change (#5199) and nothing.

I have since worked on this feature on our installation (https://datasuds.ird.fr). Our users have the option to provide an existing DOI when creating the dataset. If the DOI corresponds to the prefix of the installation, it is updated like the other DOIs. Otherwise, it is not updated during changes to the dataset.

If this feature interests you, I can make a new PR without merge conflicts.

**Comment by pdurbin** [comment]
@tcoupin hi! Here's what I think you should do, if you are willing.

I noticed that DataSuds doesn't have a project board yet. I'm tracking them at https://docs.google.com/spreadsheets/d/1l2R9D1FQy88qVzg2bI6L1LgplmM2l7pnMI80jdiz4fk/edit?usp=sharing (screenshot below)...

Screenshot from 2019-10-31 06-41-09

and they appear on the new map at https://iqss.github.io/dataverse-installations/ (another screenshot below)

Screenshot from 2019-10-31 06-44-25

You could create a project board for DataSuds and put #5104 on it. This will help raise the visibility of that issue in the community. Please see also https://github.com/pdurbin/druthers/issues/1

**Pull request closed without merging**
