### PR TITLE
add section on AWS RDS monitoring #8173

### LINKED ISSUE #8173: Add section on AWS RDS (Relational Database Service) to monitoring page in Admin Guide
@djbrooke and I just decided that we'll split off...

- Add section on AWS RDS (Relational Database Service) to monitoring page in Admin Guide: https://guides.dataverse.org/en/latest/admin/monitoring.html

... from https://github.com/IQSS/dataverse.harvard.edu/issues/126

The screenshot below is not the final version but gives an idea of where we're going.

Screen Shot 2021-10-21 at 2 43 36 PM

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

There are a few Dataverse installations out there that we know are on RDS, including Harvard Dataverse. We've gone through the RDS monitoring docs and want to share some pointers to what we've learned so far.

**Which issue(s) this PR closes**:

Closes #8173

**Special notes for your reviewer**:

None.

**Suggestions on how to test this**:

Just docs. Do they make sense? Are there more tips we should include? Here's a preview of the docs:

Screen Shot 2021-10-22 at 11 43 18 AM

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

Maybe? Not worth it? I didn't include one. Happy to. Just let me know.

**Additional documentation**:

No.

### CODE REVIEW

**Review by landreev — COMMENTED** [review]
I'm happy with this PR. Just didn't want to move it into the QA queue until it's cleared for 5.8. (but please let me know if I should)

**Review by landreev — COMMENTED** [review]
Moving to QA. Lots of very useful info/links.

**Comment by landreev** [comment]
(ignoring the integration test failure above - version, etc.; no code in the pr)

**Comment by kcondon** [comment]
Great job @pdurbin! Thanks for researching this and breaking it down for us.

**Pull request merged**
