### PR TITLE
#10466: quick fix for math challenge contact form on 403 error page

### LINKED ISSUE #10466: Captcha question in contact form doesn't appear on 403 error page
**What steps does it take to reproduce the issue?**

* When does this issue occur?

When a authenticated user requests access to a resource (URL) for which he doesn't have rights (for example, a dataset in draft mode).

* Which page(s) does it occurs on?

On the 403 error page, or _"Not Authorized"_

* What happens?

A 403 error page is displayed, and telling to the user he or she doesn't have rights, with a link opening a contact form. In this case, the question _"Please fill this out to prove you are not a robot."_ only display ` + =`. And when the form is submitted, a `NullPointerException` is thrown, indicating that variable `op1` is null.

* To whom does it occur (all users, curators, superusers)?

All users who doesn't have the correct privilege on the asked resource.

* What did you expect to happen?

The contact form have to be complete with the captcha question

**Which version of Dataverse are you using?**

`5.14`, but there is present on `6.2` (`develop` branch)

**Any related open or closed issues to this bug report?**

I don't find any other issue on this theme.

**Screenshots:**

403_error_contact_form

### PR DESCRIPTION
**Pull request by jeromeroucou**
**What this PR does / why we need it**:

If a user wishes to access a page, but is prevented from doing so by a rights issue (ACL), the error message on page 403 indicates this. Actually, the form can no longer be submitted because the mathematical challenge is empty. This PR corrects this and makes it possible to submit this form again.

**Which issue(s) this PR closes**:

Closes #10466 

**Special notes for your reviewer**:

I do a simple quick fix, I don't understand why the `SendFeedbackDialog.initUserInput` method isn't called. But with the new SPA interface, this bug will disappear, as it's linked to the current JSF view (view from MVC). So it seems to me that this is acceptable.

**Suggestions on how to test this**:

I use this test case to validate this PR :
* I login into a repository with a account A
* I create a collection and publish them
* Into this dataverse, I create a dataset in draft status
* I copy the URL of the dataset
* I logout and re-sigin with a another account B
* I try to access to the dataset previously created
* On the 403 page (forbidden access), I open the contact form to verify if the math challenge is now print

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No change

**Is there a release notes update needed for this change?**:

I don't think because the contact form on forbidden access page is a small functionality. But if needed I can write them.

**Additional documentation**:

No

### CODE REVIEW

**Comment by qqmyers** [comment]
On demo, I get redirected to the login page and don't see a 403, e.g. for [my draft dataset](https://demo.dataverse.org/loginpage.xhtml?redirectPage=%2Fdataset.xhtml%3FpersistentId%3Ddoi%3A10.70122%2FFK2%2FNEQHTE%26version%3DDRAFT). What else is needed to reproduce the error?

**Review by qqmyers — APPROVED** [review]
Looks good. I tested the fix at QDR and it appears to work/ shows a valid math problem.

**Comment by pdurbin** [comment]
@cmbz @scolapasta can we prioritize this one?

**Review by pdurbin — APPROVED** [review]
I haven't tested this but it looks promising. Approved.

**Pull request merged**
