### PR TITLE
update "making releases" after 6.1

### PR DESCRIPTION
**Pull request by pdurbin**
The [making releases](https://guides.dataverse.org/en/6.0/developers/making-releases.html) page for 6.0 isn't perfect.

This PR makes some updates based on what we've learned from releasing 6.1.

Preview the changes at https://dataverse-guide--10180.org.readthedocs.build/en/10180/developers/making-releases.html

### CODE REVIEW

**Comment by landreev** [comment]
@pdurbin I'm going to click "approve", but please take a look at the few sentences I've added, and let me know, or correct as needed if there are any problems.

**Review by landreev — APPROVED** [review]

**Comment by pdurbin** [comment]
@landreev perfect, thanks. Your changes are great. I made a tiny tweak (made "demo" a link).

I could merge this now but it seems like a good opportunity for someone who hasn't made a release (someone not me or Leonid) to at least read through the changes, or the whole doc, and ask questions and otherwise fix up the doc if something is not clear.

Also, for future, I think we should move the "how to create a release note snippet" stuff out of this page and into the dev guide because it happens earlier, as pull requests are created. There's a dedicated issue for this:

- #9264

**Review by sekmiller — COMMENTED** [review]
@landreev, @pdurbin do we want to mention in the Release Notes section that we include install and upgrade instructions customized based on the changes made for this release?

**Review by sekmiller — COMMENTED** [review]
How do you "send around the draft release for any final feedback"?

**Comment by pdurbin** [comment]
@sekmiller yes, good idea.

Also, @stevenwinship asked about a template for release notes. Once it exists (there's no issue), we should definitely mention it as well.

**Comment by sekmiller** [comment]
I added a line about upgrade instructions to the Release Notes Section. The rest looks good.

**Pull request merged**
