### PR TITLE
8305 Upgrade to Jakarta EE 10 and Payara 6

### LINKED ISSUE #8305: Upgrade to Payara 6 and from EE 8 to EE 10 (end of Payara 5 Community Edition security patches Q2/2022)
As a "bklog: Deliverable" This is decomposed into smaller issues, grouped under [D: Payara 6 Upgrade](https://github.com/IQSS/dataverse/labels/D%3A%20Payara%206%20Upgrade)

---

Hat tip to @poikilotherm who [posted][] in chat a link to a video in which Steve Millidge, founder of Payara, answered a question about how long Payara 5 Community Edition (which we recommend in the guides) will receive security patches: https://youtu.be/juD0XNNq344?t=1972

[posted]: https://matrix.to/#/!AmypvmJtUjBesRrnLM:matrix.org/$YqXmiwT6hoyVLfyKuH7rQVKrOFFRHBGFoJqfXR-wjM0

I've transcribed the question and answer:

Q: "For the Community Edition, when will v5 stop getting security patches?"

A: "Payara 5 in Community was basically... when we switch the main branch over to 6, which will be on the point of 6 release, then Community will march forward on Payara 6. So Payara 5 patches, if you like, will stop at that point through Community. So then it will be Enterprise where you'll get patches and security fixes for Payara 5. Payara Community essentially is a marching version so whenever the latest release is the latest release."

I didn't watch the whole video but @poikilotherm says Payara plans to switch the main branch to 6 in Q2/2022.

(By the way, #8064 is the issue where we're tracking the next 5.x upgrade from Payara. As of this writing we are advising installations to use Payara 5.2021.5: https://guides.dataverse.org/en/5.9/installation/prerequisites.html#payara )

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:

Payara 5 is going EOL for community usage (= without a payed support contract). Payara 6 is the successor, but allows to use Jakarta EE 10 only.

**Which issue(s) this PR closes**:

- Closes #8305

**Special notes for your reviewer**:

- Do not move this to QA until Payara 6.2022.1 is out and we can test with it.
- Resolved upstream with Prettyfaces 6.0 ~~Do not move this to QA until we've made a final decision to go with the Rewrite/PrettyFaces library I built on my Mac and put in `local_lib`. Check https://github.com/ocpsoft/rewrite/issues/304 for progress toward a compatible release from upstream.~~ 
- Instead of d86e220 should we preserve backward compatibility of the SWORD API by inserting `attachment; ` for the user if it isn't supplied?
- The Perl installer has not been updated. Honestly, @pdurbin and I are ok with deleting it (and references to it, of course, if any).
- The release note snippet needs work. Upgrades have not been tested.

**Suggestions on how to test this**:

- Make sure API tests pass.
- A test server is coming, similar to the one for Payara 5: https://groups.google.com/g/dataverse-dev/c/5hfiXl4Hpd8/m/awzoSpupAQAJ
- Test everything. Test, test, test, just like the last major version change.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

Yes, a stub is included.

**Additional documentation**:

None but references in the guides to Payara 5 have been switched to Payara 6.

### CODE REVIEW

**Comment by mreekie** [comment]
Sizing:
 - Have we already tried getting the app running under teh new environment and issues have been identified?
   - Sounds like this is still going to need some exploratory work.
   - We have a DV payara channel.
   - It's been a long work in progress.
   - We can't simply test and merge. We already know we still have work to do.
 - We hit trouble at the dataset creation level. This could be hiding other issues.

This PR represents this issue having it's own branch.
- We need to break this down and approach things one by one on this branch.
- Peel the onion.

**Comment by mreekie** [comment]
Current plan:
As part of the approach of peeling the onion on this we decomposed our first issue:
- [Bug: Fix dataset creation in the payara 6 branch #921](https://github.com/IQSS/dataverse/issues/9214)
- This PR will remain in the ordered backlog and we'll continue to decompose it until we have reached the end.
- At that point, we'll decide what to do with this PR

**Comment by mreekie** [comment]
Next steps:
- The first issue: https://github.com/IQSS/dataverse/issues/9214 will be resolved. 
- Revisit what steps are next after that is completed.
- Nothing to be done during this sizing session
-

**Comment by mreekie** [comment]
Grooming:
Assigned this our largest size as a reminder that we are decomposing this over time.

**Comment by pdurbin** [comment]
As I wrote in Slack:

The next small chunk for Payara 6 (after [Leonid’s PR](https://github.com/IQSS/dataverse/pull/9271) gets merged into Oliver’s branch) is to merge develop into Oliver’s branch, fix the merge conflicts, and poke around for the next obvious bug.

**Comment by mreekie** [comment]
Next Steps:
- [ ] resolve the merge conflicts in this PR
- [ ] test until the next bug is found.
- [ ] Create that issue and it's done.

We will create a new issue:

**Comment by pdurbin** [comment]
I created the next small chunk issue:

- #9283

**Comment by mreekie** [comment]
Backlog grooming:
- Removed the size
- Added the label:  bklog: Collection
- I hope that this communicates more clearly that this has become a collection of 1 or more smaller issues that are being decomposed from this bigger issue.

**Comment by mreekie** [comment]
sizing:
- In this round, check in to see if we are at a point to break off  new piece
-

**Comment by mreekie** [comment]
Sizing:
-To move this specific pull request forward a small bit, the  next step is to resolve the conflicts. (pretty straightforward. a 3)
Separately we'll create a new issue to track the fixing of the issues that are triggered when this code is committed.
- Get the API test suite to pass (hard. alot of uncertainty around what's broken. at least 33)

---
Notes
Context:
Prior to June
- 5.14 released
  - Payara and solr upgrades are not in that.
- 6.0 release
  - Payara, solr, java included in this.

Next steps:
- meet to get the DV 6.0 release plan in writing.
- meet to get more of the details specific to the Payara 6 upgrade thought out and in writting

**Comment by poikilotherm** [comment]
> Sizing: -To move this specific pull request forward a small bit, the next step is to resolve the conflicts. (pretty straightforward. a 3)

Please be aware that the last merge was not correctly executed! This is no easy task to merge this! This is at least a size 10 task, as the last merge needs to be reverted as well!

**Comment by cmbz** [comment]
- Prioritizing Payara 6 release
- Sizing needed

**Comment by cmbz** [comment]
This appears to be a flawed PR. 
Oliver will create a new PR and close this one.

**Comment by cmbz** [comment]
See related: https://github.com/IQSS/dataverse/issues/8305

**Comment by diego-guillen** [comment]
I'm trying to install the latest version of IQSS Dataverse, 5.13:

Dataverse 5.13 installation recommends Payara 5.2022.3, but it cannot be downloaded:
- https://guides.dataverse.org/en/5.13/installation/prerequisites.html
- https://guides.dataverse.org/en/latest/installation/prerequisites.html

`sudo wget https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/5.2022.3/payara-5.2022.3.zip`
Responds: ERROR 404: Not Found.

What can be done in this case?

**Comment by poikilotherm** [comment]
I am going to close this pull request now, as we will operate on a new branch and a new pull request for the actual move for Payara 6 after the release of Dataverse 5.14. See #9685 for the successor PR.

**Pull request closed without merging**
