### PR TITLE
3156 system api

### PR DESCRIPTION
**Pull request by jacksonokuhn**
# RFI Checklist

_**Before** submitting the pull request, fill out sections (1.) Related Issues and (2.) Pull Request Checklist._

### 1. Related Issues

Addresses issue #3156 

---
### 2. Pull Request Checklist

- [x]  Functionality completed as described in FRD
- [x]  Dependencies, risks, assumptions in FRD addressed
- [x]  Unit tests completed
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [x]  Documentation completed
- [x]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

### CODE REVIEW

**Comment by pdurbin** [comment]
@jacksonokuhn much better! Please take a moment to run both Sys.java and SysIT.java through the Netbeans formatter by clicking "Source" under "Format" in the menu.

The doc change needs a bit of work. Please preview your doc changes locally before making a pull request. Details at http://guides.dataverse.org/en/4.3.1/developers/documentation.html

There are two problems with the docs. First, IP Groups and Saved Search shouldn't be under System:

screen shot 2016-06-10 at 4 00 42 pm

Second, this looks weird:

screen shot 2016-06-10 at 3 56 31 pm

**Comment by pdurbin** [comment]
@scolapasta I took a first pass at code review and it looks good to me (thanks, @jacksonokuhn !). I'm passing this to you but please be advised that I'm planning creating a new branch and pull request based on this pull request and pull request #3137 so that I can deploy it to a server for OSF to test both together for https://github.com/CenterForOpenScience/osf.io/pull/5344 as I first mentioned at https://github.com/IQSS/dataverse/issues/3156#issuecomment-224027803

**Comment by pdurbin** [comment]
@jacksonokuhn please see 1e49070 (part of pull request #3167) in which I made it so that you SysIT test will pass on a remote server. My fault for not realizing this sooner. The whole idea of having more people writing REST Assured tests is still new to me. 😄 Some day I'll adjust the job at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ to run your SysIT test, which will bring the count up.

**Comment by pdurbin** [comment]
On 2016-07-08 @scolapasta and I discussed this pull request. We looked briefly at the changes and I believe he wanted to think about them a bit more before passing to QA.

**Comment by scolapasta** [comment]
@jacksonokuhn we've decided that this API should be called "info". "System" seems too internal for a public API.

Could you please make the changes (let's rename the class too, while we're at it), then resubmit. If you can do this ASAP, we will try to get it into 4.5

**Comment by djbrooke** [comment]
@jacksonokuhn - let me know if you're going to make the changes suggested in the code review or if we should go ahead and do it. Thanks!

**Comment by jacksonokuhn** [comment]
Do you guys mind doing it? I'm pretty overwhelmed with my prov stuff.

**Comment by djbrooke** [comment]
Thanks Jackson - I'll unassign this and it's free for anyone with availability to pick up and carry across the finish line!

**Comment by pdurbin** [comment]
I just created a new pull request at #3219 and am closing this one.

**Pull request closed without merging**
