### PR TITLE
10112-ProvIT-enable-fix 

### LINKED ISSUE #10112: ProvIT test failing due provenance metadata being disabled.
**What steps does it take to reproduce the issue?**
Execute the ProvIT test

* When does this issue occur?
When running the ProvIT test

* Which page(s) does it occurs on?
n/a

* What happens?
{
"status": "ERROR",
"message": "This functionality has been administratively disabled."
}

* To whom does it occur (all users, curators, superusers)?
All users

* What did you expect to happen?
The test should be completed successfully. 

**Which version of Dataverse are you using?**
6.0

**Any related open or closed issues to this bug report?**
No

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

### PR DESCRIPTION
**Pull request by jp-tosca**
**What this PR does / why we need it**:
The ProvIT test is not working correctly due to the feature not being enabled.

**Which issue(s) this PR closes**:

Closes #10112

**Special notes for your reviewer**:
This change will enable the feature and delete the setting at the end of the test.

**Suggestions on how to test this**:

1. Check out the repo
2. Start docker, mvn -Pct clean package docker:run
3. Run the test, mvn test -Dtest=ProvIT

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
N/A

**Is there a release notes update needed for this change?**:
N/A

**Additional documentation**:
N/A

### CODE REVIEW

**Comment by jp-tosca** [comment]
I made an additional change to this PR; Initially, I expressed concerns by messing with permanent settings during the test.

The first change enables and then disables the provenance collection setting, this prevents the test from failing but then I realized by doing this, that if the setting was initially on, running this test would leave it off.

I decided to check the status of the setting and only enable it if it wasn't initially, and then disable it only if it was modified during the test.

This may not affect this test but probably if someone else is using this setting is better just to leave it on the status that it was found before the test.

**Comment by pdurbin** [comment]
In 3407fb9 I enabled the test to run automatically in our CI.

**Comment by pdurbin** [comment]
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-10113/4/ failed but I made a couple formatting commits and will re-check after the API tests run.

**Review by pdurbin — APPROVED** [review]
Tests are passing at https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-10113/5/testReport/edu.harvard.iq.dataverse.api/ProvIT/

I'm merging this.

**Pull request merged**
