### PR TITLE
Dataset files API extension for search text filtering

### LINKED ISSUE #9785: [Spike - API] Extend the Files API to support search
**Overview of the Feature Request**

The logic to be implemented will extend https://github.com/IQSS/dataverse/issues/9714 so that the API is also capable of filtering files by search criteria.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
- https://github.com/IQSS/dataverse-frontend/issues/150
- https://github.com/IQSS/dataverse-frontend/issues/135

**What existing behavior do you want changed?**
N/A

**Any brand new behavior do you want to add to Dataverse?**
Extend Files API

**Any open or closed issues related to this feature request?**
- https://github.com/IQSS/dataverse-frontend/issues/135

### PR DESCRIPTION
**Pull request by GPortas**
**What this PR does / why we need it**:

Includes new optional `searchText` query parameter to the getVersionFiles endpoint.

**Which issue(s) this PR closes**:

- Closes #9785 

**Special notes for your reviewer**:

This is an initial implementation where the search is done through DB queries in all cases, so Solr is not used.

Therefore, this implementation is subject to change. Especially after completing #9813.

**Suggestions on how to test this**:

Upload a test file to Dataverse, with a label or description you can search based on.

`curl -H "X-Dataverse-Key: <YOUR_API_KEY>" -X GET "http://localhost:8080/api/v1/datasets/:persistentId/versions/:latest/files?persistentId=<DATASED_PID>&searchText=<SEARCH_TEXT>"`

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

Yes

**Additional documentation**:

N/A

### CODE REVIEW

**Comment by scolapasta** [comment]
@GPortas  I'll move this milestone 6.1 issue to "ready for Review", but I'm assigning you first so that you can handle the 6.0 merge and address any EE10 issues.

**Review by sekmiller — APPROVED** [review]
Looks good. Just make sure that you continue to update from dev as necessary

**Comment by sekmiller** [comment]
@GPortas I just re-assigned you to remind you to make sure that the branch is up to date with dev. Thanks!

**Comment by kcondon** [comment]
@GPortas This works for some values but not sure of the scope of what it supports. It supports what would be search terms from the dataset files tab, ie. description, filename. It also supports file extension but couldn't get it to support file type as displayed on the page. Also, the filters, File type, Access, File tag didn't seem to work. Could you clarify what it should do? Thanks!

**Comment by GPortas** [comment]
@kcondon 

Sorry, my understanding was that the feature was not quite relevant. This is probably a misunderstanding I had from one of the frontend weekly discussions.

I appreciate the context on this. Since I still have to refine the last PR (the final one pointing to develop), which includes all these changes, I can evaluate if we can add the tabular tag filter along with the rest of the filter options in a direct way.

I will review this in addition to what you already mentioned on https://github.com/IQSS/dataverse/pull/9820#issuecomment-1739889082.

**Pull request merged**
