### PR TITLE
8094 Experimental CI Java 17 Maven Unittest build

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:

This adds an experimental build on the Github Workflows for IQSS/dataverse using Java 17. It's easier to recognise what fails with Java 17 if this becomes a part of regular CI.

**Which issue(s) this PR closes**:

Relates to #8094 

**Special notes for your reviewer**:
Well take a look at the failing CI which should not fail the entire build (which is good)

**Suggestions on how to test this**:
See build log of the PR

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope, dev only.

**Is there a release notes update needed for this change?**:
Nope.

**Additional documentation**:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Makes sense to start testing. Others are probably better able to comment on the implementation - from my view, if it works and isn't required, it's good.

**Review by scolapasta — APPROVED** [review]
I like the idea of starting to test on Java 17 (and using this framework for other future versions too).

**Comment by kcondon** [comment]
@poikilotherm Repeat from yesterday: please refresh from develop? Thanks!

**Comment by pdurbin** [comment]
Once this is merged does it mean we're going to see "Some checks were not successful" on all pull requests until we fix the code to support Java 17? I like the comforting feeling I get from seeing "All checks have passed". With some failures you have to get used to knowing which failures are expected. It would be nice if we could somehow have "All IMPORTANT checks have passed".

**Comment by poikilotherm** [comment]
Please see this very PR for an example how this will look like.

There is no way to tell GitHub to just print a warning, as GitHub only supports two states: ✅ yay / ❌ nay

This was the exact reason why I added the statement of "Experimental" and "Production" to the action titles.

**Comment by poikilotherm** [comment]
@kcondon rebased on current `develop`.

**Comment by poikilotherm** [comment]
Looks like we are not alone with this... https://github.com/actions/toolkit/issues/399

I don't currently work on JDK 17. Modules #8395 first, so I can push #8320 forward with them (already doing this local).

**Pull request merged**
