### PR TITLE
added missing method to BuiltinUser required by passwordreset.xhtml

### LINKED ISSUE #7724: Error Rendering View[/passwordreset.xhtml]
While experimenting with upgrading from an older encryption version in Dataverse (SHA to  BCRYPT, @qqmyers ), I bumped into a bug in `/passwordreset.xhtml` when the password reset function is called.

Log output:
`Error Rendering View[/passwordreset.xhtml]`
`javax.el.PropertyNotFoundException: /passwordreset.xhtml @104,99 value="#{PasswordResetPage.user.displayInfo.title}": The class 'edu.harvard.iq.dataverse.authorization.providers.builtin.BuiltinUser' does not have the property 'displayInfo'.`

I'm using the latest develop branch (5.3)
Should be solved quite easily by adding a `getDisplayInfo()` method to BuiltinUser

### PR DESCRIPTION
**Pull request by mderuijter**
**What this PR does / why we need it**:
Fixes bug in password reset functionality
**Which issue(s) this PR closes**:

Closes #7724 

**Special notes for your reviewer**:
No
**Suggestions on how to test this**:
You have to trigger an "upgrade" type of password reset; the way to do this is to update the encrypted password of a built in user and its encryption type of 0 directly in the db. You can get the correct encrypted password by running this from a command line (thanks @qqmyers), replacing "password" with your chosen password (within quotes):
```
echo -n "password" | openssl dgst -binary -sha1 | openssl enc -base64
```

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No
**Is there a release notes update needed for this change?**:
No
**Additional documentation**:
No

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @mderuijter - would you expect this would fix #7677 as well?

**Comment by mderuijter** [comment]
> Thanks @mderuijter - would you expect this would fix #7677 as well?

@djbrooke I'm afraid it will not fix #7677 as the function I added is only used here:
image

**Comment by qqmyers** [comment]
I think this PR should work but it essentially duplicates a method that is marked as deprecated. I'm not sure what the best approach would be but I can see two alternatives:
1) Change the passwordreset.xhtml to call the deprecated method (or change it's name from getDisplayInfoForApiCreation() to getDisplayInfo() (and remove the @Deprecated since it is really used?), or 
2) Add a PasswordResetPage.getUserDisplayInfo() method that can call authService.getAuthenticatedUser(user.getUserName()).getDisplayInfo() - using the builtinUser to get the AuthenticatedUser which has the undeprecated getDisplayInfo method. (and change the xhtml to use that method instead.)

@scolapasta - any preference? I'm starting to prefer the former as it appears the reason the method is deprecated was just to indicate that BuiltinUser only has transient values now (e.g. see https://github.com/IQSS/dataverse/blob/ac15ff5e0fd956ca4181d49d76ebf9dc6f6fdc43/src/main/java/edu/harvard/iq/dataverse/api/BuiltinUsers.java#L79-L85).

**Comment by scolapasta** [comment]
So I agree the first approach would be fine, except that it turns out, it doesn't actually get the name of the user.

image

Discussed it with @djbrooke and we're fine with dropping the user's name from the text - so this change could just be to change  the bundle message to not include the 2nd parameter (i.e. {1}) - and then you can also change the xhtml to no longer reference displayInfo at all. That should be the easiest fix to get this page working again.

**Comment by mderuijter** [comment]
> So I agree the first approach would be fine, except that it turns out, it doesn't actually get the name of the user.
> 
> image
> 
> Discussed it with @djbrooke and we're fine with dropping the user's name from the text - so this change could just be to change the bundle message to not include the 2nd parameter (i.e. {1}) - and then you can also change the xhtml to no longer reference displayInfo at all. That should be the easiest fix to get this page working again.

@scolapasta should be fixed now :)

**Comment by mderuijter** [comment]
@djbrooke Hi my PR update has probably slipped your attention, but I think it has all the suggested modifications now.

**Review by qqmyers — APPROVED** [review]

**Comment by djbrooke** [comment]
Thanks @mderuijter and @qqmyers !

**Comment by scolapasta** [comment]
Thanks @qqmyers. (I was out since late last week, so just catching up today)

**Comment by kcondon** [comment]
Hello @mderuijter, would you mind refreshing your branch from /develop? I'm about to test this and found it was still using the old release version. Thanks, Kevin

**Comment by mderuijter** [comment]
> Hello @mderuijter, would you mind refreshing your branch from /develop? I'm about to test this and found it was still using the old release version. Thanks, Kevin

Hello @kcondon, should be okay now. Let me know if it isn't

**Pull request merged**
