### PR TITLE
Update geospatial.tsv

### PR DESCRIPTION
**Pull request by inDane**
**What this PR does / why we need it**:
cosmetic; it gets rendered correctly on github.

**Which issue(s) this PR closes**:

Closes #

**Special notes for your reviewer**:
it shouldn't change anything but a correct rendering on github...

**Suggestions on how to test this**:
Upload new file to dataverse. 
curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file geospatial.tsv

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
no

**Is there a release notes update needed for this change?**:
no

**Additional documentation**:

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @inDane for the PR. Just to confirm, under the "Suggestions on how to test this" section, the suggestion is to do a regression testing and also look in GitHub to confirm that the display is correct? If so, this makes sense, and thanks again!

**Comment by inDane** [comment]
@djbrooke yes, with 
`curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file geospatial.tsv`
I tested if I broke anything... 

See [here](https://github.com/inDane/dataverse/blob/develop/scripts/api/data/metadatablocks/geospatial.tsv) to check the correct rendering.

**Review by pdurbin — COMMENTED** [review]
Seeing "Whitespace-only changes" is a good sign:

Screen Shot 2021-08-31 at 11 24 21 AM

It's nice when these TSVs render properly on GitHub. Thanks for the pull request, @inDane 

@djbrooke I didn't test this but it's probably safe to move to QA if you want to go ahead.

**Comment by djbrooke** [comment]
@pdurbin thanks, feel free to approve if it looks OK to you!

**Review by pdurbin — APPROVED** [review]
Just whitespace changes and the tests still pass: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-8081/1/testReport/

**Pull request merged**
