### PR TITLE
Add unit tests for JsonParser; implement Dataverse.getContactEmails

### PR DESCRIPTION
**Pull request by bencomp**
Although I promised to not spend more free time on coding for Dataverse, I couldn't
help myself after interacting with the "native API" and talking about code coverage
with @pdurbin some more.

The new tests parse JSON test files from the test resources - rather than test that
JsonPrinter output can be parsed. Only date and date-time tests test a round-trip.
I added comments to explain what the test tries to accomplish.

Although line coverage of JsonParser with these tests is > 56%, not all branches are
covered even though NetBeans may show green: inline if/else statements 'hide' some
branches in the green lines.

To make the tests pass, I added `dv.setAffiliation` in `JsonParser.parseDataverse`
with a default value of `null` if the JSON doesn't include affiliation and
implemented `Dataverse.getContactEmails` to produce a comma-separated string of
email addresses. I hope these have been good assumptions for how the API behaves.

Note that because the JsonParser works on a different level than the API, the default
values that the parser uses may be different than the business logic prescribes
(see `dv.setPermissionRoot` in `parseDataverse`). The tests expect the parser's
defaults.

/cc @michbarsinai @scolapasta I'll be happy to discuss these suggestions!

### CODE REVIEW

**Comment by michbarsinai** [comment]
Excuse me not responding to this yet - I'm on vacation. Will respond later this month or early on the next.

-- Michael

**Comment by michbarsinai** [comment]
I think there's an issue here with the contact emails - the code currently (branch 4.2) returns the constant string "". @scolapasta - are we using metadata fields for that? Should this field (and, thus, the updated tests) go away?

**Comment by michbarsinai** [comment]
While we're at it, `getConactEmails` (assuming it is really needed) should return `List<String>` or `Set<String>`, depending on its semantics.

**Comment by bencomp** [comment]
@michbarsinai well, yes, I had to implement the getContactEmails method and looked at the current return type.

However, what will this method be used for? Should it be removed instead?

**Comment by michbarsinai** [comment]
Not really sure these fields are used. @scolapasta?

**Comment by pdurbin** [comment]
@bencomp I've merged the 4.2 branch into master and tagged it as "v4.2" per http://guides.dataverse.org/en/latest/developers/making-releases.html so nothing new should go into the 4.2 branch (I might even delete it). This pull request either needs to be closed or switched to be against the 4.3 branch instead of 4.2.

Also, I'm not sure if it will affect this pull request but I'm actively making changes to JsonPrinter.java locally for #2579 and expect to push to 4.3 soon. It looks like you're working on JsonParser.java instead though.

**Comment by bencomp** [comment]
@pdurbin GitHub doesn't allow to switch the target branch of a pull request after it's created. It doesn't change the nature of "please review and accept my change suggestions (or reject if you have good reasons)" and on the command line you can fetch the branch and merge it into whatever you want.

Thanks for considering the changes I suggest before blindly pushing your changes.

**Comment by pdurbin** [comment]
It might be for this reason that people keep a persistent "develop" branch around in the "git flow" model described at http://nvie.com/posts/a-successful-git-branching-model/ . That way, contributors can always make pull requests against "develop".

We had a "develop" branch in the DVN 3.x code base at https://github.com/IQSS/dvn (and even [documented "master" vs. "develop"](http://guides.dataverse.org/en/3.6.2/dataverse-developer-main.html#new-branching-model-develop-vs-master)) but I feel like it encouraged developers to never ever switch branches, which is not what we want per the "allow for concurrent development in multiple branches" goal at http://guides.dataverse.org/en/latest/developers/branching-strategy.html

@bencomp you're certainly right that git aficionados can merge via the command line. Technically, you don't even have to create a pull request. I could just add your remote to my local git config.

Anyway, it sounds like this pull request must be closed if we can't change the branch to which the merge is being proposed. Again, the 4.2 branch should receive no more commits since it's been tagged. I'm thinking about deleting the 4.2 branch anyway since it's purpose of becoming stable enough to be merged to master has been fulfilled.

Here's the standard "git flow" diagram by the way:

git-model 2x

**Comment by pdurbin** [comment]
@bencomp as we've discussed above, this pull request is against an old branch (4.2) that should receive no more commits and there is no way that we know of to change the pull request to be against the current branch that's under development (4.3) so I'm closing it. I just merged the latest code from 4.2.1 into 4.3 so 4.3 is where all new commits and pull request should go.

**Pull request closed without merging**
