### PR TITLE
Fixed incorrect behavior of :BlockedApiPolicy #9742

### LINKED ISSUE #9742: Incorrect behavior of :BlockedApiPolicy when set to localhost-only and when using a load balancer
**What steps does it take to reproduce the issue?**
The upstream in the load balancer is defined to localhost, the setting dataverse-useripaddresssourceheader is not configured and the API block policy is localhost-only. If the setting is not configured, [this condition](https://github.com/IQSS/dataverse/blob/727df9794857f73fe1af35b2e404cb48414eeb5e/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java#L68) is not fulfilled  and the source IP address will be retrieved from [this line](https://github.com/IQSS/dataverse/blob/727df9794857f73fe1af35b2e404cb48414eeb5e/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java#L132C33-L132C33) which always will have localhost as its value, if the upstream in the load balancer is configured localhost.

* When does this issue occur?
When using a load balancer, for example nginx, and the API block policy localhost-only.

* Which page(s) does it occurs on?
API endpoints that should be blocked by localhost-only API policy.

* What happens?
Dataverse will always consider that every API request have localhost as origin and the API policy will fail, allowing anyone to access, for example, the admin and builtin-users API endpoints.

* To whom does it occur (all users, curators, superusers)?
All users.

* What did you expect to happen?
API endpoints defined in the setting `:BlockedApiEndpoints` should only allow requests with origin from localhost.

**Which version of Dataverse are you using?**
5.13

**Possible Fix**
There are two possible solutions to fix this bug:

1. Configure in load balancer the upstream for the private IP address instead of localhost;
2. Configure the setting dataverse-useripaddresssourceheader with the command `./asadmin create-jvm-options '-Ddataverse.useripaddresssourceheader=X-Forwarded-For'` and have the load balancer configured to correctly set the header `X-Forwarded-For`.

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

### PR DESCRIPTION
**Pull request by cesarpferreira**
**What this PR does / why we need it**:
Documentation from our findings when solving an issue related to incorrect behavior of the policy to block API access.

**Which issue(s) this PR closes**:

Closes #9742 

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No.

**Is there a release notes update needed for this change?**:
No.

**Additional documentation**:

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
https://dataverse-guide--9747.org.readthedocs.build/en/9747/installation/config.html#blocking-api-endpoints looks good to me! Approved.

Here's a screenshot:

Screen Shot 2023-07-31 at 12 00 59 PM

**Review by donsizemore — COMMENTED** [review]
is this specific to nginx? if so, should we make a note of that?

**Comment by cesarpferreira** [comment]
> is this specific to nginx? if so, should we make a note of that?

@donsizemore that is a good question. We were doing some tests with haproxy in one installation, but it had the host IP address so it was working correctly. I can try to change it to localhost and check if this happens

**Comment by cesarpferreira** [comment]
> > is this specific to nginx? if so, should we make a note of that?
> 
> @donsizemore that is a good question. We were doing some tests with haproxy in one installation, but it had the host IP address so it was working correctly. I can try to change it to localhost and check if this happens

Just confirmed, it also happens with haproxy and this situation is most common when you only have one server behind the reverse proxy service and it is easier to set up the backend as localhost.

**Comment by pdurbin** [comment]
Does that mean we're ok with the pull request as-is? Or should @cesarpferreira add an additional note? (@cesarpferreira please feel free to add more if you like!)

**Pull request merged**
