### PR TITLE
OAuth login with ORCID, Google, and GitHub

### PR DESCRIPTION
**Pull request by pdurbin**
# RFI Checklist

### 1. Related Issues

- Connects to #3338 support OAuth2 (ORCID, Google, and GitHub) authentication within dataverse
- Connects to #3420 Shibboleth: Improve help text/provide options if your institution isn't listed
- Connects to #3134 Documentation: Building PDF version of docs results in error
- Connects to #3445 500 error (NullPointerException) when creating local or shib account, Shib users don't see "account information cannot be edited" message (ORCiD-integration branch)
- Connects to #3410 Remove instantiation of `ShibAuthenticationProvider` in `AuthenticationServiceBean#startup`?
- Connects to #3543 User Guide says "Dataverse will email your unread notifications once a day"
- Connects to #3294 Link to "Metadata Crosswalk" doc from appendix of User Guide
- Connects to #1835 Edit User Account: Revisit Logic around duplicate email
- Connects to #2974 Login page for "only remote authentication" mode

---
### 2. Pull Request Checklist

- [x]  Functionality completed as described in FRD. No FRD.
- [x]  Dependencies, risks, assumptions in FRD addressed. No FRD.
- [x]  Unit tests completed
- [x]  REST Assured tests updated: AdminIT
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing). Must run upgrade_v4.6_to_v4.6.1.sql. Must use new way of enabling Shibboleth.
- [x]  Documentation completed
- [x]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

### CODE REVIEW

**Comment by dlmurphy** [comment]
Just talked with @pdurbin about user guides related to this issue. A few notes:

- As of 98e6ec4, the shibtest sign up page is giving a 500 error. This is blocking me from reviewing the full guide. 

- Under [Account Information](http://guides.dataverse.org/en/3338-oauth-login/user/account.html):
_Add datasets to dataverses, if available
Contribute to existing datasets, if available
Request access to restricted files, if available_

In all three lines, I recommend changing "if available" to "if permitted" to make it clear that this is an accounts permission issue.

- Under [Create Account](http://guides.dataverse.org/en/3338-oauth-login/user/account.html) it mentions that the Username field supports characters "a-Z". This implies that uppercase letters are allowed and that Dataverse distinguishes between lowercase and uppercase letters in usernames. Are both of these implications accurate? Would _bob11_ and _BOB11_ be separate usernames?

- On the Installation Guide's [Configuration page](http://guides.dataverse.org/en/3338-oauth-login/installation/config.html), it might be helpful to mention in the Securing Your Installation section that it's important to change the superuser login from the default.

**Comment by pdurbin** [comment]
@dlmurphy I think I fixed that 500 error in 5115a15.

**Comment by dlmurphy** [comment]
@pdurbin Looks good to me, it's working now. Thanks!

**Comment by pdurbin** [comment]
@dlmurphy I made those fixes to the wording in a815b1f. Thanks! I tested bob11 vs. BOB11 and it's apparently allowed. There's always a "dataverseAdmin" account and I was able to create a second account as "DATAVERSEADMIN". I'll let you think about if this is a bug of a feature but I will say that we disallow this for the "alias" of a small d dataverse. Here's a screenshot:

screen shot 2017-01-05 at 9 35 00 am

**Comment by pdurbin** [comment]
@dlmurphy and I chatted more about usernames which led me to open #3575.

**Pull request merged**
