### PR TITLE
#2965 Fix for the citation block persistentURL links in iframes

### PR DESCRIPTION
**Pull request by mheppler**
Related Issues:
#2965 Widgets: Handle and DOI links in the citation leave the user within the frame

RFI Checklist

- [x]  N/A... Functionality completed as described in FRD
- [x]  N/A... Dependencies, risks, assumptions in FRD addressed
- [x]  N/A... Unit tests completed
- [x]  N/A... Deployment requirements identified (e.g., SQL scripts, indexing)
- [x]  N/A... Documentation completed
- [x]  All code checkins completed

---

- [x]  Code review completed or waived
- [x]  Testing requirements completed
- [x]  Usability testing completed or waived
- [x]  Support testing completed or waived
- [x]  Merged with develop branch and resolved conflicts

### CODE REVIEW

**Comment by mheppler** [comment]
| Page/Requirements  | Issue # | Commit # |
| ------------- | ------------- | ------------- |
| Dataverse Listing Widget, Personal Site  |
| Add `target="_top"` attribute to persistentURL link in citation block on dataset result cards  | #2965  | 5977e0e0e8e0105f395d5ba9c2075b4e2684d72a  |

**Comment by scolapasta** [comment]
@kcondon because the citation is indexed, you'll have to reindex to see the changes.

**Comment by mheppler** [comment]
Ahh, doh, yeah, what @scolapasta said.

**Comment by kcondon** [comment]
Passing to Liz to for UX review. Can be tested on dataverse-internal.iq.harvard.edu/test.html

**Comment by eaquigley** [comment]
Perfect to me. Passing to @sbarbosadataverse as this request originally came from support. @sbarbosadataverse you can test it here: https://beta.dataverse.org/test.html where @kcondon has created a fake iframe page to replicate the widgets.

**Comment by sbarbosadataverse** [comment]
The title opens up in a new tab. The DOI replaces the existing tab. Do we
have a preference?
Some consistency would be great. I do prefer to open things in a new tab,
so I don't lose my original source (e.g. Gary's scholar page).




On Thu, Mar 3, 2016 at 1:51 PM, Elizabeth Quigley <notifications@github.com>
wrote:

> Assigned #2971
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_pull_2971&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pdCv63NJxAfjYahXTizCKX7iz4leDhKKFbk05LKna5s&s=9MPuBxUxSWZKemaEpY4xyv4U3Tl_GxWtgsJqUncPvcg&e=>
> to @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pdCv63NJxAfjYahXTizCKX7iz4leDhKKFbk05LKna5s&s=DrBrw0nRCkjqmsT2I1lU10-MNPIh8ct-hlV9qhmUjgA&e=>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_pull_2971-23event-2D576690055&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pdCv63NJxAfjYahXTizCKX7iz4leDhKKFbk05LKna5s&s=fhxKcfCn_efRXO4OqxRiKwKqlJzu9R4PDpbov-xzBIo&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by mheppler** [comment]
Not sure if a pull-request is the best place to have this conversation, but I'm seeing the emails, so why not.

If we decide that the persistentURL link in the citation opens in a new window for the widgets, it will also do it on the dataverse pg, where the same citation will be displayed. Unlike the link that is behind the dataset title on the cards in the widget, we don't have special render logic for the citation, with dynamic behavior depending on whether you are viewing it externally in a widget or internally on the dataverse pg.

Just wanted to put all that out there, before a rash decision is made to go and make a change. I have already considered this scenario and developed a solution that I thought was best.

**Comment by sbarbosadataverse** [comment]
otherwise, checked and works and Liz explained the situation with opening
in new tabs

On Thu, Mar 3, 2016 at 2:08 PM, Michael Heppler <notifications@github.com>
wrote:

> Not sure if a pull-request is the best place to have this conversation,
> but I'm seeing the emails, so why not.
>
> If we decide that the persistentURL link in the citation opens in a new
> window for the widgets, it will also do it on the dataverse pg, where the
> same citation will be displayed. Unlike the link that is behind the dataset
> title on the cards in the widget, we don't have special render logic for
> the citation, with dynamic behavior depending on whether you are viewing it
> externally in a widget or internally on the dataverse pg.
>
> Just wanted to put all that out there, before a rash decision is made to
> go and make a change. I have already considered this scenario and developed
> a solution that I thought was best.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_pull_2971-23issuecomment-2D191918036&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=97T6c0zHkdZ9LoAS5tM1iaVaZyGD6iJaGJoY63q1S9c&s=Pr5wL0LP1UtG83TNfNnfkWtAw9wb0LF4BHvbku0GaeQ&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by kcondon** [comment]
Go ahead and merge.

**Pull request merged**
