### PR TITLE
add local_lib mvn repo and primefaces themes, pin base image to Ubuntu 22

### LINKED ISSUE #10718: cannot build due to missing artifact org.primefaces.themes:all-themes:jar:1.0.10
Originally reported by @haarli [in Zulip](https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/Build.20fails.20due.20to.20missing.20dependency.20org.2Eprimefaces.2Ethemes.3A/near/453680152), I'm also seeing problems building the Dataverse war file (`mvn package`) if I delete my Maven cache (`~/.m2`):

`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time:  02:07 min`
`[INFO] Finished at: 2024-07-24T13:08:32Z`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Failed to execute goal on project dataverse: Could not resolve dependencies for project edu.harvard.iq:dataverse:war:6.3: The following artifacts could not be resolved: org.primefaces.themes:all-themes:jar:1.0.10 (absent): Could not find artifact org.primefaces.themes:all-themes:jar:1.0.10 in payara-nexus-artifacts (https://nexus.payara.fish/repository/payara-artifacts) -> [Help 1]`

I'm on the tip of the develop branch (d33e249a78).

### LINKED ISSUE #10722: Upgrade from Ubuntu 22 to 24 breaks container images
As @poikilotherm mentioned in last week's container meeting ([recording](https://harvard.zoom.us/rec/share/6YV8RWVgXNtANjLIpnGnL9tKN4AeMWbBjy_A6zzJu0dUgM48pOtYN8WU_J0mRSIl.9-ja80A1IHfF8cUW)), the `eclipse-temurin:17-jre` image we build on has switched from Ubuntu 22 to 24. See https://github.com/adoptium/containers/commit/d762761bff59ad4ee3bacf89050e2081e5464c65 via https://github.com/adoptium/containers/issues/606#issuecomment-2244787657

Unfortunately, this broke a few things. For example, the `addgroup` command is missing. See https://github.com/IQSS/dataverse/actions/runs/10078623902/job/27869639991?pr=10721 and https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/.5BINFO.5D.20DOCKER.3E.20ERROR.3A.20failed.20to.20solve/near/453771298

For now, I think we should revert to Ubuntu 22. Then we can worry about upgrading the Ubuntu 24 and rewriting scripts that use `addgroup` etc. at our leisure.

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

We are getting build errors.

**Which issue(s) this PR closes**:

- Closes #10718
- Closes #10722

**Special notes for your reviewer**:

The Primefaces error gets triggered first but there is a second error having to do with containers (#10722) that I'm fixing in this PR as well.

I tried added just "all-themes" but "themes-project" seems to be required as well.

We used to have a local_lib repo but we removed it in this PR:

- #9844

**Suggestions on how to test this**:

- Make sure you can build.
- Make sure the UI looks ok? I'm not sure how the themes are used.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

I hope not.

**Is there a release notes update needed for this change?**:

No.

**Additional documentation**:

None.

### CODE REVIEW

**Review by landreev — APPROVED** [review]
Thank you!
Quick and dirty, but it will fix Jenkins for the time being. And we can always remove local_lib again if PrimeFaces get their act straight.

**Comment by pdurbin** [comment]
There's active discussion of what happened to the Primefaces maven repo at https://github.com/orgs/primefaces/discussions/2382

**Comment by stevenwinship** [comment]
I re-ran "Base Container Image / Build image" a couple of times but it still fails. @pdurbin could you take a look. I won't merge this without out the tests passing. Locally I could build and run the docker version with no issues.

**Comment by pdurbin** [comment]
@stevenwinship weird. Since it's a Docker error I [kicked off a thread](https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/.5BINFO.5D.20DOCKER.3E.20ERROR.3A.20failed.20to.20solve/near/453771298) in #containers about it. It's a new one on me! Very strange. 🤔 

I looked at other PRs and my guess is that they would start seeing the Docker error after they get past the Primefaces error. But that's just a guess. 🤷

**Comment by pdurbin** [comment]
There's an offer from Primefaces to put artifacts on Maven Central so I explained what we need: https://github.com/orgs/primefaces/discussions/2382#discussioncomment-10141453

This would be better than a local_lib directory.

**Comment by pdurbin** [comment]
@stevenwinship the "base container image" is passing now that I pushed some fixes for a second issue:

- #10722

We might want to see if @poikilotherm is ok with those container-related changes before we merge. I have [a thread](https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/Upgrade.20from.20Ubuntu.2022.20to.2024/near/453771298) going in Zulip about it.

**Comment by pdurbin** [comment]
I'm closing this PR for two reasons:

- There's a better fix in place now for Primefaces. Yesterday the artifacts we need were put on Maven Central. See https://github.com/orgs/primefaces/discussions/2382
- There's a better PR for the Ubuntu container issue. See #10672

**Pull request closed without merging**
