### PR TITLE
8288 multi line textarea in guestbook

### LINKED ISSUE #8288: Feature Request/Idea: Allow multi-line textarea inputs for guestbook
**Overview of the Feature Request**
Allow a multi-line textarea input field for guestbook.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
All UI users

**What inspired the request?**
Allowing a multi-line input textarea in a guestbook allows a user to enter text in a multi-line format rather than having to type potentially long answers into a single-line text field.

**What existing behavior do you want changed?**
Allow longer text in guestbook.

**Any brand new behavior do you want to add to Dataverse?**
Yes - adding in the textarea component as a new selection for the creator of a guestbook to choose in addition to 'text' and 'options'. Then having the guestbook popup display the textareas for the user to enter their multi-line text.

**Any related open or closed issues to this feature request?**
Not sure

### PR DESCRIPTION
**Pull request by mdmADA**
**What this PR does / why we need it**:
Adds an expandable textarea customquestion questiontype for the guestbook.
The text area starts out with 8 lines but is expandable to as many as required.

**Which issue(s) this PR closes**:

Closes #8288 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Create a new guestbook. For the question type, there should now be 3 choices: Text, Text Area, Multiple Choice
Choose 'Text Area'.
Assign this guestbook to a dataset.
Log in as a regular user and navigate to the dataset assigned the guestbook in the previous step.
Download a file. Ensure the custom question set as 'Text Area' is a multi-line expandable textarea component.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Yes but minor. Simply allows a larger multi-line textarea input.

Changes to Guestbook Creation Process:

Screen Shot 2021-12-09 at 9 51 03 AM

Changes to Guestbook display:

Mutltiline textarea in guestbook screenshot

**Is there a release notes update needed for this change?**:
Not sure.

**Additional documentation**:
The 'response' field of the customquestionresponse table is of type 'text' which allows unlimited text so adding a textarea should not be an issue.

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @mdmADA. We'll review the code, but can you add a screenshot when you have a chance? Thanks!

**Comment by mdmADA** [comment]
I added the screenshot to the description above ^^. Thanks Danny.

**Comment by djbrooke** [comment]
Thanks @mdmADA! I think this provides a much better writing experience for those filling out guestbooks.

@TaniaSchlatter - I added one additional screenshot above (of the create process). My big question is if "Text Area" is the right wording here from your perspective. 

FWIW, Qualtrics has three levels that provide various entry lengths:

- Single Line
- Multiple Line
- Essay Text Box 

I'm not suggesting three options but it's interesting to see their wording on the options, and it's another tool used often by researchers.

Screen Shot 2021-12-09 at 8 33 38 AM
Screen Shot 2021-12-09 at 8 33 24 AM
Screen Shot 2021-12-09 at 8 33 09 AM

**Comment by TaniaSchlatter** [comment]
Thanks for the screenshots, @mdmADA. It's great to have this useful functionality. I'd support naming that is a little more clear. @djbrooke mentioned Qualtrics naming. Google Forms uses "short answer" and "paragraph" for two text entry options. I think either "single line" and "multiple line" or "single line" and "paragraph" provide clearer naming.

**Comment by mdmADA** [comment]
Thank you both for the feedback - your suggestions do make it clearer.

I will go with the 'Single Line' and 'Multiple Line'. 
I have left the Custom Question Type as 'text' for 'Single Line' and 'textarea' for 'Multiple Line' so there doesn't have to be a database update to the question type for 'text'.

Let me know if you would like anything changed.  Thanks!

**Comment by djbrooke** [comment]
Thanks @mdmADA and @TaniaSchlatter !

@sekmiller all yours!

**Review by sekmiller — APPROVED** [review]
Looks good. Thank you for this enhancement!

**Comment by kcondon** [comment]
@mdmADA Would you please refresh from develop? We've recently released v5.9 and the version is part of the code.

**Comment by djbrooke** [comment]
@kcondon I went ahead and updated from develop

**Comment by kcondon** [comment]
@mdmADA This generally works but noticed that responses in the text area type that span multiple lines is handled differently by different opening apps -dataverse converts cr to spaces, excel keeps up to the first cr and puts the rest in a new row, first column, numbers appears to do something similar to Excel. Anyway that content can be confined to the cell it is supposed to be in, maybe writing out response in quotes?

here are some examples:
Screen Shot 2021-12-13 at 5 07 35 PM
Screen Shot 2021-12-13 at 5 08 30 PM
Screen Shot 2021-12-13 at 5 09 17 PM
Screen Shot 2021-12-13 at 5 20 04 PM
Screen Shot 2021-12-13 at 5 20 54 PM
Screen Shot 2021-12-13 at 5 22 30 PM

**Comment by mdmADA** [comment]
Good catch @kcondon. I was only thinking of text input, and not how it might be read after the fact and didn't think to test that.

I will see if writing the response in quotes addresses the issue and let you know.

**Comment by mdmADA** [comment]
I updated the selectCustomQuestionAnswers() method in GuestbookREsponseServiceBean.java to escape the values pulled from the database. Will work with responses containing newline, comma and/or double quotes.

I tested with Excel and Numbers (noting that you have to fix the setting sin numbers to delimited instead of fixed length for it to show properly). 

I didn't 'fix' Dataverse converting the newline to a space - not sure if that's necessary?

**Comment by djbrooke** [comment]
Thanks @mdmADA for the updates to this issue, we'll take another look!

**Pull request merged**
