### PR TITLE
6339 subjects disappear on edit

### LINKED ISSUE #6339: Subjects disappear when clicked in metadata editing
Tested in version 4.17 in both Harvard and Scholars Portal Dataverse instances. Tested in Chrome (78.0.3904.70) and Firefox (70.0) on MacOS Mojave.

When creating a dataset and entering metadata in Google Chrome, clicking on the name/label of the subject makes the subject box disappear. The issue does not happen if you only click the checkbox.

The problem starts at the "Earth and Environmental Science" subject, which causes the box to partially collapse. Clicking subjects below "Earth and Environmental Science" will cause the block to disappear completely.

Clicking on the text label for "Earth and...":
 
Screen Shot 2019-11-03 at 10 38 25 AM

Clicking on any text label below "Earth and...":

Screen Shot 2019-11-03 at 10 34 27 AM

The bug does not occur in Firefox; other browsers were not tested. Screenshots above were created from the Harvard instance.

### PR DESCRIPTION
**Pull request by sekmiller**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Note that we use the "closes" syntax below to trigger Github's automation to close the corresponding issue once the pull request is merged.

Thanks for your contribution to Dataverse!

## Related Issues

- closes #6339 Subjects disappear during metadata editing

## Pull Request Checklist

- [x] Unit [tests][x] NA
- [x] Integration [tests][x]: NA
- [x] Deployment requirements: [x] None
- [x] [Documentation][docs] NA
- [x] Merged latest from "develop" [branch][x] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by kcondon** [comment]
@sekmiller This still happens with Chrome:
1. for both subject and languages, and likely other controls of the same list-type
2. to reproduce, scroll past the initially visible items, click on the name of the item, not the checkbox, and the entire list is hidden, though saving saves any selected items.

**Comment by mheppler** [comment]
@sekmiller, @kcondon:

Cleaned up the styling of the new `p:selectCheckboxMenu` component, but found a new issue with the `label` attribute. The "Select..." text is not being delivered to the component like it is in the [PrimeFaces showcase](https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml) or the Edit Tags popup from the dataset and editFilesFragment pgs.

Screen Shot 2019-11-20 at 2 37 57 PM

Screen Shot 2019-11-20 at 2 42 10 PM

**Comment by mheppler** [comment]
Reviewed latest changes to the `multiple` attribute of the `selectCheckboxMenu` component, and seeing inconsistent behavior between the create and edit form. First, you will see that the edit version of the "Select..." dropdown has a gray background color, while the create version is white. Second, selecting checkboxes displays the values in the dropdown for the edit version, while it is broken in the create version. (See screenshots.)

So there appears to be something going on with the EDIT vs CREATE versions of this form component.

**EDIT**
Screen Shot 2019-11-21 at 2 11 50 PM

**CREATE**
Screen Shot 2019-11-21 at 2 11 02 PM

Also, on the metadataFragment, there is another version of the old scrolling `selectManyCheckbox` component for compound "subdsf" fields that will need to be swapped out to the new `selectCheckboxMenu` component. There also an old `selectManyCheckbox` component on the advanced search pg for subjects and other dynamic fields, that will need to be updated.

**Comment by mheppler** [comment]
Latest changes moved the selected values of the `selectCheckboxMenu` component to custom plain text outside the component, rather than displaying in the component as the component functions in the PrimeFaces showcase, out of the box.

Screen Shot 2019-11-22 at 7 52 58 AM

Hopefully it is possible to solve the inconsistency of this component between the edit and create workflows, by fixing the component's intended functionality, and not a custom code workaround.

**Comment by pdurbin** [comment]
One question is have about the new component is if it allows authors to put the subjects in order. Can they make is so that "Physics" appears before "Chemistry"? The idea here is that the dataset is a little more about Physics than Chemistry.

**Comment by sekmiller** [comment]
@pdurbin Nope. Alphabetical order. Is it worth trying to add ordering as an enhancement?

**Comment by pdurbin** [comment]
@sekmiller nah. I'd sooner working on adding many, many more subjects before we prioritize the concept of "primary subject". Thanks.

**Comment by mheppler** [comment]
Here is the current broken UX as of the last commit to revert the AJAX changes from the component.

```
CREATE WORKFLOW
- Check boxes, selections not displayed in dropdown (broken compared to component showcase)

EDIT WORKFLOW
- Selected values displayed in dropdown
- If nothing selected, check boxes, selections not displayed in dropdown (same as create)
- If values already selected, check more boxes, selections displayed in dropdown (THIS is how it behaves in the showcase, and how it should behave across all workflows)
- Unselect everything and input if left blank, without "Select..." label text returning (broken compared to component showcase)
```

**Comment by sekmiller** [comment]
Screen Shot 2019-12-02 at 2 38 53 PM
Screen Shot 2019-12-02 at 2 38 29 PM
Screen Shot 2019-12-02 at 2 37 42 PM

**Comment by djbrooke** [comment]
We discussed in standup and I made the decision to move this as is. It is not perfect but it addresses a production bug.

**Comment by pdurbin** [comment]
I would say the user experience for picking a language from a long list is much improved. Now there's search! 😄

**Pull request merged**
