### PR TITLE
Put modifiers in the correct order

### LINKED ISSUE #10074: Code style (Sonarlint): put `public static final` modifiers in the correct order
**Overview of the Feature Request**
The order of modifiers like `public`, `static` and `final` is given in the Java Language Specification, according to Sonarcloud. See [rule java:S1124](https://sonarcloud.io/organizations/iqss/rules?open=java%3AS1124&rule_key=java%3AS1124) for details. There are (or were) 185 violations at the time of the last check.

**What kind of user is the feature intended for?**
Developers

**What inspired the request?**
Sonarcloud

**What existing behavior do you want changed?**
n/a

**Any brand new behavior do you want to add to Dataverse?**
n/a

**Any open or closed issues related to this feature request?**
#9846 may help find these issues automatically.

### PR DESCRIPTION
**Pull request by bencomp**
**What this PR does / why we need it**:
This PR replaces `final static` with `static final` to comply with the Java Language Specification. It is a small step towards more consistent code.
While working in the affected files, I replaced a few calls to deprecated `new Integer(String)` and `new Long(String)` constructors with `Integer.valueOf(String)` and `Long.valueOf(String)` static method calls.

**Which issue(s) this PR closes**:

Closes #10074

**Special notes for your reviewer**:
Thank you for reviewing!

**Suggestions on how to test this**:
None. Perhaps in the future a Checkstyle run could fail if the order is incorrect.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No.

**Is there a release notes update needed for this change?**:
No.

**Additional documentation**:
Also linked from the issue: [Sonarcloud on why and how to put modifiers in the correct order](https://sonarcloud.io/organizations/iqss/rules?open=java%3AS1124&rule_key=java%3AS1124)

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Looks fine

**Comment by bencomp** [comment]
@sekmiller I don't know if I'm in time for this sprint, but I updated the branch.

**Comment by ofahimIQSS** [comment]
@bencomp Can you please add steps to test this ticket?

**Comment by bencomp** [comment]
This PR is basically about code style; no functionality changed and hence there's not really anything to test. Most importantly the code should compile as normal.

If you want an analysis of the changes, you could use the Sonar Maven goal and Sonarcloud to see that the warnings about modifier order (should) have gone away. @pdurbin and @poikilotherm have some experience with these steps.

**Comment by ofahimIQSS** [comment]
Performed smoke test and no issues were observed. Merging pull request

**Pull request merged**
