### PR TITLE
5795 Refactoring Unit Tests

### PR DESCRIPTION
**Pull request by rschlaefli**
This pull request improves the test structure of several existing test methods and refactors them regarding code smells like indirect testing and many assertions contained within a single method. The following methods have been changed as described below:

- `authorization/AuthenticationProviderTest.java`
  - JUnit 5
  - refactored the setup logic to cleanly work with `@BeforeAll`
  - refactored `testGetFriendlyName` with many assertions into several independent test cases
  - moved from asserting within a loop to a simple parameterized test case
- `privateurl/PrivateUrlUtilTest.java`
  - JUnit 5
  - split `testIdentifier2roleAssignee` into several test cases
  - removed dead code inside try/catch blocks, as the method under test is not expected to throw
  - as part of the refactor, indirect testing of `authorization/users/PrivateUrlUser.java` has been removed. Instead, I have added a simple test class in `authorization/users/PrivateUrlUserTest.java` that covers the methods of this class.
    - it could/should go even a level deeper, as e.g. `assertEquals("Private URL Enabled", returnFromValidIdentifier.getDisplayInfo().getTitle());` was actually also relying on behavior of `RoleAssigneeDisplayInfo`. I have not made it part of this PR to add these tests.
- `search/SearchUtilTest.java`
  - JUnit 5
  - refactored `testGetSortBy` into several test cases

## Related Issues

- connects to #5795 

## Pull Request Checklist

- [x] Unit [tests][] completed
- [x] Integration [tests][]: None
- [x] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [x] [Documentation][docs] completed
- [x] Merged latest from "develop" [branch][] and resolved conflicts

### CODE REVIEW

**Comment by rschlaefli** [comment]
I am not sure why coverage for `getId` in `authorization/providers/oauth2/AbstractOAuth2AuthenticationProvider.java` decreases here. However, I would argue that the actual reduction would occur due to a reduction of indirectly testing functionality in an external class (which is a test smell). Should I investigate further or is this change acceptable as is?

**Comment by pdurbin** [comment]
Yeah, I'm a bit concerned that code coverage is decreasing. I just approved a couple pull requests that increase code coverage. :smile: 

@rschlaefli do you need any help keeping the code coverage the same or increasing it?

**Comment by rschlaefli** [comment]
Hi @pdurbin, I am a bit confused by the behavior of coveralls. I was unable to find the reason for the coverage decrease when I looked through the code (several times), and after merging develop it displays a substantial increase in coverage.

**Comment by pdurbin** [comment]
@rschlaefli yeah, I'm a bit confused to. Like you said, coverage is up now which is great. I moved this issue to QA. Please don't make any more commits. Thanks!

**Comment by oscardssmith** [comment]
I think what coveralls is doing is comparing code coverage of the branch compared to maser, not to the head, so since a bunch of other branches got merged that added code coverage to master, it didn't see an increase until those were added to the branch as well.

**Pull request merged**
