### PR TITLE
IQSS/7349-4 creator updates in schema.org

### LINKED ISSUE #5029: Improving Dataverse's Schema.org JSON-LD schema to enable author names display in Google Dataset Search's
Author names are missing from the dataset records that Google Dataset Search indexed from Dataverse.

The JSON-LD schema for authors should be updated to "@type": "Person" or other appropriate types to differentiate between organization as authors or individuals as authors.

### LINKED ISSUE #7349: Improve/update Schema.org JSON-LD export
In a meeting with folks from the FAIRsFAIR group (namely @kitchenprinzessin3880) who are building and testing tools to access the "FAIRNESS" of datasets in Dataverse repositories (https://www.fairsfair.eu/fairsfair-data-object-assessment-metrics-request-comments), some changes were recommended for the metadata that Dataverse includes in the Schema.org JSON-LD metadata it exports for datasets. I said I'd open a Github issue so we could record and explain these changes.

**For license property, use the `@type` "CreativeWorks" and use "name" instead of "text":**
As of Dataverse 5.1.1, the `@type` for the Schema.org property "license" is "Dataset". Here's an example of what that looks like:
```
license: {
   @type: "Dataset",
   text: "CC0",
   url: "https://creativecommons.org/publicdomain/zero/1.0/"
```
or if CC0 is waived:
```
license: {
   @type: "Dataset",
   text: "Text the depositor entered in the Terms of Use field"
```

   Google's guide for [describing datasets with Schema.org](https://developers.google.com/search/docs/data-types/dataset#dataset) says to use the "CreativeWorks" `@type` for license and use "name".

Here's an example of what the license metadata in the Schema.org export might look like when this issue is merged (after the "multiple license" work described at https://github.com/IQSS/dataverse/issues/7440 and https://github.com/IQSS/dataverse/issues/7742 is also merged):

If the dataset depositor chooses a license from the list of licenses:
```
license: {
   @type: "CreativeWorks",
   name: "CC0",
   url: "https://creativecommons.org/publicdomain/zero/1.0/"
```
```
license: {
   @type: "CreativeWorks",
   name: "CC BY",
   url: "https://creativecommons.org/licenses/by/4.0/"
```
Or if no license is chosen and a custom license is entered:
```
license: {
   @type: "CreativeWorks",
   name: "Text entered in the "Dataset Terms" fields"
```

 
**For files (in the "distribution" property):**
As of Dataverse 5.1.1, here's an example of what the file metadata in the Schema.org export looks like:
```
distribution: [
    {
        @type: "DataDownload",
        name: "cases_by_infection.tab",
        fileFormat: "text/tab-separated-values",
        contentSize: 56377,
        description: "",
        @id: "https://doi.org/10.70122/FK2/LQKU61/SCM19X",
        identifier: "https://doi.org/10.70122/FK2/LQKU61/SCM19X",
        contentUrl: "https://demo.dataverse.org/api/access/datafile/1653135"
    {
        @type: "DataDownload",
        name: "DatasetDiagram.png",
        fileFormat: "image/png",
        contentSize: 84006,
        description: "",
        @id: "https://doi.org/10.70122/FK2/LQKU61/SBJENW",
        identifier: "https://doi.org/10.70122/FK2/LQKU61/SBJENW"
```

Here are the changes related to file metadata being proposed in this GitHub issue:
- Use "encodingFormat" instead of "fileFormat":
    Google's guide for [describing datasets with Schema.org](https://developers.google.com/search/docs/data-types/dataset#dataset) says to use the property "encodingFormat" (doesn't mention using the "fileFormat" property)
- contentURL should always be added:
   As of Dataverse 5.1.1, Dataverse puts each file's "download URL" in Schema.org's contentURL property as long as the file isn't restricted or its dataset has no guestbook or Terms of Use metadata. (See details about the current logic at https://github.com/IQSS/dataverse/issues/4371#issuecomment-436762935)

   Instead, Dataverse should always include every file's "download URL" in Schema.org's contentURL property. Then if the file is restricted or its dataset has a guestbook or Terms of Access metadata, the download URL will return the access restricted error that it returns now.

- Add conditionsOfAccess to declare that a file is open or restricted:
   @kitchenprinzessin3880 pointed to two vocabularies whose terms we might consider using as values for conditionsOfAccess, to indicate how accessible the file is: https://guidelines.openaire.eu/en/latest/literature/field_accesslevel.html and http://vocabularies.coar-repositories.org/documentation/access_rights.

    Each vocab defines four terms. I've written in https://github.com/IQSS/dataverse/issues/5920 about current problems Dataverse has with using [the Access Rights terms from the info:eu-repo namespace](https://wiki.surfnet.nl/display/standards/info-eu-repo/#infoeurepo-AccessRights), so I'm hesitant to use those terms. To put it briefly, Dataverse has files that are restricted using Dataverse's file restriction feature and the "File Request" feature is disabled, but the depositor uses a process outside of Dataverse to manage access to the file. So the file is restricted, not "closedAccess," even though people aren't able to request access to the file through Dataverse's "File Request" feature. Most of the datasets in Harvard Dataverse's Murray collections are like this (e.g. there's a process outside of the Dataverse software for requesting access to restricted files in https://doi.org/10.7910/DVN/0PMZC6). Maybe we can discuss that in this issue.

Here's an example of what the file metadata in the Schema.org export might look like when a pull request for this issue is merged:
```
distribution: [
    {
        @type: "DataDownload",
        name: "cases_by_infection.tab",
        encodingFormat: "text/tab-separated-values",
        contentSize: 56377,
        description: "",
        @id: "https://doi.org/10.70122/FK2/LQKU61/SCM19X",
        identifier: "https://doi.org/10.70122/FK2/LQKU61/SCM19X",
        contentUrl: "https://demo.dataverse.org/api/access/datafile/1653135"
        conditionsOfAccess: (to be determined)
    {
        @type: "DataDownload",
        name: "DatasetDiagram.png",
        encodingFormat: "image/png",
        contentSize: 84006,
        description: "",
        @id: "https://doi.org/10.70122/FK2/LQKU61/SBJENW",
        identifier: "https://doi.org/10.70122/FK2/LQKU61/SBJENW"
        contentUrl: "https://demo.dataverse.org/api/access/datafile/26"
        conditionsOfAccess: (to be determined)
```

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: Per discussion in #7349 and #5029, Google ignores creator entries from Dataverse because they don't include an @type Person or Organization. Since we don't collect that directly, we have to use some mechanism to infer the @type. The OpenAire export format does this by leveraging an algorithm developed by DataCite. This PR abstracts that algorithm from the code producing the OpenAire xml format into a new PersonOrOrgUtil class that is then used to identify an @type for creators in Dataverse. The new functionality is then used to provide the @type in the schema.org export format and in-dataset-page metadata, along with the givenName and firstName for a person if/when the algorithm determines them.

The PR also updates how the 'affiliation' is handled. According to schema.org, only Persons have 'affilation' and that must be to an 'Organization'. The PR makes this change - to send the affiliation as an object of type Organization with the 'name' specified. Since Organizations don't have an 'affilation', but they do have a 'parentOrganization' key, for Organizations the code now encodes the affiliation for Orgs as a 'parentOrganzation' object of @type 'Organization' and 'name' as specified.

**Which issue(s) this PR closes**:

- Closes #7349 
- Closes #5029

**Special notes for your reviewer**:
FWIW: I think the new PersonOrOrgUtil can replace the code in the OpenAire export but I didn't do that in this PR. The algorithm is used in that code with two minor variations that I think can be handled by an appropriate entry for the organizationIfTied param.

**Suggestions on how to test this**: Unit tests cover most of this. As with others, visually inspecting the schema.org export and/or embedded datasetpage json-ld can be done to verify that Person or Organization is added and that affiliation is handled as described here. Note that miscategorizations (a person with @type Organization or vice versa) is not considered a bug and is considered better than not sending a type at all. If there are consistent issues, the algorithm can potentially be improved.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**: included.

**Additional documentation**:

### CODE REVIEW

**Comment by qqmyers** [comment]
FWIW: The 4 changes to the schema.org output are live on https://data.qdr.syr.edu now if anyone wants to take a look at the results.

**Comment by qqmyers** [comment]
After some testing at QDR, it appears that organizations ending in Project get coded as a person. The PR now adds a jvm option to allow the algorithm to assume that all Person names are added in the recommended Family Name, Given Name format which enables it to code 'John Smith Project' and any other org without a comma correctly.  This is off by default and may not be useful for non-curated repositories. 

An alternative/additional approach that could be used would be to add a configurable list of non-person names (like 'Project') that would allow finer grained control over specific cases.

**Comment by pdurbin** [comment]
@qqmyers I'm a little confused. I see you mention this issue above...

- #5029

... but this PR doesn't close it. Can you please explain what else is needed? I'll leave a comment over there as well if it makes more sense to have the conversation there. Thanks.

**Review by sekmiller — APPROVED** [review]

**Comment by sekmiller** [comment]
Looks good. thanks for adding the ToDos for code consolidation. @qqmyers Looks like there are conflicts that need to be resolved.

**Comment by kcondon** [comment]
Issues found:
1. fragment of url at the end of schema.org export
2. 500 error in server log on publish when populate affiliation field, cannot publish.
[creatorTypePrErr.txt](https://github.com/IQSS/dataverse/files/10558915/creatorTypePrErr.txt)
[export2vers.txt](https://github.com/IQSS/dataverse/files/10558916/export2vers.txt)

**Pull request merged**
