### PR TITLE
Fix some raw type references

### PR DESCRIPTION
**Pull request by bencomp**
Following up from #2589, asking to merge in the develop branch.

In an effort to get the number of Java compiler warnings about unchecked references and casts (see #2574) I added diamonds to a few classes.

I won't add more to this PR.

### CODE REVIEW

**Comment by pdurbin** [comment]
I find this pull request a bit scary personally because it touches so much code that I've never worked on myself. 17 files changed. Does all the code still work? Does this pull request introduce any regressions? It would be nice to at least point what few integration tests we have against it. @bencomp I'd be happy to show you how to run these tests if you'd like. Or it's certainly valid for you to say that this should be an exercise for the Dataverse team. I dream of a day where pull requests automatically have integration tests run against them in Travis or similar like @openscholar does (see all the various test suites at https://github.com/openscholar/openscholar/blob/SCHOLAR-3.x/.travis.yml ).

**Comment by pdurbin** [comment]
#2867 is an example of the type of pull request that is way less scary when considering possible regressions. It's a much smaller and more targeted change.

**Comment by bencomp** [comment]
This PR changes just over 100 lines in 17 files. I have not created any of these files, yet fixing type references is like fixing typos, which is (or should) not be scary.

**Comment by pdurbin** [comment]
Well, @scolapasta has a better big picture view of the code than I do so I'll assign this to him to get his opinion on when/if it should be merged.

**Comment by pdurbin** [comment]
What @bencomp is trying to do increase the type safety of the code. As of 28758208bef3fb713c903450067a47c0814655b1 in the develop branch there are 105 java warnings, many of them due to type safety problems: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-build-develop/1/warnings3Result/

I can only assume that the number is reduced from 105 in this pull request but I can't be bothered at this moment to count them at https://travis-ci.org/IQSS/dataverse/builds/102342233 which is the Travis build for this pull request. If Travis exposes this number somewhere, please let me know!

**Comment by pdurbin** [comment]
@bencomp as I've mentioned a number of times I still feel like the effort should be more about teaching developers about type safety rather than cleaning up after them. We've already established at https://github.com/IQSS/dataverse/pull/2589#discussion_r40429815 that with the Netbeans defaults developers don't even see warnings.

In short, we should be teaching people how to fish. We want the world to [stay saved](http://bl.ocks.org/pdurbin/raw/814fd29916749523db9a/#12):

stay-saved

**Comment by bencomp** [comment]
@pdurbin what do you suggest then? I don't have a lot of teaching experience. :)

Let me stress that I did this to indeed improve the type safety of the code, so that it's much easier to let tools spot bugs. NetBeans may not show all warnings by default, but it will underline in red when you try to add a `Dataverse` to a `List<DataFile>`.

How about we ask every developer to check the changes in this PR as an exercise? 

Maybe Jenkins can even fail the build when new Java warnings are found? Then new code is definitely safe, but older code may still need to be cleaned up later. (Same for `@todo`s, by the way, but let's save that for another time.)

**Comment by pdurbin** [comment]
I'd suggest giving @scolapasta time to comment. He's out today and possibly Tuesday (Monday is a holiday).

**Comment by oscardssmith** [comment]
I've looked through all these changes and none of them have potential to break code. Can we merge this?

**Pull request merged**
