### PR TITLE
Can't preview in page for files in prior public dataset versions

### LINKED ISSUE #6421: Can't preview in page for files in prior public dataset versions
Related to #6419 (and I asked about this there but am creating a separate issue), if there is more than 1 published version of a dataset, files in the earlier versions can't be previewed in page. This means that files that have been deleted can't be previewed at all and current files can only be previewed if they are accessed via the latest published version. I'm not sure if this was intended or is needed (these are still publicly accessible files). 
The related PR resolves this and still keeps all of the other limits to avoid previews of files that have restrictions/conditions/are in draft datasets/are in datasets with access terms...

### PR DESCRIPTION
**Pull request by qqmyers**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Note that we use the "closes" syntax below to trigger Github's automation to close the corresponding issue once the pull request is merged.

Thanks for your contribution to Dataverse!

## Related Issues

- closes #6421 Can't preview in page for files in prior public dataset versions

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by kcondon** [comment]
@qqmyers This is ready to merge but there is a merge conflict. Can you take a look?

**Comment by qqmyers** [comment]
@kcondon - I just accidentally resolved the conflict the wrong way, resulting in no changes to merge. I then went back to the branch in QDR and re-applied the change, but pushing that back to QDR doesn't appear to update this PR. I''m not sure why it isn't updating - are changes not allowed after approval?

In any case, let me know how you want to resolve this:
figure out why the latest commit on the QDR branch isn't getting to this PR,
somehow reverse the last change to resolve the conflict the other way, or
punt and just open a new PR with the correct change.

**Comment by qqmyers** [comment]
@kcondon - nevermind - dyslexia - I was trying to change 6241 instead of 6421. I've now committed the change to this branch and it should be good to go.

**Comment by kcondon** [comment]
@qqmyers Thanks!

**Pull request merged**
