### PR TITLE
Upgrade from Payara 5 to 6

### LINKED ISSUE #8305: Upgrade to Payara 6 and from EE 8 to EE 10 (end of Payara 5 Community Edition security patches Q2/2022)
As a "bklog: Deliverable" This is decomposed into smaller issues, grouped under [D: Payara 6 Upgrade](https://github.com/IQSS/dataverse/labels/D%3A%20Payara%206%20Upgrade)

---

Hat tip to @poikilotherm who [posted][] in chat a link to a video in which Steve Millidge, founder of Payara, answered a question about how long Payara 5 Community Edition (which we recommend in the guides) will receive security patches: https://youtu.be/juD0XNNq344?t=1972

[posted]: https://matrix.to/#/!AmypvmJtUjBesRrnLM:matrix.org/$YqXmiwT6hoyVLfyKuH7rQVKrOFFRHBGFoJqfXR-wjM0

I've transcribed the question and answer:

Q: "For the Community Edition, when will v5 stop getting security patches?"

A: "Payara 5 in Community was basically... when we switch the main branch over to 6, which will be on the point of 6 release, then Community will march forward on Payara 6. So Payara 5 patches, if you like, will stop at that point through Community. So then it will be Enterprise where you'll get patches and security fixes for Payara 5. Payara Community essentially is a marching version so whenever the latest release is the latest release."

I didn't watch the whole video but @poikilotherm says Payara plans to switch the main branch to 6 in Q2/2022.

(By the way, #8064 is the issue where we're tracking the next 5.x upgrade from Payara. As of this writing we are advising installations to use Payara 5.2021.5: https://guides.dataverse.org/en/5.9/installation/prerequisites.html#payara )

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

Payara 5 is going EOL.

**Which issue(s) this PR closes**:

- Closes #8305

**Special notes for your reviewer**:

- Do not move this to QA until Payara 6 Alpha 3 is out and we can test with it.
- Do not move this to QA until Payara 6 Final is out and we can test with it.
- Do not move this to QA until we've made a final decision to go with the Rewrite/PrettyFaces library I built on my Mac and put in `local_lib`. Check https://github.com/ocpsoft/rewrite/issues/304 for progress toward a compatible release from upstream.
- Instead of d86e220 should we preserve backward compatibility of the SWORD API by inserting `attachment; ` for the user if it isn't supplied?
- The Perl installer has not been updated. Honestly, I'm ok with deleting it (and references to it, of course, if any).
- The release note snippet needs work. Upgrades have not been tested.

**Suggestions on how to test this**:

- Make sure API tests pass.
- A test server is coming, similar to the one for Payara 5: https://groups.google.com/g/dataverse-dev/c/5hfiXl4Hpd8/m/awzoSpupAQAJ
- Test everything. Test, test, test, just like the last major version change.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

Yes, a stub is included.

**Additional documentation**:

None but references in the guides to Payara 5 have been switched to Payara 6.

### CODE REVIEW

**Review by landreev — COMMENTED** [review]
It looks like there's been some movement on the Payara side, a good time for this to go back into dev. 
(Also, note that it's showing a few conflicts now)

**Comment by donsizemore** [comment]
> It looks like there's been some movement on the Payara side, a good time for this to go back into dev. (Also, note that it's showing a few conflicts now)

Correct - a `mvn package` results in controlledvocabulary and other language bundle errors, but there is concern that a merge with develop could take several hours. I have the full Maven output if anyone is interested, but I'm less inclined to waste anyone's time with it until the branch is current with develop.

**Comment by poikilotherm** [comment]
@pdurbin what do we do with this PR? It's based on Jakarta EE 9.1, but we need EE 10. I did that in https://github.com/IQSS/dataverse/tree/8305-payara6-ee10. Should we open a new PR?

**Comment by pdurbin** [comment]
@poikilotherm yes, a new PR is better. I'm closing this one. Thanks!

**Comment by pdurbin** [comment]
This is the new PR (thanks, @poikilotherm!):

- #9116

I deleted the old branch to reduce confusion. 😄

**Pull request closed without merging**
