### PR TITLE
Minor bug fixes, including fix for null pointers in the new license selector that did not work with licenses without image URI.

### PR DESCRIPTION
**Pull request by ErykKul**
**What this PR does / why we need it**:
I am new for this project and I have run against some problems when trying out the development branch locally. More in particular some validation errors in NetBeans, as well as some errors when running the application and/or tests. I have fixed them and thought to share it with you.

**Which issue(s) this PR closes**:
I did not see any specific issues reported for the problems I did run against:
- License selector did not work for licenses without image URI (null pointer exceptions)
- DDIExporterTest.java crashed on unmarshalling of LocalDateTime class
- NetBeans complained on namespace declarations in some of the xhtml files
- File upload javascript was giving errors for not unique identifier

Closes #

**Special notes for your reviewer**:
- I am very new to this project, started one week ago, I might have missed something, etc.

**Suggestions on how to test this**:
- Uploading licenses without image URL and trying to select them in license selector.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
- No.

**Is there a release notes update needed for this change?**:
- No.

### CODE REVIEW

**Comment by ErykKul** [comment]
There is still a problem after saving the dataset with a license that does not contain an image URL, page cannot be rendered.

**Comment by ErykKul** [comment]
I have just fixed the remaining null pointers, the dataset page opens now also when license without image url was selected.

**Comment by pdurbin** [comment]
@ErykKul hi! PR #8504 has been merged, which should address your concerns about icons in Licenses. Definitely a bug. Thanks for the heads up and the commits!

For the remaining items, do you mind creating issues (and pull requests, if you feel like it) for each one? These:

- DDIExporterTest.java crashed on unmarshalling of LocalDateTime class
- NetBeans complained on namespace declarations in some of the xhtml files
- File upload javascript was giving errors for not unique identifier

Whenever possible, we try to work in small chunks. We find that work moves more quickly across our project board when small pull requests address small issues and can be reviewed, QA'ed, and merged independently.

**Comment by ErykKul** [comment]
@pdurbin 

I have created new pull requests. I have dropped this one:
- NetBeans complained on namespace declarations in some of the xhtml files

It did not fix anything and broke style import.

The other two pull requests:
https://github.com/IQSS/dataverse/pull/8516
https://github.com/IQSS/dataverse/pull/8517

**Pull request closed without merging**
