### PR TITLE
4839 pid in json ignored

### PR DESCRIPTION
**Pull request by michbarsinai**
The real issue here was an error in the demo JSON, which had the PID data in the dataset version part, rather than in the top-level dataset. So the main fix was to update the sample JSON file.

However, while playing a bit with the JSON, I encountered some ways in which the current import API did not handle errors gracefully. These issues are also addressed here.

IMHO, the main use-case of putting the PID data in the JSON is to allow complex PIDs. This is because the JSON contains the PID in parsed form (protocol, authority, identifier) and thus Dataverse does not need to parse it. This is different than the other way of specifying PID, as a single parameter in the URL.

## Related Issues

- connects to #4839:Import API-Specifying the PID in the JSON does not work

## Pull Request Checklist

- [x] Unit [tests][] completed
- [x] Integration [tests][]: None
- [x] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [x] [Documentation][docs] completed
- [x] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by michbarsinai** [comment]
Minor - fixed a Javadoc link, and added @Override to toString().

**Comment by pdurbin** [comment]
Sorry, I meant src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java

**Comment by michbarsinai** [comment]
Yes. In the importDataset method (line 237), there's some extra logic to detect when a JSON dataset contains an invalid PID data (i.e. unsupported protocol).

**Comment by pdurbin** [comment]
@pameyer and I discussed this pull request today, briefly. It has merge conflicts.

**Comment by pdurbin** [comment]
@michbarsinai please check this out: https://github.com/IQSS/dataverse/issues/5667#issuecomment-477223664

**Comment by pdurbin** [comment]
This pull request is over a year old (currently our oldest pull request), has merge conflicts, and hasn't seen any activity lately. Closing.

**Pull request closed without merging**
