### PR TITLE
Some API documentation changes

### PR DESCRIPTION
**Pull request by leeper**
This is a documentation-only change that:

 - notes the R client for dataverse is now available from [R's central repository, CRAN](https://cran.r-project.org/package=dataverse) and updates a link to it from the SWORD API page
 - standardizes some of the formatting of example across the different API guide pages
 - moves language describing the API key to the main API index page (from the native API page)

connects to #3918

### CODE REVIEW

**Comment by pdurbin** [comment]
@leeper thanks for the pull request! I just advanced it to the "Code Review" column at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@landreev if you happen to know if it's easy to change the destination branch from `master` to `develop` please let me know.

**Comment by pdurbin** [comment]
@leeper if you happen to know if it's easy to change the destination branch from master to develop please let me know.

**Comment by leeper** [comment]
@pdurbin Did that work?

**Comment by pdurbin** [comment]
@leeper much better. Thanks!

**Comment by pdurbin** [comment]
@leeper I'm thinking I'll merge these changes with another API Guide improvement effort for #3192.

**Comment by leeper** [comment]
Sounds great!

**Comment by pdurbin** [comment]
@leeper I'm closing this issue in favor of pull request #3920

The only change I backed out of is the curl commands in the SWORD docs. We need to figure out a sane way wrap long lines, as @dlmurphy and I have discussed in #3577.

**Pull request closed without merging**
