### PR TITLE
WIP: 5164 Allow multiple values for depositor field (citation metadatablock)

### PR DESCRIPTION
**Pull request by rmo-cdsp**
allow multiple values for depositor field (citation metadatablock). Solr schema.xml has to be changed. database may need a migration script

## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #5164: Allow multiple depositors for datasets

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by rmo-cdsp** [comment]
Given that I changed a tsv file, I assume that a sql script is needed to update the fields on database side for existing databases ? If so, maybe I should expand the scope to other fields, like dataCollectionSituation or samplingProcedure, and some other fields, in order to group the queries.

**Comment by pdurbin** [comment]
@rmo-cdsp this pull request has merge conflicts.

**Comment by pdurbin** [comment]
@rmo-cdsp sorry it's been so long since we've commented on this pull request. In the issue I just read that you "wrote earlier in this issue that they don't need this field to allow multiples since each of their dataset's metadata has only one depositor, but they're in favor of this change anyway."

So I'm wondering... do you still want this change? If so, there are merge conflicts. Please resolve them. If not I guess you could close the issue:

- #5164

**Comment by pdurbin** [comment]
@rmo-cdsp I'm going to go ahead and close this but if you're interested in fixing merge conflicts and continuing with it, please let us know. Thanks.

**Pull request closed without merging**
