### PR TITLE
6630 lastlogintime not updated

### LINKED ISSUE #6630: lastlogintime - not updated for users when logged in via web
We were trying to use the authenticated users and list-user APIs to generate the list of all users in Dataverse. What I found is that the lastlogintime is not updated even after we login. I think this is a bug. 

Please see the details that I got when using the authenticated users API. (I have removed sensitive details from the following list).
  "id": 23,
  "identifier": "@venki",
  "displayName": "Kannadasan Venkatachalam",
  "emailLastConfirmed": "2017-07-18T09:58:00Z",
  "createdTime": "2017-07-18T09:58:00Z",
  "lastLoginTime": "2017-07-18T09:58:00Z",
  "lastApiUseTime": "2020-01-31T06:25:45Z",
  "authenticationProviderId": "shib"

This is my details and the lastLoginTime was updated in 2017 but the lastApiUseTime was updated on 31st Jan since I used the API.

NTU Dataverse is running on v4.16.

### PR DESCRIPTION
**Pull request by stevenferey**
**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

Closes #6630 

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by qqmyers — COMMENTED** [review]
Looks like a straight-froward fix. The one question I have is whether it would be better to just include     
```
    @EJB
    UserServiceBean userService;
``` 
to be able to call userService.updateLastLogin rather than creating a pass-though method in the AuthenticationServiceBean. Not a major concern but I think just using @EJB would be cleaner unless there's a reason to avoid that.

**Comment by stevenferey** [comment]
Hello @qqmyers ,

Yes you are right, the method was initially there to include other calls
I update the PR.

**Review by qqmyers — APPROVED** [review]
Looks good - thanks!

**Review by qqmyers — APPROVED** [review]
@stevenferey  - another one where I think all that's needed is merging with develop.

**Pull request merged**
