### PR TITLE
Exclusions to remove module/classpath warnings

### LINKED ISSUE #7632: classpath/module conflicts visible in Eclipse IDE
In Eclipse, I have seen several warnings of the type:
"The package ... is accessible from more than one module: <unnamed>, java.xml"
mostly related to java.xml.* (streaming, naming, parsers).

This appears to be a restriction from Java 9+ introducing models and then not allowing a package to appear both in a module and on the classpath, combined with some of our maven dependencies including packages that have become part of standard Java (such as the above javax.xml packages). (And, of course, Eclipse actually warning you about the conflict - not sure if this is being seen in NetBeans or elsewhere.)

I've started finding/removing these dependencies at QDR (since they make it harder to find other compile issues), but, as far as I can tell, they aren't affecting things running. It is probably a good thing to get rid of these issues as we go forward, either excluding sub-dependencies in maven or updating to new versions that no longer include the affected packages.

If I get a full set of changes, I'll make a PR, but, in the meantime, if this affects anyone else, check the pom for QDR and/or let me know - I can PR the ones I have or we can coordinate on finding the last few.

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: These exclusions appear to remove warnings seen in the issue. The PR is being started as a draft - so it's visible and can serve as a place to collected other exclusions.

**Which issue(s) this PR closes**:

- Closes #7632 

**Special notes for your reviewer**: updates to the dependencies might also change to versions that don't include the problematic packages.

**Suggestions on how to test this**: nothing should break and you can try Eclipse or other IDE and verify that warnings disappear. 

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: no

**Is there a release notes update needed for this change?**: no

**Additional documentation**:

### CODE REVIEW

**Comment by pdurbin** [comment]
@qqmyers where should we expect to see warnings?

**Comment by pdurbin** [comment]
@qqmyers can you please show a screenshot?

**Comment by pdurbin** [comment]
@qqmyers thanks for the call today. I'm close to approving this but API tests are failing on Jenkins. Can you please take a look?

As for the warnings in Eclipse themselves, here are screenshots of before and after.

## Before, develop branch, shows errors

Screenshot 2024-11-26 at 11 43 08 AM

## After, this branch, no errors

Screenshot 2024-11-26 at 11 46 05 AM

I used the .project and .classpath files you gave me, putting them in the root of the git repo. These (renamed so I can upload them):

- [project.txt](https://github.com/user-attachments/files/17922881/project.txt)
- [classpath.txt](https://github.com/user-attachments/files/17922880/classpath.txt)

**Comment by qqmyers** [comment]
It passed with a rerun of the build.

**Review by pdurbin — APPROVED** [review]
API tests are passing. Approved.

I didn't do any testing myself.

**Comment by ofahimIQSS** [comment]
continuous-integration/jenkins/pr-merge is failing on this one https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-7636/26/pipeline

**Comment by ofahimIQSS** [comment]
verified - merging pr

**Pull request merged**
