### PR TITLE
add lip-computing/dataverse to prep.rst

### LINKED ISSUE #8963: add Dataverse Fault Tolerant Architecture link under Advanced Installation
As discussed at https://groups.google.com/g/dataverse-community/c/DFmmaPZ6T4k/m/CDokBCjvAgAJ we should add a link to https://gitlab.com/lip-computing/dataverse to https://guides.dataverse.org/en/5.11.1/installation/prep.html#advanced-installation

The file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/prep.rst

### PR DESCRIPTION
**Pull request by zbenta**
Added LIP's repo with resources for an advanced installation as proposed by Philip Durbin.

**What this PR does / why we need it**:
Added some new installation method to the advanced installation documentation.

**Which issue(s) this PR closes**:
The unavalabilty of a recipe for an advanced installation with all the resources needed to deploy a full functioning dataverse service with a fault tolerant architecture 

Closes #8963

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
https://dataverse-guide--8965.org.readthedocs.build/en/8965/installation/prep.html#advanced-installation looks good!

I added #8963 to the "closes" line in the PR description (so that the issue get closed when we merge the PR).

Heads up to @donsizemore @poikilotherm @4tikhonov and @lwo that @zbenta agreed that for a future PR, we might want to give each installation option more room on the page than just a link. A paragraph perhaps. Or maybe even move to a different page. For now we just wanted to get the link in there.

**Comment by 4tikhonov** [comment]
Hi @pdurbin, I can suggest to put them in the order when the advanced installation was created. So @zbenta should place it as last one in the list.

**Comment by zbenta** [comment]
> Hi @pdurbin, I can suggest to put them in the order when the advanced installation was created. So @zbenta should place it as last one in the list.

I was going to do so @4tikhonov , but @pdurbin  Suggested I added it on the second position since the puppet version was very old, but I can change it if you guys prefer.

**Comment by pdurbin** [comment]
I like the current order, which puts the older, less-maintained options at the bottom.

@4tikhonov certainly we could get more organized, list maintainers, etc. Good ideas for phase 2! 😄 If someone wants to go ahead and create an issue for future improvements, please go ahead (and drop a link in here please). We can pick up the conversation there.

This is just a one line change so I'm going to merge it. Thanks, all! 🚀

**Pull request merged**
