### PR TITLE
Large file upload - internationalization of error message

### LINKED ISSUE #8593: "Invalid file size" error message is not internationalized
**What steps does it take to reproduce the issue?**

* When does this issue occur?

When a user uploads an image that is too large on the Themes and Widgets page, the error message is not internationalized. PR forthcoming from @JayanthyChengan. 

* Which page(s) does it occurs on?

Themes and Widgets

* To whom does it occur (all users, curators, superusers)?

Users with permissions to edit collections

* What did you expect to happen?

I expected the text to be translated (to French in our case)

**Which version of Dataverse are you using?**

5.8

**Screenshots:**

File upload error message that is not translated

### PR DESCRIPTION
**Pull request by JayanthyChengan**
**What this PR does / why we need it**:
The internationalization of  "Invalid file size" message is implemented, when a user uploads a large image file on the Themes and Widgets page.

**Which issue(s) this PR closes**:

Closes #8593

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by sekmiller — COMMENTED** [review]
@JayanthyChengan the coding for the messaging looks good. I'm just wondering about the updates to the old scripts. I think they will only be effective for upgrades to versions prior to the numbers on the scripts ( 4.13 and 4.16).

**Comment by JayanthyChengan** [comment]
@sekmiller - that was my mistake, reverted them back

**Comment by sekmiller** [comment]
@JayanthyChengan, Thanks! I will pass along to QA.

**Review by sekmiller — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
