### PR TITLE
bump version to 5.12

### LINKED ISSUE #8980: Bump version for 5.12

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

Bumps the version to 5.12.

**Which issue(s) this PR closes**:

Closes #8980

**Special notes for your reviewer**:

None.

**Suggestions on how to test this**:

I checked these already but:

- make sure you see 5.12 at http://localhost:8080/api/info/version
- check for 5.12 at top of html/index.html
  - preview at https://dataverse-guide--9004.org.readthedocs.build/en/9004/index.html
- check new link at build/html/versions.html
  - preview at https://dataverse-guide--9004.org.readthedocs.build/en/9004/versions.html

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No.

**Is there a release notes update needed for this change?**:

No.

**Additional documentation**:

None.

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Looks like the same changes as for 5.11.1

**Comment by pdurbin** [comment]
At https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9004/1/consoleFull I'm seeing this:

TASK [dataverse : copy warfile over release] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Source /tmp/dataverse/target/dataverse-5.11.1.war not found"}


On the Ansible side I think we need a bump like this: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/commit/5f08dc421140d711b27eb2089a5b8db4c2748dba

I created an issue:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/258

Thank you for any assistance @donsizemore ! ❤️

**Comment by pdurbin** [comment]
@donsizemore bumped jenkin.yml for me (thanks!) in https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/commit/c382f03

I re-ran the job and it's passing now: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9004/2/testReport/

**Comment by pdurbin** [comment]
For next time this is my suggested recipe (I think):

- ensure develop is passing
- bump jenkins.yml in Ansible
- create PR to bump Dataverse, ensure tests pass
- review and merge PR to bump Dataverse
- ensure develop is passing
- merge develop to master, ensure tests pass
- make release, upload artifacts
- bump main.yml, etc. in Ansible

**Pull request merged**
