### PR TITLE
6953 mpconfig context param

### LINKED ISSUE #6953: As a developer, I want changes I make to the front end to be visible when I deploy from Netbeans
[Formerly known as _As a developer, I want changes I make to the front end to be visible when I deploy from Netbeans_]

Ever since 5f99037 developers have had to remember to comment out part of `src/main/webapp/WEB-INF/web.xml` in order for changes they are making to the front end to be visible when deploying from Netbeans. At the very least we should document this in the dev guide. This is the part that has to be commented out (but not committed, of course):

    <context-param>
        <param-name>javax.faces.FACELETS_REFRESH_PERIOD</param-name>
        <param-value>-1</param-value>
    </context-param>

Even better would be to somehow fix it so developers don't have to comment this out but I'd be satisfied with some docs for now.

<hr>

[GPD - 2020-12-16 - edited the original description -

Original said to also comment out 

    <context-param>
        <param-name>javax.faces.FACELETS_BUFFER_SIZE</param-name>
        <param-value>102400</param-value>
    </context-param>

but doing so causes flash messages to become "sticky"  - see issue #7305]

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
This allows for a very dynamic changing of JSF parameters without recompilation. It adds docs how to do this, too.

This PR also relies on the fact that people should upgrade from Payara 5.2020.6 or later to at least 5.2021.1 to gain support for MPCONFIG 2.0 and default parametes in `${MPCONFIG=...}` variable substitution, which is described in #7701

**Which issue(s) this PR closes**:

Closes #6953 
:zap: Blocked by #7701 :zap: 

**Special notes for your reviewer**:
None.

**Suggestions on how to test this**:
Change some of the documented vars e. g. via system properties.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope.

**Is there a release notes update needed for this change?**:
Yes, two. :battery: included.

**Additional documentation**:
None.

### CODE REVIEW

**Comment by pdurbin** [comment]
This seems like a great solution to #6953 but it depends on pull request #7701 so it probably doesn't below in code review.

**Comment by poikilotherm** [comment]
As this relies on Payara 5.2021.1 (see 48d6501 for an extensive explanation), I will put this back to draft.

**Comment by poikilotherm** [comment]
As #7701 is likely to be merged soonish, pushing this PR back into the pipeline.

**Comment by pdurbin** [comment]
It looks like pull request #7701 is a little more involved that we originally thought and since it's a dependency (and since the Review column is pretty full), let's leave this in Community Dev until that other pull request is merged.

**Comment by poikilotherm** [comment]
Putting this back in Review now...

**Comment by djbrooke** [comment]
Thanks @poikilotherm, we'll review. You mentioned two release notes in the PR description but I only saw one in the changed files - is there one missing or was the second release note handled elsewhere?

**Comment by poikilotherm** [comment]
Looks like a leftover. Just ignore that... Thx!

**Review by pdurbin — APPROVED** [review]
@poikilotherm I'm so happy for this pull request. In the years since 5f99037 I've had to maintain a local edit to `src/main/webapp/WEB-INF/web.xml` and be careful not to commit it to git in order to for my edits to the GUI to be visible. Now, it's just a simple change to domain.xml, which I added to the docs and the "rebuild" script (using asadmin).

**Pull request merged**
