### PR TITLE
2834 usernames not accepted pure evil test

### PR DESCRIPTION
**Pull request by majorseitan**
Ignore the previous pull request it is missing the unit tests

### CODE REVIEW

**Comment by pdurbin** [comment]
@majorseitan can you please close the other pull request if you don't want anyone to review it? Thanks.

**Comment by pdurbin** [comment]
Assigning to @scolapasta per https://github.com/IQSS/dataverse/issues/2834#issuecomment-174620285 and setting milestone to the same as that issue.

**Comment by majorseitan** [comment]
Switched from lambda functions to default methods.

**Comment by scolapasta** [comment]
Superseded by change for performance: #2027

**Pull request closed without merging**
