### PR TITLE
fix for cvv and editMetadata replace=true, and test

### LINKED ISSUE #9106: EditMetadata replace doesn't work correctly
**What steps does it take to reproduce the issue?** Reported by DANS - When using replace=true with /api/datasets/\<id\>/editMetadata, values that are in-common with the current value are not added. I.e. when the language field has `English, Japanese, Korean` and you replace with `English, Dutch, Korean`, the result is only `Dutch` . DANS also correctly identified the underlying issue: at line https://github.com/IQSS/dataverse/blob/42e2b59811576bd6034eb5c1dd25bce7a57cea31/src/main/java/edu/harvard/iq/dataverse/api/Datasets.java#L993 cvvDisplay contains the original values even in the replace=true case.

**Which version of Dataverse are you using?**
5.12

### PR DESCRIPTION
**Pull request by qqmyers**
**What this PR does / why we need it**: Fixes the case in the issue - editMetadata api call with replace=true and a cvv field.

**Which issue(s) this PR closes**:

Closes #9106

**Special notes for your reviewer**: kudos to DANS for making this easy

**Suggestions on how to test this**:  Use the editMetadata api call with replace=true on a cvv field like subject or language and verify that when the replacement list contains one of the values in the current field value that it remains, i.e. that when you replace with n values where one or more was in the original value, you get all n values. FWIW: The change to the test should check this case - Mathematical Sciences should be a current value and the replacement is with Mathematical Sciences and Social Sciences and the test checks that both values exist at the end.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by pdurbin** [comment]
@qqmyers any chance this also fixes either of the following issues?

- #7605
- #8860

**Comment by qqmyers** [comment]
maybe - #8860 looks like a good possibility while #7605 seems to suggest 'nothing' happens vs. the term disappears, but perhaps that is without replace=true. This PR only changes the replace=true logic so if #7605 involves not using replace-true, that part of it would still remain. In any case, certainly worth testing those cases.

**Comment by mreekie** [comment]
This is a PR. Dev is don.
This is a one line fix for something that Don found and diagnosed.
This comes with the fix and automated tests
It is very small.

**Comment by mreekie** [comment]
Added to 12/1/2022 sprint on 12/5/2022

**Review by sekmiller — APPROVED** [review]

**Pull request merged**
