### PR TITLE
Add a Contributor Guide

### LINKED ISSUE #10531: Feature Request/Idea: Contributor Guide
**Overview of the Feature Request**

The Contributors UX group met today (attended by @vaidap, @DieuwertjeBloemen, @rtreacy, @ekraffmiller and myself) and we think expanding [CONTRIBUTING.md](https://github.com/IQSS/dataverse/blob/develop/CONTRIBUTING.md) into a proper guide is a good idea.

I offered to stub out the Sphinx files.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

Contributors. A different role than listed above!

**What inspired the request?**

Discussion of documentation and contribution ([notes](https://docs.google.com/document/d/1EaHMzCiabiQXVAf1s8kO0kdk2bQADZhwzAyD1P8XO6s/edit?usp=sharing)).

**Any open or closed issues related to this feature request?**

- #9916
- https://github.com/IQSS/dataverse-pm/issues/177

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

[CONTRIBUTING.md](https://github.com/IQSS/dataverse/blob/develop/CONTRIBUTING.md) has served us well but we'd like to expand into a proper guide.

We are discussing the old CONTRIBUTOR.md in this doc: https://docs.google.com/document/d/1NG1cw8NqdUu_iFWFNUNIOL3sSjMVoP_uBL2ObZbmm60/edit?usp=sharing

You can preview it the new guide at https://dataverse-guide--10532.org.readthedocs.build/en/10532/contributor/index.html

Additional discussion in Zulip: https://dataverse.zulipchat.com/#narrow/stream/434038-ux-wg/topic/Contributor.20Guide

**Which issue(s) this PR closes**:

- Closes #10531

**Special notes for your reviewer**:

As you'll notice, I delete the old "writing docs" page from the dev guide after moving the content to the new contrib guide.

**Is there a release notes update needed for this change?**:

Yes, included.

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Looks good. Sounds like this has been discussed/reviewed in other channels. The only notes that I have are that 
- the build failed with ```
TASK [dataverse : fire at will] ************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/perl count.pl --non-interactive /var/lib/pgsql/13/data/log/postgresql-Fri.log > /tmp/query_count.out", "delta": "0:00:00.017408", "end": "2024-06-14 16:42:54.167980", "msg": "non-zero return code", "rc": 2, "start": "2024-06-14 16:42:54.150572", "stderr": "usage: ./count.pl <PGLOGFILE>", "stderr_lines": ["usage: ./count.pl <PGLOGFILE>"], "stdout": "", "stdout_lines": []}```
presumably not related since this is a documentation-only PR

- documentation.md has a TODO at line 148. Rather than wait for @pdurbin to return, I'd suggest when this gets QA'd/ready for merge, if the TODO hasn't been addressed we just drop it for now and go ahead.

**Comment by DieuwertjeBloemen** [comment]
@qqmyers the TODO can indeed be left out before approving it. It's something to be decided at a later point and then to add to it.

**Comment by pdurbin** [comment]
I see there are merge conflicts and I'll work on the TODO mentioned above.

**Comment by pdurbin** [comment]
@jp-tosca I re-applied your change about sphinx and docker here: 9bd0ccf

@DieuwertjeBloemen I removed the TODO: 7a64dea

No objections at standup about merging this so I'll go ahead. The preview still looks good: https://dataverse-guide--10532.org.readthedocs.build/en/10532/contributor/index.html

We can always iterate more in the future, of course! Please keep the suggestions coming! 🚀

**Pull request merged**
