### PR TITLE
Quick fix for a failing harvesting test  #8937

### LINKED ISSUE #8937: test failure in develop: HarvestingServerIT.testOaiFunctionality
**What steps does it take to reproduce the issue?**

- Open HarvestingServerIT and run testOaiFunctionality.
- Observe that the test fails

The output from the test is something like the XML below. 

```
<OAI-PMH schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2022-08-25T14:00:57Z</responseDate>
  <request verb="ListIdentifiers" metadataPrefix="oai_dc" set="YZOIGQ">http://localhost:8080/oai</request>
  <ListIdentifiers>
    <header>
      <identifier>doi:10.5072/FK2/YZOIGQ</identifier>
      <datestamp>2022-08-25T14:00:52Z</datestamp>
      <setSpec>YZOIGQ</setSpec>
    </header>
  </ListIdentifiers>
</OAI-PMH>
```

The test is looking for a list of size 1:

        // Run ListIdentifiers on this newly-created set:
        Response listIdentifiersResponse = UtilIT.getOaiListIdentifiers(setName, "oai_dc");
        List ret = listIdentifiersResponse.getBody().xmlPath().getList("OAI-PMH.ListIdentifiers.header");

        assertEquals(OK.getStatusCode(), listIdentifiersResponse.getStatusCode());
        assertNotNull(ret);
        logger.info("setName: " + setName);
        logger.info("listIdentifiersResponse.prettyPrint:..... ");
        // There should be 1 and only 1 record in the response:
        assertEquals(1, ret.size());

**Which version of Dataverse are you using?**

The first observed failure on Jenkins on the develop branch was for 1ef73b0 (the tip of develop as of this writing).

We're also seeing the failure in PR #8880 where the tip of develop was merged.

Locally I'm on 6ca1c9d8 (I haven't pulled from develop so I haven't picked up the merge from PR #8901 yet) and @sekmiller also hasn't pulled and we are both seeing the failure.

### PR DESCRIPTION
**Pull request by landreev**
**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

Closes #8937

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
Looks like a doubling, as discussed. I'm waiting for the Jenkins tests to pass before I merge this.

**Comment by landreev** [comment]
Before increasing that sleep, I ran the test a few times and it was failing about 50% of the time. After doubling it I ran it a few more times and wasn't able to get it to fail. 
So, looks like a solid fix. 😄

**Comment by landreev** [comment]
I'll take a look to see why it bombed once I'm in. ☹️

**Comment by landreev** [comment]
This is kind of insane that the harvesting test is still bombing. So maybe it's not the duration after all. (not sure yet what's up with the other test that failed)

**Comment by landreev** [comment]
Oh. Was that the wrong sleep interval to increase? - I.e., it may be failing not on account of the set create taking too long, but because we try to create the set before the publish command has completed on the dataset there...

**Comment by landreev** [comment]
This current Jenkins run appears to be stuck... But once it runs, I expect this test pass.

**Comment by landreev** [comment]
OK, the tests have passed. 
The other test that failed during the first run - it died in a really random place, with a 500 from an attempt to destroy a dataset at the end of a test. I feel like dismissing it as a fluke.

**Comment by pdurbin** [comment]
Before merging I confirmed that indeed all API tests passed. Again, all we're doing is bumping up the amount of sleep.

**Comment by landreev** [comment]
Yeah, I edited the comment in the issue, documenting that it wasn't the doubling of the 5 sec. sleep, but an extra sleep added before that step.

**Pull request merged**
