### PR TITLE
8339 file data api

### LINKED ISSUE #8339: Provide an API for retrieving information about an individual datafile
We do not have an easy way to retrieve a full information record for a single datafile, such as what's listed in `/api/datasets/{did}/versions/{vid}` (for all files in the version). 
We do have `/api/files/{id}/metadata`, but it literally only shows what's in the FileMetadata entity (such as file and folder names), plus the tags and the restriction status. I.e., it's not showing all the info that's in the DataFile entity (size, mime type, etc. etc.). So the only practical way for an API user to look up a full info record for a file is to get a full list of all the files (above) and parse it out, which is inefficient. 

We could extend `/api/files/{id}/metadata`, synchronizing its output to what's listed in the records under `/api/datasets/{did}/versions/{vid}`. 
Alternatively, we could provide a GET `/api/files/{id}` to produce such a record. (This could be a better option - since it would match the behavior of other entity APIs - `/api/datasets/{id}` etc. - ?)

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**: Adds an api endpoint to get file metadata and info from the datafile in json format

**Which issue(s) this PR closes**: 

- closes #8339

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: No

**Is there a release notes update needed for this change?**:

**Additional documentation**: Doc added to file section of Native API

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
Code, docs, and tests are looking good!

I mentioned to @sekmiller that he's using a non-default format for file DOIs but it's completely legit and shorter in the docs so I think it's fine. Others, please speak up if you think it's important the change. Details in the review.

I ran the code locally and the JSON output looks good to me.

@kcondon one addition to the JSON is categories (file tags in the UI), which I didn't test. If you could try exercising this, I'd appreciate it. I guess we could also add an automated test for categories. Please let us know if you want this.

Here's some example JSON that came out of me running the new API test (all other API test are passing in Jenkins, by the way):

```
{
  "status": "OK",
  "data": {
    "description": "",
    "label": "stata13-auto-withstrls.dta",
    "restricted": false,
    "version": 1,
    "datasetVersionId": 1,
    "dataFile": {
      "id": 4,
      "persistentId": "",
      "pidURL": "",
      "filename": "stata13-auto-withstrls.dta",
      "contentType": "application/x-stata-13",
      "filesize": 8854,
      "description": "",
      "storageIdentifier": "s3://pdurbin:185a14c1549-769c167d9eeb",
      "rootDataFileId": -1,
      "md5": "6ce6be68c8b8bccf08c1b7ba5e924e5a",
      "checksum": {
        "type": "MD5",
        "value": "6ce6be68c8b8bccf08c1b7ba5e924e5a"
      },
      "creationDate": "2023-01-11"
    }
  }
}
```

**Comment by mreekie** [comment]
size for the next sprint: 10
This is just an API that takes a file id and gets a json represenation of the file.

**Comment by kcondon** [comment]
Basic endpoint seems to work ok, json is downloaded.
Noticed a couple things:
1. The doc could maybe be simplified a bit, just two forms, id and persistentId, with env variable and fully expanded examples for each. Our doc sometimes only shows one form and mentions the other. Make sure to add export API_TOKEN to the examples. 
2. Description and path are file metadata but reside in a dataset version. The current perms always fetches the latest, even if draft and as long as file is published, anyone will get it. It seems minor given the info in question but it seem conceptually it should follow the dataset perms?

**Comment by sekmiller** [comment]
I implemented 'draft' and updated the doc. I think this is all that is pending.

**Comment by kcondon** [comment]
Retested and this works fine now. Ready to merge, waiting for integration tests to complete.

**Comment by mreekie** [comment]
sprint kickoff
- include in QATail for Jan 11, 2023

**Pull request merged**
