### PR TITLE
Update the conditions to display image_url in Solr search results for file type

### LINKED ISSUE #10875: Update the conditions to display image_url in Solr search results for file type
**Overview of the Feature Request**

We need to update the added conditions  in https://github.com/IQSS/dataverse/pull/10855 to determine whether to return image_url or not for a file type result. JSF displays images for a file type result even when it is not published, which does not happen with the newly added logic. We also need to review the other conditions (restricted, harvested...) and understand how it currently works in JSF to return or not return image_url for a file type result.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**

- https://github.com/IQSS/dataverse/pull/10855

**What existing behavior do you want changed?**

image_url display condition for file search result included in https://github.com/IQSS/dataverse/pull/10855

**Any brand new behavior do you want to add to Dataverse?**

None

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse/pull/10855

**Are you thinking about creating a pull request for this feature?**  
Yes

### PR DESCRIPTION
**Pull request by stevenwinship**
**What this PR does / why we need it**: fixes the conditions in which the visibility of the image_url field is included in the search results.

**Which issue(s) this PR closes**:https://github.com/IQSS/dataverse/issues/10875

Closes #10875

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: No

**Is there a release notes update needed for this change?**: No

**Additional documentation**: See https://github.com/IQSS/dataverse/pull/10855

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
Looks good. I made a small tweak to the release note. API tests didn't run so I'm holding on to this to see if they pass this time. They're running now.

**Comment by pdurbin** [comment]
API tests didn't run. At standup @stevenwinship said he'd take a look (thanks): https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-10886/5/testReport/

**Comment by stevenwinship** [comment]
I re-ran the tests and they all passed. 
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-10886/6/

**Review by pdurbin — APPROVED** [review]
Sure enough! Thanks! Approved!

**Comment by ofahimIQSS** [comment]
@stevenwinship Uncovered an issue while testing this PR. Collection Thumbnails aren't displayed on homepage when adding a logo, thumbnail, and footer images to a collection. 

1. Create a new Collection
2. Edit Collection> Theme + Widgets
3. Upload Logo, Thumbnail, and Footer Images 
4. Publish Collection
5. Navigate to homepage --- here is where the issue lies: Notice that the thumbnail still displays default Dataverse Collection thumbnail instead of what was just uploaded.

**Comment by stevenwinship** [comment]
RE: Navigate to homepage --- here is where the issue lies: Notice that the thumbnail still displays default Dataverse Collection thumbnail instead of what was just uploaded.

This issue exists in develop branch and is not caused by this PR

**Comment by ofahimIQSS** [comment]
Confirmed testing with Steve - no issues found with PR. Merging 
[Testing of 10886.docx](https://github.com/user-attachments/files/17525165/Testing.of.10886.docx)

**Pull request merged**
