### PR TITLE
Remove broken link and description of DataCite Proxy no longer used by ADA

### PR DESCRIPTION
**Pull request by AkiraY1**
Removed broken link to https://documentation.ands.org.au/display/DOC/ANDS+DataCite+Client+API on page https://guides.dataverse.org/en/latest/installation/config.html. Partial fix for #8874.

### CODE REVIEW

**Review by pdurbin — CHANGES_REQUESTED** [review]
Hmm, instead of a removing this link we should probably ask @mdmADA if there is a better link to use. This was added as part of #3832.

**Comment by mdmADA** [comment]
Hi Phil.

ANDS (now ARDC) used to provide an API proxy for interfacing with DataCite in order to mint DOIs. That API was decommissioned ages ago so now ADA's dataverse instances call the DataCite Fabrica API directly to mint DOIs. So there is no better link to provide for this issue.

Thanks,
M.

**Comment by pdurbin** [comment]
@mdmADA ok, thanks!

@AkiraY1 I think what we should do is simply remove all of the following (both paragraphs):

While the above two options are recommended because they have been tested by the Dataverse Project Team, it is also possible to use a DataCite Client API as a proxy to DataCite. In this case, requests made to the Client API are captured and passed on to DataCite for processing. The application will interact with the DataCite Client API exactly as if it were interacting directly with the DataCite API, with the only difference being the change to the base endpoint URL.

For example, the Australian Data Archive (ADA) successfully uses the Australian National Data Service (ANDS) API (a proxy for DataCite) to mint their DOIs through their Dataverse installation using a ``doi.baseurlstring`` value of "https://researchdata.ands.org.au/api/doi/datacite" as documented at https://documentation.ands.org.au/display/DOC/ANDS+DataCite+Client+API . As ADA did for ANDS DOI minting, any DOI provider (and their corresponding DOI configuration parameters) other than DataCite must be tested with the Dataverse Software to establish whether or not it will function properly.

**Comment by AkiraY1** [comment]
Done! I removed the two paragraphs.

**Review by pdurbin — APPROVED** [review]
Looks good. Approved. Please see discussion in this pull request about how ADA doesn't use proxy any more. I'll also retitle the PR and probably the issue.

**Comment by poikilotherm** [comment]
Please note I already have a refactoring of this entire section within the MPCONFIG PR for PIDs #8828

**Pull request merged**
