### PR TITLE
Make Series multiple #9255

### LINKED ISSUE #9255: Feature Request/Idea: Make Series repeatable
**Overview of the Feature Request**
Makes the metadata field Series in the Citation Metadata block repeatable.

**What kind of user is the feature intended for?**
API User, Curator, Depositor, Guest, Superuser, Sysadmin

**What inspired the request?**
Data contained in a dataset may belong to multiple series. Making the field Series repeatable will make it possible to reflect this fact in the dataset metadata.

**What existing behavior do you want changed?**
The field not being repeatable.

**Any brand new behavior do you want to add to Dataverse?**
No. Other, similar fields are already repeatable, e.g., Keyword.

**Any related open or closed issues to this feature request?**
No.

### PR DESCRIPTION
**Pull request by philippconzett**
**What this PR does / why we need it**:
Allows depositors to define multiple instances of the metadata field Series in the Citation Metadata block.

**Which issue(s) this PR closes**:

Closes #9255

**Special notes for your reviewer**:
No.

**Suggestions on how to test this**:
Create a test dataset with multiple instances of the Series metadata field.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
No. There are already other metadata fields that are repeatable and facetable.

**Is there a release notes update needed for this change?**:
Should briefly mention that the field now is repeatable.

**Additional documentation**:
No.

### CODE REVIEW

**Comment by mreekie** [comment]
Prio meeting with Stefano.
- Moved from Community Backlog to ordered backlog

**Comment by sekmiller** [comment]
Based on the work I did on making production place multiple (https://github.com/IQSS/dataverse/pull/9254) this PR will need additional release notes with respect to upgrading the citation block - also schema.xml and searching - possibly import

**Comment by sekmiller** [comment]
Updates for solr are done. Still needs work on ImportDDIServiceBean for multiple series. Also there may need to be notes on backwards incompatibility for dataset json that do not note that series can be multiple.

**Comment by sekmiller** [comment]
Also, currently getting an error on finalize publish export all formats.

**Comment by landreev** [comment]
Just grabbed this for review now. Based on a very quick first glance, the correct changes were made in the export DDI util (the part that we overlooked when productionPlace was made multiple), but I need to take a closer look.

**Comment by landreev** [comment]
@sekmiller I would like to take you up on syncing the branch with develop (first @philippconzett's fork needs to be synced with IQSS:dataverse). I don't think I can sync the actual remote fork, but I did try this on my own local checkout of Philipp's branch; and, to my surprise, it auto-merges just fine with IQSS/develop, without any conflicts in DdiExportUtil.java. 
Once this is done, I'd like to change the control "all fields" json file and the corresponding control ddi export to actually include multiple series, to make sure we are testing the field correctly. Again, I tried this in my local checkout and the tests passed. 
So, I'm talking about replacing 
```
             {
              "seriesName": {
                "typeName": "seriesName",
                "multiple": false,
                "typeClass": "primitive",
                "value": "SeriesName"
              },
              "seriesInformation": {
                "typeName": "seriesInformation",
                "multiple": false,
                "typeClass": "primitive",
                "value": "SeriesInformation"
              }
            }
```
with 
```
             {
                "seriesName": {
                  "typeName": "seriesName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "SeriesName1"
                },
                "seriesInformation": {
                  "typeName": "seriesInformation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "SeriesInformation1"
                }
              },
              {
                "seriesName": {
                  "typeName": "seriesName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "SeriesName2"
                },
                "seriesInformation": {
                  "typeName": "seriesInformation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "SeriesInformation2"
                }
              }
```
in `src/test/java/edu/harvard/iq/dataverse/export/ddi/dataset-create-new-all-ddi-fields.json`
and replacing 
```
      <serStmt>
        <serName>SeriesName</serName>
        <serInfo>SeriesInformation</serInfo>
      </serStmt>
```
with 
```
     <serStmt>
        <serName>SeriesName1</serName>
        <serInfo>SeriesInformation1</serInfo>
      </serStmt>
      <serStmt>
        <serName>SeriesName2</serName>
        <serInfo>SeriesInformation2</serInfo>
      </serStmt> 
```
in `src/test/java/edu/harvard/iq/dataverse/export/ddi/exportfull.xml`. 

Aside from this, I'm happy with everything in this PR, providing all the Jenkins tests pass after this. 
Thank you, and sorry for coming up with more work.

**Comment by pdurbin** [comment]
In 7748450 I merged develop into this branch/PR. I more or less followed: https://guides.dataverse.org/en/5.13/developers/version-control.html#adding-commits-to-a-pull-request-from-a-fork

The only wrinkle is if there are multiple branches called `patch-3` (in this case) across remotes you have configured. I ended up deleting a remote to get down to just the single `patch-3` I wanted to update.

**Comment by landreev** [comment]
Great, thank you @pdurbin. The branch looks good, let me check in the 2 changes I wanted to make and that should be it.

**Comment by mreekie** [comment]
sprint kickoff
- These are just waiting on jenkins tests to complete and QA

**Review by landreev — APPROVED** [review]
Moving into QA.

**Comment by kcondon** [comment]
Issues found:
1. Cannot add multiple series without error either to an existing or new dataset, see error in ui, none in logs but metadata is added. Can add a single series value without error. Maybe indexing? 
Screen Shot 2023-05-02 at 10 49 03 AM
Screen Shot 2023-05-02 at 10 49 15 AM

**Pull request merged**
