### PR TITLE
Assert true or false, not equal to true or false

### PR DESCRIPTION
**Pull request by bencomp**
**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

Closes #

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Comment by stevenwinship** [comment]
Looks good. Could you merge develop into this branch and clear the conflicts before I can approve it?

**Comment by stevenwinship** [comment]
Closing due to inactivity. Please reopen if this issue is still relevant.

**Comment by bencomp** [comment]
Although this was a draft PR before, could you reopen it? I'm happy to have current changes merged.

**Comment by stevenwinship** [comment]
I'm not able to re-open this one. You may need to re-create it?

**Pull request closed without merging**
