### PR TITLE
2073 add move to dashboard

### PR DESCRIPTION
**Pull request by PaulBoon**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #2073: Moving Dataverses + Datasets: Provide way in the UI for a user to do this

Please don't merge this yet.  
Although it does allow to move a dataset, it at least needs some GUI polishing and the text must be placed in the Bundle.properties. The input controls might also be improved, because it is now not always clear which Dataset is selected when you only see the PID. Maybe we can use the dataverse selection from the 'Link' dialog, but it looks a bit complicated to incorporate it. 

The dashboard 'card: '
Screenshot DashboardCard

The data(set) move form: 
ScreenshotDatamoveForm3

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by PaulBoon** [comment]
I choose the words 'Data' and 'Move Data' on the 'card' to leave the option for moving verses later on. 
Maybe 'Manage Data' or 'Reorganize Data' would be better.

**Comment by PaulBoon** [comment]
It's working with autocompleted, but some issues need attention:
- Dataset autocomplete can only do exact match and is not doing a 'sql like' with the globalid
- Validation message not appearing in top of form when invalid
- Validation message not removed after filling in required field previously not specified 
- Cancel button does not remember the dataset id like in the breadcrumb
- Cancel button is slightly thinner than 'save Changes' next to it

**Comment by PaulBoon** [comment]
Hi @pdurbin, can anyone take a look at it and give some feedback about what must be done to get it merged in.

**Comment by pdurbin** [comment]
@PaulBoon I'm closing this (awesome) pull request in favor of pull request #5798 which has all of your commits (so you'll still get credit from the GitHub perspective as well as in our hearts ❤️ ) and some more commits from me @mheppler and @dlmurphy . Thanks!

**Pull request closed without merging**
