### PR TITLE
#6525 update weld-osgi call to match that of docker-aio et al.

### LINKED ISSUE #6525: weld-osgi-bundle-2.2.10.SP1.jar has moved.
just an issue to accompany a pull request to point Glassfish 4.1 docs at the new location:

```
[ec2-user@ip-172-30-0-146 ~]$ wget http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar
--2020-01-15 20:09:52--  http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar
Resolving central.maven.org (central.maven.org)... 151.101.52.209
Connecting to central.maven.org (central.maven.org)|151.101.52.209|:80... connected.
HTTP request sent, awaiting response... 501 HTTPS Required
2020-01-15 20:09:52 ERROR 501: HTTPS Required.

[ec2-user@ip-172-30-0-146 ~]$ wget https://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar
--2020-01-15 20:09:58--  https://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar
Resolving central.maven.org (central.maven.org)... 151.101.52.209
Connecting to central.maven.org (central.maven.org)|151.101.52.209|:443... connected.
The certificate's owner does not match hostname ‘central.maven.org’
```

new location should/might be https://repo1.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1.jar

pull request forthcoming.

### PR DESCRIPTION
**Pull request by donsizemore**
**What this PR does / why we need it**: current weld-osgi link in installation documentation is broken

**Which issue(s) this PR closes**:

Closes #6525 

**Special notes for your reviewer**: bumping from SP1 to Final, but all other such calls in docs use Final

**Suggestions on how to test this**: spin up branch and test normally

**Does this PR introduce a user interface change?**: no

**Is there a release notes update needed for this change?**: no

**Additional documentation**:

### CODE REVIEW

**Comment by poikilotherm** [comment]
It might be pedantic, but could you change http to https? Maven Central just turned off HTTP. https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by djbrooke** [comment]
Thanks @poikilotherm. @donsizemore if this sounds OK to you please make the change. I was going to do it but I'm not knowledgeable in this area. :)

**Comment by djbrooke** [comment]
@donsizemore @poikilotherm @pdurbin Is this PR still relevant or should we close?

**Comment by donsizemore** [comment]
@djbrooke yes — maven throws a 501 when called via http rather than https.

**Pull request merged**
