### PR TITLE
#9739 - URLValidator now allows two slashes in the path component of the URL

### LINKED ISSUE #9739: Metadata Customization : url fieldType validator
Hello there,
We are facing an issue regarding [url](https://guides.dataverse.org/en/5.13/admin/metadatacustomization.html?highlight=url#datasetfield-field-properties) `fieldType` validation while using uncommon url.
Here is such url : https://archive.softwareheritage.org/swh:1:dir:561bfe6698ca9e58b552b4eb4e56132cac41c6f9;origin=https://github.com/gem-pasteur/macsyfinder;visit=swh:1:snp:1bde3cb370766b10132c4e004c7cb377979928d1;anchor=swh:1:rev:868637fce184865d8e0436338af66a2648e8f6e1 (generated by the website as a permalink)

Deeper analysis reveals that the [url validator](https://github.com/IQSS/dataverse/blob/0661c3a5c35f29e83db7799d802aa31300fb919d/src/main/java/edu/harvard/iq/dataverse/validation/URLValidator.java#L44-L47C1) is based on `org.apache.commons.validator.routines.UrlValidator` and will fail on validation due to the `//` near `6f9;origin=https://githu`.

UrlValidator as capability to be customized with options such as [ALLOW_2_SLASHES](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/UrlValidator.html#ALLOW_2_SLASHES) that _Allow two slashes in the path component of the URL_ : 

```java
UrlValidator urlValidator = new UrlValidator(schemes, UrlValidator.ALLOW_2_SLASHES);
```

The question now is : is it reasonable to add this option "for everyone and every url fields" ?
What do you think ?

Depending on the answer a PR could be considered.

### PR DESCRIPTION
**Pull request by luddaniel**
**What this PR does / why we need it**:

URLValidator now allows two slashes in the path component of the URL

**Which issue(s) this PR closes**:

Closes #9739

**Special notes for your reviewer**:

From what I see, URLValidator is used to :
- validate url type of field
- validate url filled via deaccession dialog

As discussed in #9739, a user is able to provide "valid" syntax url that can be "invalid" when used, so allowing two slashes in the path component of the URL seems to not bring any danger.

**Suggestions on how to test this**:

- Save a dataset with an url in a url field type
- Deaccessionate a dataset and specify a forwarding url

Example of allowed url : https://archive.softwareheritage.org/swh:1:dir:561bfe6698ca9e58b552b4eb4e56132cac41c6f9;origin=https://github.com/gem-pasteur/macsyfinder;visit=swh:1:snp:1bde3cb370766b10132c4e004c7cb377979928d1;anchor=swh:1:rev:868637fce184865d8e0436338af66a2648e8f6e1

**Does this PR introduce a user interface change?**

No

**Is there a release notes update needed for this change?**

No

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Looks good. FYI - I did a quick check and UrlValidator is also used to decide whether the forwarding URL for a deaccessioned dataset is OK. I think allowing two slashes there is also OK, but we should be aware that this PR as is will change that as well.

**Comment by pdurbin** [comment]
The ec2 instance didn't spin up. I just triggered another run of the API tests: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9750/2/

**Comment by scolapasta** [comment]
@luddaniel a small release note for this change would ne nice for users, as well.

**Comment by luddaniel** [comment]
@scolapasta release node is added

**Review by scolapasta — APPROVED** [review]

**Pull request merged**
