### PR TITLE
Allow optional Croissant exporter to replace JSON-LD <head> content

### PR DESCRIPTION
**Pull request by jp-tosca**
**What this PR does / why we need it**:

When the new [Croissant PR](https://github.com/gdcc/dataverse-exporters/pull/4) is ready it will replace the content on the header for LD-JSON, this PR will make that the dataset page check for croissants, and if not found it will provide the old LD-JSON, this will preserve current functionality and allow simply drop the croissant Jar on the exporters folder. 

**Which issue(s) this PR closes**:

Partially closes # https://github.com/IQSS/dataverse/issues/10341

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:

**Additional documentation**:

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
@jp-tosca from discussion in tech hours just now, I'd say this PR is close.

Can you please add a release note snippet?

We might want a different title. "Allow optional Croissant exporter to replace JSON-LD `<head>` content"?

**Comment by jp-tosca** [comment]
@pdurbin done 🚀

**Review by pdurbin — APPROVED** [review]
Looks good. Approved.

I've been running this on my dev3 server and it works fine. The only thing to be aware of is that if the Croissant exporter throws an error, the older format (Schema.org JSON-LD) is shown in the `<head>` instead. I think this is ok.

**Review by scolapasta — APPROVED** [review]

**Comment by pdurbin** [comment]
Works great! Merging!

**Pull request merged**
