### PR TITLE
7134 errorhandlers refactored - code only

### LINKED ISSUE #7134: Error Handling: Multiple server.log errors indicating http 406 Not Acceptable
Seeing this in the logs, without tying it to a specific user action, though I am testing the download all api:

[2020-07-22T08:52:30.214+0000] [Payara 5.201] [SEVERE] [] [edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler] [tid: _ThreadID=92 _ThreadName=http-thread-pool::jk-connector(5)] [timeMillis: 1595407950214] [levelValue: 1000] [[
Uncaught REST API exception:
Incident: 39be6b43-cbbf-4dc9-a19a-484f413872a3
URL: https://dataverse-internal.iq.harvard.edu/api/v1/datasets/export?exporter=dcterms&persistentId=doi%3A10.70122%2FFK2%2FEVQ2OH
Method: GET
javax.ws.rs.NotAcceptableException: HTTP 406 Not Acceptable

@qqmyers Has made the following comments:
ThrowableHandler was added prior to #7085. When it was added, it stopped the default handing for exceptions such as javax.ws.rs.NotAcceptableException . What #7085 did was to add more exception/http code-specific handlers to manage the ones Dataverse source throws so that they don't get caught be the new default ThrowableHandler. My guess is that javax.ws.rs.NotAcceptableException is being thrown by the framework code rather than Dataverse source code, so I didn't add a specific handler for it. The fix is probably to just add yet-another handler for this specific exception and just send a 406 response as intended. The Redirect handler is probably a good example.

### PR DESCRIPTION
**Pull request by poikilotherm**
NOTE: this is a successor to PR #7136 as requested by @scolapasta, containing the code only.

**What this PR does / why we need it**:

- This refactors the API error handlers to be more relaxed about non-special-treatment Jersey exceptions.
- It also removes boilerplate and duplicated code from the package.
- It takes care of a standardized response format for errors (which should be adapted in other places to be consistent throughout our beloved API).
- It streamlines the logging of exceptions by enabling debugging and proper parsing in log analysis.

**Which issue(s) this PR closes**:

Closes #7134

**Special notes for your reviewer**:

I do hope the scope is not to big. I did not change the remaining two exception handlers for JSON and constraints to keep it smaller. Happy to change those if you think that makes sense.

One might also argue that special messages for Error 403 and 405 are not of much use. Happy to delete those.

I could also switch the Jersey Error 500 message to be the same as in ThrowableHandler.

The 302 and 307 were added because sometimes you might want to see a proper message via API, for example when you don't auto-follow redirects with `curl` et al.

I'm not sure if we should add a comment about the logging to the docs.

**Suggestions on how to test this**:

After deployment:
- Try debugging verbosity: `asadmin set-log-levels edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler=FINEST` and go for a 404 error
- Not sure how to generate a 500 error...
- A 404, 405 and 406 are easy to test
- A 302/307 is not commonly used in Dataverse. The only place is for ZIP downloads. So to test this, you'll have to enable those. I created a unit test for this during development, but deleted it as it wasn't of that much use...
- No idea how to trigger a 503 error in Jersey...

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

Ah API isn't classic UI, so let's say no.

**Is there a release notes update needed for this change?**:

Nope.

**Additional documentation**:

None.

### CODE REVIEW

**Comment by kcondon** [comment]
@poikilotherm I'm still seeing the 406 errors:
[2020-08-10T20:00:42.722+0000] [Payara 5.201] [SEVERE] [] [org.glassfish.jersey.server.ServerRuntime$Responder] [tid: _ThreadID=97 _ThreadName=http-thread-pool::jk-conn
ector(2)] [timeMillis: 1597089642722] [levelValue: 1000] [[
  An exception has been thrown from an exception mapper class edu.harvard.iq.dataverse.api.errorhandlers.WebApplicationExceptionHandler.
java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
        at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:198)
        at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:66)
        at edu.harvard.iq.dataverse.api.util.JsonResponseBuilder.requestContentType(JsonResponseBuilder.java:118)
        at edu.harvard.iq.dataverse.api.errorhandlers.WebApplicationExceptionHandler.toResponse(WebApplicationExceptionHandler.java:76)
        at edu.harvard.iq.dataverse.api.errorhandlers.WebApplicationExceptionHandler.toResponse(WebApplicationExceptionHandler.java:24)
        at org.glassfish.jersey.server.ServerRuntime$Responder.mapException(ServerRuntime.java:528)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:403)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)

Not sure what is causing it but might be in export since I had just published the dataset. I was also just creating a new one but had not saved yet, just opened the edit form.

**Comment by kcondon** [comment]
@poikilotherm In the spirit of not following instructions and acting randomly, I have started creating a dataset in the UI, modified the host dv so it is invalid and not completed any required fields other than title, then saved. Big stack traces in log, ui kind of stuck in grayed out view. On Demo, form validation catches it and presents error to user. Not sure whether it is related to these changes or not.

**Comment by kcondon** [comment]
@poikilotherm After discussing with Jim, I understand these error handlers are for REST api only and that the UI, though it may call same underlying code, does not follow the same error handling path. So, I will focus on API errors here and maybe open a new issue for UI behavior I'm seeing.

**Comment by poikilotherm** [comment]
Thx @qqmyers for handling this. Was a bit late yesterday for me... :wink:

I'm fine with returning a JSON null value, although it's debatable if one would rather exclude the field from the response. Let's stick with it as is now :+1: 

@kcondon are any problems remaining with the 406 errors or all set now? (I assume as you merged, but wanted to make sure everything is fine now...)

**Comment by kcondon** [comment]
@poikilotherm Everything is set for now, thanks.

**Pull request merged**
