### PR TITLE
CVOC : add HTTP request headers (Ontoportal integration)

### LINKED ISSUE #10316: Feature Request/Idea: Add new parameter "headers" into :CVocConf
**Overview of the Feature Request**
The proposal of the issue is to permit HTTP headers customization with external controlled vocabulary services, managed via via the `:CVocConf` setting. This headers will be used when Dataverse call external vocabulary services (HTTP requests).

**What kind of user is the feature intended for?**
Sysadmin who configure `:CVocConf` setting.

**What inspired the request?**
This is related to issue https://github.com/IQSS/dataverse/issues/9276 and the [Google group discussion](https://groups.google.com/g/dataverse-community/c/4eTd3kfJeBU/m/gcgjM1ZXAAAJ)

**What existing behavior do you want changed?**
Adding a new parameter `headers` into JSON configuration of `:CVocConf` setting, like below :
```json
[{
        "field-name": "compoundDemo",
        "term-uri-field": "compoundDemoTermURI",
        "headers": {"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0"},
        "...": "..."
}]
```
`User-Agent` is mentioned only for example. The idea is to configure any HTTP headers used in HTTP requests to external vocabulary services.

**Any open or closed issues related to this feature request?**

- Issue https://github.com/IQSS/dataverse/issues/9276
- PR https://github.com/IQSS/dataverse/pull/10145
- [Google group discussion](https://groups.google.com/g/dataverse-community/c/4eTd3kfJeBU/m/gcgjM1ZXAAAJ)
- Issue gdcc/dataverse-external-vocab-support#18

### PR DESCRIPTION
**Pull request by jeromeroucou**
**What this PR does / why we need it**:

Add HTTP headers customization for [:CVocConf](https://guides.dataverse.org/en/latest/installation/config.html#cvocconf) settings. This is needed for Ontoportal integration as a external vocabulary services, which required API KEY provided by HTTP request headers.

**Which issue(s) this PR closes**:

Closes #10316 

**Suggestions on how to test this**:

Add `:CVocConf` to a external vocabulary service, with `header` customization : 
```
"headers": {
    "Accept": "application/xml",
    "Cache-Control": "no-cache"
}
```
Replace `XXX` below by the external vocabulary service protocol configured.

Verify if `span[data-cvoc-protocol="XXX"][data-cvoc-headers]` in advanced search page and dataset page (with metadata tab open) have the configuration previously configured. Verify if `input[data-cvoc-protocol="XXX"][data-cvoc-headers]` in edition dataset page have also the configuration.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

Docs:

 - https://dataverse-guide--10331.org.readthedocs.build/en/10331/installation/config.html#cvocconf
 - https://github.com/gdcc/dataverse-external-vocab-support/pull/19/files

### CODE REVIEW

**Review by qqmyers — APPROVED** [review]
Looks good. Note I asked for a combined release note in #10404 about the overall changes to the CVOC syntax/mechanism. This PR is matched by a doc/schema update over in https://github.com/gdcc/dataverse-external-vocab-support/pull/19.

**Comment by pdurbin** [comment]
This pull request is in need of documentation. It probably shouldn't have been approved.

But I'll add what I can @jeromeroucou while I'm testing it.

I'll also merge from develop to get the latest code.

**Comment by pdurbin** [comment]
@jeromeroucou I don't have permission to push to your branch:

```
$ git push Recherche-Data-Gouv 10316_cvoc_http_headers
ERROR: Permission to Recherche-Data-Gouv/dataverse.git denied to pdurbin.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can you please...

- merge the latest from develop into your branch
- add documentation for the future version of https://guides.dataverse.org/en/6.2/installation/config.html#cvocconf
- add a short release note snippet at `doc/release-notes/10316_cvoc_http_headers.md` (see https://guides.dataverse.org/en/6.2/developers/version-control.html#writing-a-release-note-snippet )

**Comment by qqmyers** [comment]
FWIW: There is documentation in https://github.com/gdcc/dataverse-external-vocab-support/pull/19/files

**Comment by qqmyers** [comment]
FWIW: There is a combined release note in #10404. There is no documentation of the contents of the Cvoc conf setting in the guides as it references the repository with all of the scripts and the schema etc.

**Comment by pdurbin** [comment]
@jeromeroucou no pressure, but there's a box you can check to allow edits:

Screenshot 2024-04-16 at 5 06 31 PM

**Comment by jeromeroucou** [comment]
Hi @pdurbin 

I merge develop branch and add a minimal release note snippet. But I doesn't have the checkbox "Allow edits by maintainers". Is it related to [this discussion](https://github.com/orgs/community/discussions/5634) ? If needed, I'll verify to allow you to push on `dataverse` project on Recherche-Data-Gouv organization.

**Comment by pdurbin** [comment]
> FWIW: There is a combined release note in #10404. There is no documentation of the contents of the Cvoc conf setting in the guides as it references the repository with all of the scripts and the schema etc.

A combined release note yes, but nothing at the future version of https://guides.dataverse.org/en/6.2/installation/config.html#cvocconf

I'm not very happy with this situation that there is basically no documentation in the guides proper. Pull requests like this one are changing the behavior of the main app.

I'm not picky about where in the guides the documentation goes. Would you prefer it in https://guides.dataverse.org/en/6.2/admin/metadatacustomization.html#using-external-vocabulary-services than https://guides.dataverse.org/en/6.2/installation/config.html#cvocconf ?

@jeromeroucou thanks for merging the latest from the develop and adding a release not snippet. I think the lack of docs is the last thing (though I haven't tested anything).

As for giving me push access to your entire fork, I didn't realize that's what I was asking for. I always assumed checking that box (which you don't have!) allowed me to push to that specific branch, not the entire repo.

**Comment by qqmyers** [comment]
I have to suggested changes and I also can't see how to commit to or create a PR against your branch. [f4da07d](https://github.com/IQSS/dataverse/commit/f4da07d15df95d2a9e903dd63c30c6f35a830870) puts in a sleep to address a failing test and [fa4a03c](https://github.com/IQSS/dataverse/commit/fa4a03cb023bbebe2464c02d15d5d312c4306bcd) notes that adding headers is now allowed in the docs (also notes we have an ROR example script along with SkosMos and ORCID these days.

**Comment by pdurbin** [comment]
@qqmyers I would suggest making a PR into this PR, like I did:

- https://github.com/Recherche-Data-Gouv/dataverse/pull/4

**Comment by qqmyers** [comment]
For some reason, Recherche-Data-Gouv isn't showing as a possible target when I try to make a PR: https://github.com/IQSS/dataverse/compare/develop...GlobalDataverseCommunityConsortium:dataverse:10316_cvoc_http_headers_QA_changes?expand=1 . I'm not sure why.

**Comment by pdurbin** [comment]
@qqmyers I had to hack no the URL like this:

https://github.com/Recherche-Data-Gouv/dataverse/compare/10316_cvoc_http_headers...IQSS:dataverse:10316-docs

**Comment by qqmyers** [comment]
OK - that worked - I was able to make PR #5. Thanks!

**Pull request merged**
