### PR TITLE
5303 termsofuse

### PR DESCRIPTION
**Pull request by JayanthyChengan**
## Related Issues

- connects to #5303 

## Pull Request Checklist
 - Merged latest from "develop"  branch

### CODE REVIEW

**Comment by pdurbin** [comment]
@JayanthyChengan heads up that this pull request has merge conflicts, but just in the docs. This file:  doc/sphinx-guides/source/installation/config.rst

**Comment by JayanthyChengan** [comment]
@pdurbin - I haven't implemented as mentioned in the comment https://github.com/IQSS/dataverse/issues/5303#issuecomment-439196523 by @scolapasta .  I will do it and submit PR again.  Thanks

**Comment by pdurbin** [comment]
@JayanthyChengan oh, I didn't realize you'll be taking a different approach. Ok. Thanks! 😄

**Comment by pdurbin** [comment]
@JayanthyChengan hi! Should this pull request be closed in favor of pull request #6042?

**Comment by JayanthyChengan** [comment]
@pdurbin - Yes, I am closing this PR.

**Pull request closed without merging**
