### PR TITLE
5274 strip aws

### LINKED ISSUE #5274: Stripping AWS Mail component with TrueZIP blocks packaging for docker images
Dear devs,
Dear @bsilverstein as the one who wrote the code for #3921,

while working on #4172, I am crafting a new Maven profile to generate smallest possible Docker images based on the [payara 5 server-full image](https://hub.docker.com/r/payara/server-full) using https://dmp.fabric8.io.

As I want to make things really small, I don't want to bundle the dataverse dependencies within the WAR file, but create a small WAR _without_ all deps, containing only classes and ressources. The deps get moved in by copying them the `/lib` of the Glassfish/Payara domain (so they are kind of "provided" scoped in Maven terminology). (For those interested in Docker: this should provide us with smaller layer changes and smaller hub transfers!)

The stripping of the mailing stuff from the AWS SDK makes this hard to achieve in two ways: a) I would to fiddle around with this, too and b) the TrueZIP plugin simply fails as I don't build the WAR with deps inside and it is not easy to skip it in a profile without making a mess in the `pom.xml`...

Back in #3921 where all of this was introduced, there has been a pointer to the [AWS dev docs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html#configuring-maven-individual-components) about using individual components.

Did you guys ever try to get that rolling? If not: maybe this would be the perfect time to do so now... Willing to contribute on this. :smile: 

----
This is related to a question I made on IRC ([see logs](http://irclog.iq.harvard.edu/dataverse/2018-11-05#i_77735)).

EDIT:
@pdurbin suggested some clarification on IRC.

The `pom.xml` plugin section I would like to see removed:

```diff
-            <!-- v4.8: The truezip-maven-plugin below deletes two copies of a file that the AWS SDK bundle
-            includes called javamail.providers which breaks system emails. TODO: make our own AWS SDK without Amazon SES.
-            - bsilverstein 8/8/2017 -->
-            <plugin>
-                <groupId>org.codehaus.mojo</groupId>
-                <artifactId>truezip-maven-plugin</artifactId>
-                <version>1.1</version>
-                <executions>
-                    <execution>
-                        <id>remove-javamail-providers-from-exploded</id>
-                        <goals>
-                            <goal>remove</goal>
-                        </goals>
-                        <phase>package</phase>
-                        <configuration>
-                            <fileset>
-                                <directory>target/dataverse-${project.version}/WEB-INF/lib/aws-java-sdk-bundle-${aws.version}.jar/META-INF</directory>
-                                <includes>
-                                    <include>javamail.providers</include>
-                                </includes>
-                            </fileset>
-                        </configuration>
-                    </execution>
-                    <execution>
-                        <id>remove-javamail-providers-from-war</id>
-                        <goals>
-                            <goal>remove</goal>
-                        </goals>
-                        <phase>package</phase>
-                        <configuration>
-                            <fileset>
-                                <directory>target/dataverse-${project.version}.war/WEB-INF/lib/aws-java-sdk-bundle-${aws.version}.jar/META-INF</directory>
-                                <includes>
-                                    <include>javamail.providers</include>
-                                </includes>
-                            </fileset>
-                        </configuration>
-                    </execution>
-                </executions>
-            </plugin>
```

And something that needs to be changed (and complemented by some more stuff):

```diff
         <dependency>
             <groupId>com.amazonaws</groupId>
-            <artifactId>aws-java-sdk-bundle</artifactId>
+            <artifactId>aws-java-sdk-s3</artifactId>
             <version>${aws.version}</version>
         </dependency>
```

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
@donsizemore asked me to reduce the WAR size file and I wanted to this for a long time anyway.
Now as we move to Payara 5, this is finally possible. This PR reduces the WAR size from 205 MB to 134 MB.

**Which issue(s) this PR closes**:

Closes #5274

**Special notes for your reviewer**:
No big changes. Removed completely unused `ehcache` dependency.
I searched the code base for other AWS SDK (besides S3) usages, but found none.

**Suggestions on how to test this**:
The whole ZIP file mangling was introduced to make mailing work. This should be tested to ensure it works.
The S3 storage driver should be tested to work, too, as the SDK version moved from 1.11.172 (2017) to 1.11.762 (2020).

**Does this PR introduce a user interface change?**:
Nope.

**Is there a release notes update needed for this change?**:
Nope.

**Additional documentation**:
I'm sure @donsizemore is happy to help testing :wink:

### CODE REVIEW

**Comment by donsizemore** [comment]
The integration test suite threw a number of failures on this PR because the PR is intended for Payara 5, and Jenkins is still running Glassfish4 until I get the go-ahead to flip the switch.

I manually ran the same branch through EC2 and everything passed except testUningestFileViaApi, which is being handled in #6821

**Comment by poikilotherm** [comment]
@pdurbin please see the history of #5274 about the incompatibility with GF 4.1. It was all about Jackson and S3 only working with the Amazon bundled version etc. New apps server, all set.

**Comment by poikilotherm** [comment]
I just saw this branch now has conflicts since the merge of #6818 
I'll resolve those and push an updated branch.

**Comment by kcondon** [comment]
@poikilotherm This works -S3, zip file. Wasn't sure what you meant when you'd said: "The whole ZIP file mangling was introduced to make mailing work. This should be tested to ensure it works."

**Comment by poikilotherm** [comment]
Hey @kcondon, in the AWS SDK was a properties file for AWS mail services. This was found by scanning the WAR when deploying and broke mail delivery for installations. 

That's why that file has been removed from the WAR. Mangling happend after packaging with a Maven ZIP plugin, which is now removed from the POM.

So the mail delivery should be tested to be sure it works and no other strange things happen.

**Comment by kcondon** [comment]
@poikilotherm OK, mail delivery has been tested and have done general smoke testing as well. I think we're good.

**Pull request merged**
