### PR TITLE
style(docs): make permanent headerlink reappear in nice look #8642

### LINKED ISSUE #8642: Guides: make permalinks to guides section headers reappear
**Overview of the Feature Request**

I need to copy the link to a guides section quite often. The clickable headers are only usable to scroll back to top. I want to have the option to copy a permalink to the section without scrolling back to top.

**What kind of user is the feature intended for?**

Everyone using the guides.

**What inspired the request?**

The UX is just bad when nowadays every header in READMEs etc has a permalink. The non-working links even made it into the guides as links, because we do not use the `autosectionlabel` extension and sometimes people just want to link to sth. (grep for `#id` in the sources to see these links)

**What existing behavior do you want changed?**

Sphinx adds anchors (`<a>`) for every header by default. This are hidden with CSS `display:none` in `_static/docsdataverse_org.css`.
The default icon is `¶`.

**Any brand new behavior do you want to add to Dataverse?**

- Add [`sphinx-icon` extension](https://sphinx-icon.readthedocs.io/en/latest/) to support Font Awesome
- Use a [pretty link icon](https://fontawesome.com/v5/icons/link?s=solid) from Font Awesome for the header link icon (or another one, I don't care). (Or go with a simple `#`...)

grafik

- Make it pretty with CSS (maybe different color, sizing, etc)

**Any related open or closed issues to this feature request?**
None I am aware of.

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
Being able to copy permalinks from the guides without scrolling to top first makes using the guides much easier.

**Which issue(s) this PR closes**:

Closes #8642 

**Special notes for your reviewer**:
THIS PR IS BASED ON #8650 / #8651, so these should be merged first. Thx!

If you don't like the color, the symbol or the size, please propose changes. Please note that the anchors only appear during "mouse over" of a heading and are hidden otherwise (see below).

**Suggestions on how to test this**:
Take a look at the screenshot or take a look at the RTD based preview (click on the "Details" link within the checks status box)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
grafik

**Is there a release notes update needed for this change?**:
Nope.

**Additional documentation**:
None.

### CODE REVIEW

**Comment by pdurbin** [comment]
> or take a look at the RTD based preview (click on the "Details" link within the checks status box)

Or here's a direct link to the "mail domain" example in the screenshot: https://dataverse-guide--8647.org.readthedocs.build/en/8647/admin/mail-groups.html

**Comment by poikilotherm** [comment]
@pdurbin who needs to review this? Shall this really wait  until next sprint? (Dunno why it wasn't added to review this week :shrug: )

**Comment by scolapasta** [comment]
@poikilotherm this did not make into this sprint because we are trying a new process where new external PRs don't immediately intterrupt the currrent sprint cadence. For now, we will take x PRs and put them into review at the beginning of a sprint. For this sprint, x was 10 and I tried to choose 1-2 for different contributors. In this case, this PR said it was dependent on the other and since I didn't know when it would get merged, I opted to leave it out.

That said, mid sprint, if we pur moving along and have merged (or removed, do to non trivial rework being needed) the majority of the external PRs, there may be room to move some additional ones. This one is. a candidate for that. If it doesn't I will make sure it is definitely in the next sprint.

**Review by pdurbin — APPROVED** [review]
I ran the code and I'm approving this but I'd like to note that I got this error when running `make html`:

```
$ make html
sphinx-build -b html -d build/doctrees  -W source build/html
Running Sphinx v3.5.4
loading translations [en]... done

Extension error:
Could not import extension sphinxcontrib.icon (exception: No module named 'sphinxcontrib.icon')
make: *** [html] Error 2
```

To me, this means we should all run `pip install -r requirements.txt` to pick up the new "sphinx-icon" dependency.

Our docs on how to get Sphinx installed were woefully out of date so I updated them to indicate that `requirements.txt` should be used to install dependencies. I also did some various cleanup while I was in there.

I must say that the new anchors are very nice! I plan to use them basically all the time. Thanks, @poikilotherm!

**Comment by kcondon** [comment]
Tested, this works but waiting on continuous integration.

**Comment by pdurbin** [comment]
> To me, this means we should all run `pip install -r requirements.txt` to pick up the new "sphinx-icon" dependency.

Now that we've merged this PR, I just emailed the dev list about this: https://groups.google.com/g/dataverse-dev/c/fZpTQYQKR0g/m/DQTARER7AwAJ

**Pull request merged**
