### PR TITLE
#2833 Add custom text to Publish Popup

### PR DESCRIPTION
**Pull request by sekmiller**
Adds a customizable text to the popup shown to a user when a dataset is published

### CODE REVIEW

**Comment by sekmiller** [comment]
Related Issues:
#2833

RFI Checklist

- [x]  Functionality completed as described in Issue Ticket
- [ ]  Dependencies, risks, assumptions in FRD addressed
- [ ]  Unit tests completed
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [ ]  Documentation completed
- [x]  All code checkins completed
<hr>
- [ ]  Code review completed or waived
- [ ]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

**Comment by kcondon** [comment]
Passing back to Mike to resolve the remaining popup issue in #2833

**Comment by mheppler** [comment]
Fixed scroll bar issue with Publish Dataset popups on dataset pg.

Sending pull-request and issue back to @kcondon for testing.

**Comment by kcondon** [comment]
Passing to Liz for User testing.

**Comment by pdurbin** [comment]
@eaquigley as I mentioned I'd like to use https://beta.dataverse.org soonish for working on #2937. Please let me know when it is available.

**Pull request merged**
