### PR TITLE
8838-cstr

### PR DESCRIPTION
**Pull request by cheneyfeng3**
@pdurbin @qqmyers  I recreate a branch name to initiate this merge. Can this resolve the conflict?

### CODE REVIEW

**Comment by jggautier** [comment]
Hi all. @scolapasta asked me to take a look at this PR and make sure the changes are the same as what's in the previous PR at https://github.com/IQSS/dataverse/pull/8913. The changes look the same to me. I just looked at the "Files changes" pages of each PR and see that the same files are changed in the same ways in both PRs.

The only question I have is about how the new ID type will appear in the dropdown. I think, and I think @qqmyers confirmed, that because the ID type in the citation.properties file is in all caps (CSTR), that's how it will appear in the GUI's metadata form, even though the ID type in the citation.tsv file is in lowercase (cstr).

Is this right? @cheneyfeng3, was making CSTR in the citation.properties file intentional?

I suggested keeping the ID type all lowercase, at least for now, since most of the other ID Types in the dropdown are all lowercase.

**Comment by cheneyfeng3** [comment]
@scolapasta @jggautier 
We thought lowercase was fine, so we changed the Code. Please review.

**Comment by jggautier** [comment]
Thanks so much @cheneyfeng3! We'll review today.

**Review by jggautier — APPROVED** [review]
Thanks for changing the ID type name to lowercase @cheneyfeng3.

**Comment by jggautier** [comment]
I added release notes. Since I see that one of the files changed looks like code that creates the Schema.org metadata export, I mentioned that CSRT IDs added in the metadata will be included in the Schema.org exports.

**Comment by jggautier** [comment]
The release note includes required steps for updating the Citation metadatablock. I copied them from [the release note included in the citation field improvements PR](https://github.com/IQSS/dataverse/pull/8708/files#diff-013e74248458ff95f3e18db4c54d9ee1b01d15fea4394f00d6e54c828874208a), which the section in the guides about reloading a repository's existing metadata block.

**Comment by kcondon** [comment]
Hi @cheneyfeng3 I'm about to build and test this but the version number has changed. Would you please refresh this branch from develop so that I can build? Thanks.

**Comment by pdurbin** [comment]
> please refresh this branch from develop

Done! In 2bb8291.

**Comment by jggautier** [comment]
About the release notes, there's a command in the upgrade instructions that references the release's version number. But I put #.# as a placeholder. Is the version number for this release known?

**Comment by pdurbin** [comment]
@jggautier as of this writing the next release is 5.13: https://github.com/IQSS/dataverse/milestone/107

That said, the release note snippet doesn't have to be perfect. Placeholders are fine. We can insert the actual release number at release time.

**Comment by kcondon** [comment]
The basic field value for cstr works fine. I do have some questions on export though. I'm not sure which exports should handle this cstr field. Testing shows the following:
Fields that export the ctr field: dc-terms, openaire, json, oai_ore. Fields that do not export it: ddi, ddi html codebook, datacite, schema.org
I'll do some more testing with existing values on previous build for comparison.

**Comment by jggautier** [comment]
Thanks @kcondon. I wrote in the issue at https://github.com/IQSS/dataverse/issues/8838 that "the CSTR ID will also have to be included in several metadata exports that already include what depositors enter in the ID Type and ID Number fields."

I thought this slipped through the cracks so I'm glad to hear the IDs are added to some of the exports. I'm not sure why the DDI.xml, DDI HTML, and Schema.org exports don't include the CSRTs. But I'd be happy to ping the contributor and help.

It shouldn't be added to the DataCite export for now. The DataCite schema requires more information (the type of relationship), so I'd put it off until we've resolved the issues related to letting depositors/curators/repository managers indicate the type of relationships between their deposits and other research objects.

**Comment by qqmyers** [comment]
Adding this  cstr identifier type should not change which exports the field shows up in. I.e. if you use DOI instead, you should see that in the same exports.

**Comment by kcondon** [comment]
Yes, testing on current version using the ark value of the field shows the exported formats are the same, so preexisting issue: dc-terms: yes, ddi: no, datacite: no, ddi html codebook: no, json: yes, 

@jggautier thanks for commenting. I did not full understand the first part of that requirement but was responding to the last part: The CSTR ID will also have to be included in several metadata exports that already include what depositors enter in the ID Type and ID Number fields: DDI, DC Terms, and OpenAIRE.

So, I tested those formats and DDI wasn't showing it. I'm still not sure what this sentence means, "The CSTR ID will also have to be included in several metadata exports that already include what depositors enter in the ID Type and ID Number fields"

**Comment by kcondon** [comment]
@jggautier has said export can be improved in a separate issue and the scope of this pr appears to be simply to add cstr to the id type list. That works fine so will merge. Thanks for clarifying everyone and apologies for delaying this further.

**Comment by xiaya2309** [comment]
Hello @jggautier
Thank you very much for your help in moving forward with adding CSTR to the list of associated identifiers.
We see that the code has been merged into the branch.
Does this mean this feature will be available in the next release?
Would you mind telling us how long it will be before users see and use CSTR on the page?
We would like to share this good news with our users.
If you have any questions, please feel free to contact us.
Thank you very much for your help!
Have a good day!

**Comment by jggautier** [comment]
Hi @xiaya2309. Yes, it looks like it'll be available in the next release. I'm not sure when the next release will be available. It depends on how soon the other changes in this upcoming release are finished, and I'll have to defer to others working on the Dataverse team to estimate that.

After the release is available, it will have to be applied to the repositories that use the Dataverse software, and then depositors and others will be able to enter related publication metadata that includes CSTR identifiers. Usually, releases are applied to the Harvard Dataverse Repository within a week of the release becoming available.

Thanks for your patience in adding this to Dataverse!

**Comment by pdurbin** [comment]
@xiaya2309 we don't have a predictable release schedule but we usually suggest simply looking at how often previous releases dropped to get a sense of timing: https://github.com/IQSS/dataverse/tags . Hope that helps! Thanks for the contribution!

**Pull request merged**
