### PR TITLE
Proper detection of IP addresses in JSF context

### PR DESCRIPTION
**Pull request by michbarsinai**
# RFI Checklist

_**Before** submitting the pull request, fill out sections (1.) Related Issues and (2.) Pull Request Checklist._

### 1. Related Issues

- #1380 IP Groups: Define and enforce IP Group scope of permissions in application
- #3273 Unpublished DvObjects' cards don't show for IpGroups contained within a group that has permission to view them.
- #3275 My Data: Does not display access via IP Groups permissions
- #3376 Attempting to create an IP Group with a duplicate name causes an error rather than updates it.

---
### 2. Pull Request Checklist

- [x]  Functionality completed as described in FRD
- [x]  Dependencies, risks, assumptions in FRD addressed
- [x]  Unit tests completed (None available, fixing the issue required accessing the JSF context)
- [x]  Deployment requirements identified (e.g., SQL scripts, indexing)
- [x]  Documentation completed
- [x]  All code checkins completed

---
### 3. Review Checklist

_**After** the pull request has been submitted, fill out this section._

- [x]  Code review completed or waived
- [x]  Testing requirements completed
- [ ]  Usability testing completed or waived
- [ ]  Support testing completed or waived
- [ ]  Merged with develop branch and resolved conflicts

Connects to #3376.

### CODE REVIEW

**Comment by kcondon** [comment]
Michael, datasets and files are still not working and cannot assign ip groups to explicit groups. I've updated the original ticket.

**Comment by pdurbin** [comment]
@michbarsinai heads up that this pull request now has conflicts that must be resolved before it can be merged.

**Comment by kcondon** [comment]
@michbarsinai , I am able to assign a member role to ipGroup3, all addresses, but cannot navigate directly to an unpublished dv. It does appear in the UI and API as a role assignment. Passing back for comment.

**Comment by djbrooke** [comment]
This came up in the 8/2 Community Call (https://docs.google.com/document/d/1FsXatbbq-F4qwD_w9dqkFXpr2Sd4MqScKevUcHLCVDY/edit).

**Comment by michbarsinai** [comment]
Important: We need to remove the logging of the IP groups detected before merging into `develop`.

**Comment by michbarsinai** [comment]
Over to @kcondon for validating the current behavior. We'll need to validate that the current behavior is correct (or, at least, harmless) prior to merging with dev.
Also prior to merging with dev, some logging has to be removed.

**Comment by pdurbin** [comment]
I just merged the latest from "develop" into this pull request: 00decd4

**Pull request merged**
