### PR TITLE
Faster redeployment for developers, skip deploy, remove version from war in dev

### LINKED ISSUE #9590: Faster turn-around times for devs using containers
Part of the [containerization strategy](https://docs.google.com/document/d/14DHDB24Cp_kzpYqhHCKCtnzOw8_WuLOOONyqJHSsaYM/edit#), [milestone D](https://docs.google.com/document/d/14DHDB24Cp_kzpYqhHCKCtnzOw8_WuLOOONyqJHSsaYM/edit#heading=h.ysp9fn6ri34v).

With #9584 we will recommend stopping, repackaging and start all containers again after code changes. This takes, depending on your local hardware, 60-120 seconds. Investigate in making this faster is the task of this issue.

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
Containers provide a bad DX at the moment with editing XHTML files. This PR enables transfering modified files from the host into the running deployment inside the container.

**Which issue(s) this PR closes**:

- Closes #9590

**Special notes for your reviewer**:
Simply start the containers and, when using Netbeans, edit an XHTML file. After a page reload the change should be picked up without any manual intervention. It does not require you to run Payara from Netbeans.

Note: as this touches the base image, you will need to package this locally first and build your app image on top of it!

**Suggestions on how to test this**:
See above.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope

**Is there a release notes update needed for this change?**:
Nope

**Additional documentation**:
https://dataverse-guide--9959.org.readthedocs.build/en/9959/container/dev-usage.html

### CODE REVIEW

**Comment by pdurbin** [comment]
I'm getting an error running `mvn -Pct -f modules/container-base install`: [err.txt](https://github.com/IQSS/dataverse/files/13378652/err.txt)

**Comment by poikilotherm** [comment]
It's the driver flag again! 🫣

**Comment by cmbz** [comment]
2024/01/31
Moved back to This Sprint until it can be addressed.

**Comment by pdurbin** [comment]
My plan is to work on this after we get the following PR merged:

- #10273

**Comment by pdurbin** [comment]
This was waiting on #10273 getting merged, which is done. I'll work on resolving merge conflicts.

**Comment by pdurbin** [comment]
I hacked quite a bit on the docs in this PR and tested the functionality in Netbeans. The new "skip deploy" flag is a huge time saver!

I had trouble getting IntelliJ to work which is strange because it worked fine back when I added these docs:

- #10102

I don't have much experience with IntelliJ however so if someone could try the instructions, I'd appreciate it.

By the way, we someday would like to add VS Code into the mix...

- #10156

... but I didn't have any luck getting fast redeploy working months ago.

Please note that we've added a new extension to Sphinx to allow for tabs...

Screenshot 2024-02-13 at 11 09 02 PM

... so you'll need to re-run a pip install. Heads up to @donsizemore that after this PR gets merged, we'll need to update the Jenkins server as well.

**Review by pdurbin — APPROVED** [review]
Works great. Merging.

I wasn't able to get watchers.xml imported. Not sure what I'm doing wrong.

Also, I got a weird error (below) the first time I tried to deploy but then I killed and removed all containers and tried again and it worked fine.

I've done the Info.java fast redeploy test for both Netbeans and IntelliJ now. I'm happy. Again, will merge.

Oh, and I also did a little doc cleanup along the way, especially the dev guide.

Screenshot 2024-02-23 at 3 07 28 PM

**Pull request merged**
