### PR TITLE
Dataset files API extension for file counts

### LINKED ISSUE #9834: [Spike - API] Extend the Files API to retrieve file counts by type
**Overview of the Feature Request**

We need this API extension to support dataset files tab display data in the new frontend, since the file counts by type are required by the different tab filters and pagination info.

**What kind of user is the feature intended for?**

API User

**What inspired the request?**

- Integrating features in the SPA (https://github.com/IQSS/dataverse-frontend/issues/134)
- https://github.com/IQSS/dataverse/issues/9763#issuecomment-1688420469

**What existing behavior do you want changed?**

None

**Any brand new behavior do you want to add to Dataverse?**

New API endpoint to retrieve file counts by type 

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse-frontend/issues/134

### PR DESCRIPTION
**Pull request by GPortas**
**What this PR does / why we need it**:

Includes new endpoint (/api/datasets/{id}/versions/{versionId}/files/counts) for obtaining file counts based on different criteria (Total count, per content type, per access status and per category name). 

Includes new endpoint (/api/files/{id}/metadata/categories) for updating file categories (by name) for an existing file. If the specified categories do not exist, they will be created.

**Which issue(s) this PR closes**:

Closes #9834 

**Special notes for your reviewer**:

Updating categories can also be done with the existing metadata update endpoint, but the new endpoint has been created to be more practical when it is only necessary to update categories and not other metadata fields.

**Suggestions on how to test this**:

Upload test files to a dataset version, categorize and embargo some, and ensure the counts are correct by calling the new counts endpoint:

`curl -H "X-Dataverse-Key: <YOUR_API_KEY>" -X GET "http://localhost:8080/api/v1/datasets/:persistentId/versions/:latest/files/counts?persistentId=<DATASET_PID>"`

For the new categories endpoint, call it and ensure categories are updated on the UI.

```
curl -H "X-Dataverse-key:<YOUR_API_KEY>" -X POST \
    -F 'jsonData={"categories":["Category1","Category2"]}' \
    "http://localhost:8080/api/files/<FILE_ID>/metadata/categories"
```

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No

**Is there a release notes update needed for this change?**:

Yes

**Additional documentation**:

None

### CODE REVIEW

**Comment by scolapasta** [comment]
@qqmyers I'll move this milestone 6.1 issto to "ready for Review", but I'm assigning you first so that you can handle the 6.0 merge and address any EE10 issues.

**Review by landreev — APPROVED** [review]
Looks good!

**Comment by kcondon** [comment]
@GPortas This looks good. One thing I noticed is the tabular tags are not counted under categories. Is this expected? Categories currently are file tags, which are separate from tabular file tags. It is confusing, they seem the same but kind of mean different things. File tags are categories, sure, tabular tags were meant to indicate what type of data as a clue to future processing apps/functionality but never really was used that way. They look similar in the UI. Otherwise, this can be merged.

**Comment by GPortas** [comment]
@kcondon 

I had that same doubt when I developed these changes. If I'm not mistaken, tabular tags are not a very relevant feature within the UI, that is why they do not have an associated filter, as is the case for the "normal" tags.

Since the SPA is not going to change this behavior, I have not considered filtering by tabular tags via API. In any case, if at some point we find that filtering by tabular tags is useful for use cases other than SPA, we can add this option to the endpoint.

**Comment by kcondon** [comment]
@GPortas I understand, this would be new behavior. However, I would say it isn't implemented in the UI currently not because it is not relevant but because tabular tags, though essentially just file tags/categories, is implemented separately, in a way that was often overlooked when implementing tag-related features. I can check with others -Leonid was of the opinion on counts that it should be counted. I have not yet asked others on UI. This is in part a policy question -would we ever change the behavior of the current implementation if it had a bug? I could see in many cases leaving it unless it was important or easy to change.

**Pull request merged**
