### PR TITLE
improve messaging for ingest failures, file upload #8096

### LINKED ISSUE #7227: File upload: undocumented setting :MultipleUploadFilesLimit (should show in UI)
We have a user creating a dataset with ~2,700 small image files, trying to upload via the web UI. This fails with an error message:

meldung-maximum-number-files-exceeded

Since be78db2 (Dataverse v4.6, 2016), the number of files to upload via Web UI is configurable via database setting `:MultipleUploadFilesLimit`. This hasn't been documented since then. The user guide does not mention a limit, only for ZIP files.

The doc fix is easy, but shouldn't we provide a hint about the configured limit in the upload UI like we do for the size limit? Pinging @TaniaSchlatter as this is UI related.

This might be related to #4818.

### LINKED ISSUE #8096: Improve text & messaging to avoid support tickets when ingest fails due to file format
Since this isn't a bug, provide better notification messages in the UI to users so they understand they don't need to contact us about failed ingests and they understand the failed to ingest message is not shown to users of their data.

### LINKED ISSUE #8205: Add text and messaging to help users know file status when ingest is not attempted due to file size being over the limit
This issue was originally opened for Harvard Dataverse [#132](https://github.com/IQSS/dataverse.harvard.edu/issues/132), but can be addressed for all installations.

There is no message when files fail ingest due to being over the size limit.

This issue is for adding informational text and feedback messaging to the UI to help users know:

- file size limits for tabular data may be different than general file size limits, and
- when a tabular file that exceeded the ingest limit is available but was not ingested, and has limited tabular file features. 

This enhancement will be useful for depositors and anyone uploading to help know the status when a data file is not ingested due to size.

### PR DESCRIPTION
**Pull request by pdurbin**
**What this PR does / why we need it**:

We are trying to soften the messaging around ingest to prevent support tickets. This pull request also improves the messaging on file upload, especially with regard to limits and providing links to information in the guides about tabular ingest.

**Which issue(s) this PR closes**:

- Closes #8096
- Closes #8205 
- Closes #7227

**Special notes for your reviewer**:

None.

**Suggestions on how to test this**:

See release note.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

## Add files on create

Screen Shot 2021-12-14 at 3 31 09 PM

## Add files on edit

Screen Shot 2022-01-04 at 2 00 24 PM

## Improved "failed ingest" messaging (dataset page)

Screen Shot 2021-12-02 at 3 58 55 PM

## Tooltip behavior (greyed out, dark on hover, popup on click)

Screen Shot 2021-12-02 at 3 59 49 PM
Screen Shot 2021-12-02 at 3 59 57 PM
Screen Shot 2021-12-02 at 3 59 39 PM

## Improved "failed ingest" messaging (file page)

Screen Shot 2021-12-03 at 8 18 43 AM

## Email: success only

Screen Shot 2021-12-16 at 12 24 55 PM

## Email: failure only

Screen Shot 2021-12-16 at 12 25 51 PM

## Email: mix of failure and success (as of 55d5ac0710 looks same as "failure only")

Screen Shot 2021-12-16 at 12 27 16 PM

## In-app notification: success

Screen Shot 2021-12-13 at 2 11 30 PM

## In-app notification: failure only or mix of failure and success

Screen Shot 2021-12-13 at 2 11 49 PM

## Add files on edit (dual mode and public only install)

This screenshot is last but relates to the "add files on edit" screenshot above. As part of this pull request, the "Multiple file upload/download methods are available for this dataset" message has been moved to under the "Files" tab (and is now plain text rather than being in a blue info box). The yellow info message "Files are stored on a publicly accessible storage server. – " has not been changed.

Screen Shot 2022-01-04 at 2 02 48 PM

**Is there a release notes update needed for this change?**:

Included.

**Additional documentation**:

Included.

### CODE REVIEW

**Comment by pdurbin** [comment]
@TaniaSchlatter @jggautier and I met this morning and in 5d9a0dd I just made the changes we talked about. I also updated the screenshots above.

This pull request is ready for review so I moved it over.

**Comment by TaniaSchlatter** [comment]
Thanks for the screenshots @pdurbin. All looks good, and I wonder if we can have the text that appears in the top of page in the info alert message on the edit page can appear as text in the File upload page instead. If we are not providing new or contextual info in the top of page message, there is not a reason to have it appear as an info alert.

**Comment by pdurbin** [comment]
@TaniaSchlatter and I just talked through moving text from the blue info alert to inline text. Implemented in a2be27b and I updated the screenshot above. I'm moving this back into review.

**Comment by TaniaSchlatter** [comment]
Looks good! Thanks @pdurbin.

**Review by sekmiller — APPROVED** [review]

**Pull request merged**
