### PR TITLE
clarify the page on docs in the dev guide is for **writing** docs

### PR DESCRIPTION
**Pull request by pdurbin**
People sometimes google for "dataverse documentation" and land on the page about **writing documentation** in the dev guide. See the screenshot below for an example screenshot.

Recently @TaniaSchlatter @scolapasta and I agreed that for external tool makers the title "Building External Tools" is better that "External Tools" because it describes the activity. By the same logic, for documentation writers, "Writing Documentation" is better than just "Documentation". So that's what this pull request is about.

Screen Shot 2019-09-13 at 8 43 08 AM

### CODE REVIEW

**Comment by pdurbin** [comment]
@mheppler oh! Sure! Great idea! Please go ahead and commit to this branch.

**Comment by mheppler** [comment]
@pdurbin had some commit hiccups. Hopefully I didn't mess nothing up. I think I also got `develop` merge in here too. Please take a look and make sure it looks kosher. Here is a screenshot of the new index pg header format.

Screen Shot 2019-09-13 at 4 53 38 PM

**Comment by pdurbin** [comment]
@mheppler hmm, yeah, git strangeness. I might make a fresh pull request with my commit and f1e9659 from you. Thanks!

**Comment by mheppler** [comment]
Also, I noticed the robots.txt for the guides blocks everything. If we want to review how Google is indexing our guides/documentation in their search results, we should open the site up to the Googlebot, provide a sitemap -- which I believe will help resolve the "no description" issue for the index pg (see screenshot in my previous comment).

**Comment by pdurbin** [comment]
Closing in favor of pull request #6169

**Pull request closed without merging**
