### PR TITLE
7423 jms config

### LINKED ISSUE #7423: Move Java Message Service configuration to application
As with JDBC #7418 , we can move the JMS definition to the application. This further reduces the necessary bash glue to install Dataverse or use in containers.

### PR DESCRIPTION
**Pull request by poikilotherm**
**What this PR does / why we need it**:
This PR enables removing the configuration of the Java Messaging System Queue used for ingest from the installer and deploying it from inside the app instead. This greatly reduces the amount of bash glue necessary in containers.

**Which issue(s) this PR closes**:

Closes #7423 

**Special notes for your reviewer**:
The release notes are missing. It's debateable wheter we want people to delete existing queue etc, as those are simply unused, doing no harm to anyone.

**Suggestions on how to test this**:
Just deploy and try ingest. 

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Nope.

**Is there a release notes update needed for this change?**:
Not yet.

**Additional documentation**:
None.

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
If this works, great. I guess I only have two questions:

1. This pull request is marked as "draft". Is it not ready for QA? My guess is that you're waiting for pull request #7422 to get merged.
2. As a potential cleanup step (which I assume is optional) during upgrades, could some values be removed from domain.xml?

**Comment by poikilotherm** [comment]
Hi @pdurbin,
sorry I left this in Code Review.

>  1. This pull request is marked as "draft". Is it not ready for QA? My guess is that you're waiting for pull request #7422 to get merged.
Yes, it would be nice to have #7422 done first. And I need to do some more testing with this.

> 2. As a potential cleanup step (which I assume is optional) during upgrades, could some values be removed from domain.xml?
We can do that. It should be only one `asadmin` call. These things should be added in a release note, which is one of the reasons this is in draft mode.

**Comment by poikilotherm** [comment]
@pdurbin looks like API tests ran smooth on EC2. Do we want people to remove the config from their domain or just leave it there? It doesn't do anything considered harmful, just sitting around as a queue.

**Comment by pdurbin** [comment]
@poikilotherm yes, the API tests are passing: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-7443/7/testReport/

(There were some earlier failures that you, @donsizemore and I talked about but they seem to be unrelated to the code.)

I don't think we need to document how to remove the old config but if you feel differently, please go ahead and put it in a release note. Either way, let's at least have a release note that indicates that config has been moved into code. @kcondon asked to me add something like that last time, which resulted in 7e3498e if you'd like an example.

Finally, please merge the latest from develop. Thanks!

**Review by pdurbin — APPROVED** [review]
Looks good. I didn't run the code myself but they API tests passed on Jenkins.

**Pull request merged**
