### PR TITLE
5055 mimetype internationalization

### PR DESCRIPTION
**Pull request by JayanthyChengan**
## Related Issues

- connects to #5055 

- Merged latest from "develop" [branch]

- I was able to test MimeTypeDisplay.properties in dataset.xhtml (Versions tab).  But not sure about the testcase for MimeTypeFacets.properties

### CODE REVIEW

**Comment by sekmiller** [comment]
Hi @JayanthyChengan 
The getResourceBundle method in BundleUtil does not look for the MimeType files when the filesRootDirectory is set - it only uses the defaultBundleFile, so it's always looking for "Bundle".

**Comment by JayanthyChengan** [comment]
Thanks @sekmiller , corrected getResourceBundle method.

**Comment by mheppler** [comment]
Sorry I am only now getting this feedback in here, as it was just moved to QA...

@JayanthyChengan, I noticed that this PR includes the `MimeTypeFacets.properties` file, which we just updated as part of #5067, in order to fix some capitalization inconsistencies in the facets list (see screenshot). It looks like you already resolved the spacing issue for "données tabulaires" and "données en réseau".

We had "Tabular Data" and "networkdata", so we updated the English file so all the facets are consistent with themselves, as well as with the file types defined in `MimeTypeDisplay.properties` (e.g. "ZIP" and "FITS"). Also, we made a change to `FileUtil.java` that will capitalize the file types applied to those types not defined in `MimeTypeFacets.properties`. With that change, it will introduce inconsistencies with your File Types facets list, where "texte" and "données" are not capitalized.

screen shot 2018-09-20 at 4 36 20 pm

**Comment by JayanthyChengan** [comment]
@mheppler :  Thanks for your notes.  Do we need to wait until #5067 is resolved?

**Comment by JayanthyChengan** [comment]
@sekmiller:  corrected FileUtil.java by importing individual items.  BundleUtil.java looks good

**Comment by sekmiller** [comment]
Great! Thanks!
Sorry about BundleUtil, I was looking at the changes and transposed the pluses and minuses.

**Comment by kcondon** [comment]
@JayanthyChengan Please update this from /develop since version number has changed. Will test right away, thanks.

**Comment by JayanthyChengan** [comment]
@kcondon: merged latest from develop branch

**Pull request merged**
