### PR TITLE
#6156: Footer image for Sub-Dataverse

### LINKED ISSUE #6156: Footer image and CSS customization for Sub-Dataverse
In Dataverse, it is only possible to customize CSS styles and the footer globally. Sometimes we need to add a style or image in the footer to some sub-dataverse. 

Similar to logo image, we add the code that allows administrators to configure an image in the footer and add some CSS style.

image

The footer image is shown above the default Footer and CSS styles are embedded as a separate file.
image

The goal of CIMMYT is to contribute with Dataverse. We would like to share with you the source code for your review and comments.

### PR DESCRIPTION
**Pull request by Gerafp**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- Closes #6156

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by djbrooke** [comment]
Thanks @Gerafp for the PR. Assigning to myself to add some documentation for this.

Can you please put this on an AWS instance (like you did for #6154) so that we can review this more easily? 

Thanks again!!

**Comment by djbrooke** [comment]
@Gerafp, I added the docs, please let us know when the branch is available and we'll review. Thanks!

**Comment by Gerafp** [comment]
> Thanks @Gerafp for the PR. Assigning to myself to add some documentation for this.
> 
> Can you please put this on an AWS instance (like you did for #6154) so that we can review this more easily?
> 
> Thanks again!!

Hi @djbrooke 

Yes, I deploy a instance here
http://ec2-52-203-33-8.compute-1.amazonaws.com:8080
dataverseAdmin
admin1

**Comment by djbrooke** [comment]
Thanks @Gerafp, we'll take a look tomorrow and provide feedback!

**Comment by djbrooke** [comment]
@TaniaSchlatter passing your way for a design review. I'm OK with how this implemented as it basically mirrors what we allow for the logo in the header, but feel free to provide design feedback to @Gerafp and @alejandratenorio if you have any. 

@Gerafp, @alejandratenorio, we'll also start a review of the code itself. Thanks again for this contribution!

**Comment by djbrooke** [comment]
Thanks @TaniaSchlatter for discussing the feature and providing documentation feedback!

**Comment by pdurbin** [comment]
@djbrooke I approved this pull request but we **could** use this as an opportunity to refactor the code for both headers and footers and make it possible to set them via API. I believe @TaniaSchlatter recently asked if setting header logos for sample data is possible and it is not currently. Or we can, of course, defer adding these APIs (and API tests) until later.

**Comment by djbrooke** [comment]
Thanks for the review the and the note @pdurbin. Let's move this to QA and not expand it to the API since it's good to go and it meets the use case for the external contributor.

**Comment by kcondon** [comment]
@Gerafp When I deployed this it throws a 500 error, missing column, "logofooter", but I did not see a flyway entry to add this. Can you take a look?

**Comment by pdurbin** [comment]
@Gerafp hi! Two things:

- Here are the docs for our use of Flyway: http://guides.dataverse.org/en/4.16/developers/sql-upgrade-scripts.html . I'm happy to answer any questions here or http://chat.dataverse.org or https://groups.google.com/forum/#!forum/dataverse-dev . It was great talking to you and your team this morning about pull request #6192! 
- Since you're already spinning on Dataverse on EC2, I wanted to mention that I am working with @donsizemore on the ability to run our API test suite within EC2. You can track our progress at https://github.com/IQSS/dataverse-ansible/issues/65 . I *think* I'm close. We recent removed a bunch of sleep statements from the API test suite and I'm hoping that adding a few back in will get the tests passing. Please stay tuned!

**Comment by Gerafp** [comment]
> @Gerafp hi! Two things:
> 
> * Here are the docs for our use of Flyway: http://guides.dataverse.org/en/4.16/developers/sql-upgrade-scripts.html . I'm happy to answer any questions here or http://chat.dataverse.org or https://groups.google.com/forum/#!forum/dataverse-dev . It was great talking to you and your team this morning about pull request #6192!
> * Since you're already spinning on Dataverse on EC2, I wanted to mention that I am working with @donsizemore on the ability to run our API test suite within EC2. You can track our progress at [IQSS/dataverse-ansible#65](https://github.com/IQSS/dataverse-ansible/issues/65) . I _think_ I'm close. We recent removed a bunch of sleep statements from the API test suite and I'm hoping that adding a few back in will get the tests passing. Please stay tuned!

Hi @pdurbin 

Yes, it was great talking with us. I sorry for my poor english, I was nervous.
Thanks, I see the docs for making a SQL Upgrade Scripts for this implementation and submit the changes in this branch @kcondon.

Yes, stay tunned to progress and observations.

**Comment by djbrooke** [comment]
@Gerafp - to repeat @pdurbin, thank you for the contribution and for the call this morning! Let us know when this is ready for us to take another look. I'll move it back to community dev for now.

**Comment by Gerafp** [comment]
> @Gerafp - to repeat @pdurbin, thank you for the contribution and for the call this morning! Let us know when this is ready for us to take another look. I'll move it back to community dev for now.

@kcondon @djbrooke @pdurbin 

We add the SQL Upgrade Scripts  for this implementation.

**Comment by pdurbin** [comment]
@Gerafp there's a space character (" ") in the name "V4.16.0.3__6156- FooterImageforSub-Dataverse.sql" that should be removed. Also, we're about to release 4.17 so the filename will need to change for that reason as well. Please change it to this:

V4.17.0.1__6156-FooterImageforSub-Dataverse.sql

Thanks!

**Comment by djbrooke** [comment]
@Gerafp @pdurbin I made these updates because if we don't get this into 4.17 we'll need to update the filename again. :) Moving to QA.

**Comment by pdurbin** [comment]
@djbrooke sounds good. I changed the .3 to .1 in 1e9abbc

**Comment by pdurbin** [comment]
@kcondon @djbrooke it occurs to me that we should probably test with multiple Glassfish and update http://guides.dataverse.org/en/4.16/installation/advanced.html#multiple-glassfish-servers if necessary. Here's what's written there now with the important bit highlighted in blue:

Screen Shot 2019-10-01 at 10 37 45 AM

**Comment by djbrooke** [comment]
Thanks @pdurbin for discussing. I:

- Updated the script name to 4.16.0.3.... because we plan to include it in 4.17
- I updated the documentation about Flyway to put more emphasis on the naming scheme using the previous version (since this confused me)
- Added the note about multiple glassfish servers that you recommended

**Comment by mheppler** [comment]
Found a few issues in the UI while demoing this feature on the test server that @kcondon set up. Created a new branch at `6156-dv-theme-footer-cleanup` that includes my changes, which I've outlined below, as well as updates from the latest merges to the `develop` branch.

- [x] dataverseFooterName, dataverseFooterTagline, dataverseFooterLink classes in CSS are not used in the XHTML and should be removed
- [x] Fix spacing between new footer and copyright and Dataverse Project logo
- [x] Footer overlaps custom footer
- [x] Add "logo" to image alt text
- [x] Remove Logo Format from footer because that is a header only feature

Will need to coordinate with @Gerafp to get this merged into his branch. (I tried to submit a PR against the original `CIMMYT:6156-footer-image` branch, but I couldn't seem to sort out how to do that in the GitHub.)

**Pull request merged**
