### PR TITLE
fix: insert correct identifierType into DataCite export XML

### PR DESCRIPTION
**Pull request by vera**
**What this PR does / why we need it**:

I noticed when exporting the metadata of a dataset with a Permalink PID that the DataCite XML export contained the wrong identifierType:

```
<identifier identifierType="DOI">https://example.com/mypermalink1234</identifier>
```

This PR fixes the bug by using `getProviderType` to insert the correct identifier type.

I also fixed some typos and added a missing return value for `getProviderType`.

**Which issue(s) this PR closes**:

not aware of any issue

**Special notes for your reviewer**:

\-

**Suggestions on how to test this**:

I tested this locally by creating a dataset with a Permalink PID and then using the "Export Metadata" > "DataCite" button in the UI.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

\-

**Is there a release notes update needed for this change?**:

I think not

**Additional documentation**:

\-

### CODE REVIEW

**Comment by pdurbin** [comment]
@vera thanks for the pull request!

Just a heads up that there is a significant refactoring by @qqmyers of the DataCite code in the works:

- #10615

**Comment by qqmyers** [comment]
FWIW: The new code does set the identifierType (to "DOI", "Handle", or "URL" (for perma)) which should be allowed values for the DataCite schema. (Maybe the original code was written before exporters/when the output was only sent to DataCite and DOI was always true?) I'm not sure how fast #10615 is moving, so if this gets merged first (so we get the other fixes), I think it's fine.

**Comment by vera** [comment]
Ah, that's great. Sorry, I wasn't aware of that.

Yes, I also checked the DataCite schema. I didn't find a list of allowed values, only that "identifierType" should be a non-empty string, so any string should be fine I think.

**Comment by qqmyers** [comment]
You're right. In this case it wasn't the DataCiteSchema but the [OpenAire Guildelines](https://guidelines.readthedocs.io/en/latest/data/field_identifier.html) that had a list.

**Comment by johannes-darms** [comment]
Can we integrate this into version 6.4 if https://github.com/IQSS/dataverse/pull/10615 is not integrated?

**Comment by pdurbin** [comment]
@vera can you please resolve merge conflicts in this pull request? They are due to us merging this PR:

- #10632

**Comment by vera** [comment]
Hmm, I actually think this PR is not necessary anymore. The main bug this PR fixes (wrong `identifierType` in the DataCite export) is already fixed by #10632 (here: https://github.com/IQSS/dataverse/pull/10632/files#diff-ceea58ab3cfad4c5eb5265ad85516df9af3b75f31b32b764367989d5c59c84a0R225-R237).

I've tested the develop branch with a PermaLink dataset and it's now correct:

`<identifier identifierType="URL">https://csh.nfdi4health.de/resource/health-IP89GF</identifier>`

The rest of the changes in this PR don't need to be merged I think.

**Comment by pdurbin** [comment]
I'm confused why this pull request doesn't have a merge conflict because src/main/resources/edu/harvard/iq/dataverse/pidproviders/doi/datacite_metadata_template.xml was removed in b1e5020d5c44a2c1dd3c8f581482f4db17e1dcd1 🤔 

@vera anyway, I think this PR will need to be adjusted to the new way added here:

- #10632

**Comment by pdurbin** [comment]
> Hmm, I actually think this PR is not necessary anymore.

Oh! @vera please feel free to close this PR if you don't need it. 😄

**Pull request closed without merging**
