### PR TITLE
10527 404static.xhtml has an old date in the footer (2023 is hard-coded) and update URLs

### LINKED ISSUE #10527: 404static.xhtml has an old date in the footer (2023 is hard-coded)
**What steps does it take to reproduce the issue?**
If you call up a flat page, an error page "404static.xhtml" appears. This still has an old date in the footer. Maybe you should adjust something there too?

**Screenshots:**
https://github.com/IQSS/dataverse/blob/develop/src/main/webapp/404static.xhtml

Screenshot from 2024-04-24 10-19-09

### PR DESCRIPTION
**Pull request by BenediktMeierUIT**
**What this PR does / why we need it**:

**Which issue(s) this PR closes**:

Closes #10527

**Special notes for your reviewer**:

**Suggestions on how to test this**:

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

**Is there a release notes update needed for this change?**:
JavaScript and update URLs

**Additional documentation**:

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
@BenediktMeierUIT thanks for the pull request.

From a quick look the date looks ok.

Why are there so many other changes? Are they important? Did you consider only changing the date?

**Comment by BenediktMeierUIT** [comment]
I made several changes because otherwise, the page would not be correct, and I would have to report multiple errors. But I can change that if it's better for you.

**Review by pdurbin — APPROVED** [review]
I haven't tested it but it looks like a good fix to me.

The "best practices" link doesn't work but let's consider that out of scope. There's a related issue here:

- #8814

**Comment by pdurbin** [comment]
This small fix is a good candidate for 6.4.

**Pull request merged**
