### PR TITLE
3583 dv cannot parse do is that don't have a separator in authority/prefix

### PR DESCRIPTION
**Pull request by qqmyers**
## New Contributors

Welcome! New contributors should at least glance at [CONTRIBUTING.md](/CONTRIBUTING.md), especially the section on pull requests where we encourage you to reach out to other developers before you start coding. Also, please note that we measure code coverage and prefer you write unit tests. Pull requests can still be reviewed without tests or completion of the checklist outlined below. Thanks!

## Related Issues

- connects to #3583  : DV cannot parse DOIs that don't have a separator in authority/prefix

## Pull Request Checklist

- [ ] Unit [tests][] completed
- [ ] Integration [tests][]: None
- [ ] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [ ] [Documentation][docs] completed
- [ ] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: https://github.com/IQSS/dataverse/tree/develop/scripts/database/upgrades
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.2.1/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by qqmyers** [comment]
Looks like this build failure is in a test or WorldMapTokens and not related to the PR itself. (possibly a random failure due to the test creating two tokens, which have calls to getCurrentTimestamp(), and comparing them to see if they are equal?).

If there's something wrong that I missed that's related to the new code, let me know.

**Comment by pdurbin** [comment]
@qqmyers I've definitely seen that failure on my laptop from time to time for no reason: `Failed tests:   testTokenValues(edu.harvard.iq.dataverse.worldmapauth.WorldMapTokenTest): expected:<true> but was:<false>`

Here's a screenshot:

screen shot 2018-04-26 at 6 42 20 pm


Let me go to https://travis-ci.org/IQSS/dataverse/builds/371542407 and see if I can restart the build on Travis.

**Comment by pdurbin** [comment]
Ok, I restarted the build at https://travis-ci.org/IQSS/dataverse/builds/371542407 and now it's green. I'm not sure what's up with that WorldMapTokenTest failing sometimes but maybe we should crack it open and look at it or delete it if it's flaky. Screenshots of the build restart:

screen shot 2018-04-26 at 6 43 21 pm

screen shot 2018-04-26 at 7 08 35 pm

**Comment by pdurbin** [comment]
Closing based on discussion at https://github.com/IQSS/dataverse/issues/3583#issuecomment-386446326 and below between @qqmyers and @scolapasta

**Pull request closed without merging**
