### PR TITLE
Fix btn text word wrap, other responsive layout improvements [ref #7326]

### LINKED ISSUE #7326: Dataset page - button and citations display issues in different languages
Hi Dataverse team,

We at Scholars Portal have begun testing Dataverse 5 (currently 5.0 and working on our merge up to 5.1.1, so apologies if this was already addressed). We have noticed an issue with the display of buttons and citations on the dataset page when we change languages to French.

Screen Shot 2020-10-13 at 4 59 28 PM

The new design does not seem to accommodate longer strings of text.

Has the new dataset page been previously tested with different languages? We only use EN/FR, but I can see this happening with other languages too.

### PR DESCRIPTION
**Pull request by mheppler**
**What this PR does / why we need it**:

Overwrite CSS from Bootstrap 3 stylesheet that causes long button text overflow to be hidden by the width of the containing button. Specifically this issue can be best scene in the action buttons on the top of the dataset and file pgs, when the language display is set to French, when the button text "Modalités d'accès à l'ensemble de données" needs to break to another line to display fully inside in the button container.

As a result of this CSS overwrite added to our stylesheet, we also had to remove the "Find" button text label from various input-btn-group components that included a magnifying glass glyphicon, because the text label inexplicably wrapped to another line under the glyphicon. This was resolved by removing the text label and moving it to the button title attribute, so that it displays on hover. This change to the search components can be found in the dataverse header, manage users dashboard pg, dataverse pg and dataset pg.

**Which issue(s) this PR closes**:

Closes #7326 Dataset page - button and citations display issues in different languages 

**Special notes for your reviewer**:

Happy to discuss any changes found in the code that are not clearly outlined above. If more detail is needed to better explain anything, I can add that as well.

**Suggestions on how to test this**:

Requires an installation configured with the French language bundle. View pages in multiple browser window sizes (Pro-tip: Safari provides a Responsive Design Mode under the Develop OS menu option.)

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

No mockups for these UI clean up changes.

**Is there a release notes update needed for this change?**:

N/A

**Additional documentation**:

N/A

### CODE REVIEW

**Comment by mheppler** [comment]
Screen Shot 2021-01-25 at 2 05 19 PM

**Review by scolapasta — COMMENTED** [review]
Code is mostly CSS changes but looks ok to me.

It does seem strange to me to remove "Find" from the buttons, as all other buttons have a glyphicon with accompanying text. (right?)

**Review by scolapasta — COMMENTED** [review]
@mheppler let me know if you plan on making any other changes here (as mentioned); otherwise I can approve when ready.

**Comment by mheppler** [comment]
Added tooltip style to search input-group-btn as suggested by @scolapasta. Ready for review and approval.

Screen Shot 2021-01-27 at 7 41 54 PM

**Review by scolapasta — APPROVED** [review]

**Pull request merged**
