### PR TITLE
#8820 render confirm delete button on delete group click

### LINKED ISSUE #8820: CRITICAL: Pressing Enter in Group Members assignment windows deletes the whole group
**What steps does it take to reproduce the issue?**
1. As an admin/curator in a TEST environment, click Edit > Groups > Create Group, and create a new user group for testing this issue.
2. Look up and add a user to the newly created test group, so that the user name displays in the Group Members field:

image

3. With the cursor placed to the right to the added user name, press Enter.

* When does this issue occur?
See above.

* Which page(s) does it occurs on?
On the Group edit page, e.g.
https://demo.dataverse.org/manage-groups.xhtml?dataverseId=XX

* What happens?
The group is deleted, and the following confirmation message appears on screen:

image

* To whom does it occur (all users, curators, superusers)?
To everyone have the rights to add users to an existing user group.

* What did you expect to happen?
Not sure. I guess many curators would expect the added user to be saved, thus they want to use Enter as a shortcut for scrolling to the bottom of the page and click Save Changes.

**Which version of Dataverse are you using?**
The behavior was tested on version v.5.6 (test.dataverse.no) and version v.5.11 (demo.dataverse.org).

**Any related open or closed issues to this bug report?**
None to my knowledge.

**Screenshots:**
See above.

### PR DESCRIPTION
**Pull request by sekmiller**
**What this PR does / why we need it**: Fixes a bug where pressing "enter" on the create group popup deletes the group because it invokes the confirm delete popup continue button

**Which issue(s) this PR closes**:

Closes #8820 CRITICAL pressing entet in Group Members assignment deletes the Group

**Special notes for your reviewer**:

**Suggestions on how to test this**: try adding a group and press enter while the cursor is in the user text box. the group should be created - not deleted

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**: no

**Is there a release notes update needed for this change?**:no

**Additional documentation**:none

### CODE REVIEW

**Comment by qqmyers** [comment]
FWIW: When I first read this issue, I assumed it was similar to #7895 and that a fix like #8500 would be required.  Is the current PR still allowing the default button on the page to be clicked and just stopping that from having an effect (versus avoiding the keypress from triggering the action at all)?

**Comment by sekmiller** [comment]
In this case according to Philipp, the preferred response to the enter key is to submit and save the group. In that other case since it was the whole dataset page, they wanted enter to be disabled.

**Review by pdurbin — APPROVED** [review]
I ran the code and it seems to do the job. Crazy that hitting enter was deleting groups!

A couple things I'll note:

- On develop (4e65f2f), in addition to the "Create Group" dialog I was also able to reproduce the "hit enter to delete" but in the "edit group" dialog. That is, got to "Group Members" and hit enter.
- Now hitting enter doesn't delete the group. Great! Perhaps it should trigger "Save Changes"? But this can wait for a future PR, I'd say.

**Comment by pdurbin** [comment]
The Jenkins tests were passing but I went ahead and refreshed from develop.

**Pull request merged**
